function CWEChromeUtilities(){return this}
CWEChromeUtilities.checkInternetConnectionAvailable=function(a){var b=null,d=function(e){try{a(e)}catch(f){Logger.instance.error(f)}};if(navigator.onLine)try{var c=new XMLHttpRequest;c.open("HEAD","https://www.google.com/?random="+Math.random(),!0);c.onreadystatechange=function(){if(4===c.readyState&&0<c.status){var e=200<=c.status&&300>c.status||304===c.status;b&&clearTimeout(b);setTimeout(function(){d(e)},0)}};c.send();b=setTimeout(function(){c.abort();setTimeout(function(){d(!1)},0)},2E3)}catch(e){b&&
clearTimeout(b),d(!1)}else d(!1)};CWEChromeUtilities.loadFile=async function(a,b){try{let d=chrome.extension.getURL(a),c=await fetch(d);a=void 0;return a="text"===b?await c.text():"json"===b?await c.json():await c.blob()}catch(d){Logger.instance.error(d)}};CWEChromeUtilities.isChromeOS=function(){return-1!=window.navigator.userAgent.indexOf("CrOS")};CWEChromeUtilities.isMacOS=function(){return-1!=window.navigator.userAgent.indexOf("Macintosh")};
CWEChromeUtilities.isWindowsOS=function(){return-1!=window.navigator.userAgent.indexOf("Windows")};CWEChromeUtilities.isMicrosoftEdge=function(){return-1!=window.navigator.userAgent.indexOf("Edg/")};CWEChromeUtilities.isLoginApp=function(){for(var a=[/.*login.*\.donjohnston\.net/,/.*login.*\.qadji\.com/,/.*login.*\.stagedji\.com/],b=window.location.hostname,d=0;d<a.length;d++)if(a[d].test(b))return!0;return!1};
CWEChromeUtilities.isGoogleSearch=function(){var a=window.location.hostname.split(".");return 2!=a.length&&3!=a.length||"google"!==a[a.length-2]?!1:2==a.length||"www"===a[0]};CWEChromeUtilities.isGoogleDocs=function(){return"docs.google.com"===window.location.hostname&&(null!==window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i)||null!==window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/edit/i))};
CWEChromeUtilities.isGooglePresentation=function(){return"docs.google.com"===window.location.hostname&&(null!==window.location.pathname.match(/^(\/a\/[^\/]+)?\/presentation\/d\//i)||null!==window.location.pathname.match(/^(\/a\/[^\/]+)?\/presentation\/edit/i))};CWEChromeUtilities.isGoogleMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.google.com")};CWEChromeUtilities.isGoogleForms=function(){return"docs.google.com"===window.location.hostname&&null!==window.location.pathname.match(/^\/forms\//i)};
CWEChromeUtilities.isYahooMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.yahoo.com")};CWEChromeUtilities.isMicrosoftMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.live.com")};CWEChromeUtilities.isEvernote=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"evernote.com")};CWEChromeUtilities.isFacebook=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"facebook.com")};
CWEChromeUtilities.isTwitter=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"twitter.com")};CWEChromeUtilities.isIframeFree=function(){return CWEChromeUtilities.isGoogleMail()};CWEChromeUtilities.stringStartsWith=function(a,b){return 0===a.indexOf(b,0)};CWEChromeUtilities.stringEndsWith=function(a,b){return-1!==a.indexOf(b,a.length-b.length)};CWEChromeUtilities.hostnameFromURL=function(a){return a.toString().replace(/^(.*\/\/[^\/?#]*).*$/,"$1")};
CWEChromeUtilities.jsonFromUrlQueryAndHash=function(a){if(!a)return null;try{var b=null,d=null;let c;a=a.split("#");1==a.length?a=a[0]:2==a.length&&(d=a[1],a=a[0]);a=a.split("?");2==a.length&&(b=a[1]);if(b)for(c in b='{"'+b.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',b=JSON.parse(b),b)b.hasOwnProperty(c)&&(b[c]=decodeURIComponent(b[c]));if(d)for(c in d='{"'+d.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',d=JSON.parse(d),d)d.hasOwnProperty(c)&&(d[c]=decodeURIComponent(d[c]));return a={query:b,
hash:d}}catch(c){Logger.instance.error(c)}return null};CWEChromeUtilities.htmlToAscii=function(a){return void 0===a||null===a||0==a.length?a:dji.utils.htmlToAsciiTextArray(a).join("")};CWEChromeUtilities.latin1Table="AAAAAAACEEEEIIIIDNOOOOOXOUUUUYpbaaaaaaaceeeeiiiidnoooooxouuuuypy.......";
CWEChromeUtilities.wikiHtmlToAscii=function(a){if(!a)return"";a=dji.utils.htmlToAsciiTextArray(a);for(var b=a.length,d=CWEChromeUtilities.latin1Table,c,e,f,g=0;g<b;g++)e=a[g],c=f=e.charCodeAt(0),"z"<c&&(e=".",192<c&&(e=d.charAt(c-192)),f=e.charCodeAt(0)),8203==f||8204===f?e=" ":128<=f?e="=":"^"==e?e=" ":"\n"==e?e="\r":("?"==e||"["==e||"]"==e)&&g<b-1&&(c=a[g+1],"0"<=c&&"9">=c||"A"<=c&&"Z">=c||"a"<=c&&"z">=c)&&(e=" "),a[g]=e;return a=a.join("")};
CWEChromeUtilities.mapIsEmpty=function(a){if(a)for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};CWEChromeUtilities.findParagraph=function(a,b){return CWEChromeUtilities.findToken(a,b,CWECharacterSet.paragraphSeparatorCharacterSet)};CWEChromeUtilities.findSentence=function(a,b){return CWEChromeUtilities.findToken(a,b,CWECharacterSet.sentenceSeparatorCharacterSet)};
CWEChromeUtilities.findWord=function(a,b,d=!0){return CWEChromeUtilities.findToken(a,b,CWECharacterSet.wordSeparatorCharacterSet,d)};CWEChromeUtilities.findToken=function(a,b,d,c=!0){if(!a||0>b||b>a.length||null==d)return null;let e=c?d.characterIsMember(a.charAt(b)):!1;for(c=b;0<=c;c--)if(d.characterIsMember(a.charAt(c)))if(e)e=!1;else{c++;break}for(;b<a.length;b++)if(d.characterIsMember(a.charAt(b))){b--;break}0>c&&(c=0);return c<=b?a.slice(c,b+1):null};
CWEChromeUtilities.elementHasParent=function(a,b){for(;a&&a!==b;)a=a.parentElement;return a===b};
CWEChromeUtilities.extractVisibleTextFromElement=function(a){if(!a)return"";if(3==a.nodeType)return a.textContent;var b="",d=null;for(a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(c){var e=c.id?c.id.toLowerCase():"";if(3==c.nodeType)return NodeFilter.FILTER_ACCEPT;if("SCRIPT"==c.tagName||"NOSCRIPT"==c.tagName||"IMG"==c.tagName||"SELECT"==c.tagName||"INPUT"==c.tagName&&(!c.type||"text"!=c.type.toLowerCase())||"dexcontrolscontainer"==e||"dexcontrolscontainermeasurement"==
e||"__dji_cwe_body_overlay"==e||"__dji_cwe_measurement_window_generic"==e||"__dji_cwe_chrome_google_docs_proxy"==e||"__dji_cwe_measurement_window_generic"==e||"none"==document.defaultView.getComputedStyle(c,null).getPropertyValue("display"))return NodeFilter.FILTER_REJECT;"SPAN"!=c.tagName&&(b+="\n");return NodeFilter.FILTER_ACCEPT},!0);d=a.nextNode();)3==d.nodeType?b+=" "+d.textContent:1==d.nodeType&&"TEXTAREA"==d.tagName&&(b+="\n"+d.value+"\n");return b};
CWEChromeUtilities.findValidDocumentElements=function(a,b){a=a.getElementsByTagName("iframe");for(var d=0;d<a.length;d++){var c=a[d];CWEChromeUtilities.validateIframe(c)&&null!==c.contentDocument&&(b.push(c.contentDocument),CWEChromeUtilities.findValidDocumentElements(c.contentDocument,b))}};
CWEChromeUtilities.findValidIframeElements=function(a,b,d){a=(a||document).getElementsByTagName("iframe");for(let c=0;c<a.length;c++){let e=a[c];CWEChromeUtilities.validateIframe(e,d)&&null!==e.contentDocument&&(b.push(e),CWEChromeUtilities.findValidIframeElements(e.contentDocument,b,d))}};
CWEChromeUtilities.validateIframe=function(a,b){b=!0;try{if(void 0===a.src||null===a.src)return!1;let d=a.getAttribute("id");if("__dji_sru_templates"===d||!b&&d&&0<=d.indexOf("dji_sru"))return!1;b=null;let c=a.src.split("/")[2];if(void 0!==c&&null!==c&&-1===c.indexOf(document.domain))return!1;b=a.contentDocument;return null!==b&&void 0!==b}catch(d){}return!1};
CWEChromeUtilities.getScrollbarSize=function(){if(void 0===CWEChromeUtilities.getScrollbarSize.__scrollbarSize){let a=document.createElement("div");a.style.visibility="hidden";a.style.position="fixed";a.style.left="-5000px";a.style.width="-5000px";a.style.height="200px";a.style.height="200px";a.style.overflow="scroll";document.body.appendChild(a);let b={width:a.offsetWidth-a.clientWidth,height:a.offsetHeight-a.clientHeight};a.parentNode.removeChild(a);CWEChromeUtilities.getScrollbarSize.__scrollbarSize=
b}return CWEChromeUtilities.getScrollbarSize.__scrollbarSize};CWEChromeUtilities.generateUUID=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var d=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?d:d&7|8).toString(16)})};CWEChromeUtilities.blobToText=function(a,b){if(a){var d=new FileReader;d.onloadend=function(){b(d.result)};d.onerror=function(c){b(null)};d.readAsText(a)}else b(null)};
CWEChromeUtilities.convertFontPercentageToPixels=function(a){switch(a){case 0:return 13;case 20:return 16;case 40:return 20;case 60:return 24;case 80:return 32;case 100:return 48;default:return 16}};CWEChromeUtilities.convertFontPercentageToFontSize=function(a){switch(a){case 0:return 2;case 20:return 3;case 40:return 4;case 60:return 5;case 80:return 6;case 100:return 7;default:return 4}};CWEChromeUtilities.convertGuessPercentageToPixels=function(a){return parseInt(10+38*a/100)};
CWEChromeUtilities.convertMarginsPercentageToPixels=function(a){return parseInt(80*a/100)};CWEChromeUtilities.capsState=function(a){if(0<a.length&&a[0]===a[0].toUpperCase()){if(1===a.length)return"FIRSTCAPS";for(let b=1;b<a.length;b++)if(a[b]!==a[b].toUpperCase())return"FIRSTCAPS";return"ALLCAPS"}return"NOCAPS"};CWEChromeUtilities.setCapsState=function(a,b){return"FIRSTCAPS"===b?a=a[0].toUpperCase()+a.slice(1).toLowerCase():"ALLCAPS"===b?a.toUpperCase():a.toLowerCase()};
CWEChromeUtilities.titleFromPage=function(a){let b=document.title||"";if(0>=b.length){let d=document.querySelector('meta[name="DC.title"]');d||(d=document.querySelector('meta[name="dji-document-title"]'));d&&(b=d.getAttribute("content")||"")}a&&(b=CWEChromeUtilities.htmlToAscii(b));return b=b.trim()};
CWEChromeUtilities.titleForTopic=function(a){let b="",d=[];var c=!!a.useAscii;if(a.usePageTitle){var e=CWEChromeUtilities.titleFromPage().replace(/\W/g," ");c&&(e=CWEChromeUtilities.htmlToAscii(e));e=e.trim();0<e.length&&(e=e.split(/\s/).filter(function(h){return!!(h&&0<h.length)}),0<e.length&&d.push(...e))}if(a.text&&0<a.text.length&&(a.combine||0>=d.length)){e=a.text.split(/[\r\n]/);for(var f=0;f<e.length;f++){var g=c?CWEChromeUtilities.htmlToAscii(e[f]).replace(/\W/g," ").trim():e[f].replace(/\W/g,
" ").trim();if(g&&0<g.length&&(g=g.split(/\s/).filter(function(h){return!!(h&&0<h.length)}),0<g.length)){0<d.length&&d.push("-");d.push(...g);break}}}if(0<d.length)for(a=isNaN(a.maxLength)||0>=a.maxLength?34:a.maxLength,c=0;c<d.length&&b.length<a;c++)if(e=d[c],f=0<b.length?1:0,b.length+f+e.length<=a)0<f&&(b+=" "),b+=e;else if(0>=b.length)b=e.substr(0,a);else break;return b};CWEChromeUtilities.isNullOrUndefined=function(a){return null===a||void 0===a};
CWEChromeUtilities.createLastErrorHandler=function(){if(Logger.instance===console){const a=Error().stack;return function(){chrome.runtime.lastError&&Logger.instance.error(chrome.runtime.lastError.message,"\nStack:",a)}}return CWEChromeUtilities.checkLastError};CWEChromeUtilities.checkLastError=function(){chrome.runtime.lastError&&Logger.instance.error(chrome.runtime.lastError.message,"\nStack:",Error().stack)};CWEChromeUtilities.sleepAsync=async function(a){return new Promise(b=>setTimeout(b,a))};
