window.cwe=window.cwe||{};
window.cwe.CWEAsNeededController=function(){class e{constructor(a,d){this.m_icon=void 0;this.m_iconInfo={x:0,y:0,width:0,height:0,hidden:!0,fixed:!1};this.m_listeners={onIconClicked:[]};a&&a.onIconClicked&&"function"===typeof a.onIconClicked&&this.m_listeners.onIconClicked.push(a.onIconClicked);this.__create(d)}__create(a){if(!this.m_icon){a=a||document.documentElement;var d=a.ownerDocument,b=a.getElementById("__CWE_AS_NEEDED_ICON");b||(b=d.createElement("div"),b.id="__CWE_AS_NEEDED_ICON",a.append(b));
this.m_icon=b;this.hide();b.addEventListener("click",c=>{dji.utils.notifyListeners(this.m_listeners.onIconClicked)});return this.m_icon}}move(a,d,b,c){if(this.m_iconInfo.x!==a||this.m_iconInfo.y!==d||this.m_iconInfo.width!==b||this.m_iconInfo.height!==c)this.m_iconInfo.x=a,this.m_iconInfo.y=d,this.m_iconInfo.width=b,this.m_iconInfo.height=c,this.m_iconInfo.hidden||this.m_iconInfo.fixed||this.__doMove()}__doMove(){this.m_icon.style.left=`${this.m_iconInfo.x}px`;this.m_icon.style.top=`${this.m_iconInfo.y}px`;
this.m_icon.style.width=`${this.m_iconInfo.width}px`;this.m_icon.style.height=`${this.m_iconInfo.height}px`;this.m_icon.style.backgroundSize=`${this.m_iconInfo.width}px ${this.m_iconInfo.height}px`}hide(){this.m_iconInfo.hidden||(this.m_iconInfo.hidden=!0,this.m_icon.removeAttribute("visible"))}show(){this.m_iconInfo.hidden&&(this.m_iconInfo.hidden=!1,this.m_icon.setAttribute("visible",""),this.__doMove())}setVisible(a){a?this.show():this.hide()}setFixed(a){this.m_iconInfo.fixed!==a&&((this.m_iconInfo.fixed=
a)||this.__doMove())}setImageURL(a){this.m_icon.style.backgroundImage=a?`url(${a})`:""}}class f{constructor(a,d){this.m_iconListener={onIconClicked:()=>{this.__onIconClicked()}};this.m_icon=new e(this.m_iconListener,d);this.m_spellcheckError={word:null};this.m_lastInputtedChar=void 0;this.m_talkingProcessorActive=this.m_editorHasFocus=!1;this.m_state={prediction:!1,dictation:!1,active:!0,icon:null};this.m_speechErrorDetails=null;let b=this;this.targetForEventData=function(c){switch(c){case 0:return"off";
case 1:return"default_prediction_off";case 2:return"auto_prediction_off";case 3:return"speech_to_text_off";default:return"default_prediction_off"}};this.m_fsm=window.dji.fsm.create({initialState:"off",off:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!0,dictation:null,icon:null})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"off"},action(){}},blur:{target(){return"off"},action(){b.__updateState({prediction:!1,
dictation:null,icon:null})}},focus:{target(){return"off"},action(){b.__updateState({prediction:!0,dictation:null,icon:null})}}}},default_prediction_on:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!0,dictation:null,icon:"Graphics/cw_as_needed_icon.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"default_prediction_off"},action(){}},blur:{target(){return"default_prediction_on"},action(){b.__updateState({prediction:!1,
dictation:null,icon:"Graphics/cw_as_needed_icon.svg"})}},focus:{target(){return"default_prediction_on"},action(){b.__updateState({prediction:!0,dictation:null,icon:"Graphics/cw_as_needed_icon.svg"})}},highlight_on:{target(){return"default_prediction_on"},action(){b.m_talkingProcessorActive?b.__updateState({prediction:!0,dictation:null,icon:null}):b.__updateState({prediction:!0,dictation:null,icon:"Graphics/cw_as_needed_icon.svg",fixedIcon:!0})}},highlight_off:{target(){return"default_prediction_on"},
action(){b.__updateState({prediction:!0,dictation:null,icon:"Graphics/cw_as_needed_icon.svg",fixedIcon:!1})}}}},default_prediction_off:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:null,icon:"Graphics/cw_as_needed_icon.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"default_prediction_on"},action(){}},blur:{target(){return"default_prediction_off"},action(){}},focus:{target(){return"default_prediction_off"},
action(){}}}},auto_prediction_off:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:null,icon:null})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},spellcheck_results:{target(){return!window.dji.utils.isNullOrUndefined(b.m_lastInputtedChar)&&window.dji.charSet.wordSeparator.characterIsMemberNoHypen(b.m_lastInputtedChar)&&b.__hasSpellcheckErrorsForLastWord()?"auto_prediction_on":"auto_prediction_off"},action(){}},text_input:{target(c){return window.dji.charSet.wordSeparator.characterIsMemberNoHypen(c)?
b.__hasSpellcheckErrorsForLastWord()?"auto_prediction_on":"auto_prediction_off":"auto_prediction_off"},action(){}}}},auto_prediction_on:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!0,dictation:null,icon:"Graphics/cw_as_needed_misspell.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},spellcheck_results:{target(){return b.__hasSpellcheckErrorsForLastWord()?"auto_prediction_on":"auto_prediction_off"},action(){}},text_input:{target(c){return window.dji.charSet.wordSeparator.characterIsMemberNoHypen(c)?
"auto_prediction_on":"auto_prediction_off"},action(){}},suggestion_selected:{target(){return"auto_prediction_off"},action(){}},blur:{target(){return"auto_prediction_off"},action(){}}}},speech_to_text_off:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:null,icon:"Graphics/ic_mic_blue.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"speech_to_text_starting"},action(){}},highlight_on:{target(){return"speech_to_text_highlighting"},
action(){}},speech_error:{target(){return"speech_to_text_error"},action(){}},focus:{target(){return"speech_to_text_off"},action(){b.__updateState({prediction:!1,dictation:null,icon:"Graphics/ic_mic_blue.svg"})}}}},speech_to_text_starting:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:!0,icon:"Graphics/ic_mic_white.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){b.__updateState({prediction:!1,dictation:!1,icon:"Graphics/ic_mic_white.svg"})}},
toggle:{target(){return"speech_to_text_starting"},action(){}},advance:{target(){return"speech_to_text_on"},action(){}},highlight_on:{target(){return"speech_to_text_highlighting"},action(){}},highlight_off:{target(){return"speech_to_text_off"},action(){}},speech_error:{target(){return"speech_to_text_error"},action(){}},speech_error_dismissed:{target(){return"speech_to_text_off"},action(){}}}},speech_to_text_stopping:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:!1,
icon:"Graphics/ic_mic_white.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"speech_to_text_stopping"},action(){}},advance:{target(){return"speech_to_text_off"},action(){}},highlight_on:{target(){return"speech_to_text_highlighting"},action(){}},highlight_off:{target(){return"speech_to_text_off"},action(){}},speech_error:{target(){return"speech_to_text_error"},action(){}},speech_error_dismissed:{target(){return"speech_to_text_off"},
action(){}}}},speech_to_text_on:{actions:{onAboutToEnter(){},onEntered(){b.__updateState({prediction:!1,dictation:!0,icon:"Graphics/ic_mic_white.svg"})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"speech_to_text_stopping"},action(){}},advance:{target(){return"speech_to_text_off"},action(){}},highlight_on:{target(){return"speech_to_text_highlighting"},action(){}},highlight_off:{target(){return"speech_to_text_off"},action(){}},spellcheck_results:{target(){return"speech_to_text_on"},
action(){const c=b.__hasSpellcheckErrors();b.__updateState({prediction:c,dictation:!0,icon:c?"Graphics/stt_misspelling.svg":"Graphics/ic_mic_white.svg"})}},text_input:{target(){return"speech_to_text_on"},action(){}},suggestion_selected:{target(){return"speech_to_text_stopping"},action(){}},blur:{target(){return"speech_to_text_off"},action(){}},speech_error:{target(){return"speech_to_text_error"},action(){}},speech_error_dismissed:{target(){return"speech_to_text_off"},action(){}}}},speech_to_text_highlighting:{actions:{onAboutToEnter(){},
onEntered(){b.__updateState({prediction:!1,dictation:null,icon:null})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"speech_to_text_highlighting"},action(){}},highlight_off:{target(){return"speech_to_text_off"},action(){}},blur:{target(){return"speech_to_text_off"},action(){}},speech_error:{target(){return"speech_to_text_error"},action(){}},speech_error_dismissed:{target(){return"speech_to_text_off"},action(){}}}},speech_to_text_error:{actions:{onAboutToEnter(){},
onEntered(){b.__updateState({prediction:!0,dictation:!1,icon:null})},onExit(){}},transitions:{switch:{target(c){return b.targetForEventData(c)},action(){}},toggle:{target(){return"speech_to_text_off"},action(){}},speech_error_dismissed:{target(){return"speech_to_text_off"},action(){}},focus:{target(){return"speech_to_text_off"},action(){}},blur:{target(){return"speech_to_text_off"},action(){}}}}});this.m_delegates={getLastWrittenWord:void 0};this.setDelegates(a);this.m_eventTarget=new EventTarget;
this.m_fsm.transition(this.m_fsm.value,"switch",1)}addEventListener(a,d){this.m_eventTarget.addEventListener(a,d)}setDelegates(a){a&&a.getLastWrittenWord&&"function"===typeof a.getLastWrittenWord&&(this.m_delegates.getLastWrittenWord=a.getLastWrittenWord)}isPredictionActive(){return this.m_state.prediction}isSpellingActive(){return"auto_prediction_on"===this.m_fsm.value||"speech_to_text_on"===this.m_fsm.value}isSpellingAware(){return"auto_prediction_off"===this.m_fsm.value||"auto_prediction_on"===
this.m_fsm.value||"speech_to_text_on"===this.m_fsm.value}isSpeechActive(){return"speech_to_text_on"===this.m_fsm.value}isSpeechStopping(){return"speech_to_text_stopping"===this.m_fsm.value}hasSpeechError(){return"speech_to_text_error"!==this.m_fsm.value?!1:this.m_speechErrorDetails&&this.m_speechErrorDetails.isPermissionError&&dji.permissionsController.isMicrophonePermissionGranted()?(this.onSpeechRecognitionErrorDismissed(),!1):!0}getLevel(){return"off"===this.m_fsm.value?0:"default_prediction_off"===
this.m_fsm.value||"default_prediction_on"===this.m_fsm.value?1:"auto_prediction_off"===this.m_fsm.value||"auto_prediction_on"===this.m_fsm.value?2:"speech_to_text_off"===this.m_fsm.value||"speech_to_text_on"===this.m_fsm.value||"speech_to_text_starting"===this.m_fsm.value||"speech_to_text_stopping"===this.m_fsm.value||"speech_to_text_highlighting"===this.m_fsm.value||"speech_to_text_error"===this.m_fsm.value?3:0}setLevel(a){2===a&&(a=0);this.getLevel()!==a&&this.m_fsm.transition(this.m_fsm.value,
"switch",a)}allowTextProcessing(){return this.isSpeechActive()?!0:this.isSpellingAware()?!1:this.m_state.prediction}__updateState(a){a.prediction=a.prediction&&this.m_editorHasFocus;const d=this.m_state;this.m_state=Object.assign({},this.m_state,a);d.icon!==a.icon&&this.__updateIconPath(a.icon);this.m_icon.setVisible(this.m_state.active&&!window.dji.utils.isNullOrUndefined(a.icon)&&this.m_editorHasFocus);this.m_icon.setFixed(!window.dji.utils.isNullOrUndefined(a.fixedIcon)&&a.fixedIcon);d.prediction!==
a.prediction&&this.__notifyPredictionStateChanged();window.dji.utils.isNullOrUndefined(a.dictation)||a.dictation===d.dictation||this.__notifyDictationStateChanged(!!a.dictation)}__updateIconPath(a){a&&0!==a.length?this.m_icon.setImageURL(chrome.extension.getURL(a)):this.m_icon.setImageURL(null)}__notifyPredictionStateChanged(){this.m_eventTarget.dispatchEvent(new CustomEvent("prediction-changed",{detail:{data:this.isPredictionActive()}}))}__notifyDictationStateChanged(a){setTimeout(()=>{this.m_eventTarget.dispatchEvent(new CustomEvent("dictation-changed",
{detail:{data:a}}))},0)}__updateIconPosition(a){if(a){var d=null!==a.height&&void 0!==a.height&&0<a.height?Math.max(a.height/2,16):Math.max(Math.ceil(Math.abs(a.bottom-a.top)/2),16);this.m_icon.move(a.right,a.bottom-d,d,d)}}__onIconClicked(){this.m_fsm.transition(this.m_fsm.value,"toggle",null)}__parseSpellCheckResult(a){if(window.dji.utils.isNullOrUndefined(a))return null;for(const d of a)if(!window.dji.utils.isNullOrUndefined(d)&&!window.dji.utils.isNullOrUndefined(d.isPredictionLang)&&d.isPredictionLang){if(!window.dji.utils.isNullOrUndefined(d.misspelled)&&
d.misspelled)return{word:d.word,isTranslation:!1};if(d.matchFound)return null;break}for(const d of a)if(!window.dji.utils.isNullOrUndefined(d)&&!window.dji.utils.isNullOrUndefined(d.translations)&&d.translations){if(!window.dji.utils.isNullOrUndefined(d.misspelled)&&d.misspelled)return{word:d.word,isTranslation:!0};break}return null}__hasSpellcheckErrors(){return!(window.dji.utils.isNullOrUndefined(this.m_spellcheckError)||window.dji.utils.isNullOrUndefined(this.m_spellcheckError.word)||0===this.m_spellcheckError.word.length)}__hasSpellcheckErrorsForLastWord(){return!window.dji.utils.isNullOrUndefined(this.m_spellcheckError)&&
this.m_spellcheckError.word===this.m_delegates.getLastWrittenWord()}onCaretChanged(a){this.__updateIconPosition(a);a||(this.m_editorHasFocus=!1,this.__updateState(this.m_state),this.m_fsm.transition(this.m_fsm.value,"blur"))}onActivateChanged(a){this.m_state.active!==a&&(this.m_state.active=a,this.__updateState(this.m_state))}onEditorChanged(a){this.m_editorHasFocus=a;this.__updateState(this.m_state);this.m_fsm.transition(this.m_fsm.value,a?"focus":"blur")}onSpeechRecognitionStarted(){this.m_fsm.transition(this.m_fsm.value,
"advance")}onSpeechRecognitionEnded(){this.m_fsm.transition(this.m_fsm.value,"advance")}onSpeechRecognitionError(a){this.m_speechErrorDetails=a;this.m_fsm.transition(this.m_fsm.value,"speech_error")}onSpeechRecognitionErrorDismissed(){this.m_speechErrorDetails=null;this.m_fsm.transition(this.m_fsm.value,"speech_error_dismissed")}onTextHighlightStarted(a){this.m_talkingProcessorActive=a;this.m_fsm.transition(this.m_fsm.value,"highlight_on")}onTextHighlightEnded(){this.m_fsm.transition(this.m_fsm.value,
"highlight_off")}onSpellcheckDone(a){this.isSpellingAware()&&(this.m_spellcheckError=this.__parseSpellCheckResult(a.entries),this.m_fsm.transition(this.m_fsm.value,"spellcheck_results"))}onTextInput(a){this.isSpellingAware()&&(this.m_lastInputtedChar=a,this.m_fsm.transition(this.m_fsm.value,"text_input",a))}onSuggestionSelected(){this.m_fsm.transition(this.m_fsm.value,"suggestion_selected")}}return f}();
