function CWEChromeEditorInfo(b,a,c){this.m_iframes=b;this.m_document=a;this.m_editor=c;return this}
function CWEChromeHookGeneric(b,a){this.m_ime=b;this.m_editors=[];this.m_textareaCaretHelper=new window.dji.utils.TextareaCaretHelper(a);this.m_isGoogleDocs=CWEChromeUtilities.isGoogleDocs();this.m_isGooglePresentation=CWEChromeUtilities.isGooglePresentation();this.m_isGoogleSearch=CWEChromeUtilities.isGoogleSearch();this.m_isGoogleMail=CWEChromeUtilities.isGoogleMail();this.m_isYahooMail=CWEChromeUtilities.isYahooMail();this.m_isMicrosoftMail=CWEChromeUtilities.isMicrosoftMail();this.m_isEvernote=
CWEChromeUtilities.isEvernote();this.m_isFacebook=CWEChromeUtilities.isFacebook();this.m_isTwitter=CWEChromeUtilities.isTwitter();this.m_writeTextTask=null;return this}CWEChromeHookGeneric.prototype.install=function(b){b=b||!1;this.__uninstallHooks();this.m_editors=[];this.__findEditableElements(document,b,[],this.m_editors);Logger.instance.log(this.m_editors);this.__installHooks();this.__detectActiveEditor(!0)};
CWEChromeHookGeneric.prototype.uninstall=function(){this.__uninstallHooks();this.m_editors=[]};CWEChromeHookGeneric.prototype.reload=function(b){b=b||!1;this.__uninstallHooks();this.m_editors=[];this.__findEditableElements(document,b,[],this.m_editors);Logger.instance.log(this.m_editors);this.__installHooks();this.__detectActiveEditor(!1)};
CWEChromeHookGeneric.prototype.__findEditableElements=function(b,a,c,d,f){var e=b.evaluate("//*[@contenteditable]|//input|//textarea|//body",b);for(var g=null;g=e.iterateNext();)this.__validateEditor(g)&&d.push(new CWEChromeEditorInfo(c,b,g));if(a)for(b=b.getElementsByTagName("iframe"),f||window.top!==window||(f=document.getElementById("__dji_sru_main_container"))&&f.shadowRoot&&(f=f.shadowRoot.getElementById("__dji_sru_main_container_iframe"))&&(b=[...b,f]),f=0;f<b.length;f++)e=b[f],this.__validateIframe(e)&&
null!==e.contentDocument&&(g=[e].concat(c),this.__findEditableElements(e.contentDocument,a,g,d,!0))};
CWEChromeHookGeneric.prototype.__validateEditor=function(b){if(b.hasAttribute("dji-cwu-no-prediction"))return!1;var a=b.tagName.toLowerCase();if("input"===a){if((this.m_isGoogleDocs||this.m_isGooglePresentation)&&b.classList.contains("goog-toolbar-combo-button-input")||this.m_isGooglePresentation&&b.classList.contains("docs-link-urlinput-url"))return!1;b=b.getAttribute("type");return!b||"text"===b.toLowerCase()}if("textarea"===a&&(this.m_isGoogleDocs||this.m_isGooglePresentation)){a=b.getAttribute("class");
var c=this.m_isGoogleDocs?"docos-input-textarea":"dcs-a-dcs-gb-dcs-hf";if(a&&-1!==a.indexOf(c))for(a=b.parentElement;a;){if((c=a.getAttribute("class"))&&-1!==c.indexOf("docs-titlebar-buttons"))return!1;a=a.parentElement}}if((a=b.getAttribute("id"))&&"__DJI_CWE_QUICKTOPIC_WINDOW_SEARCH_INPUT"===a)return!1;if("BODY"===b.tagName){if(!this.m_isGoogleDocs)if(this.m_isYahooMail){if((b=b.getAttribute("aria-label"))&&"Message Body"===b)return!0}else if("true"===b.getAttribute("contenteditable")||this.m_isEvernote&&
(b=b.getAttribute("class"))&&-1!=b.indexOf("ennote"))return!0;return!1}c=b.getAttribute("name");let d=b.getAttribute("class");if("username"===a||"username"===c||"login"===c||"email"===a||"email"===c||"reg_email_confirmation__"===c||"signin-email"===a||d&&-1!=d.indexOf("email-input"))return!1;if(this.m_isGoogleDocs){if((b=b.getAttribute("class"))&&-1!=b.indexOf("goog-sa-searchbox-input"))return!1}else if(this.m_isGoogleMail){if("true"===b.getAttribute("aria-haspopup"))return!1}else if(this.m_isYahooMail){if("list"===
b.getAttribute("aria-autocomplete"))return!1}else if(this.m_isFacebook){if("TEXTAREA"!==b.tagName&&(a=b.getAttribute("aria-autocomplete"),b=b.getAttribute("aria-expanded"),"list"===a&&"true"===b))return!1}else if(this.m_isTwitter&&"search-query"===a)return!1;return!0};CWEChromeHookGeneric.prototype.__validateIframe=function(b){return b.classList.contains("docs-texteventtarget-iframe")||!CWEChromeUtilities.validateIframe(b)?!1:!0};
CWEChromeHookGeneric.prototype.__installHooks=function(){for(let b=0;b<this.m_editors.length;b++)this.__installHooksInEditor(this.m_editors[b])};
CWEChromeHookGeneric.prototype.__installHooksInEditor=function(b){if(void 0===b.__djiHook||null===b.__djiHook){var a=this;b=b.m_editor;b.__djiHook=this;b.__djiHookOnFocus=function(c){a.onFocus(b,c)};b.__djiHookOnBlur=function(c){a.onBlur(b,c)};b.__djiHookOnSelect=function(c){a.onSelect(b,c)};b.__djiHookOnMouseDown=function(c){a.onMouseDown(b,c)};b.__djiHookOnMouseUp=function(c){a.onMouseUp(b,c)};b.__djiHookOnKeyDown=function(c){a.onKeyDown(b,c)};b.__djiHookOnKeyPress=function(c){a.onKeyPress(b,c)};
b.__djiHookOnKeyUp=function(c){a.onKeyUp(b,c)};b.addEventListener("focus",b.__djiHookOnFocus,!0);b.addEventListener("blur",b.__djiHookOnBlur,!0);b.addEventListener("select",b.__djiHookOnSelect,!0);b.addEventListener("mousedown",b.__djiHookOnMouseDown,!0);b.addEventListener("mouseup",b.__djiHookOnMouseUp,!0);b.addEventListener("keydown",b.__djiHookOnKeyDown,!0);b.addEventListener("keypress",b.__djiHookOnKeyPress,!0);b.addEventListener("keyup",b.__djiHookOnKeyUp,!0)}};
CWEChromeHookGeneric.prototype.__uninstallHooks=function(){for(var b=0;b<this.m_editors.length;b++){var a=this.m_editors[b].m_editor;void 0!==a.__djiHook&&null!==a.__djiHook&&(a.removeEventListener("focus",a.__djiHookOnFocus,!0),a.removeEventListener("blur",a.__djiHookOnBlur,!0),a.removeEventListener("select",a.__djiHookOnSelect,!0),a.removeEventListener("mousedown",a.__djiHookOnMouseDown,!0),a.removeEventListener("mouseup",a.__djiHookOnMouseUp,!0),a.removeEventListener("keydown",a.__djiHookOnKeyDown,
!0),a.removeEventListener("keypress",a.__djiHookOnKeyPress,!0),a.removeEventListener("keyup",a.__djiHookOnKeyUp,!0),a.__djiHookOnFocus=null,a.__djiHookOnBlur=null,a.__djiHookOnSelect=null,a.__djiHookOnMouseDown=null,a.__djiHookOnMouseUp=null,a.__djiHookOnKeyDown=null,a.__djiHookOnKeyPress=null,a.__djiHookOnKeyUp=null,a.__djiHook=null)}this.m_editors=[]};
CWEChromeHookGeneric.prototype.__findActiveEditorInfo=function(){for(let b=0;b<this.m_editors.length;b++){let a=this.m_editors[b];if(a.m_editor===a.m_document.activeElement){let c=document,d=!0;for(let f=0;d&&f<a.m_iframes.length;f++){let e=a.m_iframes[f];d=c.activeElement===e;if(!d){let g=e.getRootNode({composed:!1});g&&g.host&&g.activeElement===e&&g.host===c.activeElement&&(d=!0)}c=e.contentDocument}if(d)return a}}return null};
CWEChromeHookGeneric.prototype.__getEditorInfo=function(b){for(var a=0;a<this.m_editors.length;a++)if(this.m_editors[a].m_editor===b)return this.m_editors[a];return null};CWEChromeHookGeneric.prototype.__detectActiveEditor=function(b){var a=this.__findActiveEditorInfo();a=a?a.m_editor:null;if(this.m_isMicrosoftMail&&a&&"BODY"===a.tagName){var c=a.getBoundingClientRect();if(0>=c.width||0>=c.height)a=null}if(b){if(a)this.m_ime.onEditorChanged(this,a)}else this.m_ime.onEditorChanged(this,a)};
CWEChromeHookGeneric.prototype.setTrueKeyMode=function(){};CWEChromeHookGeneric.prototype.onFocus=function(b,a){this.m_writeTextTask&&this.m_writeTextTask.isRunning()||(this.m_ime.onEditorEvent(this,b,a),this.m_ime.onEditorChanged(this,b))};CWEChromeHookGeneric.prototype.onBlur=function(b,a){this.m_writeTextTask&&this.m_writeTextTask.isRunning()||(this.m_ime.onEditorEvent(this,b,a),this.m_ime.onEditorChanged(null,null))};
CWEChromeHookGeneric.prototype.onSelect=function(b,a){this.m_ime.onEditorEvent(this,b,a);this.m_ime.onContextChanged(this)};CWEChromeHookGeneric.prototype.onMouseDown=function(b,a){b.__djiLastEvent={clientX:a.clientX,clientY:a.clientY};this.m_ime.onEditorEvent(this,b,a)};CWEChromeHookGeneric.prototype.onMouseUp=function(b,a){this.m_ime.onEditorEvent(this,b,a);this.m_ime.onContextChanged(this)};
CWEChromeHookGeneric.prototype.onKeyDown=function(b,a){b.__djiLastEvent={keyCode:a.keyCode};this.m_writeTextTask&&this.m_writeTextTask.isRunning()||(this.m_ime.onEditorEvent(this,b,a),this.m_ime.onKeyDown(this,a)&&(a.stopPropagation(),a.preventDefault()))};CWEChromeHookGeneric.prototype.onKeyPress=function(b,a){this.m_writeTextTask&&this.m_writeTextTask.isRunning()||(this.m_ime.onEditorEvent(this,b,a),this.m_ime.onKeyPress(this,a)&&(a.stopPropagation(),a.preventDefault()))};
CWEChromeHookGeneric.prototype.onKeyUp=function(b,a){this.m_writeTextTask&&this.m_writeTextTask.isRunning()||(this.m_ime.onEditorEvent(this,b,a),this.m_ime.onKeyUp(this,a)&&(a.stopPropagation(),a.preventDefault()))};
CWEChromeHookGeneric.prototype.getCaret=function(b){let a={left:0,top:0,right:0,bottom:0},c=this.__getEditorInfo(b);if(null===c)return a;if(b=this.m_textareaCaretHelper.getCaretPosition(b))a=b;else{b=c.m_document.getSelection();const g=b.focusNode,h=b.focusOffset;try{var d=0<b.rangeCount?b.getRangeAt(0).cloneRange():null;!d&&g&&(d=document.createRange(),d.setStart(g,h),d.setEnd(g,h));let k=[];d&&(k=d.getClientRects(),0>=k.length&&0<h&&h<=g.childNodes.length&&(d.detach(),d.selectNode(g.childNodes[h-
1]),k=d.getClientRects()),d.detach());if(0<k.length){var f=k[k.length-1];a.left=f.right;a.top=f.top;a.right=0;a.bottom=f.bottom-f.top}else if(g){var e=g.nodeType===Node.TEXT_NODE?g.parentElement:g;const l=document.defaultView.getComputedStyle(e,null),m=e.getBoundingClientRect(),n=parseFloat(l.getPropertyValue("padding-left")),p=parseFloat(l.getPropertyValue("padding-top")),q=parseFloat(l.getPropertyValue("font-size"));a.left=Math.round(n+m.left+Math.max(0,(e.offsetWidth-e.clientWidth)/2));a.top=Math.round(p+
m.top+Math.max(0,(e.offsetHeight-e.clientHeight)/2));a.right=0;a.bottom=Math.round(1.14*q)}}catch(k){Logger.instance.error(k,g,h,b)}}a.left+=window.pageXOffset;a.top+=window.pageYOffset;if(0<c.m_iframes.length)for(d=0;d<c.m_iframes.length;d++)f=c.m_iframes[d],e=f.getBoundingClientRect(),a.left+=Math.round(e.left+Math.max(0,(f.offsetWidth-f.clientWidth)/2)),a.top+=Math.round(e.top+Math.max(0,(f.offsetHeight-f.clientHeight)/2));a.right=a.left+a.right;a.bottom=a.top+a.bottom;return a};
CWEChromeHookGeneric.prototype.getContext=function(b){let a={selection:{start:0,length:0},text:null,custom:null};if(!b)return a;void 0!==b.selectionStart?(b=this.__getContextFromInput(b,null),a.text=b.text,a.selection.start=b.selection.start,a.selection.length=b.selection.length,a.custom=b.custom,a.extended=b.extended):(b=this.__getContextFromContentEditable(b,null),a.text=b.text,a.selection.start=b.selection.start,a.selection.length=b.selection.length,a.custom=b.custom,a.extended=b.extended);return a};
CWEChromeHookGeneric.prototype.__getContextFromInput=function(b,a){a=window.dji.utils.htmlToUnicode(b.value);b={selection:{start:b.selectionStart,length:b.selectionEnd-b.selectionStart},text:a,custom:{selectionOffset:0},extended:{text:a,selection:{start:b.selectionStart,length:b.selectionEnd-b.selectionStart}}};if(0<b.text.length){a=b.text.lastIndexOf("\n",b.selection.start-1);var c=b.text.indexOf("\n",b.selection.start+b.selection.length),d=Math.max(0,b.selection.start-160),f=Math.min(b.text.length,
b.selection.start+b.selection.length+32);for(a=Math.max(a,b.selection.start-128);a>=d&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(b.text.charAt(a));a--);a++;for(c=Math.min(b.text.length,Math.max(c,b.selection.start+b.selection.length+10));c<f&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(b.text.charAt(c));c++);b.text=a<c?b.text.slice(a,c):"";b.selection.start-=a;b.custom.selectionOffset=a;a=Math.max(0,b.text.lastIndexOf("\n",a-1));c-a<b.text.length&&(b.extended.selection.start-=
a,b.extended.custom.selectionOffset=a,b.extended.text=b.extended.text.slice(a,c))}return b};
CWEChromeHookGeneric.prototype.__getContextFromContentEditable=function(b,a){b=this.__mapContentFromContentEditable(b,a);b={selection:b.selection,text:b.text,custom:{map:b.map,selectionOffset:0},extended:{text:b.text,selection:{start:b.selection.start,length:b.selection.length}}};if(0<b.text.length){a=b.text.lastIndexOf("\n",b.selection.start-1);var c=b.text.indexOf("\n",b.selection.start+b.selection.length),d=Math.max(0,b.selection.start-160),f=Math.min(b.text.length,b.selection.start+b.selection.length+
32);for(a=Math.max(a,b.selection.start-128);a>=d&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(b.text.charAt(a));a--);a++;for(c=Math.min(b.text.length,Math.max(c,b.selection.start+b.selection.length+10));c<f&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(b.text.charAt(c));c++);b.text=a<c?b.text.slice(a,c):"";b.selection.start-=a;b.custom.selectionOffset=a;a=Math.max(0,b.text.lastIndexOf("\n",a-1));c-a<b.text.length&&(b.extended.selection.start-=a,b.extended.custom.selectionOffset=
a,b.extended.text=b.extended.text.slice(a,c))}return b};
CWEChromeHookGeneric.prototype.__mapContentFromContentEditable=function(b,a){var c=this.__getEditorInfo(b);if(null===c)return{selection:{start:0,length:0},text:"",map:[]};c=c.m_document.getSelection();if(0>=c.rangeCount)return{selection:{start:0,length:0},text:"",map:[]};var d=c.getRangeAt(0);c={selection:{start:0,length:0},text:"",map:[],params:{startContainer:d.startContainer,startOffset:d.startOffset,endContainer:d.endContainer,endOffset:d.endOffset,selection:c,range:d,prevNode:null,stop:!1}};
1===c.params.startContainer.nodeType&&0<c.params.startOffset&&(c.params.startContainer=c.params.startContainer.childNodes[c.params.startOffset-1]);1===c.params.endContainer.nodeType&&0<c.params.endOffset&&(c.params.endContainer=c.params.endContainer.childNodes[c.params.endOffset-1]);this.__mapContentFromContentEditableUsingParams(b,c,a);b={selection:c.selection,text:window.dji.utils.htmlToUnicode(c.text),map:c.map};b.selection.length-=b.selection.start;return b};
CWEChromeHookGeneric.prototype.__mapContentFromContentEditableUsingParams=function(b,a,c=null){for(var d=b.childNodes,f=0;!a.params.stop&&f<d.length;f++){var e=d[f],g=e.tagName,h=e.nodeType;if("STYLE"!==g&&"SCRIPT"!==g){null!==c&&(Logger.instance.log(c+f+": tag = "+e.tagName+", id = "+e.id+", type = "+e.nodeType+", text = #"+e.textContent+"#"),Logger.instance.log(e));null!==a.params.prevNode&&(this.__tagNameRequiresNewLine(g)||3==h&&this.__tagNameRequiresNewLine(a.params.prevNode.tagName))&&(a.text+=
"\n",a.map.push({element:a.params.prevNode,offset:a.params.prevNode.childNodes.length,text:"\n",embeded:!0}),null!=a.params.startContainer&&(a.selection.start+=1),null!=a.params.endContainer&&(a.selection.length+=1));if(a.params.startContainer&&a.params.startContainer===e||a.params.endContainer&&a.params.endContainer===e){g=3==h?e.textContent:" ";var k=3==h?a.params.startOffset:1,l=3==h?a.params.endOffset:1;if(3==h)for(h=0;h<g.length;h++)a.map.push({element:e,offset:h,text:g.charAt(h),embeded:!1});
else a.map.push({element:b,offset:f+1,text:" ",embeded:!0});a.text+=g;a.params.startContainer===e&&(a.selection.start+=k,a.params.startContainer=null,null!==c&&(Logger.instance.log(c+f+": start found = "+e.tagName+", text = #"+e.textContent+"#"),Logger.instance.log(c+f+": all text = #"+a.text+"#")));a.params.endContainer===e?(a.selection.length+=l,a.params.endContainer=null,null!==c&&(Logger.instance.log(c+f+": end found = "+e.tagName+", text = #"+e.textContent+"#"),Logger.instance.log(c+f+": all text = #"+
a.text+"#"))):a.params.endContainer&&(a.selection.length+=g.length)}else if(3==h){g=e.textContent;a.text+=g;for(h=0;h<g.length;h++)a.map.push({element:e,offset:h,text:g.charAt(h),embeded:!1});null!=a.params.startContainer&&(a.selection.start+=g.length);null!=a.params.endContainer&&(a.selection.length+=g.length)}else 1==h&&("IMG"===g?(a.text+=" ",a.map.push({element:b,offset:f+1,text:" ",embeded:!0}),null!=a.params.startContainer&&(a.selection.start+=1),null!=a.params.endContainer&&(a.selection.length+=
1)):this.__mapContentFromContentEditableUsingParams(e,a,null===c?null:"  "+c));a.params.prevNode=e}}};CWEChromeHookGeneric.prototype.__tagNameRequiresNewLine=function(b){return"P"===b||"DIV"===b||"LI"===b||"TD"===b};CWEChromeHookGeneric.prototype.replaceText=function(b,a,c){let d=this.__getEditorInfo(b);null!==d&&(void 0!==b.selectionStart?this.__replaceTextInInput(d,a,c):this.__replaceTextInContentEditable(d,a,c))};
CWEChromeHookGeneric.prototype.__replaceTextInInput=function(b,a,c){var d=c.custom.selectionOffset+a.selection.start;c=c.custom.selectionOffset;a.selection.hasOwnProperty("end")&&!isNaN(a.selection.end)?c+=a.selection.end:a.selection.hasOwnProperty("length")&&!isNaN(a.selection.length)&&(c+=a.selection.start+a.selection.length);b.m_editor.setSelectionRange(d,c);b.m_document.execCommand("insertHTML",!1,a.text)};
CWEChromeHookGeneric.prototype.__replaceTextInContentEditable=function(b,a,c){if(a.selection.start<a.selection.end){var d=b.m_document.getSelection();try{var f=c.custom.selectionOffset+a.selection.start,e=c.custom.selectionOffset+a.selection.end-1,g=0;c.custom.map[e].embeded&&(f==e&&(g=1,f--),e--);var h=c.custom.map[f];d.extend(b.m_editor,0);d.collapseToStart();d.extend(h.element,h.offset+g);d.collapseToEnd();if(f<=e){var k=c.custom.map[e];d.extend(k.element,k.offset+g+1)}}catch(l){Logger.instance.log(d),
Logger.instance.log(l)}}this.m_isTwitter||this.m_isFacebook?(this.m_writeTextTask?this.m_writeTextTask.isRunning()&&(window.dji.logger.warn("Already writing text!"),this.m_writeTextTask.cancel()):this.m_writeTextTask=new window.cwe.ime.tasks.WriteTextTwitterIMETask(this.m_ime),this.m_writeTextTask.run({document:b.m_document,editor:b.m_editor,input:a.text})):b.m_document.execCommand("insertText",!1,a.text)};
CWEChromeHookGeneric.prototype.getContextForMomentaryTopic=function(b,a){Logger.instance.log("---------------------------- CWEChromeHookGeneric.getContextForMomentaryTopic");Logger.instance.log(b);a(CWEChromeUtilities.extractVisibleTextFromElement(document.body))};CWEChromeHookGeneric.prototype.acquireTextForTopicAsync=async function(b){return new Promise(function(a){let c="selection"===b?document.getSelection().toString():CWEChromeUtilities.extractVisibleTextFromElement(document.body);a(c)})};
CWEChromeHookGeneric.prototype.shouldIgnoreMutations=function(b){let a=!0;for(let d=0;d<b.length;d++){let f=b[d],e=f.target.ownerDocument;if(e.querySelector("#__dji_sru_main_container_content")){a=!1;break}let g=!1;for(var c=0;c<f.addedNodes.length&&!g;c++)0<e.evaluate("count(descendant-or-self::*[@contenteditable]|descendant-or-self::input|descendant-or-self::textarea)",f.addedNodes[c],null,XPathResult.NUMBER_TYPE).numberValue&&(g=!0);for(c=0;c<f.removedNodes.length&&!g;c++)0<e.evaluate("count(descendant-or-self::*[@contenteditable]|descendant-or-self::input|descendant-or-self::textarea)",
f.removedNodes[c],null,XPathResult.NUMBER_TYPE).numberValue&&(g=!0);if(g){a=!1;break}}return a};
