window.CWEChromeHookOffice365=function(){class e{constructor(a,b){this.m_installed=!1;this.m_ime=a;this.m_messageProxy=b;this.m_editor=b.window;this.m_hasFocus=!1;this.m_cache={cursor:void 0,context:void 0};this.__initialize()}__initialize(){let a=this;this.m_messageProxy.on(window.dji.utils.MessageProxy.MSG_SRV_DISCONNECT,function(){a.m_installed&&(a.m_hasFocus=!1,a.m_ime&&a.m_ime.serviceUnavailable(a.m_messageProxy.service,a))});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.ready",
function(){if(a.m_installed&&a.m_ime)a.m_ime.onCapabilitiesUpdate(this,"office365-word-document")});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.focus",function(){if(a.m_installed)a.onFocus(a.m_editor)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.blur",function(){if(a.m_installed)a.onBlur(a.m_editor)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.cursor",function(b,c){if(a.m_installed)a.onCursorAvailable(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.context",
function(b,c){if(a.m_installed)a.onContextAvailable(a.m_editor,c,!0)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.trueKeyMode",function(){if(a.m_installed)a.onToggleTrueKeyMode()});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.digitKey",function(b,c){if(a.m_installed)a.onDigitKey(c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keydown",function(b,c){if(a.m_installed)a.onKeyDown(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keypress",
function(b,c){if(a.m_installed)a.onKeyPress(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keyup",function(b,c){if(a.m_installed)a.onKeyUp(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.input",function(b,c){if(a.m_installed)a.onInput(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.mousedown",function(b,c){if(a.m_installed)a.onMouseDown(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.mouseup",
function(b,c){if(a.m_installed)a.onMouseUp(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.event",function(b,c){if(a.m_installed)a.onEvent(a.m_editor,c)});this.m_messageProxy.enable(!0)}install(){this.m_installed||(this.m_installed=!0,this.m_messageProxy.send("com.donjohnston.cwu.office365.word.activate",void 0,!0),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.cursor"),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.context"),DexController.instance.setCursorInfoDelegate(this.getCaret.bind(this)))}uninstall(){this.m_installed&&
(DexController.instance.setCursorInfoDelegate(null),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.activate",void 0,!1),this.m_installed=!1)}reload(){if(this.m_hasFocus)this.m_ime.onEditorChanged(this,this.m_editor)}setTrueKeyMode(a){this.m_installed&&this.m_messageProxy.send("com.donjohnston.cwu.office365.word.trueKeyMode",void 0,a)}setHighlightMode(a,b){this.m_installed&&this.m_messageProxy.send("com.donjohnston.cwu.office365.word.highlightMode",void 0,a,b)}setOptions(a){this.m_installed&&
this.m_messageProxy.send("com.donjohnston.cwu.office365.word.options",void 0,a)}onFocus(a,b){this.m_hasFocus=!0;this.m_ime&&(this.m_ime.onEditorEvent(this,a,b||{type:"focus",isTrusted:!0}),this.m_ime.onEditorChanged(this,this.m_editor))}onBlur(a,b){this.m_hasFocus=!1;this.m_ime&&(this.m_ime.onEditorEvent(this,a,b||{type:"blur",isTrusted:!0}),this.m_ime.onEditorChanged(null,null))}onCursorAvailable(a,b){this.m_cache.cursor=b;if(this.m_hasFocus&&this.m_ime)this.m_ime.onContextChanged(this)}onContextAvailable(a,
b,c){a=c&&(!this.m_cache||b&&this.m_cache.context&&this.m_cache.context.session!==b.session);this.m_cache.context=b;if(a&&this.m_hasFocus&&this.m_ime)this.m_ime.onContextChanged(this)}onMouseDown(a,b){}onMouseUp(a,b){}onEvent(a,b){if(this.m_ime)this.m_ime.onEditorEvent(this,a,b)}onKeyDown(a,b){b.skipHandleInput=!0;this.m_ime&&(this.m_ime.onEditorEvent(this,a,b||{type:"keydown"}),this.m_ime.onKeyDown(this,b))}onKeyPress(a,b){b.skipHandleInput=!0;this.m_ime&&(this.m_ime.onEditorEvent(this,a,b||{type:"keypress"}),
this.m_ime.onKeyPress(this,b))}onKeyUp(a,b){b.skipHandleInput=!0;this.m_ime&&(this.m_ime.onEditorEvent(this,a,b||{type:"keyup"}),this.m_ime.onKeyUp(this,b))}onInput(a,b){b.skipHandleInput=!0;if(this.m_ime)this.m_ime.onInput(this,b)}onToggleTrueKeyMode(){this.m_ime&&this.m_ime.__toggleTruKeyMode(this)}onDigitKey(a){if(this.m_ime)this.m_ime.onDigitKey(this,a)}getCaret(a){return this.m_cache.cursor||{left:0,top:0,right:0,bottom:10}}getContext(a,b){return b||!this.m_cache.context?new Promise(c=>{this.m_messageProxy.send("com.donjohnston.cwu.office365.word.context",
d=>{this.onContextAvailable(this.m_editor,d,!1);c(this.__getContextFromCache())})}):this.__getContextFromCache()}__getContextFromCache(){let a={session:-1,selection:{start:0,length:0},text:"",extended:{text:"",selection:{start:0,length:0}}};this.m_cache.context&&(a.session=this.m_cache.context.session,a.text=this.m_cache.context.text,a.selection.start=this.m_cache.context.selection.start,a.selection.end=this.m_cache.context.selection.start+this.m_cache.context.selection.length,a.selection.length=
this.m_cache.context.selection.length,a.extended.text=this.m_cache.context.text,a.extended.selection.start=this.m_cache.context.selection.start,a.extended.selection.length=this.m_cache.context.selection.length);return a}replaceText(a,b,c,d){this.m_installed&&this.m_cache.context?(b.session=this.m_cache.context.session,this.m_messageProxy.send("com.donjohnston.cwu.office365.word.replaceText",d,b)):d("")}replaceTextAsync(a,b,c){return new Promise(d=>this.replaceText(a,b,c,d))}getContextForMomentaryTopic(a,
b){this.m_installed?this.m_messageProxy.send("com.donjohnston.cwu.office365.word.text",function(c){b(c||"")}):b("")}async acquireTextForTopicAsync(a){const b=this;return new Promise(function(c){b.m_messageProxy.send("com.donjohnston.cwu.office365.word.text",c,a)})}shouldIgnoreMutations(a){return!0}}return e}();
