function CWEChromeHookGoogleDocs(a,b){this.m_ime=a;this.m_hookOnContextMenu=this.m_hookOnScroll=this.m_hookOnKeyUp=this.m_hookOnKeyPress=this.m_hookOnKeyDown=this.m_hookOnMouseUp=this.m_hookOnMouseDown=this.m_hookOnSelect=this.m_hookOnBlur=this.m_hookOnFocus=this.m_contextMenuRemovePersonalWords=this.m_contextMenuAddPersonalWords=this.m_contextMenuStopSpeak=this.m_contextMenuStartSpeak=this.m_contextMenuCoWriterSubmenu=this.m_contextMenuCoWriter=this.m_contextMenuSeparator=this.m_contextMenu=this.m_selectionOverlays=
this.m_appViewEditor=this.m_appView=this.m_textEventTargetDoc=this.m_textEventTargetIframe=this.m_caret=this.m_cursor=null;this.m_forwardEvents=!0;this.m_lastKeyPressTimestamp=void 0;this.m_watchKeyCodes=new Set(["Backspace","Delete","Tab","Enter"]);this.m_textMapperAdapter=this.m_embededIds=this.m_range=this.m_windowProxy=null;this.__initialize(b);return this}
CWEChromeHookGoogleDocs.prototype.__initialize=function(a){a=a||document.documentElement;var b=a.getRootNode(),c=a.ownerDocument;this.__findEditorElements();this.m_windowProxy=document.querySelector("dji-cowriter");this.m_range=document.createRange();this.m_embededIds=new Set(["docs-smartcompose-suggestion-id"]);(b=b.getElementById("__DJI_CWE_CHROME_GOOGLE_DOCS_SERVERSIDE"))?(b=new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(b)):(b=c.createElement("script"),b.id="__DJI_CWE_CHROME_GOOGLE_DOCS_SERVERSIDE",
b.type="text/javascript",b.async=!0,b.src=chrome.extension.getURL("ContentScripts/cweEventDispatcherGD.js"),b.onload=function(){Logger.instance.log("Co:Writer Javascript for Google Docs downloaded!")},a.appendChild(b));c=c.createElement("style");c.setAttribute("type","text/css");c.setAttribute("id","__DJI_CWE_CSS_DYN");c.textContent=".__dji_cwe_icon {width: 21px; height: 19px; margin-top: 2px;background: url('"+chrome.extension.getURL("Graphics/CoWriterIcon-16x16.png")+"') no-repeat !important;}";
a.appendChild(c);this.m_hookOnContextMenu=d=>this.onContextMenu(this.m_appViewEditor,d);document.addEventListener("contextmenu",this.m_hookOnContextMenu)};
CWEChromeHookGoogleDocs.prototype.__findEditorElements=function(){if(this.m_textEventTargetIframe=document.getElementsByClassName("docs-texteventtarget-iframe")[0])this.m_textEventTargetDoc=this.m_textEventTargetIframe.contentDocument,this.m_appView=document.getElementById("kix-appview"),this.m_appViewEditor=this.m_appView.getElementsByClassName("kix-appview-editor")[0],this.m_selectionOverlays=this.m_appView.getElementsByClassName("kix-selection-overlay"),this.m_cursor=this.m_appView.getElementsByClassName("kix-cursor")[0],
this.m_caret=this.m_appView.getElementsByClassName("kix-cursor-caret")[0],Logger.instance.log(this.m_textEventTargetIframe),Logger.instance.log(this.m_textEventTargetDoc),Logger.instance.log(this.m_appView),Logger.instance.log(this.m_appViewEditor),Logger.instance.log(this.m_selectionOverlays),Logger.instance.log(this.m_cursor),Logger.instance.log(this.m_caret)};
CWEChromeHookGoogleDocs.prototype.install=function(a){this.__findEditorElements();null===this.m_hookOnFocus&&(this.m_hookOnFocus=b=>{if(this.m_forwardEvents)this.onFocus(this.m_appViewEditor,b)},this.m_hookOnBlur=b=>{if(this.m_forwardEvents)this.onBlur(this.m_appViewEditor,b)},this.m_hookOnSelect=b=>{if(this.m_forwardEvents)this.onSelect(this.m_appViewEditor,b)},this.m_hookOnMouseDown=b=>{if(this.m_forwardEvents)this.onMouseDown(this.m_appViewEditor,b)},this.m_hookOnMouseUp=b=>{if(this.m_forwardEvents)this.onMouseUp(this.m_appViewEditor,
b)},this.m_hookOnKeyDown=b=>{if(this.m_forwardEvents)this.onKeyDown(this.m_appViewEditor,b);this.m_watchKeyCodes.has(b.code)&&(this.m_lastKeyPressTimestamp=Date.now())},this.m_hookOnKeyPress=b=>{if(this.m_forwardEvents)this.onKeyPress(this.m_appViewEditor,b);this.m_lastKeyPressTimestamp=Date.now()},this.m_hookOnKeyUp=b=>{if(this.m_forwardEvents)this.onKeyUp(this.m_appViewEditor,b)},this.m_hookOnScroll=b=>{if(this.m_forwardEvents)this.onScroll(this.m_appViewEditor,b)});if(this.__appViewIsVisible())a=
new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(a),this.__installHooks(),this.m_ime.onEditorChanged(this,this.m_appViewEditor);else this.m_ime.onEditorChanged(null,null)};CWEChromeHookGoogleDocs.prototype.uninstall=function(){this.__uninstallHooks()};
CWEChromeHookGoogleDocs.prototype.reload=function(a){this.__uninstallHooks();this.__findEditorElements();if(this.__appViewIsVisible())a=new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(a),Logger.instance.log(this.m_appView),Logger.instance.log(this.m_appView.style.display),this.__installHooks(),this.m_ime.onEditorChanged(this,this.m_appViewEditor);else this.m_ime.onEditorChanged(null,null)};CWEChromeHookGoogleDocs.prototype.setTrueKeyMode=function(){};
CWEChromeHookGoogleDocs.prototype.getState=function(){var a=this.__appViewIsVisible();return{active:a,hook:a?this:null,editor:a?this.m_appViewEditor:null}};CWEChromeHookGoogleDocs.prototype.__appViewIsVisible=function(){var a=document.defaultView.getComputedStyle(this.m_appView),b=a.getPropertyValue("display");a=a.getPropertyValue("visibility");return"none"!==b&&"hidden"!==a};CWEChromeHookGoogleDocs.prototype.__findEditableElements=function(a,b){};
CWEChromeHookGoogleDocs.prototype.__validateEditor=function(a){};CWEChromeHookGoogleDocs.prototype.__validateIframe=function(a){};
CWEChromeHookGoogleDocs.prototype.__installHooks=function(){this.m_textEventTargetDoc.addEventListener("keydown",this.m_hookOnKeyDown,!0);this.m_textEventTargetDoc.addEventListener("keypress",this.m_hookOnKeyPress,!0);this.m_textEventTargetDoc.addEventListener("keyup",this.m_hookOnKeyUp,!0);this.m_textEventTargetDoc.addEventListener("focus",this.m_hookOnFocus,!0);this.m_textEventTargetDoc.addEventListener("blur",this.m_hookOnBlur,!0);this.m_appViewEditor.addEventListener("mousedown",this.m_hookOnMouseDown,
!0);this.m_appViewEditor.addEventListener("mouseup",this.m_hookOnMouseUp,!0)};
CWEChromeHookGoogleDocs.prototype.__uninstallHooks=function(){this.m_textEventTargetDoc&&(this.m_textEventTargetDoc.removeEventListener("keydown",this.m_hookOnKeyDown,!0),this.m_textEventTargetDoc.removeEventListener("keypress",this.m_hookOnKeyPress,!0),this.m_textEventTargetDoc.removeEventListener("keyup",this.m_hookOnKeyUp,!0),this.m_textEventTargetDoc.removeEventListener("focus",this.m_hookOnFocus,!0),this.m_textEventTargetDoc.removeEventListener("blur",this.m_hookOnBlur,!0),this.m_textEventTargetDoc=
null);this.m_appViewEditor&&(this.m_appViewEditor.removeEventListener("mousedown",this.m_hookOnMouseDown,!0),this.m_appViewEditor.removeEventListener("mouseup",this.m_hookOnMouseUp,!0))};CWEChromeHookGoogleDocs.prototype.onFocus=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onEditorChanged(this,a)};CWEChromeHookGoogleDocs.prototype.onBlur=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onEditorChanged(this,null)};
CWEChromeHookGoogleDocs.prototype.onSelect=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onContextChanged(this)};CWEChromeHookGoogleDocs.prototype.onMouseDown=function(a,b){this.m_ime.onEditorEvent(this,a,b)};CWEChromeHookGoogleDocs.prototype.onMouseUp=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onContextChanged(this)};CWEChromeHookGoogleDocs.prototype.onKeyDown=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onKeyDown(this,b)&&(b.stopPropagation(),b.preventDefault())};
CWEChromeHookGoogleDocs.prototype.onKeyPress=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onKeyPress(this,b)&&(b.stopPropagation(),b.preventDefault())};CWEChromeHookGoogleDocs.prototype.onKeyUp=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onKeyUp(this,b)&&(b.stopPropagation(),b.preventDefault())};CWEChromeHookGoogleDocs.prototype.onScroll=function(a,b){this.m_ime.onEditorEvent(this,a,b);this.m_ime.onContextChanged(this)};
CWEChromeHookGoogleDocs.prototype.onContextMenu=function(a,b){for(a=b.toElement;a&&a!==this.m_appViewEditor;a=a.parentElement);a&&(a=this.__getContextMenu(),Logger.instance.log("--------------------------------------------------- CWEChromeHookGoogleDocs.onContextMenu"),Logger.instance.log(b),Logger.instance.log(a))};
CWEChromeHookGoogleDocs.prototype.__getContextMenu=function(){if(null===this.m_contextMenu)for(var a=document.getElementsByClassName("goog-menu"),b=0;b<a.length;b++){var c=a[b].getAttribute("role"),d=parseInt(a[b].getAttribute("tabindex"));if("menu"===c&&0===d){this.m_contextMenu=a[b];this.__buildContextMenu();break}}return this.m_contextMenu};
CWEChromeHookGoogleDocs.prototype.__buildContextMenu=function(){var a=this;if(null===this.m_contextMenuCoWriter){this.m_contextMenuSeparator=this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP");this.m_contextMenuCoWriter=this.__createCoWriterMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_SM");this.m_contextMenuCoWriterSubmenu=this.__createSubmenu();this.m_contextMenuStartSpeak=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_STARTSPEAK","Speak");this.m_contextMenuStopSpeak=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_STOPSPEAK",
"Stop Speak");var b=this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP_SPEAK");this.m_contextMenuAddPersonalWords=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_APW","Add Personal Words");this.m_contextMenuRemovePersonalWords=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_RPW","Remove Personal Words");this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP_PW");this.m_contextMenu.addEventListener("mouseover",function(c){a.m_contextMenuCoWriter.__mouseOver||(a.m_contextMenuCoWriterSubmenu.style.display=
"none",window.dji.utils.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight"))});this.m_contextMenu.addEventListener("blur",function(c){a.m_contextMenuCoWriterSubmenu.style.display="none";window.dji.utils.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight")});this.m_contextMenu.addEventListener("keydown",function(c){a.m_contextMenuCoWriterSubmenu.style.display="none";window.dji.utils.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight")});
this.m_contextMenuCoWriterSubmenu.addEventListener("mouseover",function(c){a.m_contextMenuCoWriterSubmenu.__mouseOver=!0});this.m_contextMenuCoWriterSubmenu.addEventListener("mouseout",function(c){a.m_contextMenuCoWriterSubmenu.__mouseOver=!1});this.m_contextMenuCoWriter.addEventListener("mouseover",function(c){a.m_contextMenuCoWriter.__mouseOver=!0;a.m_contextMenuCoWriter.__mouseOutHandler&&null!==a.m_contextMenuCoWriter.__mouseOutHandler&&(clearTimeout(a.m_contextMenuCoWriter.__mouseOutHandler),
a.m_contextMenuCoWriter.__mouseOutHandler=null);c=a.m_contextMenu.querySelectorAll("div.goog-menuitem-highlight");for(var d=0;d<c.length;d++)c[d]!==a.m_contextMenuCoWriter&&window.dji.utils.removeClassFromElement(c[d],"goog-menuitem-highlight");a.m_contextMenu.setAttribute("aria-activedescendant",a.m_contextMenuCoWriter.id);window.dji.utils.addClassToElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight");c=a.m_contextMenuCoWriter.getBoundingClientRect();a.m_contextMenuCoWriterSubmenu.style.left=
c.right+"px";a.m_contextMenuCoWriterSubmenu.style.top=c.top-7+"px";a.m_contextMenuCoWriterSubmenu.style.display=""},!0);this.m_contextMenuCoWriter.addEventListener("mouseout",function(c){a.m_contextMenuCoWriter.__mouseOutHandler=setTimeout(function(){a.m_contextMenuCoWriter.__mouseOver=!1;!1===a.m_contextMenuCoWriterSubmenu.__mouseOver&&(a.m_contextMenuCoWriterSubmenu.style.display="none",a.m_contextMenu.removeAttribute("aria-activedescendant"),window.dji.utils.removeClassFromElement(a.m_contextMenuCoWriter,
"goog-menuitem-highlight"))},10)},!0);this.m_contextMenuCoWriter.addEventListener("mousedown",function(c){c.stopPropagation();c.preventDefault()},!0);this.m_contextMenuStartSpeak.addEventListener("mouseover",function(c){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",a.m_contextMenuStartSpeak.id);window.dji.utils.addClassToElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight")});this.m_contextMenuStartSpeak.addEventListener("mouseout",function(c){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");
window.dji.utils.removeClassFromElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight")});this.m_contextMenuStartSpeak.addEventListener("mousedown",function(c){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");window.dji.utils.removeClassFromElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight");a.__contextMenuStartSpeak()});this.m_contextMenuStopSpeak.addEventListener("mouseover",function(c){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",
a.m_contextMenuStopSpeak.id);window.dji.utils.addClassToElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight")});this.m_contextMenuStopSpeak.addEventListener("mouseout",function(c){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");window.dji.utils.removeClassFromElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight")});this.m_contextMenuStopSpeak.addEventListener("mousedown",function(c){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");
window.dji.utils.removeClassFromElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight");a.__contextMenuStopSpeak()});this.m_contextMenuAddPersonalWords.addEventListener("mouseover",function(c){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",a.m_contextMenuAddPersonalWords.id);window.dji.utils.addClassToElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight")});this.m_contextMenuAddPersonalWords.addEventListener("mouseout",function(c){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");
window.dji.utils.removeClassFromElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight")});this.m_contextMenuAddPersonalWords.addEventListener("mousedown",function(c){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");window.dji.utils.removeClassFromElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight");a.__contextMenuAddPersonalWords()});this.m_contextMenuRemovePersonalWords.addEventListener("mouseover",function(c){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",
a.m_contextMenuRemovePersonalWords.id);window.dji.utils.addClassToElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight")});this.m_contextMenuRemovePersonalWords.addEventListener("mouseout",function(c){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");window.dji.utils.removeClassFromElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight")});this.m_contextMenuRemovePersonalWords.addEventListener("mousedown",function(c){a.m_contextMenu.style.display=
"none";a.m_contextMenu.removeAttribute("aria-activedescendant");window.dji.utils.removeClassFromElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight");a.__contextMenuRemovePersonalWords()});this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuStartSpeak);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuStopSpeak);this.m_contextMenuCoWriterSubmenu.appendChild(b);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuAddPersonalWords);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuRemovePersonalWords);
document.body.appendChild(this.m_contextMenuCoWriterSubmenu);a.m_contextMenu.insertBefore(this.m_contextMenuSeparator,a.m_contextMenu.children[0]);a.m_contextMenu.insertBefore(this.m_contextMenuCoWriter,a.m_contextMenu.children[0])}};
CWEChromeHookGoogleDocs.prototype.__createCoWriterMenuItem=function(a){var b=document.createElement("div");b.id=a;b.className="goog-menuitem goog-submenu";b.setAttribute("aria-haspopup","true");b.setAttribute("role","menuitem");b.setAttribute("style","-webkit-user-select: none;");b.innerHTML='<div class="docs-icon goog-inline-block goog-menuitem-icon" style="-webkit-user-select: none;"><div class="__dji_cwe_icon" style="-webkit-user-select: none;"></div></div><div class="goog-menuitem-content"><span aria-label="CoWriter;" style="-webkit-user-select: none;">Co:Writer</span><span class="goog-submenu-arrow" style="-webkit-user-select: none;">&#9658;</span></div>';
return b};CWEChromeHookGoogleDocs.prototype.__createSimpleMenuItem=function(a,b){var c=document.createElement("div");c.id=a;c.className="goog-menuitem";c.setAttribute("role","menuitem");c.setAttribute("style","-webkit-user-select: none;");c.innerHTML='<div class="goog-menuitem-content">'+b+"</div>";return c};
CWEChromeHookGoogleDocs.prototype.__createSeparatorMenuItem=function(a){var b=document.createElement("div");b.id=a;b.className="goog-menuseparator";b.setAttribute("role","separator");b.setAttribute("aria-hidden","true");b.setAttribute("style","-webkit-user-select: none;");return b};
CWEChromeHookGoogleDocs.prototype.__createSubmenu=function(){var a=document.createElement("div");a.className="goog-menu goog-menu-vertical goog-menu-noaccel docs-menu-hide-mnemonics";a.setAttribute("aria-haspopup","true");a.setAttribute("role","menu");a.setAttribute("style","-webkit-user-select: none; left: 0px; top: 0px; display: none;");return a};CWEChromeHookGoogleDocs.prototype.__contextMenuStartSpeak=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onSpeak(a)};
CWEChromeHookGoogleDocs.prototype.__contextMenuStopSpeak=function(){this.m_ime.onStopSpeak()};CWEChromeHookGoogleDocs.prototype.__contextMenuAddPersonalWords=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onAddPersonalWords(a)};CWEChromeHookGoogleDocs.prototype.__contextMenuRemovePersonalWords=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onRemovePersonalWords(a)};
CWEChromeHookGoogleDocs.prototype.__getSelectedText=function(){var a=this.getContext(this.m_appViewEditor);Logger.instance.log(a);return 0<a.text.length&&0<a.selection.length?a.text.substring(a.selection.start,a.selection.start+a.selection.length):""};
CWEChromeHookGoogleDocs.prototype.getCaret=function(a){a=this.m_cursor?this.m_cursor.getBoundingClientRect():this.m_appView.getElementsByClassName("kix-cursor")[0].getBoundingClientRect();const b=this.m_caret?this.m_caret.getBoundingClientRect():this.m_appView.getElementsByClassName("kix-cursor-caret")[0].getBoundingClientRect();return{left:a.left,top:b.top,right:a.right,bottom:b.bottom}};
CWEChromeHookGoogleDocs.prototype.getContext=function(a){var b=this.__getSelectionOverlayInfo(),c=b.first;a=b.last;var d=c.left,k=a.right;const g=this.__getSourandingLines(b,1,1);if(0>=g.lines.length)return this.m_textMapperAdapter||(this.m_textMapperAdapter=new window.dji.cwe.DocumentTextMapperAdapter),(a=this.m_textMapperAdapter.mapContextForPredictions())&&a.isLayered&&(a.updateInProgress||this.m_lastKeyPressTimestamp&&(!a.updatedAt||a.updatedAt<this.m_lastKeyPressTimestamp))&&(a.__unstable=!0),
a;const e={selection:{start:0,length:0},text:"",custom:{embeddedLocations:{}},extended:{text:"",selection:{start:0,length:0}}};for(var h=this.__getChunksFromLine(g.lines[g.firstLineIndex]),l,m=-1,f=0;f<h.length;f++)if(l=h[f].chunk.getBoundingClientRect(),l.left<=d&&d<=l.right){m=f;break}-1===m&&0<h.length&&(m=h.length);for(f=0;f<=g.firstLineIndex;f++)if(0<f&&(e.selection.start+=1,e.selection.length+=1),f<g.firstLineIndex)d=this.__computeTextLengthOfLine(g.lines[f]),e.selection.start+=d,e.selection.length+=
d;else for(d=0;d<m;d++)1===h[d].type&&(0<h[d].paddingLeft&&(e.selection.start+=1),e.selection.start+=this.__computeTextLengthOfChunk(h[d]));g.extras&&(f=g.extras.firstLineIndex-g.firstLineIndex,0<f&&(f=g.extras.lines.slice(Math.max(0,f-5),f),e.extended.text=this.__computeText(f,null)));e.text=this.__computeText(g.lines,e.custom.embeddedLocations);0<=m&&m<h.length?(0<h[m].paddingLeft&&(e.selection.start+=1),e.selection.start+=this.__measureTextBlock(h[m],c.left,c.top)):h.length<=m&&(e.selection.start+=
1,e.text+=" ");if(b.isSelection){b=this.__getChunksFromLine(g.lines[g.lastLineIndex]);c=-1;for(f=0;f<b.length;f++)if(h=b[f].chunk.getBoundingClientRect(),h.left<=k&&k<=h.right){c=f;break}-1===c&&0<b.length&&(c=b.length);if(g.firstLineIndex==g.lastLineIndex)for(d=0;d<c;d++)e.selection.length+=this.__computeTextLengthOfChunk(b[d]);else for(f=g.firstLineIndex;f<=g.lastLineIndex;f++)if(f>g.firstLineIndex&&(e.selection.length+=1),f<g.lastLineIndex)e.selection.length+=this.__computeTextLengthOfLine(g.lines[f]);
else for(d=0;d<c;d++)1===b[d].type&&(0<b[d].paddingLeft&&(e.selection.length+=1),e.selection.length+=this.__computeTextLengthOfChunk(b[d]));0<=c&&c<b.length?(0<b[c].paddingLeft&&(e.selection.start+=1),e.selection.length+=this.__measureTextBlock(b[c],a.right,a.top)):b.length<=c&&(e.selection.length+=1);e.selection.length-=e.selection.start}else e.selection.length=0;g.extras&&(e.extended.selection.start=e.extended.text.length+e.selection.start,e.extended.text+=e.text);return e};
CWEChromeHookGoogleDocs.prototype.__getChunksFromLine=function(a){let b=a.querySelectorAll("span.kix-lineview-text-block"),c=[];for(let e=0;e<b.length;e++){let h=b[e],l=h.childNodes;var d=h.style;let m=d.paddingLeft?parseFloat(d.paddingLeft):0;d=d.paddingRight?parseFloat(d.paddingRight):0;for(let f=0;f<l.length;f++){var k=l[f];if(k.nodeType===Node.ELEMENT_NODE){if("SPAN"!==k.tagName){Logger.instance.log("Invalid chunk type!");continue}var g={type:1,block:h,chunk:k,paddingLeft:m,paddingRight:d,parts:[]};
k=k.childNodes;let n=k.length;a.__isLastLine&&f===l.length-1&&0<n&&k[n-1].nodeType===Node.ELEMENT_NODE&&"SPAN"===k[n-1].tagName&&160===k[n-1].innerText.charCodeAt(0)&&n--;for(let q=0;q<n;q++){let p=k[q];if(p.nodeType===Node.ELEMENT_NODE){if(this.__isSmartComposeElement(p))continue;let r=p.childNodes;1!==r.length||r[0].nodeType!==Node.TEXT_NODE||this.m_embededIds.has(p.getAttribute("id"))?g.parts.push({type:1,element:p,text:" "}):g.parts.push({type:1,element:p,textElement:r[0],text:window.dji.utils.normalizedText(r[0].textContent)})}else p.nodeType===
Node.TEXT_NODE&&g.parts.push({type:3,element:p,text:window.dji.utils.normalizedText(p.textContent)})}c.push(g)}else k.nodeType===Node.TEXT_NODE&&(g={type:3,block:h,chunk:h,paddingLeft:m,paddingRight:d,parts:[{type:3,element:k,text:window.dji.utils.normalizedText(k.textContent)}]},c.push(g))}}return c};CWEChromeHookGoogleDocs.prototype.__isSmartComposeElement=function(a){return"DIV"===a.nodeName&&a.classList&&a.classList.contains("docs-smartcompose-suggestion")};
CWEChromeHookGoogleDocs.prototype.__cleanupIndex=function(a,b){if(0>=a||!b||0>=b.length)return a;for(let c=Math.min(a,b.length-1);0<=c;c--)switch(b.charCodeAt(c)){case 8203:case 8204:a--}return a};CWEChromeHookGoogleDocs.prototype.__computeText=function(a,b){if(null===a||0===a.length)return"";for(var c="",d=0;d<a.length;d++)0<d&&(c+=" "),c+=this.__computeTextOfLine(a[d],c.length,b);return c};
CWEChromeHookGoogleDocs.prototype.__computeTextOfLine=function(a,b,c){if(null===a)return"";var d="";a=this.__getChunksFromLine(a);for(var k=0;k<a.length;k++){var g=a[k];1===g.type&&(d+=this.__computeTextOfChunk(g,d.length+b,c))}return d};CWEChromeHookGoogleDocs.prototype.__computeTextLengthOfLine=function(a){if(null===a)return 0;var b=0;a=this.__getChunksFromLine(a);for(var c=0;c<a.length;c++)b+=this.__computeTextLengthOfChunk(a[c]);return b};
CWEChromeHookGoogleDocs.prototype.__computeTextOfChunk=function(a,b,c){if(null===a)return 0;let d="";if(1===a.type){0<a.paddingLeft&&(d+=" ");for(let k=0;k<a.parts.length;k++){let g=a.parts[k];switch(g.type){case Node.ELEMENT_NODE:d=g.textElement?d+g.text:d+" ";c&&(c[d.length+b]=g);break;case Node.TEXT_NODE:d+=g.text}}}return d};
CWEChromeHookGoogleDocs.prototype.__computeTextLengthOfChunk=function(a){if(null===a)return 0;var b=0;if(1===a.type){0<a.paddingLeft&&(b+=1);for(var c=0;c<a.parts.length;c++)switch(a.parts[c].type){case 1:b+=1;break;case 3:b+=a.parts[c].text.length}}return b};
CWEChromeHookGoogleDocs.prototype.__getSelectionOverlayInfo=function(){var a=this.getCaret(),b=this.m_appView.querySelectorAll("div.kix-page-content-wrapper");this.m_selectionOverlays=[];for(var c=0,d=-1;c<b.length;c++){var k=Array.prototype.slice.call(b[c].querySelectorAll("div.kix-selection-overlay"));if(0<k.length){if(d<c-1)return this.m_selectionOverlays=[],{first:a,last:a,caret:a,isSelection:!1};this.m_selectionOverlays=this.m_selectionOverlays.concat(k);d=c}}if(0>=this.m_selectionOverlays.length)return{first:a,
last:a,caret:a,isSelection:!1};c=b=null;for(d=0;d<this.m_selectionOverlays.length;d++)null===b?b=c=this.m_selectionOverlays[d].getBoundingClientRect():c=this.m_selectionOverlays[d].getBoundingClientRect();return b&&c&&(d=(a.top+a.bottom)/2,d<b.top||c.bottom<d)?(this.m_selectionOverlays=[],{first:a,last:a,caret:a,isSelection:!1}):{first:b,last:c,caret:a,isSelection:!0}};
CWEChromeHookGoogleDocs.prototype.__getSourandingLines=function(a,b,c){var d={currentLineIndex:0,firstLineIndex:0,lastLineIndex:0,lines:[]},k=(a.first.top+a.first.bottom)/2,g=(a.last.top+a.last.bottom)/2,e=(a.caret.top+a.caret.bottom)/2;a=this.__getCurrentParagraphs(a);for(var h=[],l=0;l<a.length;l++)for(var m=a[l].querySelectorAll("div.kix-lineview div.kix-lineview-content"),f=0;f<m.length;f++)m[f].__isLastLine=f===m.length-1,h.push(m[f]);f=-1;for(l=1;l<h.length;l++)if(m=h[l].getBoundingClientRect(),
k<m.top){f=l-1;break}-1===f&&(f=h.length-1);for(l=f+1;l<h.length;l++)if(m=h[l].getBoundingClientRect(),g<m.top){l--;break}l>=h.length&&(l=h.length-1);d.currentLineIndex=Math.abs(k-e)<Math.abs(g-e)?f:l;d.firstLineIndex=f;d.lastLineIndex=l;void 0!==b&&(f=Math.max(0,f-b));void 0!==c&&(l=Math.min(h.length-1,l+c));d.currentLineIndex-=f;d.firstLineIndex-=f;d.lastLineIndex-=f;d.lines=h.slice(f,l+1);1===a.length&&(d.extras={lines:h,currentLineIndex:d.currentLineIndex+f,firstLineIndex:d.firstLineIndex+f,lastLineIndex:d.lastLineIndex+
f});return d};
CWEChromeHookGoogleDocs.prototype.__getCurrentParagraphs=function(a){var b=(a.first.top+a.first.bottom)/2,c=a.first.left,d=a.first.right,k=a.isSelection?0:a.first.right-a.first.left+1,g=(a.last.top+a.last.bottom)/2,e=a.last.right,h=this.m_appViewEditor.querySelectorAll("div.kix-page div.kix-paragraphrenderer"),l=[],m;for(m=0;m<h.length;m++){var f=h[m].getBoundingClientRect();if(f.top<=b&&b<=f.bottom&&f.left<=d&&c<=f.right+k)break}if(a.isSelection)for(a=m;a<h.length;a++)if(f=h[a].getBoundingClientRect(),f.top<
g&&(f.right<=e||f.left<=e&&e<=f.right))l.push(h[a]);else break;else for(a=m;a<h.length;a++)if(f=h[a].getBoundingClientRect(),f.top<g&&f.left<=e&&c<=f.right+k)l.push(h[a]);else break;return l};
CWEChromeHookGoogleDocs.prototype.__measureTextBlock=function(a,b,c){if(null===a)return 0;let d=Number.MAX_SAFE_INTEGER;c=this.m_range;c.__initialized=!1;let k=0;for(let m=0;m<a.parts.length;m++){if(c.__initialized){var g=c.getBoundingClientRect();var e=Math.abs(g.right-b);if(e<d)d=e;else if(d<e)break}e=a.parts[m];c.__initialized||(c.setStart(e.element,0),c.__initialized=!0);if(e.type===Node.ELEMENT_NODE)if(c.setEndAfter(e.element),g=c.getBoundingClientRect(),g=g.right,g<b)k++;else{var h=e.element.getBoundingClientRect();
h.x<=b&&b<=g&&(e=e.element.classList.contains("kix-embeddedobject-view")?3:10,h.x+h.width/e<b&&k++)}else if(e.type===Node.TEXT_NODE){h=e.element.textContent;let f=0,n=h.length;for(var l=void 0;f<n;)if(l=parseInt((f+n)/2),c.setEnd(e.element,l),g=c.getBoundingClientRect(),g=g.right,.4>=Math.abs(g-b)){f=l;break}else g<b?f=l+1:n=l;l=f;if(0<f){f=Math.max(0,l-3);n=Math.min(l+3,h.length);let q=Number.MAX_SAFE_INTEGER;for(;f<=n;f++)if(c.setEnd(e.element,f),g=c.getBoundingClientRect(),g=g.right,g=Math.abs(g-
b),g<=q)l=f,q=g;else if(q<g)break}l=this.__cleanupIndex(l,h);k+=l}}a=k;c.__initialized=!1;c.detach();return a};CWEChromeHookGoogleDocs.prototype.__debuggableText=function(a,b){if(!a||0>=a.length)return[];a=a.split("");for(let c=0;c<a.length;c++)switch(a[c].charCodeAt(0)){case 8203:a[c]="#";break;case 8204:a[c]="$";break;case 160:a[c]="_"}return isNaN(b)?a:a.slice(-b)};
CWEChromeHookGoogleDocs.prototype.replaceText=function(a,b,c){if(0===c.selection.length&&c.selection.start<b.selection.end)for(a=b.selection.end;a>b.selection.start;a--)a in c.custom.embeddedLocations&&(b.selection.end=a-1);b.extended={rightKey:Math.max(0,0===c.selection.length?b.selection.end-c.selection.start:0),backspaceKey:Math.max(0,0===c.selection.length?b.selection.end-b.selection.start:0)};try{let d=new CustomEvent("__DJI_CWE_IME_REPLACETEXT",{detail:b});this.m_forwardEvents=!1;this.m_windowProxy.dispatchEvent(d)}catch(d){Logger.instance.error(d)}finally{this.m_lastKeyPressTimestamp=
Date.now(),this.m_forwardEvents=!0,this.m_ime.onContextChanged(this)}};CWEChromeHookGoogleDocs.prototype.getContextForMomentaryTopic=function(a,b){this.m_textMapperAdapter||(this.m_textMapperAdapter=new window.dji.cwe.DocumentTextMapperAdapter);a=this.m_textMapperAdapter.getDocumentText();b(a?a.text:"")};
CWEChromeHookGoogleDocs.prototype.acquireTextForTopicAsync=async function(a){const b=this;return new Promise(function(c){b.m_appViewEditor||b.__findEditorElements();if(!b.m_appViewEditor)return c(null);let d=null;if("selection"===a){var k=b.getContext();if(k||0<k.selection.length)d=k.text.substr(k.selection.start,k.selection.length)}else if("page"===a){d="";k=b.m_appViewEditor.querySelectorAll("div.kix-page div.kix-paragraphrenderer");for(let g=0;g<k.length;g++){0<g&&(d+="\n");const e=k[g].querySelectorAll("div.kix-lineview div.kix-lineview-content");
for(let h=0;h<e.length;h++)0<h&&(d+=" "),d+=e[h].textContent}}c(d)})};
CWEChromeHookGoogleDocs.prototype.shouldIgnoreMutations=function(a){let b=!0;for(let d=0;d<a.length;d++){let k=a[d],g=k.target.ownerDocument;if(g.querySelector("#__dji_sru_main_container_content")){b=!1;break}let e=!1;for(var c=0;c<k.addedNodes.length&&!e;c++)0<g.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",k.addedNodes[c],null,XPathResult.NUMBER_TYPE).numberValue&&(e=!0);for(c=0;c<k.removedNodes.length&&!e;c++)0<g.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",k.removedNodes[c],
null,XPathResult.NUMBER_TYPE).numberValue&&(e=!0);if(e){b=!1;break}}return b};
