function CWEBackgroundManagerInstance(){return CWEBackgroundManager.instance}
function CWEBackgroundManager(){this.m_tabs={};this.m_activeTabId=this.m_activeWindowId=-1;this.m_busy=this.m_on=this.m_turnOnInProgress=this.m_loaded=!1;this.m_contextMenu={CoWriter:null,startSpeak:null,addPersonalWord:null,removePersonalWord:null};this.m_quickTopicActionInfo={action:"",topic:null,fromWiki:!1,tabId:-1};this.m_userDirectory=this.m_userName="";this.m_fileSystem=null;this.m_locale=this.findValidLanguage(window.localStorage.locale||"US");this.m_defaultLocale="US";this.m_localeRequiresReboot=
!1;this.m_translationLanguages=[];this.m_translationLanguagesMap={};this.m_appUrlPattern="chrome-extension://"+chrome.runtime.id+"/*";this.m_appOptionsUrlPattern="chrome-extension://"+chrome.runtime.id+"/Options/*";this.m_appOptions="/Options/options.html";this.m_token=null;this.m_restartReason=window.localStorage.__runtime_restart_reason||null;this.directories={common:"/common/dictionaries",mainDictionaries:"main",predefinedTopicDictionaries:"predefined_topics",hunspell:"/common/hunspell",sensitiveWords:"/common/sensitive-words",
specialPredictions:"/common/special-predictions"};this.m_defaultDisplayTopics={US:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),UK:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),BE:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),CAN:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),
FR:"Tour de France;Le Vendee Globe;football;Victor Hugo;Musee d'Orsay;Samuel de Champlain".split(";"),GER:"Fusball;Albert Einstein;Ludwig van Beethoven;Schwarzwald;Jasmund;Bodensee".split(";"),SPA:"Futbol;Pablo Picasso;Antoni Gaudi;Frida Kahlo;Dia de Muertos;Astronomia".split(";")};this.m_wikiReader=new CWEWikiReader;window.localStorage.__runtime_restart_reason=null;this.m_ttsListener={start:null,progress:null,stop:null,error:null,wait:null};this.m_ttsTimer=new DjiTimer(this,this.sendTextToSpeechTriggeredEvent);
this.GoogleAnalytics=this.CWEI18n=null;return this}CWEBackgroundManager.instance=null;CWEBackgroundManager.initialize=async function(){if(null===CWEBackgroundManager.instance)try{Logger.instance.monitor({event:"bm_will_intialize"}),CWEBackgroundManager.instance=new CWEBackgroundManager,await CWEBackgroundManager.instance.__initialize()}catch(a){CWEBackgroundManager.instance=null,Logger.instance.error("Background Manager - cannot create instance!"),Logger.instance.error(a)}};
CWEBackgroundManager.prototype.isLoaded=function(){return this.m_loaded};CWEBackgroundManager.prototype.isBusy=function(){return!!(this.m_busy||this.m_turnOnInProgress||CWEPredictionEngine.instance&&CWEPredictionEngine.instance.state.action)};CWEBackgroundManager.prototype.__enterBusyState=function(){this.m_busy||(this.m_busy=!0,this.__sendNotification("busy_started"))};CWEBackgroundManager.prototype.__leaveBusyState=function(){this.m_busy&&(this.m_busy=!1,this.__sendNotification("busy_finished"))};
CWEBackgroundManager.prototype.isTurnOnInProgress=function(){return this.m_turnOnInProgress};CWEBackgroundManager.prototype.isLoggedIn=function(){return window.cwe.login.isLoggedIn()};CWEBackgroundManager.prototype.userInfo=function(){return window.cwe.login.userInfo()};CWEBackgroundManager.prototype.settings=function(){return CWESettings.instance};CWEBackgroundManager.prototype.locale=function(){return this.m_locale};
CWEBackgroundManager.prototype.localeLang=function(a,b){return window.cwe.locale.localeLang(a,b||this.m_locale)};CWEBackgroundManager.prototype.isEnglish=function(){return"FR"!==this.m_locale&&"GER"!==this.m_locale&&"SPA"!==this.m_locale};CWEBackgroundManager.prototype.translationLanguages=function(){return this.m_translationLanguages};CWEBackgroundManager.prototype.translationLanguageInfo=function(a){return this.m_translationLanguagesMap[a]};CWEBackgroundManager.prototype.localeRequiresReboot=function(){return this.m_localeRequiresReboot};
CWEBackgroundManager.prototype.restartReason=function(){return this.m_restartReason};CWEBackgroundManager.prototype.fileSystem=function(){return this.m_fileSystem};CWEBackgroundManager.prototype.requestFileSystem=function(a){a(this.m_fileSystem)};
CWEBackgroundManager.prototype.__initialize=async function(){Logger.instance.monitor({event:"bm_intialize_prepare"});Logger.instance.log("Initializing Co:Writer Extension...");this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}});this.CWEI18n=window.dji.cwe.i18n;await this.CWEI18n.initialize();this.GoogleAnalytics=window.dji.cwe.ga4;const a=window.dji.config.ga4();this.GoogleAnalytics.initialize(a.measurementID,a.APISecret);this.GoogleAnalytics.instance.setDebugViewEnabled(a.debugViewEnabled);
CWESettings.initialize(this);this.__startInitialization()};CWEBackgroundManager.prototype.__startInitialization=function(){Logger.instance.monitor({event:"bm_intialize_start"});this.__initializePersistentStorage()};
CWEBackgroundManager.prototype.__initializePersistentStorage=function(){Logger.instance.monitor({event:"bm_intialize_step_1a"});DjiHtml5FileSystem.initialize(async a=>{Logger.instance.monitor({event:"bm_intialize_step_1b"});this.m_fileSystem=a;try{Logger.instance.monitor({event:"bm_intialize_step_1c"}),await CWEPredictionEngine.load(this),Logger.instance.monitor({event:"bm_intialize_step_1d"}),CWEPredictionEngine.instance.addEventListener("crash",this.__predictionEngineCrashed.bind(this)),this.__predictionEngineLoaded(!0)}catch(b){Logger.instance.monitor({event:"bm_intialize_step_1x",
reason:"error",error:b}),this.__predictionEngineLoaded(!1)}})};
CWEBackgroundManager.prototype.__predictionEngineLoaded=function(a){Logger.instance.monitor({event:"bm_intialize_step_2a",success:a});a?(this.m_wikiReader.setOptions({sensitiveWords:CWEPredictionEngine.instance.sensitiveWords()}),this.resetHunspellLanguages(),Logger.instance.monitor({event:"bm_intialize_step_2b"}),setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_2c"});dji.tts.initialize({onlineServiceAllowed:!0,settingsFactor:1},()=>{this.__ttsEngineInitialized()})},10)):(Logger.instance.monitor({event:"bm_intialize_step_2x"}),
Logger.instance.error("Failed to load Prediction Engine! Change status to UNAVAILABLE!"))};
CWEBackgroundManager.prototype.__ttsEngineInitialized=function(){Logger.instance.monitor({event:"bm_intialize_step_3a"});CWESettings.initialize(this);Logger.instance.monitor({event:"bm_intialize_step_3b"});dji.speechRecognition.initialize();Logger.instance.monitor({event:"bm_intialize_step_3c"});setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_3b"});this.loadConfig(()=>{Logger.instance.monitor({event:"bm_intialize_step_3c"});setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_3d"});
this.__initializeDataManager()},10)})},0)};
CWEBackgroundManager.prototype.__initializeDataManager=function(){Logger.instance.monitor({event:"bm_intialize_step_4a"});CWEDataManager.initialize(()=>{Logger.instance.monitor({event:"bm_intialize_step_4b"});CWEDataManager.instance.setDataSyncManager(window.cwe.sync);window.cwe.sync.setDataManager(CWEDataManager.instance);window.cwe.sync.addUserSettingsUpdateListener(()=>{this.__onUserSettingsSynced()});window.cwe.sync.addDictionariesUpdateListener((a,b)=>{this.__onTopicsSynced(a,b)});Logger.instance.log("Initializing storage... DONE!");
setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_4c"});this.__initializeDataMeasurements()},10)})};CWEBackgroundManager.prototype.__initializeDataMeasurements=function(){Logger.instance.monitor({event:"bm_intialize_step_5a"});window.cwe.measure.initialize(()=>{Logger.instance.monitor({event:"bm_intialize_step_5b"});Logger.instance.log("Initializing measurements... DONE!");setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_5c"});this.__initializeSettings()},10)})};
CWEBackgroundManager.prototype.__initializeSettings=function(){Logger.instance.monitor({event:"bm_intialize_step_6a"});CWESettings.initialize(this);Logger.instance.monitor({event:"bm_intialize_step_6b"});CWESettings.instance.load(()=>{Logger.instance.monitor({event:"bm_intialize_step_6c"});Logger.instance.log("Initializing settings... DONE!");setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_6d"});this.__initializeTranslation()},0)})};
CWEBackgroundManager.prototype.__initializeTranslation=function(){Logger.instance.monitor({event:"bm_intialize_step_7a"});dji.translator.init({load:CWEDataManager.instance.loadTranslationCache.bind(CWEDataManager.instance),save:CWEDataManager.instance.saveTranslationCache.bind(CWEDataManager.instance)});setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_7b"});this.__initializeDefaultUser()},0)};
CWEBackgroundManager.prototype.__initializeDefaultUser=function(){Logger.instance.monitor({event:"bm_intialize_step_8a"});this.changeUser("DefaultUser",()=>{Logger.instance.monitor({event:"bm_intialize_step_8b"});Logger.instance.log("Initializing default user... DONE!");setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_8c"});this.__loadLastUserInfo()},0)})};
CWEBackgroundManager.prototype.__loadLastUserInfo=function(){Logger.instance.monitor({event:"bm_intialize_step_9a"});var a=this,b=this.__changeToLastLoggedInUser.bind(this);this.__readUserInfo(function(c){Logger.instance.monitor({event:"bm_intialize_step_9b"});window.cwe.login.silentAuth(function(d){Logger.instance.monitor({event:"bm_intialize_step_9c",code:d?d.code:null});d&&500!=d.code?0==d.code?(Logger.instance.monitor({event:"bm_intialize_step_9f"}),c&&c.checksum!==d.user.checksum?(Logger.instance.monitor({event:"bm_intialize_step_9j"}),
a.__removeUserData(c,function(){Logger.instance.monitor({event:"bm_intialize_step_9k"});a.__loadUserInfo(function(){Logger.instance.monitor({event:"bm_intialize_step_9l"});setTimeout(b,10)})})):(Logger.instance.monitor({event:"bm_intialize_step_9g"}),a.__saveUserInfo(function(){Logger.instance.monitor({event:"bm_intialize_step_9h"});a.__loadUserInfo(function(){Logger.instance.monitor({event:"bm_intialize_step_9i"});setTimeout(b,10)})}))):(Logger.instance.monitor({event:"bm_intialize_step_9m"}),a.__removeUserData(c,
function(){Logger.instance.monitor({event:"bm_intialize_step_9n"});a.__loadUserInfo(function(){Logger.instance.monitor({event:"bm_intialize_step_9o"});setTimeout(b,10)})})):(Logger.instance.monitor({event:"bm_intialize_step_9d"}),a.__loadUserInfo(function(){Logger.instance.monitor({event:"bm_intialize_step_9e"});setTimeout(b,10)}))})})};
CWEBackgroundManager.prototype.__changeToLastLoggedInUser=function(){Logger.instance.monitor({event:"bm_intialize_step_10a"});window.cwe.login.isLoggedIn()?(Logger.instance.monitor({event:"bm_intialize_step_10b"}),this.changeUser(window.cwe.login.userInfo().checksum,()=>{Logger.instance.monitor({event:"bm_intialize_step_10c"});setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_10d"});this.__createContextMenus();Logger.instance.monitor({event:"bm_intialize_step_10e"});this.__cacheTabs();
Logger.instance.monitor({event:"bm_intialize_step_10f"})},0)})):(Logger.instance.monitor({event:"bm_intialize_step_10g"}),setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_10h"});this.__removeContextMenus();Logger.instance.monitor({event:"bm_intialize_step_10i"});this.__cacheTabs();Logger.instance.monitor({event:"bm_intialize_step_10j"})},0))};
CWEBackgroundManager.prototype.__createContextMenus=function(){var a=this;chrome.contextMenus.removeAll();this.m_contextMenu.CoWriter=chrome.contextMenus.create({title:"Co:Writer",contexts:["all"]});this.m_contextMenu.startSpeak=chrome.contextMenus.create({title:"Speak",contexts:["selection"],parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onSpeakSelection(c.id,b.selectionText)}});this.m_contextMenu.addPersonalWord=chrome.contextMenus.create({title:"Add Personal Word",contexts:["selection"],
parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onAddPersonalWords(c.id,b.selectionText)}});this.m_contextMenu.removePersonalWord=chrome.contextMenus.create({title:"Remove Personal Word",contexts:["selection"],parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onRemovePersonalWords(c.id,b.selectionText)}})};
CWEBackgroundManager.prototype.__removeContextMenus=function(){this.m_contextMenu.CoWriter&&(chrome.contextMenus.remove(this.m_contextMenu.CoWriter),delete this.m_contextMenu.CoWriter,delete this.m_contextMenu.startSpeak,delete this.m_contextMenu.addPersonalWord,delete this.m_contextMenu.removePersonalWord)};
CWEBackgroundManager.prototype.__updatePersonalWordContextMenuItems=function(){var a=CWESettings.instance.features();a=!(a&&!a.allowPersonalDictionary);chrome.contextMenus.update(this.m_contextMenu.addPersonalWord,{enabled:a});chrome.contextMenus.update(this.m_contextMenu.removePersonalWord,{enabled:a})};
CWEBackgroundManager.prototype.__cacheTabs=function(){Logger.instance.monitor({event:"bm_intialize_step_11a"});chrome.tabs.query({},a=>{Logger.instance.monitor({event:"bm_intialize_step_11b"});chrome.windows.getCurrent(null,b=>{Logger.instance.monitor({event:"bm_intialize_step_11c"});if(b)for(this.m_activeWindowId=b.id,b=0;b<a.length;b++){var c=a[b];this.m_tabs[c.id]={tabId:c.id,windowId:c.windowId,port:null};c.active&&c.windowId==this.m_activeWindowId&&(this.m_activeTabId=c.id)}Logger.instance.monitor({event:"bm_intialize_step_11d"});
Logger.instance.log("CWEBackgroundManager.__cacheTabs");Logger.instance.log(this.m_tabs);setTimeout(()=>{Logger.instance.monitor({event:"bm_intialize_step_11e"});this.__finishInitialization()},0)})})};
CWEBackgroundManager.prototype.__finishInitialization=function(){Logger.instance.monitor({event:"bm_intialize_step_12a"});const a=this;this.m_ttsListener.start=(c,d,e)=>{this.__onTtsStart(c,d,e)};this.m_ttsListener.progress=(c,d,e,f,g)=>{this.__onTtsProgress(c,d,e,f,g)};this.m_ttsListener.stop=(c,d,e)=>{this.__onTtsStop(c,d,e)};this.m_ttsListener.error=(c,d,e)=>{this.__onTtsError(c,d,e)};this.m_ttsListener.wait=(c,d)=>{this.__onTtsWait(c,d)};chrome.windows.onFocusChanged.addListener(function(c){a.__onWindowOrTabFocusChanged(c,
null)});chrome.tabs.onCreated.addListener(function(c){a.__onTabCreated(c)});chrome.tabs.onActivated.addListener(function(c){a.__onWindowOrTabFocusChanged(null,c)});chrome.tabs.onRemoved.addListener(function(c,d){a.__onTabRemoved(c,d)});chrome.tabs.onHighlighted.addListener(function(c){a.__onTabHighlighted(c)});chrome.runtime.onMessage.addListener(function(c,d,e){return a.__onRuntimeMessage(c,d,e)});chrome.runtime.onConnect.addListener(function(c){a.__onPortConnect(c)});var b=function(){Logger.instance.monitor({event:"bm_intialize_step_12i"});
if(a.m_localeRequiresReboot)Logger.instance.monitor({event:"bm_intialize_step_12l"}),Logger.instance.log("Initializing Co:Writer Extension... DONE! Locales change requires restart!");else{Logger.instance.monitor({event:"bm_intialize_step_12j"});a.m_loaded=!0;for(var c in a.m_tabs)try{a.m_tabs[c].port=null,chrome.tabs.sendMessage(a.m_tabs[c].tabId,{message:window.dji.messages.cwe.chrome.ENGINE_READY})}catch(d){Logger.instance.log(d)}a.reloadAppTabs();Logger.instance.monitor({event:"bm_intialize_step_12k"});
Logger.instance.log("Initializing Co:Writer Extension... DONE!")}Logger.instance.monitor({event:"bm_intialize_step_12m"});window.cwe.login.monitor({authRequired:a.__onAuthRequired.bind(a),signoutRequired:a.__onSignoutRequired.bind(a)});Logger.instance.monitor({event:"bm_intialize_step_12n"});dji.proxy.init({onNotification:a.__onExternalNotification.bind(a)});Logger.instance.monitor({event:"bm_intialize_step_12o"});a.__sendNotification("load");Logger.instance.monitor({event:"bm_intialize_step_12p"});
Logger.instance.monitor({event:"bm_intialize_finish"});CWEDataManager.instance.readRtmOptionsAsync().then(d=>{d instanceof Object&&d.on&&!a.m_on&&!a.m_turnOnInProgress&&window.cwe.login.isLoggedIn()&&(a.allowTogglePrediction()||a.allowMicrophone())&&a.__onBrowserAction()})};Logger.instance.monitor({event:"bm_intialize_step_12b"});window.cwe.login.isLoggedIn()?(Logger.instance.monitor({event:"bm_intialize_step_12c"}),this.__prepareUserLanguages(window.cwe.login.userInfo(),function(c){Logger.instance.monitor({event:"bm_intialize_step_12d"});
c?(Logger.instance.monitor({event:"bm_intialize_step_12e"}),a.__validateTranslationSource(),window.cwe.sync.changeLanguage(a.m_locale),a.__onStartSync(),a.setIcon({path:a.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),Logger.instance.monitor({event:"bm_intialize_step_12f"})):Logger.instance.monitor({event:"bm_intialize_step_12g"});b()})):(Logger.instance.monitor({event:"bm_intialize_step_12h"}),
this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),b())};
CWEBackgroundManager.prototype.__onRuntimeMessage=function(a,b,c){if(b.id===chrome.runtime.id){if(a.message===window.dji.messages.cwe.ui.RESOURCES)return!0;if(a.message===window.dji.messages.cwe.app.QUERY_STATE)return a=window.cwe.login.userInfo(),a={loaded:this.isLoaded(),busy:this.isBusy(),active:this.m_on,authenticated:!!a,user:a},c(a);if(a.message===window.dji.messages.cwe.app.ACTIVATE)return this.__onBrowserAction(()=>{let d=window.cwe.login.userInfo();c({active:this.m_on,authenticated:!!d,user:d})}),
!0;if(a.message===window.dji.messages.cwe.chrome.OPEN_CONTENT_SETTINGS)return chrome.tabs.create({url:"chrome://settings/content"}),!0;if(a.message===window.dji.messages.cwe.app.DEACTIVATE)return this.__onBrowserAction(c),!0;if(a.message===window.dji.messages.cwe.chrome.OPTIONS)this.onOptions();c instanceof Function&&c()}};
CWEBackgroundManager.prototype.__onExternalNotification=function(a){if(a){var b=dji.config.loginUrlSignature();"auth"===a.category&&(!a.hasOwnProperty("version")||a.hasOwnProperty("version")&&2===a.version&&a.signature===b)&&("auth"===a.reason?this.__onAuthRequired():"signout"===a.reason&&this.__onSignoutRequired())}};
CWEBackgroundManager.prototype.__onAuthRequired=function(){var a=this;this.m_turnOnInProgress||(this.m_turnOnInProgress=!0,window.cwe.login.userInfo(),this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),window.cwe.login.silentAuth(function(b){b&&500!=b.code?0==b.code?a.__saveUserInfo(function(){a.__loadUserInfo(function(){if(window.cwe.login.isLoggedIn()){var c=window.cwe.login.userInfo();a.__saveUserInfo(function(){a.__prepareUserLanguages(c,
function(d){d?a.changeUser(c.checksum,function(){a.m_turnOnInProgress=!1;a.__validateTranslationSource();a.__onStartSync();a.setIcon({path:a.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})}):(a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1,dji.notifications.show({message:"Text prediction language has changed. Please reload the extension."}))})})}else dji.notifications.showByAuthCode(500),
a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1})}):(dji.notifications.showByAuthCode(b.code),a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1):(dji.notifications.showByAuthCode(b?b.code:null),a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=
!1)}))};CWEBackgroundManager.prototype.__onSignoutRequired=function(){this.signOut()};CWEBackgroundManager.prototype.__onStartSync=async function(){const a=this.__onStartSync.__session=CWEChromeUtilities.generateUUID();let b=null,c=0;for(;a===this.__onStartSync.__session&&(b=await window.jsdapi.cow.checkSyncOptionsAsync()),!b&&a===this.__onStartSync.__session;)c=Math.min(c+2E3,6E4),await CWEChromeUtilities.sleepAsync(c);b&&b.allowed&&a===this.__onStartSync.__session&&window.cwe.sync.start()};
CWEBackgroundManager.prototype.__onStopSync=function(){delete this.__onStartSync.__session;window.cwe.sync.stop()};CWEBackgroundManager.prototype.__reloadRelatedWebsites=function(a){Logger.instance.log("Reload related websites:",a,dji.config.relatedUris());this.__notifyRelatedExtensionsAboutAuth(a);chrome.tabs.query({url:dji.config.relatedUris()},function(b){if(b)for(let c=0;c<b.length;c++)chrome.tabs.reload(b[c].id,{bypassCache:!0})})};
CWEBackgroundManager.prototype.__notifyRelatedExtensionsAboutAuth=function(a){dji.proxy.broadcastNotification({category:"auth",version:2,reason:a?"auth":"signout",signature:dji.config.loginUrlSignature()})};CWEBackgroundManager.prototype.__sendNotification=function(a,b){const c={message:"com.donjohnston.cowriter.notification",reason:a,details:b};chrome.runtime.sendMessage(c);chrome.tabs.query({},function(d){for(let e=0;e<d.length;e++)chrome.tabs.sendMessage(d[e].id,c)})};
CWEBackgroundManager.prototype.__onBrowserAction=function(a,b){if(this.m_loaded)if(this.m_turnOnInProgress)Logger.instance.log("Turn on is already in progress!");else{this.m_turnOnInProgress=!0;this.__sendNotification("activation");Logger.instance.log("------------- CWEBackgroundManager.__onBrowserAction");Logger.instance.log(this.m_activeTabId);this.onStopSpeak();dji.speechRecognition.stop();var c=this,d=function(e){var f=async function(k){return b?CWEDataManager.instance.saveRtmOptionsAsync(k):
Promise.resolve()},g=function(k){f({on:k}).then(()=>{c.m_turnOnInProgress=!1;c.m_on=k;setTimeout(function(){c.setIcon({path:c.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})},0);a&&a();c.__sendNotification(c.m_on?"activated":"deactivated");c.__enableInActiveTab(c.m_on)})};e?(c.sendGA4Event("ApplicationStarted",null,null),c.__initializePredictionEngine(function(k){c.downloadAdditionalOnlineResources();
g(k)},!0)):(c.sendGA4Event("ApplicationStopped",null,null),g(!1))};if(c.m_on)return d(!1);window.cwe.login.isLoggedIn()?d(!c.m_on):window.cwe.login.login(function(e){e?(c.__createContextMenus(),c.__saveUserInfo(function(){c.__prepareUserLanguages(e,function(f){f?c.changeUser(e.checksum,function(){c.__validateTranslationSource();c.__onStartSync();d(!0)}):c.m_turnOnInProgress=!1});c.__reloadRelatedWebsites(!0)})):c.m_turnOnInProgress=!1})}else this.m_localeRequiresReboot&&this.activateLocaleRequiresReboot()};
CWEBackgroundManager.prototype.__initializePredictionEngine=async function(a,b){if(!b&&this.m_turnOnInProgress)return dji.utils.callMethod(a,!1,!1);if(CWEPredictionEngine.isInitialized())return dji.utils.callMethod(a,!0,!0);b=this.m_turnOnInProgress;this.m_turnOnInProgress=!0;this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}});this.__sendNotification("initialize_nacl_started");Logger.instance.info("__initializePredictionEngine   #1");let c=
await CWEPredictionEngine.instance.initializeAsync(this.m_locale,CWESettings.instance.translationSource(),this.m_userDirectory);c&&(c=await CWEPredictionEngine.instance.updateFromUserSettingsAsync());c||this.__predictionEngineCrashed();this.setIcon({path:c?this.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}});
this.m_turnOnInProgress=b;this.__sendNotification("initialize_nacl_finished");dji.utils.callMethod(a,c,!0)};CWEBackgroundManager.prototype.__getFocusedWindowAsync=async function(a){return new Promise(function(b,c){chrome.windows.getAll({},function(d){if(chrome.runtime.lastError)return c(chrome.runtime.lastError);d=d&&d.find(e=>e.focused);!d&&a&&a!==chrome.windows.WINDOW_ID_NONE||b(d);chrome.windows.get(a,{},function(e){if(chrome.runtime.lastError)return c(chrome.runtime.lastError);b(e)})})})};
CWEBackgroundManager.prototype.__getFocusedTabAsync=async function(a){return new Promise(function(b,c){const d=function(){chrome.tabs.getSelected(a,function(e){const f=chrome.runtime.lastError;if(f)return"Tabs cannot be edited right now (user may be dragging a tab)."===f.message?setTimeout(d,50):c(chrome.runtime.lastError);b(e)})};d()})};
CWEBackgroundManager.prototype.__onWindowOrTabFocusChanged=async function(a,b){const c=this.__onWindowOrTabFocusChanged.queue=this.__onWindowOrTabFocusChanged.queue||[];1<c.length&&c.splice(1);c.push({windowId:a,activeTabInfo:b});if(!(1<c.length))for(;0<c.length;){a=c[0];try{await this.__processFocusedStateAsync(a.windowId,a.activeTabInfo)}catch(d){Logger.instance.error(d)}c.splice(0,1)}};
CWEBackgroundManager.prototype.__processFocusedStateAsync=async function(a,b){if(a&&a===chrome.windows.WINDOW_ID_NONE)try{var c=await this.__getFocusedWindowAsync(this.m_activeWindowId);c&&(a=c.id)}catch(e){Logger.instance.error(e)}if(a&&a!==chrome.windows.WINDOW_ID_NONE&&!b)try{var d=await this.__getFocusedTabAsync(a);d&&(b={windowId:a,tabId:d.id})}catch(e){Logger.instance.error(e)}a=this.m_activeTabId;c=b&&b.windowId||-1;d=b&&b.tabId||-1;b&&(this.m_tabs.hasOwnProperty(d)?this.m_tabs[d].windowId=
c:this.m_tabs[d]={tabId:d,windowId:c,port:null});this.m_on&&a!==d?(a!==d&&(this.__notifyActiveTab("deactivate"),this.m_on&&this.__enableInActiveTab(!1)),this.m_activeWindowId=c,this.m_activeTabId=d,a!==d&&(this.__notifyActiveTab(),this.m_on&&this.m_loaded&&0<=this.m_activeTabId&&(CWEPredictionEngine.instance&&CWEPredictionEngine.instance.resetState(),this.__enableInActiveTab(!0)))):(this.m_activeWindowId=c,this.m_activeTabId=d)};
CWEBackgroundManager.prototype.__onTabCreated=function(a){window.cwe.login.isPreparing()||window.cwe.login.tabId()===a.id||((new RegExp(this.m_appOptionsUrlPattern)).test(a.pendingUrl)&&this.sendGA4Event("OptionsOpened",null,null),this.m_tabs[a.id]={tabId:a.id,windowId:a.windowId,port:null})};CWEBackgroundManager.prototype.__onTabHighlighted=function(a){Logger.instance.log("--------------- CWEBackgroundManager.__onHighlighted:");Logger.instance.log(a)};
CWEBackgroundManager.prototype.__onTabRemoved=function(a,b){Logger.instance.log("--------------- CWEBackgroundManager.__onTabRemoved:");Logger.instance.log(b);this.m_activeTabId===a&&(this.onStopSpeak(),dji.speechRecognition.stop());a in this.m_tabs?delete this.m_tabs[a]:Logger.instance.log("     - tab not cached");Logger.instance.log(this.m_tabs)};
CWEBackgroundManager.prototype.__onPortConnect=function(a){Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect");Logger.instance.log(a);if("__dji__cowriter_port"===a.name)if(a.sender&&a.sender.tab){var b=a.sender.tab.id;b in this.m_tabs||(Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect: unknow tabId "+b),this.m_tabs[b]={tabId:b,windowId:a.sender.tab.windowId,port:null});Logger.instance.log(" - active window: "+this.m_activeWindowId);Logger.instance.log(" - active tab: "+
this.m_activeTabId);Logger.instance.log(" - tabId: "+b);this.m_tabs[b].port=new CWEBackgroundPort(a,b,this)}else Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect: no sender details")};CWEBackgroundManager.prototype.__onPortDisconnect=function(a,b){Logger.instance.log("------------- CWEBackgroundManager.__onPortDisconnect, tabId="+a);Logger.instance.log(b)};
CWEBackgroundManager.prototype.__enableInActiveTab=function(a){if(!a||-1!==this.m_activeTabId)try{a&&this.__applySettingsInActiveTab(!0,!0);const b=this,c=this.m_activeTabId,d={message:a?window.dji.messages.cwe.chrome.ACTIVATE:window.dji.messages.cwe.chrome.DEACTIVATE,token:CWEChromeUtilities.generateUUID()};a&&(d.state=CWEPredictionEngine.instance.state);this.m_token=d.token;a&&this.__notifyActiveTab();if(a)try{this.m_tabs.hasOwnProperty(c)&&null!==this.m_tabs[c].port&&chrome.tabs.sendMessage(c,
d,function(e){CWEChromeUtilities.checkLastError();a&&e&&e.active&&e.token===b.m_token&&b.requestMomentaryTopicContext()})}catch(e){Logger.instance.log(e)}else for(let e in this.m_tabs)if(this.m_tabs.hasOwnProperty(e)&&null!==this.m_tabs[e].port)try{chrome.tabs.sendMessage(this.m_tabs[e].tabId,d,CWEChromeUtilities.createLastErrorHandler())}catch(f){Logger.instance.log(f)}}catch(b){Logger.instance.error(b)}};
CWEBackgroundManager.prototype.__notifyActiveTab=function(a,b){if(this.m_loaded&&0<=this.m_activeTabId)try{void 0===a&&void 0===b&&(b=CWEPredictionEngine.instance.state,b.action||(b=void 0),b&&(a="update_topic_started")),(a||b)&&this.m_tabs.hasOwnProperty(this.m_activeTabId)&&this.m_tabs[this.m_activeTabId].port&&chrome.tabs.sendMessage(this.m_activeTabId,{message:window.dji.messages.cwe.chrome.NOTIFICATION,reason:a||"generic",details:b},CWEChromeUtilities.createLastErrorHandler())}catch(c){Logger.instance.error(c)}};
CWEBackgroundManager.prototype.__applySettings=function(){this.allowToggleOnOff()||this.m_turnOnInProgress||this.m_on&&this.__onBrowserAction();this.__updatePersonalWordContextMenuItems()};
CWEBackgroundManager.prototype.__applySettingsInActiveTab=function(a){if(this.m_loaded&&this.m_on&&-1!==this.m_activeTabId)try{if(this.m_tabs[this.m_activeTabId].port){let b=this.prepareSpeechRecognitionInfo(CWESettings.instance.translationSource());dji.tts.settings(CWESettings.instance.speech());this.m_tabs[this.m_activeTabId].port.port().postMessage({message:window.dji.messages.cwe.chrome.SETTINGS,settings:{locale:this.locale(),presentationLang:CWESettings.instance.presentationLang(),prediction:CWESettings.instance.prediction(),
window:CWESettings.instance.window(),text:CWESettings.instance.guessWindowForUI(),speech:{letters:CWESettings.instance.speechLetters(),words:CWESettings.instance.speechWords(),sentences:CWESettings.instance.speechSentences(),afterSTT:CWESettings.instance.speechAfterSTT(),highlightTextColor:CWESettings.instance.highlightTextColor(),highlightBackgroundColor:CWESettings.instance.highlightBackgroundColor(),rate:CWESettings.instance.speechRate()},translation:{target:this.prepareSpeechRecognitionInfo(this.m_locale),
source:b},isEnglish:this.isEnglish(),features:CWESettings.instance.features(),asNeeded:CWESettings.instance.asNeeded(),gdocsConfig:window.dji.config.gdocsConfig()}});this.provideTopicsData(this.m_activeTabId);a||this.requestMomentaryTopicContext()}}catch(b){}};
CWEBackgroundManager.prototype.displayTopics=function(){const a=this.m_defaultDisplayTopics[this.locale()]||[],b=CWESettings.instance.topicsActive(),c=CWESettings.instance.topicsRecent(),d=new Set(b),e=b.map(function(f){return{name:f,active:!0}});c.forEach(function(f){d.has(f)||(e.push({name:f,active:!1}),d.add(f))});a.forEach(function(f){d.has(f)||(e.push({name:f,active:!1}),d.add(f))});return e.slice(0,6)};
CWEBackgroundManager.prototype.provideTopicsData=async function(a,b,c){if(this.m_loaded&&-1!==a)try{if(this.m_tabs[a].port){const d=b?CWEPredictionEngine.instance.allTopics():await CWEPredictionEngine.instance.getTopicsAsync(),e=this.displayTopics(),f={topics:d.topics,activeTopics:CWESettings.instance.topicsActive(),recentTopics:CWESettings.instance.topicsRecent(),displayTopics:e};c?chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.topics.DATA,data:f}):this.m_tabs[a].port.port().postMessage({message:window.dji.messages.cwe.topics.DATA,
data:f})}}catch(d){Logger.instance.error(d)}};CWEBackgroundManager.prototype.toggleOnOff=function(){(this.allowTogglePrediction()||this.allowMicrophone())&&this.__onBrowserAction(null)};CWEBackgroundManager.prototype.requestMomentaryTopicContext=function(){this.m_loaded&&this.m_on&&CWESettings.instance.predictionMomentaryTopic()&&-1!=this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&this.m_tabs[this.m_activeTabId].port.port().postMessage({message:window.dji.messages.cwe.topics.GET_CONTEXT_FOR_MOMENTARY_TOPIC})};
CWEBackgroundManager.prototype.tabNeedsSetup=function(a){chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.chrome.SETUP,data:{}})};CWEBackgroundManager.prototype.documentReadyInTab=function(a){this.m_loaded&&this.m_on&&a===this.m_activeTabId&&this.__enableInActiveTab(!0)};CWEBackgroundManager.prototype.documentCapabilitiesUpdateInTab=function(a,b){this.m_loaded&&this.m_on&&this.m_activeTabId===a&&-1!==a&&"office365-word-document"===b.service&&this.requestMomentaryTopicContext()};
CWEBackgroundManager.prototype.scheduleSpeakInTab=function(a,b,c,d,e,f){this.m_loaded&&this.m_on&&this.allowSpeech()&&a===this.m_activeTabId&&dji.tts.scheduleSpeak(b,c,null,{tabId:a,forwardEvents:d},this.m_ttsListener,e,f)};CWEBackgroundManager.prototype.speakInTab=function(a,b,c,d,e){this.m_loaded&&(this.m_on&&this.allowSpeech()&&a===this.m_activeTabId||c)&&dji.tts.speak(b,{tabId:a,forwardEvents:d},this.m_ttsListener,e)};CWEBackgroundManager.prototype.stopSpeakInTab=function(a){this.onStopSpeak()};
CWEBackgroundManager.prototype.onSpeakSelection=function(a,b){dji.tts.speak(b)};CWEBackgroundManager.prototype.onStopSpeak=function(){dji.tts.stop()};
CWEBackgroundManager.prototype.__onTtsStart=function(a,b,c){chrome.tabs.get(this.m_activeTabId,d=>{this.m_ttsTimer.stop();this.m_ttsTimer.userData=this.m_ttsTimer.userData||{};this.m_ttsTimer.userData.voiceUsed=c;var e=this.m_ttsTimer.userData.hostname||null;d=(new URL(d.url)).hostname;e&&e!==d?this.sendTextToSpeechTriggeredEvent():this.m_ttsTimer.userData.hostname=d;a&&a.forwardEvents&&a.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(e={message:window.dji.messages.cwe.tts.START,
info:a,sessionID:b},this.m_tabs[this.m_activeTabId].port.port().postMessage(e))})};CWEBackgroundManager.prototype.__onTtsWait=function(a){};
CWEBackgroundManager.prototype.__onTtsProgress=function(a,b,c,d,e){if(0<b&&e){let f=this.m_ttsTimer.userData&&this.m_ttsTimer.userData.counters||null;f||(f=this.m_ttsTimer.userData.counters={letterCounter:0,wordCounter:0});1===e?f.letterCounter+=1:1<e&&(f.wordCounter+=1);this.m_ttsTimer.userData.counters={letterCounter:f.letterCounter,wordCounter:f.wordCounter}}c&&c.forwardEvents&&c.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(a={message:window.dji.messages.cwe.tts.PROGRESS,
info:c,charIndex:a,endIndex:b,sessionID:d},this.m_tabs[this.m_activeTabId].port.port().postMessage(a))};CWEBackgroundManager.prototype.__onTtsStop=function(a,b,c){this.m_ttsTimer.trigger(5E3);a&&a.forwardEvents&&a.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(a={message:window.dji.messages.cwe.tts.STOP,info:a,timeSpent:b,sessionID:c},this.m_tabs[this.m_activeTabId].port.port().postMessage(a))};
CWEBackgroundManager.prototype.__onTtsError=function(a,b,c){a.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(a={message:window.dji.messages.cwe.tts.ERROR,info:a,sessionID:b,errObj:c},this.m_tabs[this.m_activeTabId].port.port().postMessage(a))};
CWEBackgroundManager.prototype.sendTextToSpeechTriggeredEvent=function(){const a=this.m_ttsTimer.userData;this.sendGA4Event("TextToSpeechTriggered",{letters_read:a&&a.counters&&a.counters.letterCounter,words_read:a&&a.counters&&a.counters.wordCounter,voice_used:a.voiceUsed},{website:a&&a.hostname});this.m_ttsTimer.userData={hostname:null,voice_used:null,counters:{letterCounter:0,wordCounter:0}}};
CWEBackgroundManager.prototype.onAddPersonalWords=function(a,b){this.m_loaded&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.addPersonalWords(b)};CWEBackgroundManager.prototype.onRemovePersonalWords=function(a,b){this.m_loaded&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.removePersonalWords(b)};
CWEBackgroundManager.prototype.updateTopicAsync=async function(a,b){const c=this;return new Promise(function(d){c.updateTopic(a,b,e=>{c.sendGA4Event("TopicStatusChanged",{topic_name:e.name,topic_status:e.active},null);d()})})};
CWEBackgroundManager.prototype.updateTopic=async function(a,b,c){if(this.m_busy)return c({status:"busy",name:b.name});const d={details:{name:b.name},userData:b.userData};try{if(b.local)return this.activateTopic(a,{name:b.name,activate:!0,provideTopicsData:!0},c);if(!b.local){const e=CWEPredictionEngine.instance.canActivateTopic(b.name);this.__enterBusyState();this.__sendNotification("update_topic_started",d);this.__notifyActiveTab("update_topic_started",d);let f=b.data;f||(f=await this.m_wikiReader.loadAsync(b.name,
this.locale()));if(!f)return this.__leaveBusyState(),this.__sendNotification("update_topic_finished",d),this.__notifyActiveTab("update_topic_failed",d),c({status:"failed",name:b.name});const g=await CWEPredictionEngine.instance.createWikiTopicAsync(b.name,f,e,b.userData);g&&a&&await this.provideTopicsData(a);this.__sendNotification("update_topic_finished",d);this.__leaveBusyState();if(g)return this.__notifyActiveTab("update_topic_finished",d),c({status:"ok",active:e,name:g.topic});this.__notifyActiveTab("update_topic_failed",
d);return c({status:"failed",name:b.name})}return c({status:"NOT IMPLEMENTED"})}catch(e){return Logger.instance.error(e),this.__leaveBusyState(),this.__notifyActiveTab("update_topic_failed",d),c({status:"failed",name:b.name})}};CWEBackgroundManager.prototype.activateTopicAsync=async function(a,b){const c=this;return new Promise(function(d){c.activateTopic(a,b,d)})};
CWEBackgroundManager.prototype.activateTopic=async function(a,b,c){if(this.m_busy)return c({status:"busy",name:b.name});if(b.activate&&!CWEPredictionEngine.instance.canActivateTopic(b.name))return c({status:"too_many_active_topics",name:b.name});let d={status:null,active:!!b.activate,name:b.name};this.__enterBusyState();try{this.__sendNotification("activate_topic_started",b);let e=void 0;e=b.activate?await CWEPredictionEngine.instance.activateTopicAsync(b.name):await CWEPredictionEngine.instance.deactivateTopicAsync(b.name);
b.provideTopicsData&&0<a&&await this.provideTopicsData(a);d.status="ok";d.name=e.topic}catch(e){Logger.instance.error(e),d.status="failed"}this.__leaveBusyState();this.__sendNotification("ok"===d.status?"activate_topic_finished":"activate_topic_failed",d);c(d)};CWEBackgroundManager.prototype.searchTopicsOnWeb=async function(a,b,c){a=await this.m_wikiReader.searchAsync(b.pattern,b.locale);c(a)};
CWEBackgroundManager.prototype.contextAvailable=async function(a,b,c,d){if(CWEPredictionEngine.instance){a={tabId:a,requestId:d};CWEPredictionEngine.instance.followTextChange(b.changed,b.selection.start,b.selection.length,b.text,a);try{if(CWEPredictionEngine.instance.spellcheckerIsRunning()){const e=CWEChromeUtilities.findWord(b.text,b.selection.start-1,!1);dji.logger.warn("[CWEBackgroundManager.prototype.contextAvailable]:",e);if(e&&0<e.length){const f=await CWEPredictionEngine.instance.spellcheck(e,
c,a);f&&(f.userData=a,this.spellcheckDone(f))}}}catch(e){Logger.instance.error(e)}}else Logger.instance.log("CWEPrediction not intialized"+(b.changed+":"+b.selection.start+":"+b.selection.length+":"+b.text))};
CWEBackgroundManager.prototype.guessesAvailable=function(a){Logger.instance.log("------------- CWEBackgroundManager.guessesAvailable: "+a);Logger.instance.log(this.m_tabs);Logger.instance.log(this.m_activeTabId);a.userData.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(a={message:window.dji.messages.cwe.ime.GUESSES_AVAILABLE,guesses:a.guesses,replacements:a.replacements,requestId:a.userData.requestId},this.m_tabs[this.m_activeTabId].port.port().postMessage(a))};
CWEBackgroundManager.prototype.spellcheckDone=function(a){if(a.userData.tabId===this.m_activeTabId)for(let b of a){if(b.locale!==CWESettings.instance.translationSource())continue;if(!b.matchFound)break;let c=this;dji.translator.translateWord(b.locale,this.localeLang(),b.word,function(d){d&&0<d.length&&a.userData.tabId===c.m_activeTabId&&-1!==c.m_activeTabId&&c.m_tabs[c.m_activeTabId].port&&(b.translations=d,d={message:window.dji.messages.cwe.ime.TRANSLATIONS_AVAILABLE,translations:d,requestId:a.userData.requestId},
c.m_tabs[c.m_activeTabId].port.port().postMessage(d))})}};CWEBackgroundManager.prototype.replaceText=function(a,b,c){-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port.port().postMessage({message:window.dji.messages.cwe.ime.REPLACE_TEXT,info:{selection:{start:a,end:b},text:c}})};CWEBackgroundManager.prototype.settingsChangedPredictionGuesses=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.setMaxPredictedGuesses(a)};
CWEBackgroundManager.prototype.settingsChangedPredictionMainDictionary=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.setMainDictionary(a)};CWEBackgroundManager.prototype.settingsChangedPredictionMomentaryTopic=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.enableMomentaryTopic(a)};CWEBackgroundManager.prototype.settingsChangedPredictionAhead=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.enablePredictAhead(a)};
CWEBackgroundManager.prototype.settingsChangedPredictionFlexibleSpelling=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.enableFlexibleSpelling(a)};
CWEBackgroundManager.prototype.topicCreated=function(a){Logger.instance.log("------------------------- CWEBackgroundManager.topicCreated:");Logger.instance.log(a);try{"create"===this.m_quickTopicActionInfo.action&&(Logger.instance.log(this.m_tabs),Logger.instance.log(this.m_quickTopicActionInfo.tabId),-1!=this.m_quickTopicActionInfo.tabId&&this.m_tabs[this.m_quickTopicActionInfo.tabId].port&&this.m_tabs[this.m_quickTopicActionInfo.tabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.topicCreated",
success:!0}),this.m_quickTopicActionInfo.action="")}catch(b){Logger.instance.log(b)}CWEPredictionEngine.instance.removeOptionsListener(this);return!0};
CWEBackgroundManager.prototype.changeLocale=async function(a){this.m_loaded&&a!==this.m_locale&&(this.onStopSpeak(),dji.speechRecognition.stop(),this.__onStopSync(),window.cwe.sync.changeLanguage(null),this.leaveTestingMode(),this.__enterBusyState(),this.m_on=!1,this.m_restartReason="--options-language-change",this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),this.__enableInActiveTab(!1),this.__sendNotification("deactivated"),CWEPredictionEngine.instance.reset(),
this.m_locale=window.localStorage.locale=a,this.m_userDirectory=`${this.m_userName}-${this.m_locale}`,await this.__changeUserDirectoryAsync(),window.cwe.sync.changeLanguage(this.m_locale),this.__onStartSync(),this.setIcon({path:this.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),this.__leaveBusyState(),this.reloadAppTabs())};
CWEBackgroundManager.prototype.changeSpellcheckerLocale=function(a){this.m_loaded&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.changeSpellcheckerLocale(a)};CWEBackgroundManager.prototype.prepareSpellchecker=async function(){const a=CWESettings.instance.translationSource();a&&await this.downloadHunspellResources(a)&&this.changeSpellcheckerLocale(a)};
CWEBackgroundManager.prototype.downloadPredictionResources=function(a,b){let c=window.cwe.locale.localeMap()[a];if(!a||!c)return b(!1);if("en-US"===c)return b(!0);let d=this,e=this.directories.common;window.jsdapi.resources.downloadLanguageResources(c,window.jsdapi.resources.Type.Prediction,e,{main:this.directories.mainDictionaries,topics:this.directories.predefinedTopicDictionaries},d.m_fileSystem,function(f){if(!f.errorCode)return b(!0);d.m_fileSystem.removeDirectory(e,function(){b(!1)})})};
CWEBackgroundManager.prototype.downloadHunspellLanguages=async function(){let a=this;return new Promise(function(b){window.jsdapi.resources.listAvailableLanguages(window.jsdapi.resources.Type.Hunspell,function(c){c=!c.errorCode&&c.languages?c.languages:[];let d=[...CWEPredictionEngine.instance.spellcheckerBundledLanguages()],e={};for(var f=0;f<d.length;f++){var g=d[f];e[g.language_code]=g}for(f=0;f<c.length;f++)g=c[f],e.hasOwnProperty(g.language_code)||(d.push(g),e[g.language_code]=g);d.sort(function(k,
h){return k.name.localeCompare(h.name)});a.m_translationLanguages=d;a.m_translationLanguagesMap=e;b()})})};
CWEBackgroundManager.prototype.downloadHunspellResources=async function(a){if(CWEPredictionEngine.instance.spellcheckerHasBundledResource(a)||""==a)return!0;let b=this;return new Promise(function(c){let d=b.directories.hunspell;window.jsdapi.resources.downloadLanguageResources(a,window.jsdapi.resources.Type.Hunspell,d,{},b.m_fileSystem,function(e){if(!e.errorCode)return c(!0);b.m_fileSystem.removeDirectory(d,function(){c(!1)})})})};
CWEBackgroundManager.prototype.resetHunspellLanguages=function(){let a=[...CWEPredictionEngine.instance.spellcheckerBundledLanguages()],b={};for(let c=0;c<a.length;c++){let d=a[c];b[d.language_code]=d}a.sort(function(c,d){return c.name.localeCompare(d.name)});this.m_translationLanguages=a;this.m_translationLanguagesMap=b};
CWEBackgroundManager.prototype.downloadSensitiveWordsResources=async function(){var a=CWEBackgroundManager.prototype.downloadSensitiveWordsResources.__timestamp=CWEBackgroundManager.prototype.downloadSensitiveWordsResources.__timestamp||0;a=Date.now()-a;if(!(-1E3<a&&9E5>a)){a=!1;try{a=await window.jsdapi.resources.downloadSensitiveWordsResourcesAsync(this.directories.sensitiveWords,this.m_fileSystem)||!CWEPredictionEngine.instance.hasCustomSensitiveWords(),CWEBackgroundManager.prototype.downloadSensitiveWordsResources.__timestamp=
Date.now()}catch(b){Logger.instance.error(b);try{await this.m_fileSystem.removeDirectoryAsync(this.directories.sensitiveWords)}catch(c){Logger.instance.error(c)}}if(a)try{await CWEPredictionEngine.instance.reloadSensitiveWordsAsync(),this.m_wikiReader.setOptions({sensitiveWords:CWEPredictionEngine.instance.sensitiveWords()})}catch(b){Logger.instance.error(b)}}};
CWEBackgroundManager.prototype.downloadSpecialPredictionsResources=async function(){var a=CWEBackgroundManager.prototype.downloadSpecialPredictionsResources.__timestamp=CWEBackgroundManager.prototype.downloadSpecialPredictionsResources.__timestamp||0;a=Date.now()-a;if(!(-1E3<a&&9E5>a)){a=!1;try{a=await window.jsdapi.resources.downloadSpecialPredictionsResourcesAsync(this.directories.specialPredictions,this.m_fileSystem)||!CWEPredictionEngine.instance.hasCustomSpecialPredictions(),CWEBackgroundManager.prototype.downloadSpecialPredictionsResources.__timestamp=
Date.now()}catch(b){Logger.instance.error(b);try{await this.m_fileSystem.removeDirectoryAsync(this.directories.specialPredictions)}catch(c){Logger.instance.error(c)}}if(a)try{await CWEPredictionEngine.instance.reloadSpecialPredictionsAsync()}catch(b){Logger.instance.error(b)}}};
CWEBackgroundManager.prototype.downloadAdditionalOnlineResources=async function(){let a=CWEBackgroundManager.prototype.downloadAdditionalOnlineResources.__info=CWEBackgroundManager.prototype.downloadAdditionalOnlineResources.__info||{promise:void 0};a.promise||(a.promise=new Promise(async b=>{try{await this.downloadSensitiveWordsResources(),await this.downloadSpecialPredictionsResources()}catch(c){Logger.instance.error(c)}a.promise=void 0;b()}));return a.promise};
CWEBackgroundManager.prototype.__predictionEngineLocaleChanged=function(a){a?(Logger.instance.debug("Successful switched to locale "+this.m_locale),window.localStorage.locale=this.m_locale,CWEPredictionEngine.instance.updateFromUserSettingsAsync(),window.cwe.login.isLoggedIn()?this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}):this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),
this.m_loaded=!0,this.changeUser(this.m_userName)):Logger.instance.error("Failed switching to locale "+this.m_locale)};CWEBackgroundManager.prototype.reloadAppTabs=function(a){chrome.tabs.query({url:this.m_appOptionsUrlPattern},function(b){let c=!1;try{for(let d=0;d<b.length;d++)chrome.tabs.reload(b[d].id),c=!0}catch(d){Logger.instance.error(d)}a&&a(c)})};
CWEBackgroundManager.prototype.__prepareUserLanguages=async function(a,b){b=b||function(){};if(!a)return b(!0);await this.downloadHunspellLanguages();await this.prepareSpellchecker();if(CWESettings.instance.showPresentationLanguageOption())try{await this.__checkUserPresentaionLanguage()}catch(c){Logger.instance.error(c)}this.__checkUserLanguage(a,b)};
CWEBackgroundManager.prototype.__checkUserPresentaionLanguage=async function(){var a=await window.jsdapi.cow.getPresentationLanguageAsync();a=a&&a.language||null;a||(a=this.CWEI18n.instance.getLanguage(),await window.jsdapi.cow.updatePresentationLanguageAsync(a));this.CWEI18n.instance.setCustomLanguage(a);CWESettings.instance.presentationLang(a)};
CWEBackgroundManager.prototype.__checkUserLanguage=async function(a,b){b=b||function(){};if(!a)return b(!0);let c=this;window.jsdapi.cow.getLanguage(a.openID,async function(d){Logger.instance.log("REMOTE LANGUAGE: "+d);Logger.instance.log("LOCALE LANGUAGE: "+c.m_locale);if(!d){d=c.CWEI18n.instance.getLanguage().toUpperCase();try{await window.jsdapi.cow.updateLanguageAsync(d)}catch(f){Logger.instance.error(f)}}if("BE"===d){d="UK";try{await window.jsdapi.cow.updateLanguageAsync(d)}catch(f){Logger.instance.error(f)}}let e=
c.findValidLanguage(d);c.downloadPredictionResources(e,async function(f){f&&d&&d===e&&d===c.m_locale?setTimeout(b,0,!0):f&&d&&d===e?(c.m_locale=window.localStorage.locale=d,await c.__changeUserDirectoryAsync(),setTimeout(b,0,!0)):(d=c.m_defaultLocale,window.jsdapi.cow.updateLanguage(d,function(g){setTimeout(b,0,!0)}))})})};CWEBackgroundManager.prototype.__validateTranslationSource=async function(){const a=this.localeLang(!1),b=(CWESettings.instance.translationSource()||"").split("-")[0];a===b&&CWESettings.instance.translationSource(null)};
CWEBackgroundManager.prototype.changeUser=async function(a,b){if(this.m_userName===a){if(b)try{b()}catch(c){Logger.instance.error(c)}}else if(this.m_loaded&&this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),this.__onStopSync(),CWEPredictionEngine.instance.reset(),this.m_userName=a,await this.__changeUserDirectoryAsync(),this.m_loaded&&(window.cwe.login.isLoggedIn()?(this.m_on&&this.__enableInActiveTab(!0),this.setIcon({path:this.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",
38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})):this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}})),window.cwe.sync.changeLanguage(this.m_locale),this.reloadAppTabs(),b)try{b()}catch(c){Logger.instance.error(c)}};
CWEBackgroundManager.prototype.__changeUserDirectoryAsync=async function(){const a=this;this.m_userDirectory=`${this.m_userName}-${this.m_locale}`;return new Promise(function(b){CWEDataManager.instance.changeUser(a.m_userDirectory,function(){CWESettings.instance.reload(a.m_userDirectory,function(){b()})})})};
CWEBackgroundManager.prototype.signOut=function(a){var b=this;this.__sendNotification("activation");this.onStopSpeak();dji.speechRecognition.stop();this.leaveTestingMode();b.m_on&&(b.m_on=!1,b.setIcon({path:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),b.__enableInActiveTab(b.m_on));this.__onStopSync();window.cwe.login.silentSignout(function(c){if(c)b.resetHunspellLanguages(),window.cwe.sync.changeLanguage(null),b.__removeContextMenus(),b.m_fileSystem.removeDirectory("/Users",
function(){b.__saveUserInfo(function(){b.changeUser("DefaultUser",function(){b.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}})})});if(a)try{a(c)}catch(d){Logger.instance.error(d)}a&&b.__reloadRelatedWebsites(!1);b.__sendNotification("activation")});else{b.__onStartSync();if(a)try{a(c)}catch(d){Logger.instance.error(d)}b.__sendNotification("activation")}})};
CWEBackgroundManager.prototype.__saveUserInfo=function(a){var b=window.cwe.login.userInfo();b=b?JSON.stringify(b):"";b=CryptoJS.AES.encrypt(b,"4$W%(WSFKS%W$W$@$%WMsdfsi042");this.m_fileSystem.writeFile("/info",b,function(){a&&a()})};CWEBackgroundManager.prototype.__loadUserInfo=function(a){window.cwe.login.userInfo()?a&&a():this.__readUserInfo(function(b){b&&window.cwe.login.userInfo(b);a&&a()})};
CWEBackgroundManager.prototype.__readUserInfo=function(a){this.m_fileSystem.readFileAsBinaryString("/info",function(b){var c=null;if(b&&0<b.length)try{(b=CryptoJS.AES.decrypt(b,"4$W%(WSFKS%W$W$@$%WMsdfsi042"))&&0<b.sigBytes&&(c=JSON.parse(CryptoJS.enc.Utf8.stringify(b)))}catch(d){Logger.instance.error(d)}a(c)})};
CWEBackgroundManager.prototype.__removeUserData=function(a,b){if(a){var c=this;this.m_fileSystem.removeDirectory("/Users",function(){c.m_userName="DefaultUser";c.m_userDirectory=c.m_userName+"-"+c.m_locale;CWEDataManager.instance.changeUser(c.m_userDirectory,function(){c.__removeUserInfo(function(){if(b)try{b()}catch(d){Logger.instance.error(d)}})})})}else b&&b()};CWEBackgroundManager.prototype.__removeUserInfo=function(a){this.m_fileSystem.removeFile("/info",function(){a&&a()})};
CWEBackgroundManager.prototype.tryEnterTestingMode=function(a){if(window.cwe.login.isLoggedIn()){var b=CWESettings.instance;if(a){if(!b.isInTestingMode(a))return!0}else b.isInTestingMode()&&b.leaveTestingMode()&&this.__onUserSettingsSynced()}return!1};CWEBackgroundManager.prototype.enterTestingMode=function(a){return window.cwe.login.isLoggedIn()&&CWESettings.instance.enterTestingMode(a)?!0:!1};
CWEBackgroundManager.prototype.leaveTestingMode=function(){return window.cwe.login.isLoggedIn()?CWESettings.instance.leaveTestingMode():!1};CWEBackgroundManager.prototype.isInTestingMode=function(){return window.cwe.login.isLoggedIn()?CWESettings.instance.isInTestingMode():!1};
CWEBackgroundManager.prototype.allowToggleOnOff=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return CWEChromeUtilities.isMicrosoftEdge()?!(a&&!a.allowTogglePrediction&&!a.allowSpeech):!(a&&!a.allowTogglePrediction&&!a.allowMicrophone&&!a.allowSpeech)}return!0};CWEBackgroundManager.prototype.allowTogglePrediction=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return!(a&&!a.allowTogglePrediction)}return!1};
CWEBackgroundManager.prototype.allowMicrophone=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return!CWEChromeUtilities.isMicrosoftEdge()&&!(a&&!a.allowMicrophone)}return!1};CWEBackgroundManager.prototype.allowSpeech=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return!(a&&!a.allowSpeech)}return!1};
CWEBackgroundManager.prototype.allowSettings=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return!(a&&!a.allowSettings)}return!1};CWEBackgroundManager.prototype.allowCreateTopics=function(){if(window.cwe.login.isLoggedIn()){const a=CWESettings.instance.features();return!(a&&!a.allowCreateTopics)}return!1};CWEBackgroundManager.prototype.allowChanges=function(){return window.cwe.login.isLoggedIn()?CWESettings.instance.allowChanges():["<none>"]};
CWEBackgroundManager.prototype.__onUserSettingsSynced=async function(){CWEPredictionEngine.instance&&(CWEPredictionEngine.instance.cacheTopics(),CWEPredictionEngine.instance.updateFromUserSettingsAsync());this.__applySettings();this.__sendNotification("update_user_settings");this.__applySettingsInActiveTab();this.reloadAppTabs();await this.prepareSpellchecker()};
CWEBackgroundManager.prototype.__onTopicsSynced=function(a,b){CWEPredictionEngine.instance&&(a||b?CWEPredictionEngine.instance.reloadDictionaries(a,b):CWEPredictionEngine.instance.rebuildTopicsCache())};
CWEBackgroundManager.prototype.onFilesChanged=async function(a){let b={};for(let c=0;c<a.length;c++){const d=a[c];b.hasOwnProperty(d.type)?b[d.type].push(d):b[d.type]=[d]}b.hasOwnProperty("dictionary/user")&&await CWEDataManager.instance.updateDictionaries(b["dictionary/user"]);b.hasOwnProperty("dictionary/user/personal")&&(a=b["dictionary/user/personal"][0],await CWEDataManager.instance.updatePersonalDictionary(a.filePath,a.name,a.type,a.language))};
CWEBackgroundManager.prototype.onTopicActivated=function(a){CWESettings.instance.data().addActiveTopic(a)&&CWESettings.instance.save()};CWEBackgroundManager.prototype.onTopicDeactivated=function(a){CWESettings.instance.data().removeActiveTopic(a)&&CWESettings.instance.save()};
CWEBackgroundManager.prototype.onTopicCreated=function(a,b){a&&0<a.length&&(b=CWESettings.instance.data().addOnlyMissingTopics(b),(b=CWESettings.instance.data().addRecentTopic(a)||b)&&CWESettings.instance.save());if(this.m_loaded&&this.m_on&&0<this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port)try{this.m_tabs[this.m_activeTabId].port.port().postMessage({message:window.dji.messages.cwe.topics.UPDATE})}catch(c){Logger.instance.error(c)}};
CWEBackgroundManager.prototype.activateLocaleRequiresReboot=function(){this.m_localeRequiresReboot=!0;this.m_loaded=!1;this.reloadAppTabs(function(a){a||chrome.tabs.create({url:"/Options/options.html",active:!0})})};CWEBackgroundManager.prototype.findValidLanguage=function(a){return"BE"===a||"CAN"===a||"UK"===a||"US"===a||"FR"===a||"SPA"===a||"GER"===a?a:"US"};
CWEBackgroundManager.prototype.prepareSpeechRecognitionInfo=function(a){if(!a)return null;var b=window.cwe.locale.localeMap();a=b.hasOwnProperty(a)?b[a]:a;b=a.split("-")[0];let c=dji.languages.languageInfo(b);return{langCode:a,langShortName:b.toUpperCase(),langFullName:c?c.name:a}};CWEBackgroundManager.prototype.applyActivationCode=function(a,b){window.jsdapi.account.applyActivationCode({activationCode:a},b)};
CWEBackgroundManager.prototype.loadConfig=function(a){this.m_fileSystem.readFile("env.config",function(b){if(b)try{var c=JSON.parse(b),d=c.configName;for(b=0;b<c.configs.length;b++){var e=c.configs[b];e.name===d&&dji.config.update(e)}}catch(f){Logger.instance.error(f)}window.jsdapi.http.setup({headers:{"x-dji-app-product":"cowriter","x-dji-app-platform":"chrome-extension","x-dji-app-os":dji.utils.os().name,"x-dji-app-extension-id":chrome.runtime.id}});window.jsdapi.translator.setUrls({server:dji.config.translateUrl()});
window.jsdapi.cow.setUrls({dapi:dji.config.dapiUrl()});window.jsdapi.resources.setUrls({resources:dji.config.resourcesUrl(),dapi:dji.config.dapiUrl()});window.jsdapi.setServerUrl({login:dji.config.loginUrl(!0),dapi:dji.config.dapiUrl()});window.jsdapi.setRefreshTokenDelegate(window.cwe.login.silentRefreshToken);window.jsdapi.setClientId(dji.config.clientID());a()})};
CWEBackgroundManager.prototype.imeActivationChanged=function(a,b){a?(window.cwe.measure.setHostname(b),window.cwe.measure.startTimeTracker()):window.cwe.measure.stopTimeTracker()};CWEBackgroundManager.prototype.accumulateAndMeasureData=function(a){window.cwe.measure.accumulateAndMeasureData(a)};CWEBackgroundManager.prototype.measurementResults=function(a){return window.cwe.measure.measurementResults(a)};CWEBackgroundManager.prototype.resetMeasurement=function(){return window.cwe.measure.reset()};
CWEBackgroundManager.prototype.updateGuessWindowPosition=function(a,b){CWESettings.instance.guessWindowPosition(b)};CWEBackgroundManager.prototype.sendTranslatedMessage=async function(a,b){const c=await this.CWEI18n.instance.getMessage(b);this.m_tabs[a].port.port().postMessage({message:window.dji.messages.cwe.i18n.TRANSLATE_TEXT,messageId:b,translatedText:c})};
CWEBackgroundManager.prototype.sendGA4Event=async function(a,b,c,d){if("PlaySelected"===a||"PreviousTenWordsSelected"===a){const e=CWESettings.instance.speech();b=b||{};b.voice_used=e&&e.voice}await this.GoogleAnalytics.instance.sendEvent(a,b,c,d)};
CWEBackgroundManager.prototype.toggleSpeechRecognition=function(a,b,c,d,e){if(!b)return dji.speechRecognition.stop();const f=(b="dictation"===d)?this.localeLang():void 0,g=b?CWESettings.instance.translationSource():void 0,k=b&&c===g;this.onStopSpeak();c=c||this.locale();dji.speechRecognition.start(c,function(h,l){chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.speech_recognition.NOTIFICATION,details:h,scope:h.scope,session:l.session})},function(h,l){k&&!h.error?dji.translator.translateText(g,
f,h.text,function(m){m&&0<m.length&&chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.speech_recognition.PROGRESS,error:h.error,text:m,scope:h.scope,session:l.session})}):chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.speech_recognition.PROGRESS,error:h.error,text:h.text,scope:h.scope,session:l.session})},function(h,l){chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.speech_recognition.END,error:h.error,scope:h.scope,session:l.session})},{tabId:a,scope:d,session:e})};
CWEBackgroundManager.prototype.translateHtmlDocument=async function(a){await window.dji.cwe.i18n.translateHtmlDocument(a)};CWEBackgroundManager.prototype.onOptions=function(){let a=this.m_appOptions;chrome.tabs.query({url:this.m_appOptionsUrlPattern},function(b){if(b&&0<b.length){try{for(let c=0;c<b.length;c++)chrome.tabs.reload(b[c].id)}catch(c){}chrome.tabs.update(b[0].id,{active:!0})}else chrome.tabs.create({url:a,active:!0})})};
CWEBackgroundManager.prototype.onProfile=function(){this.sendGA4Event("ProfileOpened",null,null);let a=dji.config.cowriterUrl();chrome.tabs.create({url:a,active:!0})};CWEBackgroundManager.prototype.onCreateTopicFromPage=function(a){this.onCreateTopic(a,!1)};CWEBackgroundManager.prototype.onCreateTopicFromSelection=function(a){this.onCreateTopic(a,!0)};
CWEBackgroundManager.prototype.onCreateTopic=async function(a,b){if(this.m_loaded)if(await this.__ensurePredictionEngineInitialized())try{chrome.tabs.sendMessage(a,{message:window.dji.messages.cwe.topics.CREATE,params:{from:b?"selection":"page",locale:this.m_locale,isEnglish:this.isEnglish(),topics:CWEPredictionEngine.instance.allTopics(),activeTopics:CWESettings.instance.topicsActive(),recentTopics:CWESettings.instance.topicsRecent(),displayTopics:this.displayTopics()}})}catch(c){Logger.instance.error(c)}else Logger.instance.error("Failed to initialize the prediction engine!")};
CWEBackgroundManager.prototype.__ensurePredictionEngineInitialized=async function(){const a=this;return new Promise(function(b){const c=function(){a.__initializePredictionEngine(function(d,e){d?setTimeout(b,0,d):e?setTimeout(b,0,d):setTimeout(c,500)})};c()})};
CWEBackgroundManager.prototype.__predictionEngineCrashed=function(a){dji.notifications.show({message:"Co:Writer has encountered an error! Please reactivate it after a few moments!",noUuid:!1});this.m_on&&(this.m_on=!1,this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),this.__enableInActiveTab(!1));this.reloadAppTabs()};
CWEBackgroundManager.prototype.setIcon=function(a){const b=CWEBackgroundManager.prototype.setIcon.session||(CWEBackgroundManager.prototype.setIcon.session={session:0,active:!1,queue:[]});b.session++;b.queue.push({session:b.session,details:a});if(!b.active){var c=function(){0>=b.queue.length?b.active=!1:chrome.browserAction.setIcon(b.queue.pop().details,c)};b.active=!0;c()}};
