function CWEBackgroundPort(a,b,c){if(!c)throw Error("Invalid arguments: listener is not provided!");this.m_port=a;this.m_tabId=b;this.m_listener=c;this.m_messageMap={[window.dji.messages.cwe.topics.UPDATE]:c.updateTopic,[window.dji.messages.cwe.topics.ACTIVATE]:c.activateTopic,[window.dji.messages.cwe.topics.SEARCH_WEB]:c.searchTopicsOnWeb};this.__intialize();return this}
CWEBackgroundPort.prototype.__intialize=function(){const a=this;this.m_port.onDisconnect.addListener(function(b){a.__onPortDisconnect(b)});this.m_port.onMessage.addListener(function(b){a.__onPortMessage(b)})};CWEBackgroundPort.prototype.__onPortDisconnect=function(a){Logger.instance.log("CWEBackgroundPort.__onPortDisconnect");Logger.instance.log(a);this.m_listener&&this.m_listener.__onPortDisconnect(this.m_tabId,this.m_port)};
CWEBackgroundPort.prototype.__onPortMessage=function(a){if(CWEBackgroundManager.instance.m_loaded)if(Logger.instance.log(a),a.message===window.dji.messages.cwe.chrome.TOGGLE)this.m_listener&&this.m_listener.toggleOnOff();else if(a.message===window.dji.messages.cwe.chrome.NEEDS_SETUP)this.m_listener&&this.m_listener.tabNeedsSetup(this.m_tabId,a.details);else if(a.message===window.dji.messages.cwe.chrome.DOCUMENT_READY)this.m_listener&&this.m_listener.documentReadyInTab(this.m_tabId);else if(a.message===
window.dji.messages.cwe.chrome.DOCUMENT_CAPABILITIES_UPDATE)this.m_listener&&this.m_listener.documentCapabilitiesUpdateInTab(this.m_tabId,a.details);else if(a.message===window.dji.messages.cwe.ime.RESTART_GUESSES)CWEPredictionEngine.instance&&CWEPredictionEngine.instance.restartGuesses();else if(a.message===window.dji.messages.cwe.ime.CONTEXT_AVAILABLE)this.m_listener&&this.m_listener.contextAvailable(this.m_tabId,a.context,a.fullSpelling,a.requestId);else if(a.message===window.dji.messages.cwe.topics.CONTEXT_FOR_MOMENTARY_TOPIC_AVAILABLE)CWEPredictionEngine.instance?
CWEPredictionEngine.instance.updateMomentaryTopic(a.context.text):Logger.instance.log(a.context.text);else if(a.message===window.dji.messages.cwe.ime.GUESS_SELECTED)CWEPredictionEngine.instance?CWEPredictionEngine.instance.acceptGuess(a.guess):Logger.instance.log(a.guess);else if(a.message===window.dji.messages.cwe.speak.SCHEDULE)this.m_listener&&this.m_listener.scheduleSpeakInTab(this.m_tabId,a.text,a.stopCurrentSpeech,a.listenForEvents,a.sessionID,a.speechOptions);else if(a.message===window.dji.messages.cwe.speak.SPEAK)this.m_listener&&
this.m_listener.speakInTab(this.m_tabId,a.text,a.force,a.listenForEvents,a.sessionID);else if(a.message===window.dji.messages.cwe.speak.STOP)this.m_listener&&this.m_listener.stopSpeakInTab(this.m_tabId);else if(a.message===window.dji.messages.cwe.personal_words.ADD){if(this.m_listener)this.m_listener.onAddPersonalWords(this.m_tabId,a.text)}else if(a.message===window.dji.messages.cwe.personal_words.REMOVE){if(this.m_listener)this.m_listener.onRemovePersonalWords(this.m_tabId,a.text)}else if(a.message===
window.dji.messages.cwe.ime.ACTIVATION_CHANGED)this.m_listener&&this.m_listener.imeActivationChanged(a.active,a.hostname);else if(a.message===window.dji.messages.cwe.ime.ACCUMULATE_DATA)this.m_listener&&this.m_listener.accumulateAndMeasureData(a.text);else if(a.message===window.dji.messages.cwe.speech_recognition.TOGGLE)this.m_listener&&this.m_listener.toggleSpeechRecognition(this.m_tabId,a.on,a.langCode,a.scope,a.session);else if(a.message===window.dji.messages.cwe.ime.GUESS_WINDOW_POS_UPDATE)this.m_listener&&
this.m_listener.updateGuessWindowPosition(this.m_tabId,a.position);else if(a.message===window.dji.messages.cwe.i18n.TRANSLATE_TEXT)this.m_listener&&this.m_listener.sendTranslatedMessage(this.m_tabId,a.messageId);else if("googleAnalyticsEvent"===a.message)this.m_listener&&a.data&&this.m_listener.sendGA4Event(a.data.eventName,a.data.customProperties,a.data.defaultProperties);else{const b=a.options?a.options.callbackMessage||a.message:a.message,c=this.m_messageMap.hasOwnProperty(a.message)?this.m_messageMap[a.message]:
void 0;if(!(c instanceof Function))return this.m_port.postMessage({message:b,error:"No valid handler has been registered!"});const d=this;c.call(this.m_listener,this.m_tabId,a.params,function(e){d.m_port.postMessage({message:b,params:e})})}};CWEBackgroundPort.prototype.port=function(){return this.m_port};
