window.cwe=window.cwe||{};
(function(k){function w(c){c&&(q.has(c)?(c=q.get(c),c.measureData=e,c.totalTime+=l.total()):q.set(c,{measureData:e,totalTime:l.total()}),l.reset())}function x(){for(var c={},a,b=n.length,f=0;f<b;f++){var g=n[f];var d=g.word;a=[];d=d.toLowerCase();for(var p=0;p<d.length;p++){var h=d.charAt(p);CWECharacterSet.wordSeparatorCharacterSet.characterIsMember(h)?CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(h)?0!=a.length&&0==a[a.length-1].length||a.push(""):(0==a.length||0!=a[a.length-1].length?
a.push(h):a[a.length-1]+=h,a.push("")):0==a.length?a.push(h):a[a.length-1]+=h}d=a;a=c;for(h=0;h<d.length;h++)0<d[h].length&&(a.hasOwnProperty(d[h])?a=a[d[h]]:a[d[h]]=a={});a.hasOwnProperty("@")?a["@"].push({id:g.id,category:g.category,word:g.word}):a["@"]=[{id:g.id,category:g.category,word:g.word}]}return c}function t(c){if(c)try{c.apply(this,[].slice.call(arguments).splice(1))}catch(a){Logger.instance.error(a)}}var u=-1,n=[],r=[],e={chunks:[],chunkStatus:[],chunkCount:0,words:{},totalWords:0};let v=
null,q=new Map;var l=new CWETimeTracker,m=!1;k.initialize=function(c){CWEBackgroundManager.instance.requestFileSystem(function(a){a.readFile("wordList",function(b){if(b)try{var f=JSON.parse(b);u=f.version;n=f.words;r=f.tree}catch(g){Logger.instance.error(g)}t(c)})},function(){t(c)})};k.enablePrivacyMode=function(c){c!=m&&(c&&(l.stop(),k.reset()),m=c)};k.timeTracker=function(){return l};k.startTimeTracker=function(){return m?null:l.start()};k.stopTimeTracker=function(){return m?null:l.stop()};k.totalTime=
function(){return m?null:l.total()};k.version=function(){return u};k.words=function(){return n};k.tree=function(){return r};k.update=function(c,a){if(!c||!c.version||!c.words)return t(a);u=c.version;n=c.words||n;r=x();CWEBackgroundManager.instance.requestFileSystem(function(b){c=JSON.stringify({version:u,words:n,tree:r});b.writeFile("wordList",c,function(){t(a)})},function(){t(a)})};k.setHostname=function(c){m||v===c||(w(v),e=q.has(c)?q.get(c).measureData:{chunks:[],chunkStatus:[],chunkCount:0,words:{},
totalWords:0},v=c)};k.accumulateAndMeasureData=function(c){if(!m&&(c||0!=e.chunks.length&&0!=e.chunks[e.chunks.length-1].length)){var a=e.chunks,b=e.chunkStatus;var f=(c||" ").toLowerCase();for(var g=0;g<f.length;g++){var d=f.charAt(g);if(CWECharacterSet.wordSeparatorCharacterSet.characterIsMember(d))if(CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(d)){if(0==a.length||0!=a[a.length-1].length)a.push(""),b.push(0)}else 0==a.length||0!=a[a.length-1].length?(a.push(d),b.push(0)):(a[a.length-
1]+=d,b[b.length-1]=0),a.push(""),b.push(0);else"\b"==d?0<a.length&&(0==a[a.length-1].length?(a.splice(a.length-1,1),b.splice(b.length-1,1)):(a[a.length-1]=a[a.length-1].substring(0,a[a.length-1].length-1),b[b.length-1]=0)):0==a.length?(a.push(d),b.push(0)):(a[a.length-1]+=d,b[b.length-1]=0)}f=e.chunks;d=e.chunkStatus;if(0<f.length&&0==f[f.length-1].length&&0==d[d.length-1]){a=r;var p;for(b=0;b<f.length;b++)if(0==f[b].length)d[b]=1;else{if(0==d[b]){if(1<f[b].length||!CWECharacterSet.wordSeparatorCharacterSet.characterIsMember(f[b]))e.totalWords+=
1;d[b]=1}if(a.hasOwnProperty(f[b])){if(a=a[f[b]],2!=d[b]&&a.hasOwnProperty("@")&&(p=a["@"]))for(g=0;g<p.length;g++){let h=p[g];e.words[h.id]={count:(e.words[h.id]&&e.words[h.id].count||0)+1,category:e.words[h.id]&&e.words[h.id].category||h.category,word:e.words[h.id]&&e.words[h.id].word||h.word};d[b]=2}}else{a=r;f.splice(0,1);d.splice(0,1);for(g=0;g<d.length;g++)2==d[g]&&(d[g]=1);b=-1}}e.chunkCount=f.length}c||(e.chunks=[],e.chunkStatus=[],e.chunkCount=0)}};k.measurementResults=function(c){if(m)return null;
w(v);let a={};q.forEach((b,f,g)=>{0<b.totalTime&&(a[f]={words:b.measureData.words,totalWords:b.measureData.totalWords,totalTime:b.totalTime},c&&(b.measureData.words={},b.measureData.totalWords=0,b.totalTime=0))});return a};k.reset=function(){m||(e={chunks:[],chunkStatus:[],chunkCount:0,words:{},totalWords:0},l.reset())}})(window.cwe.measure=window.cwe.measure||{});
