function CWEDataManager(){this.user="DefaultUser";this.userDir="/Users/DefaultUser/";this.userTopicDir="/Users/DefaultUser/Topics/";this.userSettingsFile=this.userDir+"Preferences.txt";this.userDictionariesInfoFile=this.userDir+"UserDictionariesInfo.txt";this.userPersonalDictionaryInfoFile=this.userDir+"UserPersonalDictionaryInfo.txt";this.userMeasuredDataFile=this.userDir+"Measurements.txt";this.userRtmOptFile=this.userDir+"RtmOpt.txt";this.userDictionariesInfo={};this.m_syncUserSettingsTimer=this.m_dataSyncManager=
this.userMeasurementsInfo=this.userPersonalDictionaryInfo=null}CWEDataManager.instance=null;CWEDataManager.initialize=function(b){try{null===CWEDataManager.instance&&(CWEDataManager.instance=new CWEDataManager,CWEDataManager.instance.__initialize(b))}catch(d){Logger.instance.error(d)}};CWEDataManager.prototype.__initialize=function(b){var d=this;this.__loadPersonalDictionary(function(){d.__loadDictionaries(function(){d.__loadMeasurements(b)})})};
CWEDataManager.prototype.setDataSyncManager=function(b){this.m_dataSyncManager=b};
CWEDataManager.prototype.changeUser=function(b,d){let c=this;c.__cancelSyncUserSettingsTimer();(function(){window.cwe.measure.reset();c.user=b;c.userDir="/Users/"+b+"/";c.userTopicDir="/Users/"+b+"/Topics/";c.userTopicFile="/Users/"+b+"/topics.cache";c.userSettingsFile=c.userDir+"Preferences.txt";c.userDictionariesInfoFile=c.userDir+"UserDictionariesInfo.txt";c.userPersonalDictionaryInfoFile=c.userDir+"UserPersonalDictionaryInfo.txt";c.userMeasuredDataFile=c.userDir+"Measurements.txt";c.userRtmOptFile=
c.userDir+"RtmOpt.txt";c.userDictionariesInfo={};c.userPersonalDictionaryInfo=null;c.userMeasurementsInfo=null;CWEBackgroundManager.instance.requestFileSystem(function(a){a.createDirectory(c.userTopicDir,function(){a.getFile(c.userTopicFile,!0,function(){c.__initialize(d)})})})})()};
CWEDataManager.prototype.updateDictionaries=async function(b){if(b&&!(0>=b.length)){var d=new DjiFileSystemDirectoryEntryProxy(CWEBackgroundManager.instance.fileSystem().m_fileSystem.root),c=[];for(let h=0;h<b.length;h++){var a=b[h];if(!(a&&a.filePath&&a.name&&a.language))continue;let k="";var e=a.filePath.split("/");0<e.length&&(k=e[e.length-1]);e=null;for(const l in this.userDictionariesInfo)if(this.userDictionariesInfo.hasOwnProperty(l)){e=this.userDictionariesInfo[l];if(e.title===a.name&&e.preview===
k)break;e=null}e?(e.modifiedDate=Date.now(),e.modifiedUuid=CWEChromeUtilities.generateUUID()):(e=CWEUserDictionaryInfo.createNew(a.filePath,a.name,a.type,a.language),this.userDictionariesInfo[e.uuid]=e);a=await d.readAsBinaryStringAsync(a.filePath);e.checksum=CryptoJS.MD5(JSON.stringify(a)).toString();c.push(e)}if(!(0>=c.length)){var f=this;return new Promise(h=>{f.saveDictionariesInfo(function(){if(f.m_dataSyncManager)for(let k=0;k<c.length;k++)f.m_dataSyncManager.enqueueUpdateDictionary(c[k]);h()})})}}};
CWEDataManager.prototype.updateDictionariesFromDapiFileMap=function(b,d){var c=this,a={filesToDownload:[],filesToUpload:[],filesToDelete:[]},e=function(){for(var p in c.userDictionariesInfo){var n=c.userDictionariesInfo[p];n.dapiFile?n.deleted?a.filesToDelete.push(n):n.downloadRequired?a.filesToDownload.push(n):n.checksum!==n.dapiFile.checksum&&a.filesToUpload.push(n):a.filesToUpload.push(n)}return a};if(b){var f=[],h=[],k=[],l;for(l in this.userDictionariesInfo){var g=this.userDictionariesInfo[l];
g.dapiFile&&!b.hasOwnProperty(l)&&f.push(l)}for(l in b){var m=b[l];this.userDictionariesInfo.hasOwnProperty(l)?(g=this.userDictionariesInfo[l],!g.deleted&&g.dapiFile&&g.dapiFile.version<m.version&&h.push(l)):k.push(l)}if(0>=f.length&&0>=h.length&&0>=k.length)d&&(e(),d(!1,a));else{var t=function(){for(var p=[],n=0;n<f.length;n++){var q=f[n],r=c.userDictionariesInfo[q];delete c.userDictionariesInfo[q];p.push(c.userTopicDir+r.preview)}return p}();(function(){for(var p=0;p<h.length;p++){var n=h[p],q=
c.userDictionariesInfo[n];q.updateFromDapiFile(b[n]);q.downloadRequired=!0}})();(function(){for(var p=0;p<k.length;p++){var n=k[p],q=CWEUserDictionaryInfo.createNewFromDapiFile(b[n]);q.downloadRequired=!0;c.userDictionariesInfo[n]=q}})();e();CWEBackgroundManager.instance.requestFileSystem(function(p){p.writeFile(c.userDictionariesInfoFile,JSON.stringify(c.userDictionariesInfo),function(){p.removeFiles(t,function(){d&&d(!0,a)})})})}}else d&&(e(),d(!1,a))};
CWEDataManager.prototype.updateDictionaryFromDapi=function(b,d,c,a){if(b){var e=this.userDictionariesInfo[b.uuid];e?e.updateFromDapiFile(b):(e=CWEUserDictionaryInfo.createNewFromDapiFile(b),this.userDictionariesInfo[b.uuid]=e);e.downloadRequired=d;var f=this,h=this.userTopicDir+e.preview;CWEBackgroundManager.instance.requestFileSystem(function(k){k.writeFile(f.userDictionariesInfoFile,JSON.stringify(f.userDictionariesInfo),function(l){l?f.updateTopicsCache(e.preview,function(){c?k.writeFile(h,c,function(g){f.__callback(a)}):
f.__callback(a)}):f.__callback(a)})})}else this.__callback(a)};CWEDataManager.prototype.saveDictionaryInfo=function(b,d){this.saveDictionariesInfo(d)};CWEDataManager.prototype.saveDictionariesInfo=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.writeFile(d.userDictionariesInfoFile,JSON.stringify(d.userDictionariesInfo),b)})};
CWEDataManager.prototype.updatePersonalDictionary=async function(b,d,c,a){if(b&&d&&a){this.userPersonalDictionaryInfo?(this.userPersonalDictionaryInfo.modifiedDate=Date.now(),this.userPersonalDictionaryInfo.modifiedUuid=CWEChromeUtilities.generateUUID()):this.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNew(b,d,c,a);var e=this;return new Promise(f=>{CWEBackgroundManager.instance.requestFileSystem(function(h){h.readFile(b,function(k){k?(e.userPersonalDictionaryInfo.checksum=CryptoJS.MD5(k).toString(),
e.savePersonalDictionaryInfo(function(){e.m_dataSyncManager&&e.m_dataSyncManager.enqueueUpdatePersonalDictionary(e.userPersonalDictionaryInfo);f()})):f()})})})}};
CWEDataManager.prototype.updatePersonalDictionaryFromDapi=function(b,d,c,a){if(b){this.userPersonalDictionaryInfo?this.userPersonalDictionaryInfo.updateFromDapiFile(b):this.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNewFromDapiFile(b);this.userPersonalDictionaryInfo.downloadRequired=d;var e=this,f=this.userDir+this.userPersonalDictionaryInfo.preview;CWEBackgroundManager.instance.requestFileSystem(function(h){h.writeFile(e.userPersonalDictionaryInfoFile,JSON.stringify(e.userPersonalDictionaryInfo),
function(k){k?c?h.writeFile(f,c,function(l){e.__callback(a)}):e.__callback(a):e.__callback(a)})})}else this.__callback(a)};
CWEDataManager.prototype.updatePersonalDictionariesFromDapiFileMap=function(b,d){var c={filesToDownload:[],filesToUpload:[]},a=this.userPersonalDictionaryInfo,e=!1;b?a&&a.dapiFile?a.downloadRequired||a.dapiFile.version<b.version?(a.updateFromDapiFile(b),a.downloadRequired=!0,c.filesToDownload.push(a),e=!0):a.modifiedDate>b.modifiedDate&&c.filesToUpload.push(a):(a?a.updateFromDapiFile(b):a=this.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNewFromDapiFile(b),a.downloadRequired=!0,c.filesToDownload.push(a),
e=!0):a&&c.filesToUpload.push(a);if(e){var f=this;this.savePersonalDictionaryInfo(function(){f.__callback(d,!0,c)})}else this.__callback(d,!1,c)};CWEDataManager.prototype.savePersonalDictionaryInfo=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.writeFile(d.userPersonalDictionaryInfoFile,JSON.stringify(d.userPersonalDictionaryInfo),b)})};
CWEDataManager.prototype.syncUserSettings=function(){this.__cancelSyncUserSettingsTimer();if(this.m_dataSyncManager&&!CWEBackgroundManager.instance.isInTestingMode()){var b=this,d=CWEBackgroundManager.instance.settings().data();if(!d.dapiFile||d.dapiFile.modifiedDate<d.modifiedDate)this.m_syncUserSettingsTimer=setTimeout(function(){b.m_dataSyncManager.enqueueUpdateUserSettings(d)},500)}};
CWEDataManager.prototype.saveUserSettings=function(b,d){var c=this;this.__cancelSyncUserSettingsTimer();CWEBackgroundManager.instance.isInTestingMode()||CWEBackgroundManager.instance.requestFileSystem(function(a){JSON.stringify(b);a.writeFile(c.userSettingsFile,JSON.stringify(b),function(){c.syncUserSettings();c.__callback(d)})})};
CWEDataManager.prototype.loadUserSettings=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.readFileAsText(d.userSettingsFile,function(a){var e=null;if(a)try{e=JSON.parse(a)}catch(f){Logger.instance.error(f)}d.__callback(b,e)})})};
CWEDataManager.prototype.updateUserSettingsFromDapiFileMap=function(b,d){var c=!1,a={filesToDownload:[],filesToUpload:[]},e=CWEBackgroundManager.instance.settings();if(!e.isInTestingMode()){var f=e.data();b?f.dapiFile?f.downloadRequired||f.dapiFile.version<b.version?(f.updateFromRemoteData(b,null),f.downloadRequired=!0,a.filesToDownload.push(f),c=!0):f.modifiedDate>b.modifiedDate&&a.filesToUpload.push(f):(f.updateFromRemoteData(b,null),f.downloadRequired=!0,a.filesToDownload.push(f),c=!0):a.filesToUpload.push(f)}if(c){var h=
this;this.saveUserSettings(f,function(){h.__callback(d,!0,a)})}else this.__callback(d,!1,a)};CWEDataManager.prototype.updateUserSettingsFromDapi=function(b,d,c,a){if(b){var e=CWEBackgroundManager.instance.settings();if(e.isInTestingMode())this.__callback(a,!1);else{e=e.data();e.updateFromRemoteData(b,c);e.downloadRequired=d;var f=this;f.saveUserSettings(e,function(){f.__callback(a,!0)})}}else this.__callback(a,!1)};
CWEDataManager.prototype.updateTestingSettingsFromDapi=function(b,d,c){if(b){var a=CWEBackgroundManager.instance.settings();a.isInTestingMode()?(a=a.data(),a.updateFromRemoteData(b,d,!0),a.downloadRequired=!1,this.__callback(c,!0)):this.__callback(c,!1)}else this.__callback(c,!1)};CWEDataManager.prototype.checkDataWordListNeedsDownload=function(b,d){return b?window.cwe.measure.version()<b.version:!0};
CWEDataManager.prototype.updateDataWordList=function(b,d){if(!b)return d();window.cwe.measure.update(b,d)};CWEDataManager.prototype.enablePrivacyMode=function(b,d){if(b!=this.userMeasurementsInfo.privacyMode){this.userMeasurementsInfo.privacyMode=b;window.cwe.measure.enablePrivacyMode(b);var c=this,a=JSON.stringify(this.userMeasurementsInfo);CWEBackgroundManager.instance.requestFileSystem(function(e){e.writeFile(c.userMeasuredDataFile,a,function(){c.__callback(d)})})}else this.__callback(d)};
CWEDataManager.prototype.prepareMeasuredDataForSync=function(b){if(this.userMeasurementsInfo.privacyMode)return this.__callback(b,null,null);var d=window.cwe.measure.measurementResults(!0);let c=this.userMeasurementsInfo||{},a=c.current||{};for(const [g,m]of Object.entries(d))if(a.hasOwnProperty(g)){a[g].words=a[g].words||{};a[g].totalWords=a[g].totalWords||0;a[g].totalTime=a[g].totalTime||0;d=0;for(var e in m.words)m.words.hasOwnProperty(e)&&(d=m.words[e],a[g].words[e]=(a[g].words[e]||0)+d);a[g].totalWords+=
m.totalWords;a[g].totalTime+=m.totalTime}else a[g]=JSON.parse(JSON.stringify(m));e=c.history||{};for(var f in e){d=c.history[f].data;for(const [g,m]of Object.entries(d))if(a.hasOwnProperty(g)){a[g].words=a[g].words||{};a[g].totalWords=a[g].totalWords||0;a[g].totalTime=a[g].totalTime||0;e=0;for(var h in m.words)m.words.hasOwnProperty(h)&&(e=m.words[h],a[g].words[h]=(a[g].words[h]||0)+e);a[g].totalWords+=m.totalWords;a[g].totalTime+=m.totalTime}else a[g]=JSON.parse(JSON.stringify(m))}c.history={};f=
{words:{},totalWords:0,totalTime:0};for(const [,g]of Object.entries(a)){h=0;for(let m in g.words)g.words.hasOwnProperty(m)&&(h=g.words[m],f.words[m]=(f.words[m]||0)+h);f.totalWords+=g.totalWords;f.totalTime+=g.totalTime}c.current=a;c.aggregateMeasurements=f;this.userMeasurementsInfo=c;if(0>=CWEChromeUtilities.mapIsEmpty(f.words)&&0>=f.totalWords&&0>=f.totalTime)this.__callback(b,null,null);else{var k=this;uuid=CWEChromeUtilities.generateUUID();c.history=c.history||{};c.history[uuid]={timestamp:Date.now(),
data:a};c.current={};var l=JSON.stringify(c);CWEBackgroundManager.instance.requestFileSystem(function(g){g.writeFile(k.userMeasuredDataFile,l,function(){a=c.history[uuid].data;k.__callback(b,{measurements:a,aggregateMeasurements:c.aggregateMeasurements},uuid)})})}};
CWEDataManager.prototype.measuredDataSyncDone=function(b,d,c){let a=this.userMeasurementsInfo;if(!b){var e=a.history[d].data;b=a.current||{};for(const [k,l]of Object.entries(e))if(b.hasOwnProperty(k)){b[k].words=b[k].words||{};b[k].totalWords=b[k].totalWords||0;b[k].totalTime=b[k].totalTime||0;e=0;for(let g in l.words)l.words.hasOwnProperty(g)&&(e=l.words[g],b[k].words[g]=(b[k].words[g]||0)+e);b[k].totalWords+=l.totalWords;b[k].totalTime+=l.totalTime}else b[k]=JSON.parse(JSON.stringify(l));a.current=
b}delete a.history[d];a.aggregateMeasurements={};var f=JSON.stringify(a),h=this;CWEBackgroundManager.instance.requestFileSystem(function(k){k.writeFile(h.userMeasuredDataFile,f,function(){h.__callback(c)})})};
CWEDataManager.prototype.__loadPersonalDictionary=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.readFile(d.userPersonalDictionaryInfoFile,function(a){if(a)try{var e=JSON.parse(a);d.userPersonalDictionaryInfo=new CWEUserDictionaryInfo(e)}catch(f){Logger.instance.error(f)}d.__callback(b)})},function(){d.__callback(b)})};
CWEDataManager.prototype.__loadDictionaries=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.readFile(d.userDictionariesInfoFile,function(a){if(a)try{var e=JSON.parse(a),f;for(f in e)d.userDictionariesInfo[f]=new CWEUserDictionaryInfo(e[f])}catch(h){Logger.instance.error(h)}d.__callback(b)})},function(){d.__callback(b)})};
CWEDataManager.prototype.__loadMeasurements=function(b){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(c){c.readFile(d.userMeasuredDataFile,function(a){if(a)try{d.userMeasurementsInfo=JSON.parse(a)}catch(e){Logger.instance.error(e)}d.userMeasurementsInfo||(d.userMeasurementsInfo={});d.userMeasurementsInfo.hasOwnProperty("privacyMode")||(d.userMeasurementsInfo.privacyMode=!1);window.cwe.measure.enablePrivacyMode(d.userMeasurementsInfo.privacyMode);d.__callback(b)})},function(){d.__callback(b)})};
CWEDataManager.prototype.saveRtmOptionsAsync=async function(b){try{await (new DjiFileSystemDirectoryEntryProxy(CWEBackgroundManager.instance.fileSystem().m_fileSystem.root)).writeFileAsJSONAsync(this.userRtmOptFile,b||{})}catch(d){Logger.instance.error(d)}};CWEDataManager.prototype.readRtmOptionsAsync=async function(){let b={};try{b=await (new DjiFileSystemDirectoryEntryProxy(CWEBackgroundManager.instance.fileSystem().m_fileSystem.root)).readFileAsJSONAsync(this.userRtmOptFile)}catch(d){Logger.instance.log(d)}return b};
CWEDataManager.prototype.__stopSync=function(){this.m_dataSyncManager&&this.m_dataSyncManager.stop()};CWEDataManager.prototype.__startSync=function(){this.m_dataSyncManager&&this.m_dataSyncManager.start()};CWEDataManager.prototype.__cancelSyncUserSettingsTimer=function(){this.m_syncUserSettingsTimer&&(clearTimeout(this.m_syncUserSettingsTimer),this.m_syncUserSettingsTimer=null)};
CWEDataManager.prototype.readUserDictionaryFile=function(b,d){if(this.userDictionariesInfo.hasOwnProperty(b)){var c=this,a=c.userTopicDir+this.userDictionariesInfo[b].preview;CWEBackgroundManager.instance.requestFileSystem(function(e){e.readFileAsArrayBuffer(a,function(f){c.__callback(d,f)})})}else this.__callback(d,null)};
CWEDataManager.prototype.readUserPersonalDictionaryFile=function(b){if(this.userPersonalDictionaryInfo){var d=this,c=this.userDir+this.userPersonalDictionaryInfo.preview;CWEBackgroundManager.instance.requestFileSystem(function(a){a.readFileAsArrayBuffer(c,function(e){d.__callback(b,e)})})}else this.__callback(b,null)};CWEDataManager.prototype.translationCacheFileName=function(b,d){if(b&&d)return`${this.userDir}TranslationCache_${b}_${d}.txt`};
CWEDataManager.prototype.saveTranslationCache=function(b,d,c,a){let e=this.translationCacheFileName(b,d);if(!e||CWEBackgroundManager.instance.isInTestingMode())return this.__callback(a,!1);let f=this;CWEBackgroundManager.instance.requestFileSystem(function(h){c=JSON.stringify(c);h.writeFile(e,c,function(){f.__callback(a,!0)})})};
CWEDataManager.prototype.loadTranslationCache=function(b,d,c){let a=this.translationCacheFileName(b,d);if(!a)return this.__callback(c,null);let e=this;CWEBackgroundManager.instance.requestFileSystem(function(f){f.readFileAsText(a,function(h){if(null!==h&&void 0!==h)try{h=JSON.parse(h)}catch(k){h=null,Logger.instance.error(k)}e.__callback(c,h)})})};
CWEDataManager.prototype.updateTopicsCache=function(b,d){let c=this;CWEBackgroundManager.instance.requestFileSystem(function(a){let e=Object.values(c.userDictionariesInfo).map(f=>"Topics/"+f.preview).join("\n");a.writeFile(c.userTopicFile,e,d)})};CWEDataManager.prototype.__callback=function(b){if(b)try{b.apply(this,[].slice.call(arguments).splice(1))}catch(d){Logger.instance.error(d)}};
