window.cwe=window.cwe||{};
(function(k){function E(a){y.dispatchEvent(new CustomEvent("ga4-domain-license",{detail:{data:a}}))}function F(a,b,c,d){y.dispatchEvent(new CustomEvent("ga4-send-event",{detail:{data:{eventName:a,customProperties:b,defaultProperties:c,resetSessionId:d}}}))}function G(a){y.dispatchEvent(new CustomEvent("ga4-privacy-mode",{detail:{data:a}}))}function H(a){f&&f.id==a&&(f=null,setTimeout(Q,0))}function R(){chrome.tabs.create({url:window.dji.config.loginUrlEx(CWESettings.instance.disabledLoginProviders()),active:!0},
function(a){f=a;chrome.tabs.onRemoved.addListener(H)})}function I(a){u=a.url;chrome.tabs.remove(f.id)}function J(a){Logger.instance.monitor({event:"login_bsrrr_1a"});if(a=dji.utils.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a){if(a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}if(a.hasOwnProperty("expires_at"))try{a.expires_at=parseInt(a.expires_at)}catch(b){}}Logger.instance.monitor({event:"login_bsrrr_1b"});setTimeout(A,0,a);return{redirectUrl:"javascript:"}}function K(a){Logger.instance.monitor({event:"login_hsrrr_1a",
...a});400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&(Logger.instance.monitor({event:"login_hsrrr_1b"}),setTimeout(A,0,{code:a.statusCode}));Logger.instance.monitor({event:"login_hsrrr_1c"})}function L(a){Logger.instance.monitor({event:"login_esr_1a",...a});-1==a.tabId&&0<a.frameId&&(Logger.instance.monitor({event:"login_esr_1b"}),Logger.instance.error(a),setTimeout(A,0,null));Logger.instance.monitor({event:"login_esr_1a"})}function M(a){Logger.instance.monitor({event:"login_bssr_1a"});if(a=dji.utils.jsonFromUrlQueryAndHash(a.url))a=
a.query;if(a&&a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}Logger.instance.monitor({event:"login_bssr_1b"});setTimeout(B,0,a);return{redirectUrl:"javascript:"}}function N(a){Logger.instance.monitor({event:"login_hsr_1a",...a});400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&(Logger.instance.monitor({event:"login_hsr_1b"}),setTimeout(B,0,{code:a.statusCode}));Logger.instance.monitor({event:"login_hsr_1c"})}function O(a){Logger.instance.monitor({event:"login_ess_1a",...a});-1==a.tabId&&
0<a.frameId&&(Logger.instance.monitor({event:"login_ess_1b"}),Logger.instance.error(a),setTimeout(B,0,null));Logger.instance.monitor({event:"login_ess_1c"})}async function S(a,b,c,d,n){c=c||3;d=d||1E4;n=n||0;Logger.instance.monitor({event:"login_lr_1a",baseUrl:b,retryCount:c,baseTimeout:d,timeoutIncrement:n});const C=(new URL(b)).origin,p=document.createElement("iframe");p.setAttribute("id",a);document.body.appendChild(p);try{for(a=0;a<c;a++){const l=`${chrome.runtime.id}/${Date.now()}/${Math.round(1E5*
Math.random())}`,h=`${Date.now()}/${Math.round(1E5*Math.random())}`,q=`${b}&response_mode=message_post&response_message=${encodeURIComponent(l)}&state=${encodeURIComponent(h)}`,v=d+a*n,z=T(p.contentWindow,C,l,h,v);p.src=q;Logger.instance.monitor({event:"login_lr_2a",url:q,message:l,state:h,timeout:v});try{let m=await z;Logger.instance.monitor({event:"login_lr_3a",url:q,message:l,state:h,timeout:v});return m}catch(m){if(Logger.instance.monitor({event:"login_lr_3b",error:m}),Logger.instance.error(m),
"timeout"!==m.code)throw m;}}Logger.instance.monitor({event:"login_lr_1b",baseUrl:b,retryCount:c,baseTimeout:d,timeoutIncrement:n});let r=Error("All retries have been used!");r.code="no_more_retry";throw r;}finally{p.remove()}}async function T(a,b,c,d,n){return new Promise((C,p)=>{let r=null,l=null,h=null;const q=g=>{if(h){try{h.port1.close()}catch(Z){}h=h.port1.onmessage=null}g||(l&&(clearInterval(l),l=null),r&&(clearTimeout(r),r=null),window.removeEventListener("message",z))},v=()=>{q();let g=Error("Timeout encountered while waiting for response!");
g.code="timeout";p(g)},z=g=>{g.source===a&&g.origin===b&&m(g)},m=g=>{if(g.data instanceof Object&&g.data.message===c&&(void 0===d||g.data.state===d))return q(),C(g.data.data)};window.addEventListener("message",z);l=setInterval(()=>{q(!0);h=new MessageChannel;h.port1.onmessage=m;a.postMessage({message:c,state:d},b,[h.port2])},2E3);n&&(r=setTimeout(v,n))})}var U="https://"+chrome.runtime.id+".chromiumapp.org",V="https://"+chrome.runtime.id+".chromiumapp.org/auth/callback",W="https://"+chrome.runtime.id+
".chromiumapp.org/silent/token/refresh/callback",X="https://"+chrome.runtime.id+".chromiumapp.org/silent/token/refresh/callback?*",Y="https://"+chrome.runtime.id+".chromiumapp.org/silent/signout/callback?*",P=/[?&](auth|lauth|sauth|signout)_stamp=97eb647a233b(&|#|$)/i,f=null,w=null,t=!1,u=null,e=null,x=CWEChromeUtilities.generateUUID,D=CWEChromeUtilities.generateUUID;let y=new EventTarget;k.addEventListener=function(a,b){y.addEventListener(a,b)};k.monitor=function(a){a&&chrome.webRequest.onBeforeRequest.addListener(function(b){if(!(0>
b.tabId)){var c=null;(0==b.url.indexOf("https://")||0==b.url.indexOf("http://"))&&0>b.url.indexOf(U)&&0<b.url.indexOf("_stamp=97eb647a233b")&&(c=new URL(b.url));if(c&&c.search)if(Logger.instance.monitor({event:"login_m_1a"}),b=c.search.match(P))if(b=b[1].toUpperCase(),"AUTH"==b||"LAUTH"==b)Logger.instance.monitor({event:"login_m_1c"}),k.isLoggedIn()||(Logger.instance.monitor({event:"login_m_1d"}),a.authRequired(),Logger.instance.monitor({event:"login_m_1e"}));else{if("SIGNOUT"==b)if(Logger.instance.monitor({event:"login_m_1f"}),
b=c.search.match(P)){c=500;try{Logger.instance.monitor({event:"login_m_1h"}),c=parseInt(b[1]),Logger.instance.monitor({event:"login_m_1i"})}catch(d){Logger.instance.monitor({event:"login_m_1j",error:d}),Logger.instance.error(d)}500!=c&&(Logger.instance.monitor({event:"login_m_1k"}),a.signoutRequired());Logger.instance.monitor({event:"login_m_1l"})}else Logger.instance.monitor({event:"login_m_1g"})}else Logger.instance.monitor({event:"login_m_1b"})}},{urls:["<all_urls>"]})};k.userInfo=function(a){if(a)e=
a;else return e};k.isLoggedIn=function(){return!t&&null!=e&&void 0!=e};k.login=function(a){Logger.instance.monitor({event:"login_l_1a"});if(t)return Logger.instance.monitor({event:"login_l_1b"}),f&&(Logger.instance.monitor({event:"login_l_1c"}),chrome.tabs.update(f.id,{active:!0,highlighted:!0})),Logger.instance.monitor({event:"login_l_1d"}),!1;if(e)try{Logger.instance.monitor({event:"login_l_1e"}),a(e),Logger.instance.monitor({event:"login_l_1f"})}catch(b){Logger.instance.monitor({event:"login_l_1g",
error:b}),Logger.instance.error(b)}else return t=!0,w=a,u=null,Logger.instance.monitor({event:"login_l_1h"}),chrome.webRequest.onBeforeRequest.addListener(I,{urls:[V]}),R(),Logger.instance.monitor({event:"login_l_1i"}),!0};k.silentAuth=async function(a){Logger.instance.monitor({event:"login_sa_1a"});if(document.getElementById(x))return Logger.instance.monitor({event:"login_sa_1b"}),a(null);Logger.instance.monitor({event:"login_sa_1c"});let b=null;try{b=await S(x,window.dji.config.silentAuthUrl(),
5,1E4,5E3),Logger.instance.monitor({event:"login_sa_1d"})}catch(c){return Logger.instance.error(c),Logger.instance.monitor({event:"login_sa_1e",error:c}),a(null)}Logger.instance.monitor({event:"login_sa_2a",status:b?b.error:null,code:b?b.code:null});if(500==b.code)return Logger.instance.monitor({event:"login_sa_2b"}),a(null);0==b.code?(Logger.instance.monitor({event:"login_sa_2c"}),window.jsdapi.setAuth(b),window.jsdapi.account.me(async function(c){Logger.instance.monitor({event:"login_sa_2d",status:c?
c.error:null});if(c)if(c.error)switch(c.error){case 401:b.code=800002}else{e=c;b.user=c;try{let d=await window.jsdapi.cow.getPrivacyModeAsync();G(d.privacyMode)}catch(d){Logger.instance.error(d)}e.analytics&&E(e.analytics);F("th_global_license_check",null,null)}Logger.instance.monitor({event:"login_sa_2e",status:b?b.error:null});a(b);Logger.instance.monitor({event:"login_sa_2f"})})):(Logger.instance.monitor({event:"login_sa_2g"}),a(b),Logger.instance.monitor({event:"login_sa_2h"}))};k.silentSignout=
function(a){Logger.instance.monitor({event:"login_ss_1a"});var b=document.getElementById(x);if(b)return Logger.instance.monitor({event:"login_ss_1b"}),a(null);Logger.instance.monitor({event:"login_ss_1c"});b=document.createElement("iframe");b.setAttribute("id",x);b.__calback=a;b.src=window.dji.config.silentSignoutUrl();chrome.webRequest.onBeforeRequest.addListener(M,{urls:[Y]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(N,{urls:[window.dji.config.silentAuthUrl()]},["blocking"]);
chrome.webRequest.onErrorOccurred.addListener(O,{urls:[window.dji.config.silentSignoutUrl()]});document.body.appendChild(b);Logger.instance.monitor({event:"login_ss_1d"})};k.isPreparing=function(){return t&&!f};k.tabId=function(){return f?f.id:null};k.silentRefreshToken=function(a,b){Logger.instance.monitor({event:"login_srt_1a"});var c=document.getElementById(D);if(c)return Logger.instance.monitor({event:"login_srt_1b"}),b(null);Logger.instance.monitor({event:"login_srt_1c"});a=a.login_url+"/silent/token/refresh?client_id="+
encodeURIComponent(a.client_id)+"&refresh_token="+encodeURIComponent(a.refresh_token)+"&redirect_uri="+encodeURIComponent(W);c=document.createElement("iframe");c.setAttribute("id",D);c.__calback=b;c.src=a;chrome.webRequest.onBeforeRequest.addListener(J,{urls:[X]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(K,{urls:[a]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(L,{urls:[a]});document.body.appendChild(c);Logger.instance.monitor({event:"login_srt_1d"})};var Q=function(){Logger.instance.monitor({event:"login_af_1a"});
chrome.tabs.onRemoved.removeListener(H);chrome.webRequest.onBeforeRequest.removeListener(I);f&&(chrome.tabs.remove(f.id),f=null);var a=dji.utils.jsonFromUrlQueryAndHash(u);if((a=a?a.hash:null)&&a.access_token&&a.expires_at)Logger.instance.monitor({event:"login_af_1f"}),window.jsdapi.setAuth(a),window.jsdapi.account.me(async function(b){Logger.instance.monitor({event:"login_af_1g",status:b?b.error:null});if(b&&!b.error){e=b;try{let c=await window.jsdapi.cow.getPrivacyModeAsync();G(c.privacyMode)}catch(c){Logger.instance.error(c)}e.analytics&&
E(e.analytics);F("th_global_license_check",null,null,!0);try{Logger.instance.monitor({event:"login_af_1h"}),w(e),Logger.instance.monitor({event:"login_af_1i"})}catch(c){Logger.instance.monitor({event:"login_af_1j",error:c}),Logger.instance.error(c)}w=u=null;t=!1}}),Logger.instance.monitor({event:"login_af_1k"});else{try{Logger.instance.monitor({event:"login_af_1b"}),w(e),Logger.instance.monitor({event:"login_af_1c"})}catch(b){Logger.instance.monitor({event:"login_af_1d"}),Logger.instance.error(b)}w=
u=null;t=!1;Logger.instance.monitor({event:"login_af_1e"})}},A=function(a){chrome.webRequest.onBeforeRequest.removeListener(J);chrome.webRequest.onHeadersReceived.removeListener(K);chrome.webRequest.onErrorOccurred.removeListener(L);var b=document.getElementById(D);if(!b)return dji.log.error("Invalid state for silent refresh.");var c=b.__calback;document.body.removeChild(b);c(a)},B=function(a){Logger.instance.monitor({event:"login_ssf_1a"});chrome.webRequest.onBeforeRequest.removeListener(M);chrome.webRequest.onHeadersReceived.removeListener(N);
chrome.webRequest.onErrorOccurred.removeListener(O);var b=document.getElementById(x);if(!b)return Logger.instance.monitor({event:"login_ssf_1b"}),dji.log.error("Invalid state for silent signout.");var c=b.__calback;document.body.removeChild(b);if(!a||500==a.code)return Logger.instance.monitor({event:"login_ssf_1c"}),c(!1);e=null;try{Logger.instance.monitor({event:"login_ssf_1d"}),c(!0),Logger.instance.monitor({event:"login_ssf_1e"})}catch(d){Logger.instance.monitor({event:"login_ssf_1f"}),Logger.instance.error(d)}}})(window.cwe.login=
window.cwe.login||{});
