function CWEPredictionEngineInstance(){return CWEPredictionEngine.instance}
function CWEPredictionEngine(a){this.m_nacl="WebAssembly";this.m_spellcheckerWorker=new DjiSpellCheckerWorkerProxy({url:"cweSpellCheckerWorker.js",appDir:`/${this.m_nacl}`});this.m_predictionWorker=new DjiPredictionWorkerProxy({url:"cwePredictionWorker.js",appDir:`/${this.m_nacl}`});this.m_bundleResources={prediction:null,hunspell:null};this.m_customResources={useSensitiveWords:!1,sensitiveWordsDir:"/common/sensitive-words",useSpecialPredictions:!1,specialPredictionsDir:"/common/special-predictions"};
this.m_spellcheckLanguage=this.m_predictionLocale=null;this.m_spellcheckBundledLanguages=[];this.m_spellcheckBundledLanguagesMap={};this.m_sensitiveWordsMap={};this.m_listeners=[a];this.m_optionsListeners=[];this.m_allTopics=[];this.m_recentTopics=[];this.m_activeTopics=[];this.m_initialized=this.m_loaded=!1;this.m_state={action:null,details:{},userData:null};this.m_eventTarget=new EventTarget;Object.defineProperty(this,"state",{value:this.m_state,writable:!1});Object.defineProperty(this,"maxActiveTopics",
{value:6,writable:!1});this.m_predictionWorker.onFollowTextChange(this.onFollowTextChange.bind(this));return this}CWEPredictionEngine.instance=null;
CWEPredictionEngine.load=async function(a){Logger.instance.log("Loading Prediction module! Please wait...");if(null==CWEPredictionEngine.instance)try{Logger.instance.monitor({event:"pe_will_load"}),CWEPredictionEngine.instance=new CWEPredictionEngine(a),await CWEPredictionEngine.instance.__load()}catch(b){CWEPredictionEngine.instance=null,Logger.instance.error("Prediction Engine - cannot create instance!"),Logger.instance.error(b)}};
CWEPredictionEngine.isLoaded=function(){return CWEPredictionEngine.instance&&CWEPredictionEngine.instance.m_loaded};CWEPredictionEngine.isInitialized=function(){return CWEPredictionEngine.isLoaded()&&CWEPredictionEngine.instance.m_initialized};
CWEPredictionEngine.prototype.__load=async function(){Logger.instance.monitor({event:"pe_load_step_1a"});await this.__prepareBundleResources();Logger.instance.monitor({event:"pe_load_step_1b"});await this.__loadSpellcheckerLanguages();Logger.instance.monitor({event:"pe_load_step_1c"});await this.__loadSensitiveWords();Logger.instance.monitor({event:"pe_load_step_1d"});this.m_loaded=!0};
CWEPredictionEngine.prototype.__prepareBundleResources=async function(){try{Logger.instance.monitor({event:"pe_load_step_2a"}),await CWEBackgroundManager.instance.fileSystem().removeDirectoryAsync("/bundle"),Logger.instance.monitor({event:"pe_load_step_2b"})}catch(a){Logger.instance.monitor({event:"pe_load_step_2c",error:a})}try{Logger.instance.monitor({event:"pe_load_step_2d"});const a=await DjiFileSystemDirectoryEntryProxy.getPackageDirectoryEntryAsync();Logger.instance.monitor({event:"pe_load_step_2e"});
const b=await a.fileAsync(`${this.m_nacl}/resources/prediction.pvfs`);Logger.instance.monitor({event:"pe_load_step_2f"});const c=await a.fileAsync(`${this.m_nacl}/resources/hunspell.pvfs`);this.m_bundleResources.prediction=b;this.m_bundleResources.hunspell=c;Logger.instance.monitor({event:"pe_load_step_2g"})}catch(a){throw Logger.instance.monitor({event:"pe_load_step_2h"}),Logger.instance.error(a),a;}};
CWEPredictionEngine.prototype.__loadSpellcheckerLanguages=async function(){try{Logger.instance.monitor({event:"pe_load_step_3a"});var a=await VfsContainer.fromContainerAsync(this.m_bundleResources.hunspell);Logger.instance.monitor({event:"pe_load_step_3b"});const b=await a.readFileAsJSONAsync("manifest.json.txt");Logger.instance.monitor({event:"pe_load_step_3c"});if(b&&b.hasOwnProperty("languages")&&b.languages)for(this.m_spellcheckBundledLanguages=b.languages,a=0;a<b.languages.length;a++)this.m_spellcheckBundledLanguagesMap[b.languages[a].language_code]=
b.languages[a];Logger.instance.monitor({event:"pe_load_step_3d"})}catch(b){Logger.instance.monitor({event:"pe_load_step_3e",error:b}),Logger.instance.error(b)}};
CWEPredictionEngine.prototype.__loadSensitiveWords=async function(a){try{Logger.instance.monitor({event:"pe_load_step_4a"});let c=!1,d={};var b=await VfsContainer.fromContainerAsync(this.m_bundleResources.prediction);Logger.instance.monitor({event:"pe_load_step_4b"});const e=b.getDirectoryFiles("SensitiveWords");Logger.instance.monitor({event:"pe_load_step_4c"});for(let f of e){const g=await b.readFileAsTextAsync(f);if(g){let h=f.split(/[\/]/).pop();d[h]=g}}if(a)try{Logger.instance.monitor({event:"pe_load_step_4d"});
const f=CWEBackgroundManager.instance.fileSystem(),g=await f.directoryExistsAsync(this.m_customResources.sensitiveWordsDir);Logger.instance.monitor({event:"pe_load_step_4e",hasCustom:g});if(g){const h=await f.readFileAsJSONAsync(`${this.m_customResources.sensitiveWordsDir}/manifest.json`);if(h&&h.files){for(let k of h.files)try{Logger.instance.monitor({event:"pe_load_step_4f",file:`${this.m_customResources.sensitiveWordsDir}/${k}`});const l=await f.readFileAsTextAsync(`${this.m_customResources.sensitiveWordsDir}/${k}`);
d[k]=l}catch(l){Logger.instance.monitor({event:"pe_load_step_4g",file:`${this.m_customResources.sensitiveWordsDir}/${k}`,error:l}),Logger.instance.error(l)}c=!0}}}catch(f){Logger.instance.monitor({event:"pe_load_step_4h",error:f}),Logger.instance.error(f)}a={};b=/\s+/;d=Object.values(d);for(let f of d){let g=f.split(b);for(let h of g){let k=h.trim().toUpperCase();0<k.length&&(a[k]=!0)}}this.m_sensitiveWordsMap=a;this.m_customResources.useSensitiveWords=c;Logger.instance.monitor({event:"pe_load_step_4i"})}catch(c){Logger.instance.monitor({event:"pe_load_step_4j",
error:c}),Logger.instance.error(c)}};CWEPredictionEngine.prototype.addEventListener=function(a,b){this.m_eventTarget.addEventListener(a,b)};CWEPredictionEngine.prototype.addListener=function(a){let b=this.m_listeners.indexOf(a);Logger.instance.log("-------------------------------- CWEPredictionEngine.addListener: "+b);-1===b&&this.m_listeners.push(a);Logger.instance.log(this.m_listeners)};
CWEPredictionEngine.prototype.removeListener=function(a){a=this.m_listeners.indexOf(a);Logger.instance.log("-------------------------------- CWEPredictionEngine.removeListener: "+a);-1!==a&&this.m_listeners.splice(a,1);Logger.instance.log(this.m_listeners)};CWEPredictionEngine.prototype.addOptionsListener=function(a){let b=this.m_optionsListeners.indexOf(a);Logger.instance.log("-------------------------------- CWEPredictionEngine.addOptionsListener: "+b);-1===b&&this.m_optionsListeners.push(a);Logger.instance.log(this.m_optionsListeners)};
CWEPredictionEngine.prototype.removeOptionsListener=function(a){a=this.m_optionsListeners.indexOf(a);Logger.instance.log("-------------------------------- CWEPredictionEngine.removeOptionsListener: "+a);-1!==a&&this.m_optionsListeners.splice(a,1);Logger.instance.log(this.m_optionsListeners)};CWEPredictionEngine.prototype.onCrash=function(){this.m_eventTarget.dispatchEvent(new CustomEvent("crash"))};
CWEPredictionEngine.prototype.initializeAsync=async function(a,b,c){if(!this.m_initialized)try{const d=this.m_customResources.useSensitiveWords,e=this.m_customResources.useSpecialPredictions;await this.__initializePredictionAsync(a,c);try{this.m_spellcheckLanguage=b,await this.__initializeSpellcheckerAsync([this.m_spellcheckLanguage])}catch(f){dji.logger.error(f)}this.m_initialized=!0;d!==this.m_customResources.useSensitiveWords&&await this.m_predictionWorker.reloadSensitiveWordsAsync(this.m_customResources.useSensitiveWords?
this.m_customResources.sensitiveWordsDir:null);e!==this.m_customResources.useSpecialPredictions&&await this.m_predictionWorker.reloadSensitiveWordsAsync(this.m_customResources.useSensitiveWords?this.m_customResources.sensitiveWordsDir:null)}catch(d){dji.logger.error(d)}return this.m_initialized};
CWEPredictionEngine.prototype.__initializePredictionAsync=async function(a,b){try{this.m_predictionLocale=window.cwe.locale.localeLang(!0,a);let c="";switch(a.toUpperCase()){case "BE":case "UK":case "FR":case "SPA":case "GER":c="/common/dictionaries"}let d={locale:a,resourceDirectory:"/bundle/resources/prediction",commonDirectory:c,userDirectory:`/Users/${b}`,resourceContainer:this.m_bundleResources.prediction};this.m_customResources.useSensitiveWords&&(d.sensitiveWordsDirectory=this.m_customResources.sensitiveWordsDir);
this.m_customResources.useSpecialPredictions&&(d.specialPredictionsDirectory=this.m_customResources.specialPredictionsDir);await this.m_predictionWorker.initAsync(d,!0);this.rebuildTopicsCache(!0)}catch(c){throw Logger.instance.error(c),this.m_predictionWorker.terminate(),c;}};
CWEPredictionEngine.prototype.__initializeSpellcheckerAsync=async function(a){if(!window.dji.utils.isNullOrUndefined(a)&&0!==a.length){var b=[];for(let c of a){if(window.dji.utils.isNullOrUndefined(c)||0===c.length)continue;let d="",e="",f=null;this.spellcheckerHasBundledResource(c)?(f=this.m_bundleResources.hunspell,e="/bundle/resources/hunspell"):d="/common/hunspell";b.push({locale:c,commonDirectory:d,resourceDirectory:e,resourceContainer:f})}0!==b.length&&(this.m_spellcheckerWorker.initAsync(b,
!0)||dji.logger.warn("[__initializeSpellcheckerAsync]. Failed to initialize spellchecker for locales ",a))}};CWEPredictionEngine.prototype.syncAsync=async function(){return this.m_predictionWorker.syncAsync()};CWEPredictionEngine.prototype.reset=function(){this.m_predictionWorker.terminate();this.m_spellcheckerWorker.terminate();this.m_spellcheckLanguage=this.m_predictionLocale=null;this.m_allTopics=[];this.m_recentTopics=[];this.m_activeTopics=[];this.m_initialized=!1};
CWEPredictionEngine.prototype.supportsUnicode=function(){return!0};
CWEPredictionEngine.prototype.updateFromUserSettingsAsync=async function(a){if(this.m_initialized)try{let b=CWESettings.instance.features(),c={mainDictionary:CWESettings.instance.predictionMainDictionary(),enableMomentaryTopic:CWESettings.instance.predictionMomentaryTopic(),enableFlexibleSpelling:CWESettings.instance.predictionFlexibleSpelling(),enableGrammar:CWESettings.instance.predictionGrammar(),enablePredictAhead:CWESettings.instance.predictionAhead(),enableAutoCapitalization:!b||b.allowAutoCapitalization?
1:0,maxPredictedGuesses:CWESettings.instance.predictionGuesses(),activeTopics:CWESettings.instance.topicsActive()};await this.m_predictionWorker.setOptionsAsync(c);await this.rebuildTopicsCache()}catch(b){if(Logger.instance.error(b),this.reset(),a)this.onCrash()}return this.m_initialized};CWEPredictionEngine.prototype.hasCustomSensitiveWords=function(){return this.m_customResources.useSensitiveWords};CWEPredictionEngine.prototype.hasCustomSpecialPredictions=function(){return this.m_customResources.useSpecialPredictions};
CWEPredictionEngine.prototype.reloadSensitiveWordsAsync=async function(){await this.__loadSensitiveWords(!0);this.m_initialized&&await this.m_predictionWorker.reloadSensitiveWordsAsync(this.m_customResources.useSensitiveWords?this.m_customResources.sensitiveWordsDir:null)};
CWEPredictionEngine.prototype.reloadSpecialPredictionsAsync=async function(){const a=CWEBackgroundManager.instance.fileSystem();this.m_customResources.useSpecialPredictions=await a.directoryExistsAsync(this.m_customResources.specialPredictionsDir);this.m_initialized&&await this.m_predictionWorker.reloadSpecialPredictionsAsync(this.m_customResources.useSpecialPredictions?this.m_customResources.specialPredictionsDir:null)};
CWEPredictionEngine.prototype.rebuildTopicsCache=async function(a){if(this.m_initialized||a){let b=await this.m_predictionWorker.getTopicsStateAsync();this.handleGetTopicsStateResult(!0,!0,b,a)}};CWEPredictionEngine.prototype.cacheTopics=async function(){this.m_initialized&&await this.m_predictionWorker.syncUserDirectoryAsync()};CWEPredictionEngine.prototype.reloadDictionaries=async function(a,b){this.m_initialized&&a&&!b&&(await this.m_predictionWorker.reloadDictionariesAsync(a,b),CWEBackgroundManager.instance.requestMomentaryTopicContext())};
CWEPredictionEngine.prototype.followTextChange=function(a,b,c,d,e){this.m_initialized&&this.m_predictionWorker.followTextChange(a,d,b,c,e)};CWEPredictionEngine.prototype.onFollowTextChange=function(a){this.m_initialized&&a.detail&&this.__notifyListeners("guessesAvailable",a.detail)};CWEPredictionEngine.prototype.acceptGuess=async function(a){this.m_initialized&&(a=await this.m_predictionWorker.acceptGuessAsync(a),this.__notifyListeners("replaceText",a.rangeStart,a.rangeStart+a.rangeLength,a.replacement))};
CWEPredictionEngine.prototype.restartGuesses=async function(){if(this.m_initialized)return this.m_predictionWorker.restartGuessesAsync()};CWEPredictionEngine.prototype.resetState=async function(){if(this.m_initialized)return this.m_predictionWorker.resetStateAsync()};CWEPredictionEngine.prototype.setMainDictionary=async function(a){this.m_initialized&&await this.m_predictionWorker.setMainDictionaryAsync(a)};
CWEPredictionEngine.prototype.setMaxPredictedGuesses=async function(a){this.m_initialized&&await this.m_predictionWorker.setMaxPredictedGuessesAsync(a)};CWEPredictionEngine.prototype.enableMomentaryTopic=async function(a){this.m_initialized&&await this.m_predictionWorker.enableMomentaryTopicAsync(a)};
CWEPredictionEngine.prototype.updateMomentaryTopic=async function(a){if(this.m_initialized){a=(a||"").replace(/(\n)+/g,"\r").replace(/(\r)+/g,"\r").replace(/( )+/g," ").replace(/( \r)+/g,"\r");let b=Math.min(a.length,3E4),c=Math.min(a.length,b+20);for(;b<c&&!dji.charSet.wordSeparator.characterIsMember(a.charAt(b));b++);b<a.length&&(a=a.substr(0,b));await this.m_predictionWorker.updateMomentaryTopicAsync(a)}};
CWEPredictionEngine.prototype.getTopics=async function(a){!a&&this.m_initialized&&(this.m_allTopics=(await this.m_predictionWorker.getTopicsAsync()).topics);this.__notifyOptionsListeners("topicsAvailable",this.m_allTopics.slice())};CWEPredictionEngine.prototype.getTopicsAsync=async function(){if(this.m_initialized){let a=await this.m_predictionWorker.getTopicsAsync();this.m_allTopics=a.topics;this.__notifyOptionsListeners("topicsAvailable",this.m_allTopics.slice());return{topics:a.topics}}};
CWEPredictionEngine.prototype.getActiveTopics=async function(a){!a&&this.m_initialized&&(this.m_activeTopics=(await this.m_predictionWorker.getActiveTopicsAsync()).activeTopics);this.__notifyOptionsListeners("activeTopicsAvailable",this.m_activeTopics.slice())};
CWEPredictionEngine.prototype.activateTopic=async function(a){if(this.m_initialized){let b=null;try{b=await this.m_predictionWorker.activateTopicAsync(a)}catch(c){throw Logger.instance.error(c),this.reset(),this.onCrash(),c;}this.handleGetTopicsStateResult(!1,!1,b);CWEBackgroundManager.instance.sendGA4Event("TopicStatusChanged",{topic_name:a,topic_status:!0},null);CWEBackgroundManager.instance.onTopicActivated(a);this.__notifyOptionsListeners("topicActivated",a)}};
CWEPredictionEngine.prototype.activateTopicAsync=async function(a){if(this.m_initialized){let b=null;try{b=await this.m_predictionWorker.activateTopicAsync(a)}catch(c){throw Logger.instance.error(c),this.reset(),this.onCrash(),c;}this.handleGetTopicsStateResult(!1,!1,b);CWEBackgroundManager.instance.onTopicActivated(a);this.__notifyOptionsListeners("topicActivated",a);return{topic:a}}};
CWEPredictionEngine.prototype.deactivateTopic=async function(a){if(this.m_initialized){let b=await this.m_predictionWorker.deactivateTopicAsync(a);this.handleGetTopicsStateResult(!1,!1,b);CWEBackgroundManager.instance.onTopicDeactivated(a);this.__notifyOptionsListeners("topicDeactivated",a)}};
CWEPredictionEngine.prototype.deactivateTopicAsync=async function(a){if(this.m_initialized){let b=await this.m_predictionWorker.deactivateTopicAsync(a);this.handleGetTopicsStateResult(!1,!1,b);CWEBackgroundManager.instance.onTopicDeactivated(a);this.__notifyOptionsListeners("topicDeactivated",a);return{topic:a}}};
CWEPredictionEngine.prototype.createWikiTopicAsync=async function(a,b,c,d){if(this.m_initialized){c&&(c=this.canActivateTopic(a));let e=null;this.__changeState("create_topic",{name:a},d);try{e=await this.m_predictionWorker.createWikiTopicAsync(a,b,c)}catch(f){throw Logger.instance.error(f),this.reset(),this.onCrash(),f;}this.handleGetTopicsStateResult(!0,!1,e.topicsState);this.__changeState();this.handleFilesUpdateInfo(e.filesUpdateInfo);CWEBackgroundManager.instance.onTopicCreated(e.topic,this.m_activeTopics.slice());
this.__notifyOptionsListeners("topicCreated",e.topic,this.m_activeTopics.slice());return{topic:e.topic}}};CWEPredictionEngine.prototype.addPersonalWords=async function(a){this.m_initialized&&(a=await this.m_predictionWorker.addPersonalWordsAsync(a),this.handleFilesUpdateInfo(a.filesUpdateInfo))};CWEPredictionEngine.prototype.removePersonalWords=async function(a){this.m_initialized&&(a=await this.m_predictionWorker.removePersonalWordsAsync(a),this.handleFilesUpdateInfo(a.filesUpdateInfo))};
CWEPredictionEngine.prototype.enableFlexibleSpelling=async function(a){this.m_initialized&&await this.m_predictionWorker.enableFlexibleSpellingAsync(a)};CWEPredictionEngine.prototype.enableGrammar=async function(a){this.m_initialized&&await this.m_predictionWorker.enableGrammarAsync(a)};CWEPredictionEngine.prototype.enablePredictAhead=async function(a){this.m_initialized&&await this.m_predictionWorker.enablePredictAheadAsync(a)};CWEPredictionEngine.prototype.recentTopics=function(){return this.m_recentTopics};
CWEPredictionEngine.prototype.activeTopics=function(){return this.m_activeTopics};CWEPredictionEngine.prototype.allTopics=function(){return this.m_allTopics};
CWEPredictionEngine.prototype.topicNameToDisplayName=function(a){if(null===a||void 0===a)return null;a=a.replace("_"," ");CWEChromeUtilities.stringEndsWith(a," TD")&&(a=a.slice(0,a.length-3));let b="";for(let c=0;c<a.length;c++){let d=a.charAt(c);b+=a.charAt(c);if(c<a.length-1){let e=a.charAt(c+1);d.toLowerCase()!=d.toUpperCase()&&e.toLowerCase()!=e.toUpperCase()&&d==d.toLowerCase()&&e==e.toUpperCase()&&(b+=" ")}}return b};CWEPredictionEngine.prototype.sensitiveWords=function(){return this.m_sensitiveWordsMap};
CWEPredictionEngine.prototype.spellcheckerBundledLanguages=function(){return this.m_spellcheckBundledLanguages};CWEPredictionEngine.prototype.spellcheckerHasBundledResource=function(a){return!(!a||!this.m_spellcheckBundledLanguagesMap.hasOwnProperty(a))};CWEPredictionEngine.prototype.changeSpellcheckerLocale=async function(a){this.m_spellcheckLanguage=a;if(this.m_initialized)return this.m_spellcheckerWorker.terminate(),this.__initializeSpellcheckerAsync([this.m_spellcheckLanguage])};
CWEPredictionEngine.prototype.spellcheck=async function(a,b){return this.m_spellcheckerWorker.spellCheck(a,b?[this.m_spellcheckLanguage,this.m_predictionLocale]:[this.m_spellcheckLanguage])};CWEPredictionEngine.prototype.spellcheckerIsRunning=function(){return this.m_spellcheckerWorker.isRunning()};CWEPredictionEngine.prototype.topicIsActive=function(a){const b=this.m_activeTopics;a=this.topicNameToDisplayName(a);for(let c=0;c<b.length;c++)if(b[c]===a)return!0;return!1};
CWEPredictionEngine.prototype.canActivateTopic=function(a){return this.m_activeTopics.length<this.maxActiveTopics||this.topicIsActive(a)};CWEPredictionEngine.prototype.__topicIndex=function(a){for(let b=0;b<this.m_allTopics.length;b++)if(this.m_allTopics[b]===a)return b;return-1};CWEPredictionEngine.prototype.__activeTopicIndex=function(a){for(let b=0;b<this.m_activeTopics.length;b++)if(this.m_activeTopics[b]===a)return b;return-1};
CWEPredictionEngine.prototype.handleGetTopicsStateResult=function(a,b,c,d){(this.m_initialized||d)&&c&&(a&&(this.m_allTopics=c.allTopics),this.m_activeTopics=c.activeTopics,this.m_recentTopics=c.recentTopics,b&&(a&&this.__notifyOptionsListeners("topicsAvailable",this.m_allTopics.slice()),this.__notifyOptionsListeners("recentTopicsAvailable",this.m_recentTopics.slice()),this.__notifyOptionsListeners("activeTopicsAvailable",this.m_activeTopics.slice())))};
CWEPredictionEngine.prototype.handleFilesUpdateInfo=function(a){CWEBackgroundManager.instance.onFilesChanged(a.files)};CWEPredictionEngine.prototype.__notifyListeners=function(a){let b=[].slice.call(arguments).splice(1),c=this.m_listeners.length;for(let d=0;d<c;d++)try{let e=this.m_listeners[d];a in e&&e[a].apply(e,b)}catch(e){Logger.instance.log(e)}};
CWEPredictionEngine.prototype.__notifyOptionsListeners=function(a,b){b=[].slice.call(arguments).splice(1);let c=this.m_optionsListeners.length;for(let d=0;d<c;d++)try{let e=this.m_optionsListeners[d];a in e&&(e[a].apply(e,b),this.m_optionsListeners.length<c&&(d--,c--))}catch(e){this.m_optionsListeners.splice(d,1),d--,c--,Logger.instance.log(e)}};
CWEPredictionEngine.prototype.__changeState=function(a,b,c){this.m_state.action=a||null;this.m_state.details=this.m_state.action?b:null;this.m_state.userData=this.m_state.action?c:null};
