const GoogleAnalyticsEvents={th_global_license_check:{eventName:"th_global_license_check",params:{category:"Application",feature:"NA",website:location.hostname}},ApplicationStarted:{eventName:"ApplicationStarted",params:{category:"Application",feature:"NA",website:location.hostname}},ApplicationStopped:{eventName:"ApplicationStopped",params:{category:"Application",feature:"NA",website:location.hostname}},PredictionTabOpened:{eventName:"PredictionTabOpened",params:{category:"Feature",feature:"Prediction",
website:location.hostname}},WordSuggestionSelected:{eventName:"WordSuggestionSelected",params:{category:"Feature",feature:"Prediction",website:location.hostname},customProperties:{number_value:null}},WordSuggestionByNumberSelected:{eventName:"WordSuggestionByNumberSelected",params:{category:"Feature",feature:"Prediction",website:location.hostname},customProperties:{number_value:null}},ReadTabOpened:{eventName:"ReadTabOpened",params:{category:"Feature",feature:"Speech",website:location.hostname}},
PlaySelected:{eventName:"PlaySelected",params:{category:"Feature",feature:"Speech",website:location.hostname}},PauseSelected:{eventName:"PauseSelected",params:{category:"Feature",feature:"Speech",website:location.hostname}},TextToSpeechTriggered:{eventName:"TextToSpeechTriggered",params:{category:"Feature",feature:"Speech",website:location.hostname},customParameters:{words_read:null,letters_read:null,voice_used:null}},PreviousTenWordsSelected:{eventName:"PreviousTenWordsSelected",params:{category:"Feature",
feature:"Speech",website:location.hostname}},SpeedChanged:{eventName:"SpeedChanged",params:{category:"Feature",feature:"Speech",website:location.hostname},customProperties:{speed_set:null}},SpeechToTextTabOpened:{eventName:"SpeechToTextTabOpened",params:{category:"Feature",feature:"Speech Input",website:location.hostname}},SpeechToTextStarted:{eventName:"SpeechToTextStarted",params:{category:"Feature",feature:"Speech Input",website:location.hostname}},SpeechToTextEnded:{eventName:"SpeechToTextEnded",
params:{category:"Feature",feature:"Speech Input",website:location.hostname},customProperties:{number_of_words_spoken:null}},TopicTabOpened:{eventName:"TopicTabOpened",params:{category:"Feature",feature:"Topics",website:location.hostname}},TopicSearchEngaged:{eventName:"TopicSearchEngaged",params:{category:"Feature",feature:"Topics",website:location.hostname},customProperties:{topic_name:null}},TopicStatusChanged:{eventName:"TopicStatusChanged",params:{category:"Feature",feature:"Topics",website:location.hostname},
customProperties:{topic_name:null,topic_status:null}},TopicFromPageCreated:{eventName:"TopicFromPageCreated",params:{category:"Feature",feature:"Topics",website:location.hostname}},TopicFromTextCreated:{eventName:"TopicFromTextCreated",params:{category:"Feature",feature:"Topics",website:location.hostname}},OptionsOpened:{eventName:"OptionsOpened",params:{category:"Settings",feature:"NA",website:location.hostname}},SignedOut:{eventName:"SignedOut",params:{category:"Application",feature:"NA",website:location.hostname}},
ProfileOpened:{eventName:"ProfileOpened",params:{category:"Settings",feature:"NA",website:location.hostname}},SwitchToNumericSelected:{eventName:"SwitchToNumericSelected",params:{category:"Feature",feature:"Prediction",website:location.hostname}},SwitchToAlphabetSelected:{eventName:"SwitchToAlphabetSelected",params:{category:"Feature",feature:"Prediction",website:location.hostname}},ViewReportsOpened:{eventName:"ViewReportsOpened",params:{category:"Feature",feature:"Reports",website:location.hostname}},
ManageStudentsOpened:{eventName:"ManageStudentsOpened",params:{category:"Settings",feature:"NA",website:location.hostname}},ManageEducatorsOpened:{eventName:"ManageEducatorsOpened",params:{category:"Settings",feature:"NA",website:location.hostname}},TranslateWritingOn:{eventName:"TranslateWritingOn",params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{language:null}},AsNeededOn:{eventName:"AsNeededOn",params:{category:"Settings",feature:"NA",website:location.hostname},
customProperties:{setting:null}},WordTranslationSelected:{eventName:"WordTranslationSelected",params:{category:"Feature",feature:"Translation",website:location.hostname}},NumberOfGuessChanged:{eventName:"NumberOfGuessChanged",params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{new_value:null}},FontChanged:{eventName:"FontChanged",params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{new_value:null}},FontSizeChanged:{eventName:"FontSizeChanged",
params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{new_value:null}},TextColourChanged:{eventName:"TextColourChanged",params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{new_value:null}},BackgroundColourChanged:{eventName:"BackgroundColourChanged",params:{category:"Settings",feature:"NA",website:location.hostname},customProperties:{new_value:null}}};window.dji=window.dji||{};window.dji.cwe=window.dji.cwe||{};
window.dji.cwe.ga4=window.dji.cwe.ga4||{};window.dji.cwe.ga4.events=GoogleAnalyticsEvents;
