function CWETextOptions(a,c){this.m_cweSettings=a;this.m_cweBackgroundManager=c;this.m_fonts="Arial;Courier New;Georgia;Helvetica;Times New Roman;Verdana;OpenDyslexic".split(";");this.m_guesses=$("#dji-cwu-number-of-guesses");this.m_font=$("#dji-cwu-text-font");this.m_color=$("#dji-cwu-text-color");this.m_background=$("#dji-cwu-text-background-color");this.m_size=$("#dji-cwu-text-size");this.m_imeSample=$("#dji-cwu-ime-sample");this.m_imeSampleHideTimer=null;this.__initialize();return this}
CWETextOptions.instance=null;
CWETextOptions.prototype.__initialize=function(){let a=this,c=$("div[dji-cwu-template-id=dji-cwu-font-family]");this.m_guesses.on("change",function(b){if(b.value!=a.m_cweSettings.predictionGuesses()){a.m_cweBackgroundManager.sendGA4Event("NumberOfGuessChanged",{new_value:b.value},null);let d=$("[dji-cwu-template-id=dji-cwu-number-of-guesses]");d.find("[dji-check]").removeAttr("dji-check");d.find("[dji-cwu-value='"+b.value+"']").attr("dji-check","");b.noSave||a.m_cweSettings.predictionGuesses(parseInt(b.value))}});this.m_font.on("change",
function(b){a.m_cweBackgroundManager.sendGA4Event("FontChanged",{new_value:a.m_fonts[b.value]},null);c.find("[dji-check]").removeAttr("dji-check");c.find("[dji-cwu-value='"+b.value+"']").attr("dji-check","");b.noSave||a.m_cweSettings.guessWindowFontFamily(a.m_fonts[b.value]);a.__updateSample(!0)});this.m_color.on("change",function(b){a.m_cweBackgroundManager.sendGA4Event("TextColourChanged",{new_value:b.color},null);a.m_color.css({"background-color":b.color});b.noSave||a.m_cweSettings.guessWindowColor(b.color);
a.__updateSample(!0)});this.m_background.on("change",function(b){a.m_cweBackgroundManager.sendGA4Event("BackgroundColourChanged",{new_value:b.color},null);a.m_background.css({"background-color":b.color});b.noSave||a.m_cweSettings.guessWindowBackgroundColor(b.color);a.__updateSample(!0)});$("body").on("dji-cwu-change-colors",function(b){a.m_color.css({"background-color":b.color});a.m_background.css({"background-color":b.backgroundColor});b.noSave||(a.m_cweSettings.guessWindowColor(b.color),a.m_cweSettings.guessWindowBackgroundColor(b.backgroundColor));
a.__updateSample(!0)});this.m_size.on("input change",function(b){let d=parseInt($(b.currentTarget).val());d+="%";$(b.currentTarget).closest(".dji-cwu-option-slider-item").find(".dji-cwu-slider-value").text(d);b.noSave||(a.m_cweBackgroundManager.sendGA4Event("FontSizeChanged",{new_value:parseInt(d)},null),a.m_cweSettings.guessWindowFontSize(parseInt(d)));b.hasOwnProperty("noImeSample")&&!1!==b.noImeSample||a.__updateSample(!0)});this.m_imeSample.on("click",function(b){null!==a.m_imeSampleHideTimer&&
(clearTimeout(a.m_imeSampleHideTimer),a.m_imeSampleHideTimer=null);a.m_imeSample.removeClass("dji-cwu-visible")});this.__load();this.__updateUI()};
CWETextOptions.prototype.__updateUI=function(){if(this.m_cweSettings){var a=this.m_cweSettings.features();a=!!(!a||a.allowSettings&&a.allowChangeSettings);var c={disabled:!a,"dji-not-allowed":!a};this.m_guesses.attr("disabled",!a);this.m_font.attr("disabled",!a);this.m_size.prop(c);this.m_color.attr("disabled",!a);this.m_background.attr("disabled",!a);a?(this.m_size.closest("dji-cwu-option-slider-item").removeClass("dji-cwu-disable"),this.m_color.closest(".dji-cwu-option-color-picker-item").removeClass("dji-cwu-disable"),
this.m_background.closest(".dji-cwu-option-color-picker-item").removeClass("dji-cwu-disable")):(this.m_size.closest(".dji-cwu-option-slider-item").addClass("dji-cwu-disable"),this.m_color.closest(".dji-cwu-option-color-picker-item").addClass("dji-cwu-disable"),this.m_background.closest(".dji-cwu-option-color-picker-item").addClass("dji-cwu-disable"))}};
CWETextOptions.prototype.__load=function(){if(this.m_cweSettings){this.m_guesses.find(".dji-cwu-option-item-value").text(this.m_cweSettings.predictionGuesses());$("[dji-cwu-template-id=dji-cwu-number-of-guesses]").find("[dji-cwu-value='"+this.m_cweSettings.predictionGuesses()+"']").attr("dji-check","");var a=this.m_cweSettings.guessWindowFontFamily(),c="",b=0,d=$("div[dji-cwu-template-id=dji-cwu-font-family]"),h=$("div[dji-cwu-template-id=dji-cwu-font-family-item]");for(let e=0;e<this.m_fonts.length;e++){let g=
dji.utils.escapeHtml(this.m_fonts[e]);a===this.m_fonts[e]&&(c=g,b=e);let f=h.clone();f.find(".dji-cwu-menu-item-text").text(g);f.attr("dji-cwu-value",e);d.append(f)}d.find("[dji-cwu-value='"+b+"']").attr("dji-check","");this.m_font.find(".dji-cwu-option-item-value").text(c);this.m_color.css({"background-color":this.m_cweSettings.guessWindowColor()});this.m_background.css({"background-color":this.m_cweSettings.guessWindowBackgroundColor()});this.m_size.val(this.m_cweSettings.guessWindowFontSize()).trigger({type:"change",
noImeSample:!0,noSave:!0});this.__updateSample(!1)}};
CWETextOptions.prototype.__updateSample=function(a){window.cweMainView.windowOptions={scale:this.m_cweSettings.guessWindowScale(),fontFamily:this.m_cweSettings.guessWindowFontFamily(),textColor:this.m_cweSettings.guessWindowColor(),backgroundColor:this.m_cweSettings.guessWindowBackgroundColor()};if(a){let c=this;this.m_imeSample.addClass("dji-cwu-visible");null!==this.m_imeSampleHideTimer&&clearTimeout(this.m_imeSampleHideTimer);this.m_imeSampleHideTimer=setTimeout(function(){c.m_imeSampleHideTimer=
null;c.m_imeSample.removeClass("dji-cwu-visible")},15E3)}};
