window.dji=window.dji||{};
(function(l){function V(a){let b=function(){dji.logger.monitor({event:"tts_gv_step_3a",os:p.name});let c=window.speechSynthesis.getVoices();dji.logger.monitor({event:"tts_gv_step_3b",os:p.name,vl:c?c.length:null});if(p.chrome||c&&0<c.length)return dji.logger.monitor({event:"tts_gv_step_3c",os:p.name,vl:c?c.length:null}),a(c);setTimeout(b,500)};b()}function N(a,b){dji.logger.monitor({event:"tts_dv_step_2a",tryCount:a,os:p.name});V(function(c){dji.logger.log("try to detect voices: ",a);dji.logger.monitor({event:"tts_dv_step_2b",
vl:c?c.length:null});if(p.chrome&&(null===c||0>=c.length))dji.logger.monitor({event:"tts_dv_step_2c"}),setTimeout(function(){function d(h){dji.logger.monitor({event:"tts_dv_step_2e",reason:h.type});f||(f=!0,clearTimeout(g),"timeout"===h.type&&window.speechSynthesis.cancel(),"timeout"!==h.type&&"end"!==h.type&&"error"!==h.type||setTimeout(N,"end"===h.type||"timeout"===h.type?10:1E4,a+1,b))}let f=!1,g=null,e=new SpeechSynthesisUtterance(" ");e.onerror=d;e.onend=d;g=setTimeout(d,1E4,{type:"timeout"});
window.speechSynthesis.speak(e);dji.logger.monitor({event:"tts_dv_step_2d"})},10);else{dji.logger.monitor({event:"tts_dv_step_2m"});const d=/Heather|Ryan|Graham|Lucy|SOLO|Flite|Acapela|Google/i;let f=[];for(let g=0;g<c.length;g++){let e=c[g];null===e.name||0===e.name.length||d.test(e.name)?dji.logger.warning("TTS voice excluded:",e.name,e):f.push(e)}t=W(f,!1);dji.logger.monitor({event:"tts_dv_step_2n"});l.cacheOnlineVoices(function(){dji.logger.monitor({event:"tts_dv_step_2o"});for(let e=0;e<t.length;e++){let h=
t[e],k=h.extras;var g=A[k.lang]=A[k.lang]||{};g=g[k.culture]=g[k.culture]||{};(g[k.gender]=g[k.gender]||[]).push(h)}X();dji.logger.monitor({event:"tts_dv_step_2p"});setTimeout(function(){dji.logger.groupEnd();G(b,!0)},0)})}})}function O(){q.voice=l.defaultVoice();q.translationVoice=null;q.rate=q.pitch=q.volume=1}function y(a){for(let b=0;b<t.length;b++)if(t[b].voiceName===a)return t[b];return null}function L(a){a=y(a);return!!a}function W(a,b){let c=[];for(let f=0;f<a.length;f++){var d=a[f];d={"default":!(b||
!d.default),localService:!(b||!d.localService),remote:!(!b||!d.remote),lang:d.lang,name:b?d.voiceName:d.name,voiceName:b?d.voiceName:d.name,voiceURI:b?d.voiceIdentifier:d.voiceURI,voiceIdentifier:b?d.voiceIdentifier:d.voiceURI,adjustable:!(b&&!d.adjustable),rawVoice:d};P(d,b);c.push(d)}return c}function P(a,b){let c=(a.lang||"neutral").split("-"),d=(2<=c.length?c[1]:"").toUpperCase(),f=(a.gender||"neutral").toLowerCase();const g=b?a.voiceName:a.name;a.extras={langInfo:dji.languages.languageInfo(c[0]),
lang:(c[0]||"").toLowerCase(),culture:d,gender:f,isGoogle:l.isGoogleVoice(g),isMicrosoft:l.isMicrosoftVoice(g),isOnline:!!b}}function X(){for(let a in A){if(!A.hasOwnProperty(a))continue;let b=A[a],c=[];for(let d in b){if(!b.hasOwnProperty(d))continue;let f=b[d],g=[];for(let e in f)f.hasOwnProperty(e)&&(g=g.concat(f[e]),c=c.concat(g));f["@"]=g}b["@"]=c}}function Q(a,b,c,d,f){let g=null,e=null,h=null;for(let k=0;k<b.length;k++){let m=b[k];m===a||!c&&m.extras.isOnline||!d&&!m.extras.isOnline||(c&&!g&&
m.extras.isOnline&&(g=m),!d||e||m.extras.isOnline||m.extras.isGoogle||(e=m),f&&!h&&m.extras.isGoogle&&(h=m))}return e||h||g||null}function H(a,b,c,d,f){var g=b[a.extras.gender]||[];g=Q(a,g,c,d,f);if(!g)for(let e in b)if(e!==a.extras.gender&&b.hasOwnProperty(e)&&(g=b[e]||[],g=Q(a,g,c,d,f)))break;return g||null}function I(a){if((a=y(a))&&!a.extras.isOnline)return a.voiceName;if(!a||"en"===a.extras.lang)return l.defaultVoice(!0);let b=a.extras,c=A[b.lang]||{};var d=c[b.culture]||{};d=H(a,d,!1,!0,!0);
if(!d)for(let f in c)if(f!==b.culture&&c.hasOwnProperty(f)&&(d=c[f]||{},d=H(a,d,!1,!0,!0)))break;return d?d.voiceName:l.defaultVoice(!0)}function M(){null!==J&&(clearTimeout(J),J=null)}function R(a){if(void 0===a||null===a||1>a.length||0===a.trim().length)return!1;let b=!1;for(let c=0;c<a.length;c++){let d=a.charAt(c);if(!dji.charSet.wordSeparator.characterIsMember(d)){b=!0;break}}return b}function S(a,b,c,d,f,g){let e=[];g=g?g.extras.isGoogle?200:2E4:-1;b=b||0;if(0>g)e.push({offset:b,text:a,isTranslated:c,
isMath:d,mathFormat:f});else{let r=0;do{a:{var h=a;var k=r;var m=g;if(0>m){h=Math.max(0,h.length-1);break a}if(6*(h.length-k)<=m){h=Math.max(0,h.length-1);break a}let z=h.length,B=0,x,n,C=k;for(;k<z&&B<m;k++){n=h.charCodeAt(k);if(127>=n)x=1;else if(2047>=n)x=2;else if(65535>=n)x=3;else for(x=4;n>>6*x;)x++;if(m<B+x)break;B+=x;C=k}h=C}h=k=h;if(h<a.length-1)for(h=k;r<=h&&(m=a.charAt(h),!dji.charSet.wordSeparator.characterIsMember(m));h--);h<=r&&(h=k);e.push({offset:d?b:b+r,text:a.substring(r,h+1),isTranslated:c,
isMath:d,mathFormat:f});r=h+1}while(r<a.length)}0<e.length&&(b=d?e[e.length-1].offset+1:e[e.length-1].offset+e[e.length-1].text.length);return{chunks:e,additionalOffset:b}}function T(a,b,c,d){let f=[];b=b||0;for(let e=0;e<a.length;e++){var g=a[e].isTranslated?d:c;if(a[e].isMath)g={chunks:[{offset:b,text:a[e].text,isTranslated:!1,isMath:!0,mathFormat:a[e].mathFormat,mathReady:a[e].mathReady}],additionalOffset:b+1};else{const h=a[e];g=S(h.text,b,!!h.isTranslated,h.isMath,h.mathFormat,g)}b=g.additionalOffset;
f=f.concat(g.chunks)}return f}function U(a,b,c,d,f,g){g=y(q.voice);let e=y(q.translationVoice),h={};h=f?Object.assign(h,q,f):q;a={chunks:T(a,0,g,e),isSpoken:!1,cancel:!1,userData:b,listener:c,sessionID:d,settings:JSON.parse(JSON.stringify(h))};u.push(a);D&&1!==u.length||(a.isSpoken=K(a))}function K(a){var b=!D;D||(D=!0);if(0>=a.chunks.length||0>=a.settings.volume)return a.cancel=!0,setTimeout(E,0,a),!0;a.startTime=Date.now();let c=a.chunks[0],d=c.isTranslated?a.settings.translationVoice:a.settings.voice;
if(!d)return a.cancel=!0,setTimeout(E,0,a),!0;let f=y(d);f||(f=I(d));let g=window.dji.tts_service&&window.dji.tts_service.isOnlineVoice(d);b&&(v(a.listener,"wait",a.userData,a.sessionID),g||v(a.listener,"start",a.userData,a.sessionID,f.voiceName));b=[];c.isMath&&!c.mathReady&&(v(a.listener,"wait",a.userData,a.sessionID),b.push((new Promise(function(e,h){SreAdapter.mathToText(c.text,c.mathFormat,Y(d),!0,function(k){k.error?h(k):e(k)})})).then(function(e){c.text=e.text;c.mathReady=!0;e=S(c.text,c.offset,
!1,!0,c.mathFormat,c.voice);for(let h=e.chunks.length-1;0<=h;h--)e.chunks[h].mathReady=!0,a.chunks.splice(1,0,e.chunks[h]);a.chunks.splice(0,1)}).catch(function(e){dji.logger.error("__enqueueParts mathPromise failed",e,JSON.parse(JSON.stringify(c)));v(a.listener,"error",a.userData,a.sessionID,e)})));Promise.all(b).then(function(){c=a.chunks[0];g||v(a.listener,"start",a.userData,a.sessionID,f.voiceName);if(!R(c.text)||!d||"No Voice"===d)return setTimeout(E,0,a),!0;dji.logger.log("__doSpeak using voice:",
d," (translated:",c.isTranslated,") / settings:",JSON.stringify(a.settings,!0,2));if(g)Z(a,c,d);else{let e=new SpeechSynthesisUtterance(c.text);e.lang=f.lang;e.voice=f.rawVoice;e.volume=a.settings.volume;e.rate=a.settings.rate;e.pitch=a.settings.pitch;e.onboundary=function(h){var k=a,m=c;const r=h.charIndex||0,z=h.charLength||0;k=k||h.utterance.__item;m=m||k.chunks[0];v(k.listener,"progress",m&&m.isMath?m.offset:r+k.chunks[0].offset,z,k.userData,k.sessionID,m.text&&m.text.length)};e.onstart=function(h){};
e.onerror=function(h){var k=a;k=k||h.utterance.__item;k.cancel=!0;E(k)};e.onend=function(h){var k=a;k=k||h.utterance.__item;E(k)};window.speechSynthesis.speak(e)}});return!0}function Z(a,b,c){let d=!1,f=0;window.dji.tts_service.onStart=function(){v(a.listener,"start",a.userData,a.sessionID,c);v(a.listener,"progress",b.offset,-1,a.userData)};window.dji.tts_service.onProgress=function(g,e){f=e;b&&b.isMath?v(a.listener,"progress",b.offset,-1,a.userData,a.sessionID,b.text&&b.text.length):v(a.listener,
"progress",g+b.offset,e-g,a.userData,a.sessionID,b.text&&b.text.length)};window.dji.tts_service.onStop=function(){if(!d||0>=b.text.substring(f).trim().length)return setTimeout(E,10,a);let g=a.settings.voice,e=a.settings.translationVoice;var h=f;let k=I(a.settings.voice),m=I(a.settings.translationVoice),r=y(k),z=y(m);a.settings.voice=k;a.settings.translationVoice=m;a.chunks[0].text=a.chunks[0].text.substring(h);a.chunks=T(a.chunks,h,r,z);dji.logger.warning(`Switching from Online to Local voice: [${g}, ${e}] -> [${a.settings.voice}, ${a.settings.translationVoice}]`);
setTimeout(K,0,a)};window.dji.tts_service.onError=function(g){d=!0;v(a.listener,"error",a.userData,a.sessionID,g)};window.dji.tts_service.play(b.text,c,{pitch:50,rate:Math.max(0,100*q.rate-50),volume:100*q.volume})}function E(a){if(a&&!a.cancel&&1<a.chunks.length)return a.chunks.splice(0,1),K(a);D=!1;if(a){var b=u.indexOf(a);-1!==b&&(u.splice(b,1),0===u.length&&(b=Date.now()-a.startTime,v(a.listener,"stop",a.userData,b,a.sessionID)))}for(;0<u.length&&(a=u[0],!a.isSpoken)&&(a.isSpoken=K(a),!a.isSpoken);)u.splice(0,
1),v(a.listener,"stop",a.userData,0,a.sessionID)}function G(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){dji.logger.error(b)}}function v(a,b){if(a&&a[b])try{a[b].apply(a,[].slice.call(arguments).splice(2))}catch(c){dji.logger.error(c)}}function Y(a){let b="en";const c=t.find(d=>d.voiceName===a);c&&(b=c.lang.split("-")[0]);return b}let p=dji.utils.os(),q={voice:null,translationVoice:null,rate:1,pitch:1,volume:1},t=[],w=[],A={},J=null,D=!1,u=[],F=null;const aa={windows:{"fr-FR":["fr-FR_ReneeVoice"],
"de-DE":["de-DE_BirgitVoice","de-DE_DieterVoice"],"it-IT":["it-IT_FrancescaVoice"],"ja-JP":["ja-JP_EmiVoice"],"pt-BR":["pt-BR_IsabelaVoice"],"es-LA":["es-LA_SofiaVoice"],"es-ES":["es-ES_EnriqueVoice"],"es-US":["es-US_SofiaVoice"]}};l.initialize=function(a,b){F=a;if(0<t.length)return G(b,!0);O();dji.logger.group("Initialize TTS");dji.logger.monitor({event:"tts_init_step_1a",os:p.name});N(1,c=>{dji.logger.monitor({event:"tts_init_step_1b",os:p.name});b(c)})};l.settings=function(a){const b=F&&F.settingsFactor?
F.settingsFactor:100;if(void 0===a)return{voice:q.voice,translationVoice:q.translationVoice,rate:q.rate*b,pitch:q.pitch*b,volume:q.volume*b};if(null===a)O();else if(!a.voice||L(a.voice))a.voice&&(q.voice=a.voice),a.translationVoice&&(q.translationVoice=a.translationVoice),void 0!==a.rate&&null!==a.rate&&(q.rate=a.rate/b),void 0!==a.pitch&&null!==a.pitch&&(q.pitch=a.pitch/b),void 0!==a.volume&&null!==a.volume&&(q.volume=a.volume/b)};l.voices=function(a){if(a)return t;let b=[],c=l.isOnlineVoiceAllowed(a),
d=c&&p.windows;for(let e=0;e<t.length;e++)if(a=t[e],c||!a.extras.isOnline)if(d&&a.extras.isOnline){var f=a;if(p.chrome||window.dji.config.env().permissive)f=!0;else if(p.windows){var g=aa[p.name];g=g?g[f.lang]:void 0;f=!!(g&&0<=g.indexOf(f.voiceIdentifier))}else f=!1;f&&b.push(a)}else b.push(a);return b};l.voicesMap=function(){return A};l.hasVoice=L;l.hasVoiceForLanguage=function(a,b){a=l.voicesForLanguage(a)||[];for(let c=0;c<a.length;c++)if(a[c].voiceName==b)return!0;return!1};l.defaultVoice=function(a){if(p.mac)return"Samantha";
if(!p.windows&&!a&&l.onlineServiceAllowed()){if(L("Michael (Online)"))return"Michael (Online)";if(0<w.length)return w[0].voiceName}var b=null,c=null,d=null,f=null,g=null,e=null,h=null,k=null,m=null,r=null,z=null,B=null;for(let x=0;x<t.length;x++){let n=t[x];if(a&&n.extras.isOnline)continue;if(!n.voiceName)continue;let C=(n.lang||"").toUpperCase();"EN-US"===C?(b||(b=n.voiceName),!h&&n.extras.isMicrosoft&&p.windows&&(h=n.voiceName)):"EN-GB"===C?(c||(c=n.voiceName),!k&&n.extras.isMicrosoft&&p.windows&&
(k=n.voiceName)):"EN-CA"===C&&(d||(d=n.voiceName),!m&&n.extras.isMicrosoft&&p.windows&&(m=n.voiceName));0<=n.voiceName.indexOf("English")&&(e||(e=n.voiceName),!B&&n.extras.isMicrosoft&&p.windows&&(B=n.voiceName),0<=n.voiceName.indexOf("US")?(f||(f=n.voiceName),!r&&n.extras.isMicrosoft&&p.windows&&(r=n.voiceName)):0<=n.voiceName.indexOf("UK")&&(g||(g=n.voiceName),!z&&n.extras.isMicrosoft&&p.windows&&(z=n.voiceName)))}return p.windows?r?r:h?h:z?z:k?k:m?m:B||"native":f?f:b?b:g?g:c?c:d?d:e||""};l.defaultVoiceForLanguage=
function(a){a=(a||"").split("-");var b=a[0],c=(2<=a.length?a[1]:"").toUpperCase();a=(dji.languages.languageCode_639_1(b)||"").toUpperCase();if(0>=a.length||"EN"===a)return l.defaultVoice();b=A[b]||{};var d=(b[c]||{})["@"]||[];let f=b["@"]||[];for(c=0;c<d.length;c++)if(b=d[c],!b.extras.isOnline&&!b.extras.isGoogle)return b.voiceName;if(l.onlineServiceAllowed())for(c=0;c<w.length;c++)if(b=w[c],d=(b.lang||"").toUpperCase(),0===d.indexOf(a))return b.voiceName;let g=null,e=null;for(c=0;c<f.length;c++)b=
f[c],d=(b.lang||"").toUpperCase(),0===d.indexOf(a)&&(g||(g=b.voiceName),!e&&b.extras.isGoogle&&(e=b.voiceName));return e?e:g||""};l.isGoogleVoice=function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("GOOGLE")||0<=a.indexOf("CHROME")};l.isMicrosoftVoice=function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("MICROSOFT")};l.isOnlineVoice=function(a){if(!a)return!1;a=y(a);return!(!a||!a.extras.isOnline)};l.onlineServiceAllowed=function(){return F&&!F.onlineServiceAllowed?!1:!!(window.dji.config.env().permissive||
p.windows||p.chrome)};l.hasOnlineVoices=function(){return l.onlineServiceAllowed()&&0<w.length};l.cacheOnlineVoices=function(a){0>=w.length&&l.onlineServiceAllowed()?window.dji.tts_service.loadVoices(function(b){if(0>=w.length&&(w=b||[],0<w.length)){for(b=0;b<w.length;b++)P(w[b],!0);t=t.concat(w)}G(a,0<w.length)}):G(a,0<w.length)};l.isOnlineVoiceAllowed=function(a){return l.onlineServiceAllowed()?p.chrome||p.windows?!0:!!window.dji.config.env().permissive:!1};l.voicesForLanguage=function(a,b){let c=
[];b=l.voices(b);for(let d=0;d<b.length;d++){let f=b[d];f.lang&&0===f.lang.indexOf(a)&&c.push(f)}return c};l.localAlternativeForVoice=I;l.onlineAlternativeForVoice=function(a){let b=y(a);if(b&&b.extras.isOnline)return b.voiceName;if(!b||"en"===b.extras.lang)return l.defaultVoice(!1);let c=b.extras,d=A[c.lang]||{};var f=d[c.culture]||{};f=H(b,f,!0,!1,!1);if(!f)for(let g in d)if(g!==c.culture&&d.hasOwnProperty(g)&&(f=d[g]||{},f=H(b,f,!0,!1,!1)))break;return f?f.voiceName:a};l.voiceSupportsSettings=
function(a){a=y(a);return{volume:!(!a||a.extras.isOnline&&!a.adjustable),rate:!(!a||a.extras.isOnline&&!a.adjustable),pitch:!a.extras.isOnline}};l.speak=function(a,b,c,d,f){(f=!!f)||l.stop();M();"string"===typeof a?a=[{text:a,isTranslated:!1}]:a instanceof Array||(a=null);a&&0<a.length&&U(a,b,c,d,null,f)};l.scheduleSpeak=function(a,b,c,d,f,g,e){R(a)&&(b?l.stop():M(),J=setTimeout(function(){U([{text:a,isTranslated:!1}],d,f,g,e)},c||200))};l.stop=function(){M();if(0<u.length){let a;D?(a=u.splice(1,
u.length-1),u[0].cancel=!0,window.speechSynthesis.cancel()):a=u.splice(0,u.length);for(const b of a)b.listener&&v(b.listener,"stop",b.userData,0,b.sessionID)}window.dji.tts_service&&window.dji.tts_service.stop()}})(window.dji.tts=window.dji.tts||{});
