function DexController(a,b){this.m_extensionID=chrome&&chrome.runtime?chrome.runtime.id:"";this.m_isGoogleDocs="docs.google.com"===window.location.hostname&&window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i);this.m_fixPositionDelegate=this.m_cursorInfoDelegate=this.m_locationInfoDelegate=void 0;this.m_dom={container:a.domContainer||document.documentElement};this.m_commonDiv={mainContainer:null,dragSurface:null,contentContainer:null,dragOverlayContainer:null};this.m_drag={States:{Idle:0,
Waiting:1,Active:2},state:0,start:{x:0,y:0},end:{x:0,y:0},offset:{x:0,y:0},onMouseDown:null,onMouseUp:null,onMouseMove:null,onMouseOver:null,onMouseOut:null,ignoreWindowConstraints:!1};this.m_fixedPosition={active:!1,desired:{x:0,y:0},current:{x:0,y:0}};this.m_measurementTools={container:null,div:null,caret:null};var c=this;setTimeout(function(){c.__startInitializationProcedure(b)},0);return this}DexController.instance=null;
DexController.initialize=function(a,b){DexController.instance?b&&b():DexController.instance=new DexController(a,b)};DexController.prototype.setLocationInfoDelegate=function(a){this.m_locationInfoDelegate=a};DexController.prototype.setCursorInfoDelegate=function(a){this.m_cursorInfoDelegate=a};DexController.prototype.setFixPositionDelegate=function(a){this.m_fixPositionDelegate=a};DexController.prototype.addExtensionControls=function(a){this.m_commonDiv.contentContainer.appendChild(a)};
DexController.prototype.move=function(a,b){this.m_fixedPosition.active||(a&&(this.m_commonDiv.mainContainer.style.left=parseFloat(a)+"px"),b&&(this.m_commonDiv.mainContainer.style.top=parseFloat(b)+"px"))};
DexController.prototype.fixPosition=function(a){this.m_fixedPosition.active=a&&a.anchor;if(this.m_fixedPosition.active){var b=a.anchor[0];let c=a.anchor[1];"b"===c&&2>=a.y?this.m_commonDiv.mainContainer.setAttribute("dji-horizontal-layout",!0):this.m_commonDiv.mainContainer.removeAttribute("dji-horizontal-layout");let d=this.getContentBoundingRect(),f=this.__scrollbarSize(),e=window.innerWidth-d.width-f.x,g=window.innerHeight-d.height-f.y;b="l"===b?Math.min(a.x,e):Math.min(window.innerWidth-a.x-d.width-
f.x,e);a="t"===c?Math.min(a.y,g):Math.min(window.innerHeight-a.y-d.height-f.y,g);this.m_commonDiv.mainContainer.style.left=(0>b?30:b)+"px";this.m_commonDiv.mainContainer.style.top=(0>a?30:a)+"px";window.dji.utils.addClassToElement(this.m_commonDiv.mainContainer,"dexFixed")}else this.m_commonDiv.mainContainer.removeAttribute("dji-horizontal-layout"),window.dji.utils.removeClassFromElement(this.m_commonDiv.mainContainer,"dexFixed")};
DexController.prototype.__scrollbarSize=function(){let a=document.body.clientWidth-document.body.offsetWidth;return{x:document.body.clientWidth<document.body.scrollWidth?a:0,y:document.body.clientHeight<document.body.scrollHeight?a:0}};DexController.prototype.__startInitializationProcedure=function(a){var b=this;"complete"===document.readyState?(this.__initialize(),a&&a()):window.addEventListener("load",function(){b.__initialize();a&&a()})};
DexController.prototype.__initialize=function(){var a=this;this.m_commonDiv.mainContainer=document.getElementById("dexControlsContainer");this.m_commonDiv.contentContainer=document.getElementById("dexControlsContainerBody");null===this.m_commonDiv.mainContainer&&(this.m_commonDiv.mainContainer=document.createElement("div"),this.m_commonDiv.mainContainer.id="dexControlsContainer",this.m_commonDiv.dragSurface=document.createElement("div"),this.m_commonDiv.dragSurface.id="dexControlsContainerDragSurface",
this.m_commonDiv.dragOverlayContainer=document.createElement("div"),this.m_commonDiv.dragOverlayContainer.id="dexControlsContainerOverlay",this.m_commonDiv.contentContainer=document.createElement("div"),this.m_commonDiv.contentContainer.id="dexControlsContainerBody",this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.dragSurface),this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.contentContainer),this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.dragOverlayContainer),this.m_dom.container.appendChild(this.m_commonDiv.mainContainer),
this.m_drag.onMouseDown=function(b){a.__isDraggable(b.target)&&a.__onDragStart(b)&&(b.preventDefault(),b.stopPropagation(),document.addEventListener("mousemove",a.m_drag.onMouseMove,!0),document.addEventListener("mouseup",a.m_drag.onMouseUp,!0),document.addEventListener("mouseout",a.m_drag.onMouseOut,!0),document.addEventListener("mouseover",a.m_drag.onMouseOver,!0),window.dji.utils.addClassToElement(a.m_commonDiv.mainContainer,"dexPrepareDragging"))},this.m_drag.onMouseMove=function(b){a.__onDrag(b)&&
(b.preventDefault(),b.stopPropagation())},this.m_drag.onMouseOver=function(b){b.preventDefault();b.stopPropagation()},this.m_drag.onMouseOut=function(b){if(null===b.toElement)a.m_drag.onMouseUp(b);else b.preventDefault(),b.stopPropagation()},this.m_drag.onMouseUp=function(b){a.__onDragEnd(b);b.preventDefault();b.stopPropagation();document.removeEventListener("mousemove",a.m_drag.onMouseMove,!0);document.removeEventListener("mouseup",a.m_drag.onMouseUp,!0);document.removeEventListener("mouseover",
a.m_drag.onMouseOver,!0);document.removeEventListener("mouseout",a.m_drag.onMouseOut,!0);window.dji.utils.removeClassFromElement(a.m_commonDiv.mainContainer,"dexPrepareDragging")},this.m_commonDiv.mainContainer.addEventListener("mousedown",this.m_drag.onMouseDown,!0),this.m_measurementTools.container=document.createElement("div"),this.m_measurementTools.container.id="dexControlsContainerMeasurement",this.m_measurementTools.div=document.createElement("div"),this.m_measurementTools.div.id="dexControlsContainerMeasurementDiv",
this.m_measurementTools.container.appendChild(this.m_measurementTools.div),this.m_dom.container.appendChild(this.m_measurementTools.container),window.addEventListener("resize",function(b){setTimeout(function(){a.__onWindowResize(b)},0)}))};DexController.prototype.__isDraggable=function(a){for(;a;){if(a.hasAttribute("dji-non-draggable"))return!1;a=a.parentElement}return!0};DexController.prototype.__editorWillBeIgnored=function(a){for(;a;){if(a.hasAttribute("dji-dex-ignore-editor"))return!0;a=a.parentElement}return!1};
DexController.prototype.__isEntireElementVisible=function(){let a=this.getContentBoundingRect();return 0<=a.top&&a.bottom<window.innerHeight&&0<=a.left&&a.right<window.innerWidth};
DexController.prototype.__onDragStart=function(a){if(this.m_drag.state!==this.m_drag.States.Idle)return this.m_drag.onMouseUp(a),!1;if(1!==a.which)return!1;this.m_drag.state=this.m_drag.States.Waiting;this.m_drag.start.x=this.m_drag.end.x=a.x;this.m_drag.start.y=this.m_drag.end.y=a.y;this.m_drag.ignoreWindowConstraints=!this.__isEntireElementVisible();return!0};
DexController.prototype.__onDrag=function(a){if(this.m_drag.state==this.m_drag.States.Waiting||this.m_drag.state==this.m_drag.States.Active)if(this.m_drag.end.x=a.x,this.m_drag.end.y=a.y,this.m_drag.state==this.m_drag.States.Waiting){if(5<Math.sqrt((this.m_drag.end.x-this.m_drag.start.x)*(this.m_drag.end.x-this.m_drag.start.x)+(this.m_drag.end.y-this.m_drag.start.y)*(this.m_drag.end.y-this.m_drag.start.y))){this.m_commonDiv.mainContainer.hasAttribute("dji-horizontal-layout")&&(this.m_commonDiv.mainContainer.removeAttribute("dji-horizontal-layout"),
this.m_commonDiv.mainContainer.style.left=a.x+"px");var b=this.m_commonDiv.mainContainer.getBoundingClientRect(),c=this.getContentBoundingRect();this.m_drag.state=this.m_drag.States.Active;this.m_drag.start.x=this.m_drag.end.x=a.x;this.m_drag.start.y=this.m_drag.end.y=a.y;this.m_drag.offset.x=this.m_drag.start.x-b.left;this.m_drag.offset.y=this.m_drag.start.y-b.top;this.m_fixedPosition.active=!0;this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=this.m_drag.end.x-this.m_drag.offset.x;this.m_fixedPosition.desired.y=
this.m_fixedPosition.current.y=this.m_drag.end.y-this.m_drag.offset.y;this.m_commonDiv.dragOverlayContainer.style.width=c.width+"px";this.m_commonDiv.dragOverlayContainer.style.height=c.height+"px";window.dji.utils.addClassToElement(this.m_commonDiv.mainContainer,"dexFixed");window.dji.utils.addClassToElement(this.m_commonDiv.mainContainer,"dexDragging");this.m_commonDiv.mainContainer.style.left=b.left+"px";this.m_commonDiv.mainContainer.style.top=b.top+"px"}}else if(this.m_drag.state==this.m_drag.States.Active){a=
this.m_drag.end.x-this.m_drag.offset.x;b=this.m_drag.end.y-this.m_drag.offset.y;c=window.innerWidth;var d=window.innerHeight,f=parseInt(this.m_commonDiv.dragOverlayContainer.style.width),e=parseInt(this.m_commonDiv.dragOverlayContainer.style.height);let g=this.__scrollbarSize();if(this.m_drag.ignoreWindowConstraints||0<=a&&0<=b&&a+f<=c-g.x&&b+e<=d-g.y)this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=a,this.m_fixedPosition.desired.y=this.m_fixedPosition.current.y=b,this.m_commonDiv.mainContainer.style.left=
this.m_fixedPosition.desired.x+"px",this.m_commonDiv.mainContainer.style.top=this.m_fixedPosition.desired.y+"px"}return this.m_drag.state==this.m_drag.States.Active};
DexController.prototype.__onDragEnd=function(a){if(this.m_drag.state===this.m_drag.States.Waiting||this.m_drag.state===this.m_drag.States.Active){if(this.m_drag.state===this.m_drag.States.Active){var b=(a=this.m_locationInfoDelegate?this.m_locationInfoDelegate():null)?a.caret:this.__getCaretInfo();if(b){var c=Math.max(Math.abs(b.right-b.left),1),d=Math.max(Math.abs(b.bottom-b.top),1);const f=Math.max(b.left-2*c,0);c=b.right+2*c;const e=Math.max(b.top-d/2,0);d=b.bottom+d/2;const g=this.__getDragOverlayBoundingRect();
(g.left<=f&&f<=g.right||g.left<=c&&c<=g.right)&&(g.top<=e&&e<=g.bottom||g.top<=d&&d<=g.bottom)?(this.m_fixedPosition.active=!1,window.dji.utils.removeClassFromElement(this.m_commonDiv.mainContainer,"dexFixed"),a?(this.m_commonDiv.mainContainer.style.left=a.left+"px",this.m_commonDiv.mainContainer.style.top=a.top+"px"):(this.m_commonDiv.mainContainer.style.left=b.left+window.pageXOffset+"px",this.m_commonDiv.mainContainer.style.top=b.bottom+window.pageYOffset+2+"px")):g.bottom>=window.innerHeight-
10&&(this.m_commonDiv.mainContainer.setAttribute("dji-horizontal-layout",!0),a=this.getContentBoundingRect().height,this.m_commonDiv.mainContainer.style.top=window.innerHeight-a-1+"px",this.m_commonDiv.mainContainer.style.left="0px")}a=parseFloat(this.m_commonDiv.mainContainer.style.left);b=parseFloat(this.m_commonDiv.mainContainer.style.top);this.__setPositionInfo(this.m_fixedPosition.active,a,b);window.dji.utils.removeClassFromElement(this.m_commonDiv.mainContainer,"dexDragging")}this.m_drag.ignoreWindowConstraints=
!1;this.m_drag.state=this.m_drag.States.Idle}};DexController.prototype.__getDragOverlayBoundingRect=function(){const a=this.m_commonDiv.dragOverlayContainer.getBoundingClientRect();var b="fixed"===document.defaultView.getComputedStyle(this.m_commonDiv.mainContainer,null).position;const c=b?window.pageXOffset:0;b=b?window.pageYOffset:0;return{left:Math.round(a.left+c),top:Math.round(a.top+b),right:Math.round(a.right+c),bottom:Math.round(a.bottom+b)}};
DexController.prototype.getContentBoundingRect=function(){for(var a=this.m_commonDiv.contentContainer.getBoundingClientRect(),b={left:a.left,top:a.top,bottom:a.bottom,right:a.right,width:0,height:0},c=this.m_commonDiv.contentContainer.childNodes,d=0;d<c.length;d++)(a=c[d].style.display)||(a=document.defaultView.getComputedStyle(c[d],null).getPropertyValue("display")),"none"!==a&&(a=c[d].getBoundingClientRect(),a.left<b.left&&(b.left=a.left),a.top<b.top&&(b.top=a.top),b.right<a.right&&(b.right=a.right),
b.bottom<a.bottom&&(b.bottom=a.bottom));b.width=b.right-b.left;b.height=b.bottom-b.top;return b};DexController.prototype.__createSeparator=function(){var a=document.createElement("div");a.setAttribute("class","dexSeparator");return a};DexController.prototype.__getScrollOffset=function(){var a=this.m_dom.container.documentElement;return{x:(window.pageXOffset||a.scrollLeft)-(a.clientLeft||0),y:(window.pageYOffset||a.scrollTop)-(a.clientTop||0)}};
DexController.prototype.__getCaretInfo=function(){if(this.m_cursorInfoDelegate)try{return this.m_cursorInfoDelegate()}catch(b){}if(this.m_isGoogleDocs){var a=document.getElementsByClassName("kix-cursor-caret")[0];a=a.getBoundingClientRect();return a={left:a.left,top:a.top,right:a.right,bottom:a.bottom}}return this.__getCaretInfoFromGenericEditors()};
DexController.prototype.__setPositionInfo=function(a,b,c){let d=null;var f=0,e=0;if(a){d=this.__getAnchor(b,c);f=d[0];a=d[1];e=this.getContentBoundingRect();let g=this.__scrollbarSize();f="l"===f?b:window.innerWidth-b-e.width-g.x;e="t"===a?c:window.innerHeight-c-e.height-g.y}this.m_fixPositionDelegate(d,f,e)};DexController.prototype.__getAnchor=function(a,b){let c=this.getContentBoundingRect();return(a<=window.innerWidth-a-c.width?"l":"r")+(b<=window.innerHeight-b-c.height?"t":"b")};
DexController.prototype.__getCaretInfoFromGenericEditors=function(){var a=this.__getActiveElementInfo();if(null===a||this.__editorWillBeIgnored(a.element))return null;var b={left:0,top:0,right:0,bottom:0};if(void 0!==a.element.selectionStart){var c=a.element.selectionStart,d=a.element.selectionEnd-a.element.selectionStart,f=a.element.value,e=dji.utils.escapeHtml(f.slice(0,c+d));c=dji.utils.escapeHtml(f.slice(c+d,f.length));d=document.defaultView.getComputedStyle(a.element,null);"INPUT"===a.element.tagName&&
0<e.length&&(e=e.replace(/ /g,"."));this.m_measurementTools.div.innerHTML="";this.m_measurementTools.div.style.cssText=d.cssText;this.m_measurementTools.div.innerHTML=e+"<span id='dexControlsContainerMeasurementDivCaret'></span>"+c;this.m_measurementTools.caret=document.getElementById("dexControlsContainerMeasurementDivCaret");e=a.element.getBoundingClientRect();c=this.m_measurementTools.div.getBoundingClientRect();d=this.m_measurementTools.caret.getBoundingClientRect();b.left=-a.element.scrollLeft+
e.left+d.left-c.left;b.top=-a.element.scrollTop+e.top+d.top-c.top;b.right=d.right-d.left;b.bottom=d.bottom-d.top}else if(void 0!==a.element.contentEditable&&"true"===a.element.contentEditable){e=a.document.getSelection();c=e.focusNode;d=e.focusOffset;try{f=0<e.rangeCount?e.getRangeAt(0).cloneRange():null;!f&&c&&(f=document.createRange(),f.setStart(c,d),f.setEnd(c,d));let g=f.getClientRects();0>=g.length&&0<d&&d<=c.childNodes.length&&(f.detach(),f.selectNode(c.childNodes[d-1]),g=f.getClientRects());
f.detach();if(0<g.length){let h=g[g.length-1];b.left=h.right;b.top=h.top;b.right=0;b.bottom=h.bottom-h.top}else if(c){const h=document.defaultView.getComputedStyle(c,null),k=c.getBoundingClientRect(),l=parseFloat(h.getPropertyValue("padding-left")),m=parseFloat(h.getPropertyValue("padding-top")),n=parseFloat(h.getPropertyValue("font-size"));b.left=l+k.left;b.top=m+k.top;b.right=0;b.bottom=n+2}}catch(g){Logger.instance.error(g,c,d,e)}}if(0<a.iframes.length)for(e=0;e<a.iframes.length;e++)c=a.iframes[e].getBoundingClientRect(),
b.left+=c.left,b.top+=c.top;b.right=b.left+b.right;b.bottom=b.top+b.bottom;return b};
DexController.prototype.__getActiveElementInfo=function(){const a={element:document.activeElement,document,iframes:[]};if(a.element)for(;;)if(a.element.shadowRoot&&a.element.shadowRoot.activeElement)a.element=a.element.shadowRoot.activeElement;else if("IFRAME"===a.element.tagName)try{if(!this.__validateIframe(a.element))break;const b=a.element;a.element=b.contentDocument.activeElement;a.document=b.contentDocument;a.iframes=[b].concat(a.iframes)}catch(b){break}else break;return a};
DexController.prototype.__validateIframe=function(a){if(void 0===a.src||null===a.src)return!1;a=a.src.split("/")[2];return void 0===a||null===a?!0:0<=a.indexOf(document.domain)};
DexController.prototype.__onWindowResize=function(a){if(this.m_fixedPosition.active){a=this.getContentBoundingRect();var b=window.innerWidth,c=window.innerHeight,d=a.top;if(c<a.bottom||this.m_commonDiv.mainContainer.hasAttribute("dji-horizontal-layout"))d=c-a.height-1;0>d&&(d=0);c=a.left;b<a.right&&(c=b-a.width);0>c&&(c=0);c!=a.left&&(this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=c,this.m_commonDiv.mainContainer.style.left=this.m_fixedPosition.desired.x+"px");d!=a.left&&(this.m_fixedPosition.desired.y=
this.m_fixedPosition.current.y=d,this.m_commonDiv.mainContainer.style.top=this.m_fixedPosition.desired.y+"px");this.__setPositionInfo(!0,parseFloat(this.m_commonDiv.mainContainer.style.left),parseFloat(this.m_commonDiv.mainContainer.style.top))}};
