function CWEPredictionOptions(a,b,d,c){this.m_cweSettings=a;this.m_cwePredictionEngine=b;this.m_cweBackgroundManager=d;this.m_backgroundPage=c;this.m_topicsView=$("#dji-cwu-topics-view");this.m_mainDictionary=$("#dji-cwu-main-dictionary");this.m_mainDictionaryTemplate=null;this.m_momentaryTopic=$("#dji-cwu-momentary-topic");this.m_predictionAhead=$("#dji-cwu-prediction-ahead");this.m_flexibleSpelling=$("#dji-cwu-flexible-spelling");this.m_locale=$("#dji-cwu-prediction-language");this.__fillLocaleInfo();
this.m_presentationLangEl=$("#dji-cwu-presentation-language");this.m_translationLocale=$("#dji-cwu-translate-writing");this.m_asNeededOption=$("#dji-cwu-as-needed-option");this.m_topicsSearchContainer=$("#dji-cwu-search-container");this.m_topicsSearch=$("#dji-cwu-search-topic-dictionary");this.m_topicsCancelSearch=$("#dji-cwu-cancel-search");this.m_topicsResetSearch=$("#dji-cwu-reset-search");this.m_localTopics=$("#dji-cwu-local-topic-list");this.m_wikiTopics=$("#dji-cwu-wiki-topic-list");this.m_activeTopics=
$("#dji-cwu-active-topics-list");this.m_wikiReader=new CWEWikiReader(this.m_cwePredictionEngine.sensitiveWords());this.m_searchTimer=new DjiTimer(this,this.__searchTopics);this.m_wikiTopicsList=[];this.m_localTopicsList=[];this.m_selectedWikiTopicIndex=-1;this.m_lastSearchText="";this.m_allLocalTopicsList=[];this.m_allLocalTopicsListLowerCase=[];this.m_activeTopicsList=[];this.m_displayTopicList=[];this.m_displayTopicsMap={};this.m_maxDisplayedTopics=6;this.__initialize();return this}
CWEPredictionOptions.instance=null;CWEPredictionOptions.prototype.__fillLocaleInfo=function(){var a=$("[dji-cwu-template-id=dji-cwu-prediction-language]").find("[dji-cwu-value='"+this.m_cweBackgroundManager.locale()+"']");a.attr("dji-check","");a=a.text();this.m_locale.find(".dji-cwu-option-item-value").text(a);this.m_localeLang=this.m_cweBackgroundManager.locale()};
CWEPredictionOptions.prototype.__fillPresentationLanguageInfo=function(){var a=this.m_cweSettings.presentationLang().toUpperCase();a=$("[dji-cwu-template-id=dji-cwu-presentation-language]").find("[dji-cwu-value='"+a+"']");a.attr("dji-check","");a=a.text();this.m_presentationLangEl.find(".dji-cwu-option-item-value").text(a)};
CWEPredictionOptions.prototype.__initialize=function(){function a(e,f){}function b(e,f){e&&e.hasOwnProperty("text")&&(f=$("#dji-cwu-search-topic-dictionary"),f.val().trim()!==e.text&&(f.val(e.text),c.__scheduleTopicsSearch()))}function d(e,f){g()}let c=this;this.__fillLocaleInfo();this.__displayTopics();null!==this.m_cwePredictionEngine&&(this.m_cwePredictionEngine.addOptionsListener(this),this.m_cwePredictionEngine.getTopics(!0));this.m_cweSettings.showPresentationLanguageOption()?(this.__fillPresentationLanguageInfo(),
this.m_presentationLangEl.on("change",function(e){e.value.toLowerCase()!==c.m_cweSettings.presentationLang()&&c.__changePresentationLang(e.value.toLowerCase())})):this.m_presentationLangEl[0].classList.add("dji-cwu-hide-option");this.m_locale.on("change",function(e){c.__changeLocale(e.value)});this.m_translationLocale.on("change",function(e){e.value!==c.m_cweSettings.translationSource()&&c.__changeTranslationLocale(e.value,e.text)});this.m_asNeededOption.on("change",function(e){const f=parseInt(e.value);
var l=c.m_cweSettings.getAsNeededRawOption();f!==l&&(c.m_cweBackgroundManager.sendGA4Event("AsNeededOn",{setting:0===f?"off":1===f?"on":"speech-to-text"},null),l=$("[dji-cwu-template-id=dji-cwu-as-needed-options]").find("[dji-cwu-value='"+c.m_cweSettings.asNeeded()+"']"),l.removeAttr("dji-check"),c.__changeAsNeededOption(f,e.text),l=$("[dji-cwu-template-id=dji-cwu-as-needed-options]").find("[dji-cwu-value='"+c.m_cweSettings.asNeeded()+"']"),l.attr("dji-check",""))});this.m_mainDictionary.on("change",
function(e){c.m_cweSettings.predictionMainDictionary(parseInt(e.value));c.m_mainDictionaryTemplate.find("[dji-check]").removeAttr("dji-check");c.m_mainDictionaryTemplate.find("[dji-cwu-value='"+e.value+"']").attr("dji-check","")});this.m_momentaryTopic.on("change",function(e){c.m_cweSettings.predictionMomentaryTopic(e.checked?1:0)});this.m_predictionAhead.on("change",function(e){c.m_cweSettings.predictionAhead(e.checked?1:0)});this.m_flexibleSpelling.on("change",function(e){c.m_cweSettings.predictionFlexibleSpelling(e.checked?
1:0)});this.m_activeTopics.on("change",".dji-cwu-switch-container",async function(e){if(!c.m_cweBackgroundManager.isBusy()){var f=$(e.currentTarget);e=e.checked;f=f.attr("dji-cwu-topic-dictionary-id");f=c.m_displayTopicList[f];await c.m_cweBackgroundManager.activateTopicAsync(-1,{name:f.name,activate:!!e});c.m_cweBackgroundManager.sendGA4Event("TopicStatusChanged",{topic_name:f.name,topic_status:!!e},null)}});this.__load();let g=function(){let e=$("#dji-cwu-speech-to-text");e.hasClass("dji-cwu-speech-to-text-on")&&
(h(e,!1),c.m_backgroundPage.dji.speechRecognition.stop())},h=function(e,f){f?(e.addClass("dji-cwu-speech-to-text-on"),e.find("i").removeClass("svg-mic"),e.find("i").addClass("svg-mic_off")):(e.find("i").removeClass("svg-mic_off"),e.find("i").addClass("svg-mic"),e.removeClass("dji-cwu-speech-to-text-on"))},k=function(){c.__scheduleTopicsSearch()};$("#dji-cwu-speech-to-text").on("click",function(e){$(e.currentTarget).hasClass("dji-cwu-speech-to-text-on")?(h($(e.currentTarget),!1),$("#dji-cwu-search-topic-dictionary").focus(),
c.m_backgroundPage.dji.speechRecognition.stop()):(navigator.webkitGetUserMedia({audio:!0},function(f){f.getTracks()[0].stop();c.m_backgroundPage.dji.speechRecognition.start(c.m_localeLang,a,b,d,{})},function(f){Logger.instance.error(f)}),h($(e.currentTarget),!0),$("#dji-cwu-search-topic-dictionary").focus())});this.m_topicsSearch.on("focus",function(){"dji-cwu-default"===c.m_topicsSearchContainer.attr("dji-cwu-view-mode")&&($("body").addClass("dji-cwu-search"),c.m_topicsSearchContainer.attr("dji-cwu-view-mode",
"dji-cwu-have-focus"))}).on("input",k).on("search",k);this.m_topicsCancelSearch.on("click",function(){g();c.m_lastSearchText="";c.m_topicsSearch.val("");$("body").removeClass("dji-cwu-search");c.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-default").removeClass("dji-cwu-reset")});this.m_topicsResetSearch.on("click",function(){g();c.m_lastSearchText="";c.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus").removeClass("dji-cwu-reset");c.m_topicsSearch.focus().val("")});
this.m_localTopics.on("click",".dji-cwu-topic-item",function(e){e=parseInt($(e.currentTarget).attr("dji-cwu-topic-index"));c.__localTopicSelected(e);g()});this.m_wikiTopics.on("click",".dji-cwu-topic-item",function(e){e=parseInt($(e.currentTarget).attr("dji-cwu-topic-index"));c.__wikiTopicSelected(e);g()});$(document).on("keydown",function(e){27===e.keyCode&&"dji-cwu-default"!==c.m_topicsSearchContainer.attr("dji-cwu-view-mode")&&(c.__clearSearch(),c.m_topicsSearch.blur(),g())});$(window).on("blur",
function(){g()});this.__updateUI()};
CWEPredictionOptions.prototype.__updateUI=function(){if(this.m_cweSettings){var a=this.m_cweSettings.features(),b=!!(!a||a.allowSettings&&a.allowChangeSettings),d=!(a&&!a.allowTopics),c=!(a&&!a.allowChangeTopics),g={disabled:!(d&&c),"dji-not-allowed":!(d&&c)};this.m_topicsView.find("#dji-cwu-search-topic-dictionary").prop(g);this.m_topicsView.find("#dji-cwu-speech-to-text").attr("disabled",!d);this.m_activeTopics.find(".dji-cwu-switch-container").attr("disabled",!c);d?(this.m_topicsView.removeClass("dji-disable"),
this.m_activeTopics.find(".dji-cwu-option-switch-item").removeClass("dji-cwu-disable")):(this.m_topicsView.addClass("dji-disable"),this.m_activeTopics.find(".dji-cwu-option-switch-item").addClass("dji-cwu-disable"));this.m_locale.attr("disabled",!(b&&(!a||a.allowChangeLanguage)));this.m_mainDictionary.attr("disabled",!(b&&(!a||a.allowChangeDictionary)));d=b&&!(a&&!a.allowChangeMomentary);this.m_momentaryTopic.attr("disabled",!d);d?this.m_momentaryTopic.closest(".dji-cwu-option-switch-item").removeClass("dji-cwu-disable"):
this.m_momentaryTopic.closest(".dji-cwu-option-switch-item").addClass("dji-cwu-disable");d=b&&!(a&&!a.allowChangePredictAhead);this.m_predictionAhead.attr("disabled",!d);d?this.m_predictionAhead.closest(".dji-cwu-option-switch-item").removeClass("dji-cwu-disable"):this.m_predictionAhead.closest(".dji-cwu-option-switch-item").addClass("dji-cwu-disable");a=b&&!(a&&!a.allowChangeFlexibleSpelling);this.m_flexibleSpelling.attr("disabled",!a);a?this.m_flexibleSpelling.closest(".dji-cwu-option-switch-item").removeClass("dji-cwu-disable"):
this.m_flexibleSpelling.closest(".dji-cwu-option-switch-item").addClass("dji-cwu-disable");this.m_translationLocale.attr("disabled",!b)}};
CWEPredictionOptions.prototype.__load=function(){if(this.m_cweSettings){this.__fillLocaleInfo();this.__fillAvailableTranslationLang();this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.m_cweSettings.predictionMomentaryTopic()&&this.m_momentaryTopic.addClass("dji-cwu-on");this.m_cweSettings.predictionAhead()&&this.m_predictionAhead.addClass("dji-cwu-on");this.m_cweSettings.predictionFlexibleSpelling()&&this.m_flexibleSpelling.addClass("dji-cwu-on");var a=this.m_cweSettings.translationSource(),
b=this.m_locale.find(".dji-cwu-option-item-value").text().trim(),d="";if(a){let c=this.m_cweBackgroundManager.translationLanguageInfo(a);d=c?c.language_code:a;this.__isEnglish()||(b=b.substr(0,b.indexOf("(")));this.m_translationLocale.find(".dji-cwu-option-item-value").text(c?c.name:a);this.m_translationLocale.find(".dji-cwu-option-item-auxiliary").text(" > "+b)}a=this.m_translationLocale.find(".dji-cwu-option-item-label");$("[dji-cwu-template-id=dji-cwu-translate-writing]").find("[dji-cwu-value='"+
d+"']").attr("dji-check","");a.text(a.text()+" "+b);this.__displayTopics();b=this.__isEnglish();b||(this.m_predictionAhead.prop("disabled",!0),this.m_flexibleSpelling.prop("disabled",!0));this.m_mainDictionaryTemplate=b?$("[dji-cwu-template-id=dji-cwu-main-dictionary-en]"):$("[dji-cwu-template-id=dji-cwu-main-dictionary-no-en]");d=this.m_mainDictionaryTemplate.find("[dji-cwu-value='"+this.m_cweSettings.predictionMainDictionary()+"']");d.attr("dji-check","");d=d.text();this.m_mainDictionary.find(".dji-cwu-option-item-value").text(d);
this.m_mainDictionary.attr("dji-cwu-dropdown-id",b?"dji-cwu-main-dictionary-en":"dji-cwu-main-dictionary-no-en");this.__fillAsNeededOption()}};
CWEPredictionOptions.prototype.__fillAsNeededOption=function(){var a=window.browserEngine.agent.isEdge;let b=$("[dji-cwu-template-id=dji-cwu-as-needed-options]").find(".cwu-as-needed-stt");b&&(a?b.hide():b.show());a=$("[dji-cwu-template-id=dji-cwu-as-needed-options]").find("[dji-cwu-value='"+this.m_cweSettings.asNeeded()+"']");a.attr("dji-check","");a=a.text();this.m_asNeededOption.find(".dji-cwu-option-item-value").text(a)};
CWEPredictionOptions.prototype.__fillAvailableTranslationLang=function(){const a=this.m_cweBackgroundManager.localeLang(!1),b=this.m_cweBackgroundManager.translationLanguages();let d=$("[dji-cwu-template-id=dji-cwu-translate-language]"),c=$("[dji-cwu-template-id=dji-cwu-translate-writing]");c.children().slice(1).remove();let g={};b.forEach(h=>{let k=h.language_code.split("-")[0];h.lang=k;g[k]=g[k]?++g[k]:1});for(let h=0;h<b.length;h++){let k=b[h],e=k.lang,f=d.clone(!0),l=1<g[e]?k.name:k.name.split("-")[0];
$(f).attr("dji-cwu-value",k.language_code);$(f).find(".dji-cwu-menu-item-text").text(l);a===e&&$(f).attr("dji-cwu-not-available","");c.append(f)}};
CWEPredictionOptions.prototype.__changeTranslationLocale=async function(a,b){const d=this.m_cweBackgroundManager.localeLang(!1),c=(a||"").split("-")[0];d!==c&&(dji.ui.modalDlg.showMessageDlg("dji-cwu-changing-language-message"),await this.m_cweBackgroundManager.downloadHunspellResources(a)?(this.m_cweSettings.translationSource(a&&0<a.length?a:null),this.m_cweBackgroundManager.changeSpellcheckerLocale(a),this.m_cweBackgroundManager.sendGA4Event("TranslateWritingOn",{language:a},null),b=$("[dji-cwu-template-id=dji-cwu-translate-writing]"),
b.find("[dji-check]").removeAttr("dji-check"),""===a?this.m_translationLocale.find(".dji-cwu-option-item-auxiliary").attr("dji-off",""):this.m_translationLocale.find(".dji-cwu-option-item-auxiliary").removeAttr("dji-off"),b.find("[dji-cwu-value='"+a+"']").attr("dji-check",""),dji.ui.modalDlg.hideDlg()):(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showModalDlg("dji-cwu-failed-download-hunspell",{doneCallback:function(){dji.ui.modalDlg.hideDlg()}}),this.m_translationLocale.find(".dji-cwu-option-item-value").text(b)))};
CWEPredictionOptions.prototype.__changeLocale=function(a){if(this.m_cweBackgroundManager.locale()!==a){var b=this;this.m_backgroundPage.jsdapi.cow.updateLanguage(a,function(d){dji.ui.modalDlg.showMessageDlg("dji-cwu-download-resources-wait-message");b.m_cweBackgroundManager.downloadPredictionResources(a,function(c){c?b.m_backgroundPage.jsdapi.cow.updateLanguage(a,function(g){b.m_cweBackgroundManager.changeLocale(a);dji.ui.modalDlg.hideDlg()}):(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showModalDlg("dji-cwu-failed-download-language-resources",
{doneCallback:function(){dji.ui.modalDlg.hideDlg();b.__fillLocaleInfo()}}))})})}};CWEPredictionOptions.prototype.__changePresentationLang=async function(a){try{this.m_backgroundPage.jsdapi.cow.updatePresentationLanguageAsync(a)}catch(b){Logger.instance.error(b)}this.m_cweBackgroundManager.CWEI18n.instance.setCustomLanguage(a);this.m_cweSettings.presentationLang(a);window.location.reload()};CWEPredictionOptions.prototype.__scheduleTopicsSearch=function(){this.m_searchTimer.trigger(10,this.m_topicsSearch.val().trim())};
CWEPredictionOptions.prototype.__searchTopics=async function(a){a=a?a.trim():"";if(a!==this.m_lastSearchText)if(this.m_lastSearchText=a,0>=a.length)this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus").removeClass("dji-cwu-reset"),this.m_localTopicsList=[],this.m_wikiTopicsList=[];else{this.m_wikiTopics.hide();var b=void 0,d=this.m_cweSettings.features();if(d=!(d&&!d.allowCreateTopics))try{b=this.m_wikiReader.searchAsync(a,this.m_localeLang)}catch(c){Logger.instance.error(c)}this.__searchInLocalTopics(a);
if(d)try{let c=await b;c=c.reduce(function(g,h){g.push(h.name);return g},[]);a===this.m_lastSearchText&&this.__topicSearchFinished(c)}catch(c){Logger.instance.error(c)}}};CWEPredictionOptions.prototype.__searchInLocalTopics=function(a){let b=[];a=a.toLowerCase();for(let d=0;d<this.m_allLocalTopicsListLowerCase.length;d++)-1!==this.m_allLocalTopicsListLowerCase[d].indexOf(a)&&b.push(this.m_allLocalTopicsList[d]);b.sort();this.__topicSearchFinished(b,!0)};
CWEPredictionOptions.prototype.topicsAvailable=function(a){this.m_allLocalTopicsList=a;this.m_allLocalTopicsListLowerCase=[];for(let b=0;b<a.length;b++)this.m_allLocalTopicsListLowerCase.push(a[b].toLowerCase())};CWEPredictionOptions.prototype.topicActivated=function(a){this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.__updateTopicUIState(a,!0)||this.__displayTopics();dji.ui.modalDlg.hideDlg()};
CWEPredictionOptions.prototype.topicDeactivated=function(a){this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.__updateTopicUIState(a,!1)||this.__displayTopics();dji.ui.modalDlg.hideDlg()};CWEPredictionOptions.prototype.topicCreated=function(a,b){a&&0<a.length&&(this.m_cwePredictionEngine.getTopics(!0),this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[],this.__displayTopics());dji.ui.modalDlg.hideDlg()};
CWEPredictionOptions.prototype.__isEnglish=function(){return"US"===this.m_localeLang||"UK"===this.m_localeLang||"CAN"===this.m_localeLang||"BE"===this.m_localeLang};
CWEPredictionOptions.prototype.__topicSearchFinished=function(a,b){a&&0<a.length?(b?this.m_localTopics.show():this.m_wikiTopics.show(),this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-show-search-result").addClass("dji-cwu-reset")):b?this.m_localTopics.hide():this.m_wikiTopics.hide();b?(this.m_localTopics.empty(),this.m_localTopicsList=a||[]):(this.m_wikiTopics.empty(),this.m_wikiTopicsList=a||[]);if(a){0<this.m_localTopicsList.length?this.m_wikiTopics.addClass("dji-cwu-top-border"):
this.m_wikiTopics.removeClass("dji-cwu-top-border");b=b?this.m_localTopics:this.m_wikiTopics;for(let d=0;d<a.length;d++)b.append(jQuery("<div/>",{"class":"dji-cwu-topic-item",text:a[d],"dji-cwu-topic-index":d}))}else(0<this.m_wikiTopicsList.length||0<this.m_localTopicsList.length)&&this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus")};
CWEPredictionOptions.prototype.__localTopicSelected=function(a){this.m_cweBackgroundManager.sendGA4Event("TopicSearchEngaged",{topic_name:this.m_localTopicsList[a]},null);this.__clearSearch();this.__topicIsActive(this.m_localTopicsList[a],!1)||(this.m_activeTopicsList.length<this.m_maxDisplayedTopics?(dji.ui.modalDlg.showMessageDlg("dji-cwu-activating-topic-message"),this.m_cwePredictionEngine.activateTopic(this.m_localTopicsList[a])):dji.ui.modalDlg.showModalDlg("dji-cwu-topic-active-limit"))};
CWEPredictionOptions.prototype.__wikiTopicSelected=function(a){this.m_cweBackgroundManager.sendGA4Event("TopicSearchEngaged",{topic_name:this.m_wikiTopicsList[a]},null);this.__clearSearch();if(!this.m_cweBackgroundManager.isBusy()){this.m_selectedWikiTopicIndex=a;var b=this.__topicExists(this.m_wikiTopicsList[a]);if(this.m_maxDisplayedTopics<=this.m_activeTopicsList.length&&!this.__topicIsActive(this.m_wikiTopicsList[a],!0)){let d=this,c=function(g){g(!0);dji.ui.modalDlg.hideDlg();d.createTopic(d.m_wikiTopicsList[a],
b,!1)};b?dji.ui.modalDlg.showModalDlg("dji-cwu-topic-update",{doneCallback:c}):dji.ui.modalDlg.showModalDlg("dji-cwu-topic-create",{doneCallback:c})}else this.createTopic(this.m_wikiTopicsList[a],b,!0)}};CWEPredictionOptions.prototype.createTopic=async function(a,b,d){this.m_cweBackgroundManager.updateTopicAsync(-1,{name:a,local:!1,userData:{action:b?"update":"create",activate:d,initiator:"options"}})};
CWEPredictionOptions.prototype.__buildDisplayTopicsList=function(){this.m_displayTopicList=this.m_cweBackgroundManager.displayTopics();this.m_displayTopicsMap={};let a=this.m_displayTopicList.length;for(let b=0;b<a;b++){let d=this.m_displayTopicList[b];this.m_displayTopicsMap[d.name]=d}};
CWEPredictionOptions.prototype.__displayTopics=function(){this.__buildDisplayTopicsList();this.m_activeTopics.empty();for(let a=0;a<this.m_displayTopicList.length;a++){let b=this.m_displayTopicList[a],d=$(dji.templates.clone("dji-cwu-option-topic-dictionary"));d.find(".dji-cwu-option-item-label").text(b.name);d.find(".dji-cwu-switch-container").attr("dji-cwu-topic-dictionary-id",a);b.active&&d.find(".dji-cwu-switch-container").addClass("dji-cwu-on");d[0].topicIndex=a;this.m_activeTopics.append(d)}};
CWEPredictionOptions.prototype.__findUITopicIndex=function(a){for(let b=0;b<this.m_displayTopicList.length;b++)if(this.m_displayTopicList[b].name===a)return b;return-1};CWEPredictionOptions.prototype.__findUIElementWithTopicIndex=function(a){let b=this.m_activeTopics.children();for(let d=0;d<b.length;d++){let c=b[d];if(c.topicIndex===a)return c}return null};
CWEPredictionOptions.prototype.__updateTopicUIState=function(a,b){let d=this.__findUITopicIndex(a);if(-1===d)return!1;this.m_displayTopicList[d].active=b;this.m_displayTopicsMap[a].active=b;a=this.__findUIElementWithTopicIndex(d);if(null===a)return!1;b?$(a).find(".dji-cwu-switch-container").addClass("dji-cwu-on"):$(a).find(".dji-cwu-switch-container").removeClass("dji-cwu-on");return!0};
CWEPredictionOptions.prototype.__clearSearch=function(){this.m_lastSearchText="";this.m_topicsSearch.val("");$("body").removeClass("dji-cwu-search");this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-default").removeClass("dji-cwu-reset")};CWEPredictionOptions.prototype.__topicExists=function(a){a=this.m_cwePredictionEngine.topicNameToDisplayName(a);for(let b=0;b<this.m_allLocalTopicsList.length;b++)if(this.m_allLocalTopicsList[b]===a)return!0;return!1};
CWEPredictionOptions.prototype.__topicIsActive=function(a,b){b&&(a=this.m_cwePredictionEngine.topicNameToDisplayName(a));return-1!==this.__activeTopicIndex(a)};CWEPredictionOptions.prototype.__activeTopicIndex=function(a){for(let b=0;b<this.m_activeTopicsList.length;b++)if(this.m_activeTopicsList[b]===a)return b;return-1};CWEPredictionOptions.prototype.__changeAsNeededOption=function(a,b){this.m_cweSettings.asNeeded(a)};
