window.dji=window.dji||{};
(function(){function h(a){dji.ui.dropdown.showPopup(a.currentTarget,{alignTop:!0,alignRight:!0})}function u(a){a.stopPropagation();a.preventDefault();dji.ui.dropdown.hidePopup();dji.account.showConnectToEducatorModalDlg()}function k(a){a.stopPropagation();a.preventDefault();dji.ui.dropdown.hidePopup();a=e.dji.config.cowriterUrl()+"/change-password?redirect_uri="+chrome.runtime.getURL("go.html");window.location=a}function g(a){a.stopPropagation();a.preventDefault();dji.ui.dropdown.hidePopup();dji.ui.modalDlg.showMessageDlg("dji-cwu-signing-out");
d.signOut(function(c){c?(d.sendGA4Event("SignedOut",null,null),window.close()):dji.ui.modalDlg.hideDlg()})}function m(a){a.currentTarget.hasAttribute("disabled")||($(a.currentTarget).hasClass("dji-cwu-option-dropdown-item")||$(a.currentTarget).hasClass("dji-cwu-dropdown"))&&dji.ui.dropdown.showPopup(a.currentTarget)}function G(a){if(!a.currentTarget.hasAttribute("disabled")){var c=$(a.target);c.hasClass("dji-cwu-color-picker-value")&&(c=c.hasClass("dji-cwu-hide-color-templates"),dji.ui.colorPicker.showPopup(a.currentTarget,
c))}}function H(a){if(!a.currentTarget.hasAttribute("disabled")){$(a.currentTarget).toggleClass("dji-cwu-on");var c=$(a.currentTarget).hasClass("dji-cwu-on");$(a.currentTarget).trigger({type:"change",checked:c})}}function I(a){if(!this.hasAttribute("dji-cwu-not-available")){let c=$(a.currentTarget).find(".dji-cwu-menu-item-text").text(),f=$(a.currentTarget).closest(".dji-cwu-option-dropdown-item");f.find(".dji-cwu-option-item-value").text(c);f.trigger({type:"change",value:$(a.currentTarget).attr("dji-cwu-value"),
text:c})}dji.ui.dropdown.hidePopup();a.stopPropagation();a.preventDefault()}function v(a){let c=a.currentTarget.style.backgroundColor;a.preventDefault();a.stopPropagation();$(a.currentTarget).closest(".dji-cwu-color-picker-value").trigger({type:"change",color:c})}function x(a){let c=a.currentTarget.style.backgroundColor,f=a.currentTarget.style.color;a.preventDefault();a.stopPropagation();$("body").trigger({type:"dji-cwu-change-colors",color:f,backgroundColor:c})}function w(a){$(a.currentTarget).parent().find(".dji-cwu-tab-button.dji-cwu-selected").removeClass("dji-cwu-selected");
$(a.currentTarget).addClass("dji-cwu-selected");$(a.currentTarget).closest(".dji-cwu-color-popup").attr("dji-cwu-view-mode",$(a.currentTarget).attr("dji-cwu-item"));a.preventDefault();a.stopPropagation()}function C(){$("#dji-cwu-user-name").on("click","#dji-cwu-connect-with-educator",u).on("click","#dji-cwu-change-user-password",k).on("click","#dji-cwu-sign-out",g).on("click",h);$(".dji-cwu-option-color-picker-value").on("click",".dji-cwu-color-item",v).on("click",".dji-cwu-color-template",x).on("click",
".dji-cwu-colors-tab-items .dji-cwu-tab-button",w);$(".dji-cwu-color-picker-value").on("click",G);$(".dji-cwu-menu-item-text").mouseover(function(){$(this).css("background-color","red")});$(".dji-cwu-option-dropdown-item").on("click",".dji-cwu-menu-item",I).on("click",m);$(".dji-cwu-options-view").on("click",".dji-cwu-switch-container",H)}function z(){dji.account.initialize(d);let a=d.userInfo();a&&a.anonymous&&($("#dji-cwu-connect-with-educator").remove(),$("#dji-cwu-change-user-password").remove());
C();chrome.runtime.onMessage.addListener(D);dji.ui.modalDlg.hideDlg();$("body").removeClass("dji-cwu-not-ready");A()}function y(a){let c=p&&!p.isInitialized();d&&d.isLoaded()&&d.isLoggedIn()?c&&(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-loading-message"),d&&"--options-language-change"===d.restartReason()&&1===a&&(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-change-language-wait-message"))):(e||(e=chrome.extension.getBackgroundPage()),d=e&&e.CWEBackgroundManagerInstance?
e.CWEBackgroundManagerInstance():null,1===a&&(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-loading-message"),d&&"--options-language-change"===d.restartReason()&&(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("cwu_change_language_wait_message"))),d&&(q=e.CWESettingsInstance(),l=e.dji.tts,b=(p=e.CWEPredictionEngine)?p.instance:null,c=p&&!p.isInitialized(),d.isLoaded()&&!d.isLoggedIn()?(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-please-sign-in-message")):
d.localeRequiresReboot()&&(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-language-has-been-changed-message"))),a++);d&&d.isLoaded()&&d.isLoggedIn()?1<a&&!c?window.location.reload():c?setTimeout(function(){d.__initializePredictionEngine(function(f,B){f?setTimeout(z,3E3):B?Logger.instance.error("*** Failed to initialize Prediction Engine!"):(Logger.instance.log("*** Prediction Engine initialization is already in progress!"),setTimeout(y,500,a+1))})},2E3):z():setTimeout(y,500,a+1)}
async function E(){e.dji.speechRecognition.stop();d.translateHtmlDocument(document);dji.templates.cache();Logger.initialize();Logger.instance.log(q);Logger.instance.log(l);Logger.instance.log(b);await dji.ui.templatesRegistry.cache("/ContentScripts/ui/cweMainViewTemplates.html","default",!0);await window.cweMainView.initialize(document.getElementById("dji-cwu-ime-sample"),!0);window.cweMainView.suggestionsCount=5;window.cweMainView.setSuggestions(["Samples","Samplers","Sampling","Simply","Sampler"]);
window.cweMainView.show(!0);CWESpeechOptions.instance=new CWESpeechOptions(q,l,d);Logger.instance.log(CWESpeechOptions.instance);CWETextOptions.instance=new CWETextOptions(q,d);Logger.instance.log(CWETextOptions.instance);CWEPredictionOptions.instance=new CWEPredictionOptions(q,b,d,e);Logger.instance.log(CWEPredictionOptions.instance);e||(e=chrome.extension.getBackgroundPage());if(d){var a=e.dji.config.cowriterUrl();$("a[dji-cowriter-url]").attr("href",a);$("a[dji-cowriter-privacy-policy-url]").attr("href",
a+"/privacy-policy");$("a[dji-cowriter-tos-url]").attr("href",a+"/tos")}a=$("#dji-cwu-main-overlay");dji.ui.colorPicker.init(a);a=$("#dji-cwu-main-overlay");dji.ui.dropdown.init(a);a=$("#dji-cwu-modal-dlg-overlay");dji.ui.modalDlg.init(a);dji.ui.toast.init();y(1)}function D(a){let c=!1;switch(a.reason){case "load":case "initialize_nacl_started":case "initialize_nacl_finished":case "update_topic_finished":case "update_topic_started":case "busy_started":case "busy_finished":c=!0}c&&A(a.details)}function A(a){const c=
!(d&&!d.isBusy());let f=$("input").filter(function(){return!$(this).prop("dji-not-allowed")});c?(f.prop("disabled",!0),a&&a.userData&&a.userData.action?"update"===a.userData.action?(document.body.classList.remove("dji-cwu-working"),dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-updating-topic-message")):"create"===a.userData.action?(document.body.classList.remove("dji-cwu-working"),dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showMessageDlg("dji-cwu-creating-topic-message")):document.body.classList.add("dji-cwu-working"):
document.body.classList.add("dji-cwu-working")):(a&&a.userData&&a.userData.action&&dji.ui.modalDlg.hideDlg(),document.body.classList.remove("dji-cwu-working"),f.prop("disabled",!1))}let e=chrome.extension.getBackgroundPage(),d=e&&e.CWEBackgroundManagerInstance?e.CWEBackgroundManagerInstance():null,q=d?e.CWESettingsInstance():null,l=e?e.dji.tts:null,p=d?e.CWEPredictionEngine:null,b=p?p.instance:null;window.cweMainView=new DjiCwuMainView;$(document).ready(function(){$("body").addClass("dji-cwu-not-ready");
E()})})();
(function(){function h(){var b=C.value.trim();let a=z.value.trim(),c=y.value.trim(),f=E.value.trim(),B=A.value.trim(),F=e.value.trim(),r=d.value.trim().split("\n");for(var n=0;n<r.length;n++)r[n]=r[n].trim(),0===r[n].length&&(r.splice(n,1),n--);if(0!==b.length&&0!==a.length&&0!==c.length&&0!==f.length&&0!==r.length){n={disablePrimaryRenderer:D.checked};var t=g(b);t?(t.login=a,t.dapi=c,t.tts=f,t.resources=B,t.cowriter=F,t.relatedUris=r,t.gdocsConfig=n):l.push({name:b,login:a,dapi:c,tts:f,resources:B,
cowriter:F,relatedUris:r,gdocsConfig:n});q=b;x.style.display="none";b={configName:q,configs:l};b=JSON.stringify(b);p.writeFile("env.config",b,function(){chrome.runtime.reload()})}}function u(){x.style.display="none"}function k(){let b=l[w.selectedIndex];C.value=b.name;z.value=b.login;y.value=b.dapi;E.value=b.tts;A.value=b.resources;e.value=b.cowriter;d.value=b.relatedUris.join("\n");D.checked=b.gdocsConfig?.disablePrimaryRenderer}function g(b){for(let a=0;a<l.length;a++){let c=l[a];if(c.name===b)return c}return null}
function m(){if(!x){var b=Date.now(),a="__dapi-0-"+b,c="__dapi-1-"+b,f="__dapi-2-"+b;const B="__dapi-3-"+b,F="__dapi-4-"+b,r="__dapi-5-"+b,n="__dapi-6-"+b,t="__dapi-7-"+b,K="__dapi-8-"+b,J="__dapi-9-"+b,L="__dapi-10-"+b,M="__dapi-100-"+b,N="__dapi-101-"+b,O="__dapi-800-"+b;b=('<div id="#0" style="display:none;position:fixed;top:0;left:0;bottom:0;right:0;background-color:rgba(100,0,0,0.8);cursor:default;z-index:1100000010;"><style>table.opt-'+b+" input, table.opt-"+b+' textarea {font-family: monospace;font-size: 12px;}</style><div style="margin:50px auto;width:500px;background-color:#FFFFFF;padding:20px;"><h2>Login &amp; D:API settings (<i>you better logout first</i>)</h2><table style="width:100%;margin-top:2px;font-size:14px;" class="opt-'+
b+'"><tr><td style="width:80px;">Predefined:</td><td><select id="#1" style="width:100%"></select></td></tr><tr><td colspan="2" align="right"><hr/></td></tr><tr><td>Name*:</td><td><input id="#2" type="text" style="width:100%;"/></td></tr><tr><td>Login URL*:</td><td><input id="#3" type="text" style="width:100%;"/></td></tr><tr><td style="width:100px;">D:API URL*:</td><td><input id="#4" type="text" style="width:100%;"/></td></tr><tr><td style="width:100px;">TTS URL*:</td><td><input id="#8" type="text" style="width:100%;"/></td></tr><tr><td style="width:100px;">Res URL*:</td><td><input id="#5" type="text" style="width:100%;"/></td></tr><tr><td style="width:100px;">Co:Writer URL*:</td><td><input id="#7" type="text" style="width:100%;"/></td></tr><tr><td valign="top" style="width:100px;">Related URL*:</td><td><textarea id="#6" style="width:100%;height: 60px;"></textarea></td></tr><tr><td colspan="2" align="right"><hr/></td></tr><tr><td valign="top" style="width:100px;">Google docs:</td><td><input type="checkbox" id="#9" name="#9"/><label id="#10" for="#9" valign="top"> Disable primary renderer</label><br></td></tr><tr><td colspan="2" style="text-align:right;padding-top:10px;">When you press OK, the extension will be reloaded to apply the new settings.</td></tr><tr><td style="text-align:left;padding-top:10px;"><button id="#800">Reload Extension</button></td><td style="text-align:right;padding-top:10px;"><button id="#100">OK</button>&nbsp;<button id="#101">Cancel</button></td></tr></div></div>').replace("#0",
a).replace("#1",c).replace("#2",f).replace("#3",B).replace("#4",F).replace("#5",r).replace("#6",n).replace("#7",t).replace("#8",K).replace("#9",J).replace("#10",L).replace("#100",M).replace("#101",N).replace("#800",O);document.body.insertAdjacentHTML("beforeend",b);x=document.getElementById(a);w=document.getElementById(c);C=document.getElementById(f);z=document.getElementById(B);y=document.getElementById(F);A=document.getElementById(r);d=document.getElementById(n);e=document.getElementById(t);E=document.getElementById(K);
D=document.getElementById(J);w.addEventListener("change",k);document.getElementById(J).addEventListener("change",function(){document.getElementById(L).style.color=this.checked?"red":"black"});document.getElementById(M).addEventListener("click",h);document.getElementById(N).addEventListener("click",u);document.getElementById(O).addEventListener("click",()=>chrome.runtime.reload())}if("block"!==x.style.display){for(a=null;a=w.lastChild;)w.removeChild(a);for(a=0;a<l.length;a++)c=l[a],f=document.createElement("option"),
f.innerText=c.name,w.appendChild(f),c.name===q&&(w.selectedIndex=a);if(a=g(q))C.value=a.name,z.value=a.login,y.value=a.dapi,E.value=a.tts,A.value=a.resources,e.value=a.cowriter,d.value=a.relatedUris.join("\n"),D.checked=a.gdocsConfig?.disablePrimaryRenderer;x.style.display="block"}}function G(){let b="";document.addEventListener("keydown",function(a){if(!a.repeat){var c=!1;!a.altKey||a.ctrlKey||a.shiftKey||a.metaKey?0<b.length&&(b=""):(a=String.fromCharCode(a.keyCode),32<=a.charCodeAt(0)&&(0===b.length||
b.charAt(b.length-1)!==a)&&(b+=a,c=!0));c&&"QSX"===b&&(b="",m())}},!0);document.addEventListener("keyup",function(a){!a.altKey&&0<b.length&&(b="")},!0)}function H(b){p.readFile("env.config",function(a){if(a)try{let c=JSON.parse(a);q=c.configName;l=c.configs}catch(c){Logger.instance.error(c)}0===l.length&&(l=v.dji.config.allEnvs(),q=v.dji.config.env().name);b()})}function I(){v||(v=chrome.extension.getBackgroundPage());(v&&v.CWEBackgroundManagerInstance?v.CWEBackgroundManagerInstance():null).requestFileSystem(function(b){p=
b;H(G)})}let v=chrome.extension.getBackgroundPage(),x=null,w=null,C=null,z=null,y=null,E=null,D=null,A=null,e=null,d=null,q=null,l=[],p=null;$(document).ready(function(){I()})})();
(function(){let h=null,u=null;$(document).ready(function(){let k="";document.addEventListener("keydown",function(g){if(!g.repeat){var m=!1;!g.altKey||g.ctrlKey||g.shiftKey||g.metaKey?0<k.length&&(k=""):(g=String.fromCharCode(g.keyCode),32<=g.charCodeAt(0)&&(0===k.length||k.charAt(k.length-1)!==g)&&(k+=g,m=!0));m&&"LOG"===k&&(k="",m=chrome.extension.getBackgroundPage(),m=new Blob([m.Logger.instance.dump()],{type:"application/octet-stream"}),m=URL.createObjectURL(m),h||(h=document.createElement("iframe"),
h.style.position="absolute",h.style.top="-5000px",h.style.left="-5000px",h.style.width="0",h.style.height="0",h.style.overlay="hidden",h.style.display="none",document.body.append(h),u=h.contentDocument.createElement("a"),h.contentDocument.body.append(u)),u.href=m,u.download=`cowriter-extension-${Date.now()}.log`,u.click(),URL.revokeObjectURL(m))}},!0);document.addEventListener("keyup",function(g){!g.altKey&&0<k.length&&(k="")},!0)})})();
