function DjiHtml5FileSystem(){this.m_fileSystem=null;return this}DjiHtml5FileSystem.instance=null;DjiHtml5FileSystem.initialize=function(a){if(null===DjiHtml5FileSystem.instance){DjiHtml5FileSystem.instance=new DjiHtml5FileSystem;try{DjiHtml5FileSystem.instance.__initialize(function(b){DjiHtml5FileSystem.instance=b;a&&a(b)})}catch(b){DjiHtml5FileSystem.instance=null,Logger.instance.error(b)}}};
DjiHtml5FileSystem.prototype.__initialize=function(a){var b=this;navigator.webkitPersistentStorage.requestQuota(524288E3,function(d){Logger.instance.log("Quota granted: ",d);window.webkitRequestFileSystem(window.PERSISTENT,d,function(c){b.m_fileSystem=c;Logger.instance.log("fileSystem: ",c);setTimeout(function(){b.__callback(a,b)},10)},function(c){Logger.instance.error(c);b.__callback(a,null)})},function(d){Logger.instance.error(d);b.__callback(a,null)})};
DjiHtml5FileSystem.prototype.getDirectory=function(a,b,d){var c=this;this.m_fileSystem.root.getDirectory(a,{create:b},function(e){c.__callback(d,e)},function(e){Logger.instance.groupCollapsed("getDirectory failed for file: "+a);Logger.instance.error(e);Logger.instance.groupEnd();c.__callback(d,null)})};DjiHtml5FileSystem.prototype.getDirectoryAsync=function(a,b){var d=this;return new Promise(function(c,e){d.m_fileSystem.root.getDirectory(a,{create:b},c,e)})};
DjiHtml5FileSystem.prototype.getFile=function(a,b,d){var c=this;this.m_fileSystem.root.getFile(a,{create:b},function(e){c.__callback(d,e)},function(e){Logger.instance.groupCollapsed("getFile failed for file: "+a);Logger.instance.error(e);Logger.instance.groupEnd();c.__callback(d,null)})};DjiHtml5FileSystem.prototype.directoryExistsAsync=function(a){return new Promise(b=>this.directoryExists(a,b))};
DjiHtml5FileSystem.prototype.directoryExists=function(a,b){this.m_fileSystem.root.getDirectory(a,{create:!1},function(){b(!0)},function(){b(!1)})};DjiHtml5FileSystem.prototype.fileExistsAsync=function(a){return new Promise(b=>this.fileExists(a,b))};DjiHtml5FileSystem.prototype.fileExists=function(a,b){this.m_fileSystem.root.getFile(a,{create:!1},function(){b(!0)},function(){b(!1)})};
DjiHtml5FileSystem.prototype.createDirectoryAsync=function(a){return new Promise((b,d)=>{this.createDirectory(a,c=>{if(c)return b(c);d()})})};
DjiHtml5FileSystem.prototype.createDirectory=function(a,b){var d=this,c=this.__splitPath(a);if(!c||0>=c.length)d.__callback(b,null);else{var e=this.m_fileSystem.root,f=-1,g=function(){f++;f<c.length?e.getDirectory(c[f],{create:!0},function(k){e=k;f+1<c.length?g():d.__callback(b,e)},function(k){Logger.instance.error(k);d.__callback(b,null)}):d.__callback(b,e)};g()}};
DjiHtml5FileSystem.prototype.createDirectories=function(a,b){var d=this;if(!a||0>=a.length)d.__callback(b,null);else{var c=-1,e=function(){c++;if(c<a.length){var f=a[c];d.directoryExists(f,function(g){g?(Logger.instance.log("directory already exists"),c+1<a.length?e():d.__callback(b)):d.createDirectory(f,function(){c+1<a.length?e():d.__callback(b)})})}else d.__callback(b)};e()}};
DjiHtml5FileSystem.prototype.writeFileAsync=function(a,b){return new Promise((d,c)=>{this.writeFile(a,b,(e,f,g)=>{if(e)return d(f);c(g)})})};
DjiHtml5FileSystem.prototype.writeFile=function(a,b,d){var c=this;this.m_fileSystem.root.getFile(a,{create:!0},function(e){e.createWriter(function(f){var g=function(){c.__callback(d,!0,e)},k=function(h){Logger.instance.error(h);c.__callback(d,!1,null,h)};f.onwriteend=function(){f.onwriteend=g;f.onerror=k;var h=b instanceof Blob?b:new Blob([b],{type:"application/octet-stream"});f.write(h)};f.onerror=function(h){Logger.instance.error(h);c.__callback(d,!1,null,h)};f.truncate(0)},function(f){Logger.instance.error(f);
c.__callback(d,!1,null,f)})},function(e){Logger.instance.error("error getting file:",a,"error:",e);c.__callback(d,!1,null,e)})};DjiHtml5FileSystem.prototype.writeFileAsTextAsync=function(a,b){return new Promise((d,c)=>{this.writeFileAsText(a,b,(e,f,g)=>{if(e)return d(f);c(g)})})};
DjiHtml5FileSystem.prototype.writeFileAsText=function(a,b,d){var c=this;this.m_fileSystem.root.getFile(a,{create:!0},function(e){e.createWriter(function(f){var g=function(){c.__callback(d,!0,e)},k=function(h){Logger.instance.error(h);c.__callback(d,!1,null,h)};f.onwriteend=function(){f.onwriteend=g;f.onerror=k;var h=b instanceof Blob?b:new Blob([b],{type:"text/plain;charset=UTF-8"});f.write(h)};f.onerror=function(h){Logger.instance.error(h);c.__callback(d,!1,null,h)};f.truncate(0)},function(f){Logger.instance.error(f);
c.__callback(d,!1,null,f)})},function(e){Logger.instance.error("error getting file:",a,"error:",e);c.__callback(d,!1,null,e)})};DjiHtml5FileSystem.prototype.writeFiles=function(a,b,d){var c=this;0!=a.length&&0!=b.length||c.__callback(d);var e=-1,f=function(){e++;e<a.length?c.writeFile(a[e],b[e],function(){f()}):c.__callback(d)};f()};
DjiHtml5FileSystem.prototype.readFile=function(a,b){var d=this;this.m_fileSystem.root.getFile(a,{},function(c){c.file(function(e){var f=new FileReader;f.onloadend=function(){d.__callback(b,this.result,c)};f.onerror=function(g){Logger.instance.error(g);d.__callback(b,null,null)};f.readAsBinaryString(e)},function(e){Logger.instance.error(e);d.__callback(b,null,null)})},function(c){"NotFoundError"!==c.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(c),Logger.instance.groupEnd());
d.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsBinaryString=function(a,b){var d=this;this.m_fileSystem.root.getFile(a,{},function(c){c.file(function(e){var f=new FileReader;f.onloadend=function(){d.__callback(b,this.result,c)};f.onerror=function(g){Logger.instance.error(g);d.__callback(b,null,null)};f.readAsBinaryString(e)},function(e){Logger.instance.error(e);d.__callback(b,null,null)})},function(c){"NotFoundError"!==c.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(c),
Logger.instance.groupEnd());d.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsArrayBuffer=function(a,b){var d=this;this.m_fileSystem.root.getFile(a,{},function(c){c.file(function(e){var f=new FileReader;f.onloadend=function(){d.__callback(b,this.result,c)};f.onerror=function(g){Logger.instance.error(g);d.__callback(b,null,null)};f.readAsArrayBuffer(e)},function(e){Logger.instance.error(e);d.__callback(b,null,null)})},function(c){"NotFoundError"!==c.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(c),
Logger.instance.groupEnd());d.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsText=function(a,b){var d=this;this.m_fileSystem.root.getFile(a,{},function(c){c.file(function(e){var f=new FileReader;f.onloadend=function(){d.__callback(b,this.result,c)};f.onerror=function(g){Logger.instance.error(g);d.__callback(b,null,null)};f.readAsText(e)},function(e){Logger.instance.error(e);d.__callback(b,null,null)})},function(c){"NotFoundError"!==c.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(c),Logger.instance.groupEnd());
d.__callback(b,null,null)})};DjiHtml5FileSystem.prototype.readFileAsTextAsync=async function(a){return new Promise(b=>{this.readFileAsText(a,d=>{b(d)})})};DjiHtml5FileSystem.prototype.readFileAsJSONAsync=async function(a){return new Promise((b,d)=>{this.readFileAsText(a,c=>{if(null!==c)try{c=JSON.parse(c)}catch(e){d(e)}b(c)})})};
DjiHtml5FileSystem.prototype.removeDirectory=function(a,b){var d=this;this.m_fileSystem.root.getDirectory(a,{},function(c){c.removeRecursively(function(){d.__callback(b,!0)},function(e){Logger.instance.error(e);d.__callback(b,!1)})},function(c){"NotFoundError"!==c.name&&Logger.instance.error(c);d.__callback(b,"NotFoundError"===c.name)})};
DjiHtml5FileSystem.prototype.removeDirectoryAsync=async function(a){let b=this;return new Promise(function(d){b.m_fileSystem.root.getDirectory(a,{},function(c){c.removeRecursively(function(){d(!0)},function(e){Logger.instance.error(e);d(!1)})},function(c){"NotFoundError"!==c.name&&Logger.instance.error(c);d("NotFoundError"===c.name)})})};DjiHtml5FileSystem.prototype.removeDirectoryContents=function(a,b){var d=this;d.removeDirectory(a,function(){d.createDirectory(a,function(c){d.__callback(b)})})};
DjiHtml5FileSystem.prototype.removeFile=function(a,b){var d=this;this.m_fileSystem.root.getFile(a,{},function(c){c.remove(function(){d.__callback(b,!0)},function(e){Logger.instance.error(e);d.__callback(b,!1)})},function(c){"NotFoundError"!==c.name&&Logger.instance.error(c);d.__callback(b,"NotFoundError"===c.name)})};
DjiHtml5FileSystem.prototype.removeFiles=function(a,b){if(!a||0>=a.length)this.__callback(b);else{var d=this,c=-1,e=function(){c++;c<a.length?d.removeFile(a[c],function(){setTimeout(e,0)}):d.__callback(b)};e()}};
DjiHtml5FileSystem.prototype.emptyDirectory=function(a,b){var d=this;this.m_fileSystem.root.getDirectory(a,{},function(c){c.createReader().readEntries(function(e){0<e.length?d.__callback(b,!1):d.__callback(b,!0)},function(e){Logger.instance.error("error getEntries:",e);d.__callback(b)})},function(c){Logger.instance.error("error getDirectory:",c)})};
DjiHtml5FileSystem.prototype.listDirectory=function(a,b){let d=this;this.m_fileSystem.root.getDirectory(a,{},function(c){let e=c.createReader(),f=[],g=function(){e.readEntries(function(k){0>=k.length?d.__callback(b,f):(f=f.concat(Array.prototype.slice.call(k,0)),g())},function(k){Logger.instance.error("error readEntries:",k);d.__callback(b,[])})};g()},function(c){"NotFoundError"!==c.name&&Logger.instance.error("error getDirectory:",c);d.__callback(b,[])})};
DjiHtml5FileSystem.prototype.listDirectoryAsync=async function(a){let b=this;return new Promise(function(d){b.m_fileSystem.root.getDirectory(a,{},function(c){let e=c.createReader(),f=[],g=function(){e.readEntries(function(k){0>=k.length?d(f):(f=f.concat(Array.prototype.slice.call(k,0)),g())},function(k){Logger.instance.error("error readEntries:",k);d([])})};g()},function(c){"NotFoundError"!==c.name&&Logger.instance.error("error getDirectory:",c);d([])})})};
DjiHtml5FileSystem.prototype.__splitPath=function(a){if(!a||0>=a.length)return null;a=a.split("/");for(var b=[],d=0;d<a.length;d++)0<a[d].length&&b.push(a[d]);return b};DjiHtml5FileSystem.prototype.__callback=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}};
(function(){FileReader.prototype.readWithMethod=function(a,b,d,c){if(!(this[b]instanceof Function))throw Error(`${b} is not a function of FileReader!`);const e=this.onloadend,f=this.onerror;this.onloadend=function(){this.onloadend=e;this.onerror=f;d(this.result)};this.onerror=function(g){this.onloadend=e;this.onerror=f;c(g)};this[b](a)};FileReader.prototype.readAsTextEx=function(a,b,d){const c=this.onloadend,e=this.onerror;this.onloadend=function(){this.onloadend=c;this.onerror=e;b(this.result)};
this.onerror=function(f){this.onloadend=c;this.onerror=e;d(f)};this.readAsText(a)};FileReader.prototype.readAsTextAsync=async function(a){const b=this;return new Promise(function(d,c){b.readAsTextEx(a,d,c)})};FileReader.prototype.readWithMethodAsync=async function(a,b){if(!(this[b]instanceof Function))throw Error(`${b} is not a function of FileReader!`);const d=this;return new Promise(function(c,e){d.readWithMethod(a,b,c,e)})}})();
class DjiFileSystemBaseEntryProxy{constructor(a){this.m_entry=a}get name(){return this.m_entry.name}get fullPath(){return this.m_entry.fullPath}get isDirectory(){return this.m_entry.isDirectory}get isFile(){return this.m_entry.isFile}get filesystem(){return this.m_entry.filesystem}get entry(){return this.m_entry}async copyToAsync(a,b){const d=this;return new Promise(function(c,e){a instanceof DjiFileSystemBaseEntryProxy&&(a=a.entry);d.entry.copyTo(a,b,function(f){f.isDirectory?c(new DjiFileSystemDirectoryEntryProxy(f)):
c(new DjiFileSystemFileEntryProxy(f))},e)})}}
class DjiFileSystemDirectoryEntryProxy extends DjiFileSystemBaseEntryProxy{static async getPackageDirectoryEntryAsync(){return new Promise(a=>chrome.runtime.getPackageDirectoryEntry(b=>a(new DjiFileSystemDirectoryEntryProxy(b))))}async getDirectoryAsync(a,b){const d=this;return new Promise(function(c,e){(a.startsWith("/")?d.filesystem.root:d.entry).getDirectory(a,{create:!0===b},function(f){c(new DjiFileSystemDirectoryEntryProxy(f))},e)})}async getFileAsync(a,b){const d=this;b=!!b;return new Promise(function(c,
e){(a.startsWith("/")?d.filesystem.root:d.entry).getFile(a,{create:b},function(f){c(new DjiFileSystemFileEntryProxy(f))},e)})}async fileAsync(a){return(await this.getFileAsync(a)).fileAsync()}async readAsArrayBufferAsync(a){return(await this.getFileAsync(a)).readAsArrayBufferAsync()}async readAsBinaryStringAsync(a){return(await this.getFileAsync(a)).readAsBinaryStringAsync()}async readFileAsTextAsync(a){return(await this.getFileAsync(a)).readAsTextAsync()}async readFileAsJSONAsync(a){a=await (await this.getFileAsync(a)).readAsTextAsync();
null!==a&&void 0!==a&&(a=JSON.parse(a));return a}async writeFileAsTextAsync(a,b){return(await this.getFileAsync(a,!0)).writeAsTextAsync(b)}async writeFileAsJSONAsync(a,b){b=JSON.stringify(b);return(await this.getFileAsync(a,!0)).writeAsTextAsync(b)}async listDirectoryAsync(a,b){const d=this;a=!(!a&&void 0!==a);b=!(!b&&void 0!==b);return new Promise(function(c,e){let f=d.entry.createReader(),g=[],k=function(){f.readEntries(function(h){if(0>=h.length)return c(g);if(a&&b)g.push(...h);else for(let l=
0;l<h.length;l++)a&&h[l].isDirectory&&g.push(h[l]),b&&h[l].isFile&&g.push(h[l]);k()},function(h){e(h)})};k()})}}
class DjiFileSystemFileEntryProxy extends DjiFileSystemBaseEntryProxy{async fileAsync(){const a=this;return new Promise((b,d)=>a.entry.file(b,d))}async readAsArrayBufferAsync(){const a=this;return new Promise(function(b,d){a.entry.file(function(c){(new FileReader).readAsArrayBuffer(c,b,d)},d)})}async readAsBinaryStringAsync(){const a=this;return new Promise(function(b,d){a.entry.file(function(c){(new FileReader).readWithMethod(c,"readAsBinaryString",b,d)},d)})}async readAsTextAsync(){const a=this;
return new Promise(function(b,d){a.entry.file(function(c){(new FileReader).readAsTextEx(c,b,d)},d)})}async writeAsTextAsync(a){return this.writeAsync(a,"text/plain;charset=UTF-8")}async writeAsync(a,b){const d=this;return new Promise(function(c,e){d.entry.createWriter(function(f){f.onerror=e;f.onwriteend=function(){const g=a instanceof Blob?a:new Blob([a],{type:b||"application/octet-stream"});this.onwriteend=c;this.write(g)};f.truncate(0)},e)})}async truncateAsync(a){}};
