window.dji=window.dji||{};
window.dji.accessibility=function(){function r(a){return(a=a.match(y))&&2<=a.length?a[1]:void 0}function t(){let a=[];CWEChromeUtilities.findValidIframeElements(void 0,a,!0);for(let b=0;b<a.length;b++){let c=a[b];try{c.removeEventListener("load",q)}catch(d){}q.apply(c);c.addEventListener("load",q)}}function q(){CWEChromeUtilities.validateIframe(this,!0)&&u(this.contentWindow)}function u(a){a.addEventListener("keydown",z,!0);a.addEventListener("keyup",A,!0);a.addEventListener("mousedown",B,!0)}function z(a){p&&
(!a.altKey||a.ctrlKey&&32!==a.which||a.shiftKey||a.metaKey?h=e.None:(37===a.which?h=e.Previous:39===a.which?h=e.Next:13===a.which?h=e.Enter:32===a.which&&a.ctrlKey?h=e.Select:27===a.which?h=e.Escape:88===a.which?h=e.ContextMenu:"Alt"!==a.key&&(h=e.None),h!==e.None&&(a.stopPropagation(),a.preventDefault())))}function A(a){if(p&&h!==e.None){let b=h;h=e.None;a.stopPropagation();a.preventDefault();b!==e.Ignore&&(b===e.Previous?k.goPrevious():b===e.Next?k.goNext():b===e.Enter?k.enter():b===e.Select?k.select():
b===e.Escape?k.dismiss():b===e.ContextMenu&&k.contextMenu())}}function B(){k.enable(!1);k.enable(!0)}function C(a){if(0>=a.length)return a;let b={},c;var d;for(var g=0;g<a.length;g++)c=a[g].accessibilityIndex,(d=b.hasOwnProperty(c)?b[c]:null)||(d=b[c]=[]),d.push(a[g]);d=Object.keys(b).map(function(f){return parseInt(f)}).sort(function(f,l){return isNaN(f)||isNaN(l)?isNaN(f)?isNaN(l)?0:0>l?-1:1:0>=f?1:-1:0>f||0>l?0<f?-1:0<l?1:l-f:f-l});a=[];for(g=0;g<d.length;g++)c=d[g],isNaN(c)&&(c=void 0),a=a.concat(b[c]);
return a}function v(a){let b=(a?a.ownerDocument:document).activeElement;if(b&&a){for(var c=b;c&&c!==a;)c=c.parentElement;return c===a?b:null}return b}function D(a,b){if(!a)return!1;if(a.nodeType===Node.DOCUMENT_NODE)return!0;b=b||document;if(a.parentNode&&"HTML"===a.parentNode.tagName)return"BODY"===a.tagName;a.nodeType===Node.TEXT_NODE&&(a=a.parentElement);var c;for(c=!0;a&&c;){if(a.nodeType===Node.DOCUMENT_NODE||"BODY"===a.tagName||a===a.ownerDocument||a===a.ownerDocument.documentElement)return!0;
var d=b.defaultView.getComputedStyle(a,null);c=d.getPropertyValue("display");d=d.getPropertyValue("visibility");(c="none"!==c&&"hidden"!==d)&&(c=!(!a.offsetParent&&a.parentElement!==a.ownerDocument&&a.parentElement!==a.ownerDocument.documentElement));a=a.parentElement}return c}const e={Ignore:-1,None:0,Previous:200,Next:201,Enter:202,Select:203,ContextMenu:204,Escape:205};let k=void 0,p=!1,h=e.None;const y=/^{([^}]+)}$/;class w{constructor(a,b){this.m_domElem=a;this.m_parent=b;this.m_focused=!1;this.m_accessibilityIndex=
void 0;if(a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible"):void 0){try{a=parseInt(a)}catch(c){}a&&!isNaN(a)&&(this.m_accessibilityIndex=a)}}get domElement(){return this.m_domElem}get accessibilityIndex(){return this.m_accessibilityIndex}get isUsable(){return!D(this.m_domElem)||$(this.m_domElem).hasClass("dji-disable")?!1:!0}get isFocused(){return this.m_focused}get requiresStrongFocus(){let a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible-strong-focus"):void 0;return null!==
a&&void 0!==a}get requiresNoFocus(){let a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible-no-focus"):void 0;return null!==a&&void 0!==a}get requiresScrollIntoView(){let a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible-scroll-into-view"):void 0;return null!==a&&void 0!==a}focus(a){a=void 0===a||!0===a;this.m_focused=!0;$(this.m_domElem).addClass("dji-x-highlighted");a&&$(this.m_domElem).focus();(a||this.requiresScrollIntoView)&&this.m_domElem.scrollIntoView(!1);this.m_domElem.dispatchEvent(new CustomEvent("x-focus"))}blur(a){if(a=
void 0===a||!0===a){let b=v(this.m_domElem);b&&$(b).blur()}this.m_focused&&(this.m_focused=!1,a&&$(this.m_domElem).blur(),$(this.m_domElem).removeClass("dji-x-highlighted"),this.m_domElem.dispatchEvent(new CustomEvent("x-blur")))}enter(){this.m_domElem.dispatchEvent(new CustomEvent("x-enter"))}select(){this.m_domElem.dispatchEvent(new CustomEvent("x-select"))}contextMenu(){this.m_domElem.dispatchEvent(new CustomEvent("x-contextmenu"))}dismiss(){this.m_domElem.dispatchEvent(new CustomEvent("x-dismiss"))}reset(){this.blur()}}
class m extends w{constructor(a,b,c){super(void 0,b);this.m_name=a;this.m_children=[];this.m_current=void 0;(this.m_setup=c||void 0)&&this.setup()}get name(){return this.m_name}get isUsable(){for(let a=0;a<this.m_children.length;a++)if(this.m_children[a].isUsable)return!0;return!1}get elements(){let a=[];for(let b=0;b<this.m_children.length;b++){let c=this.m_children[b];c instanceof m?a=a.concat(c.elements):a.push(c)}return a}get domElements(){let a=this.elements,b=[];for(let c=0;c<a.length;c++)b.push(a[c].m_domElem);
return b}focus(){}blur(a,b){for(let c=0;c<this.m_children.length;c++){let d=this.m_children[c];d!==b&&d.blur(a,b)}}findBlock(a){for(let b=0;b<this.m_children.length;b++){let c=this.m_children[b];if(c instanceof m&&c.name===a)return c}return null}findBlockInPath(a){if(!(a instanceof Array)||0>=a.length)return null;let b=this;for(let c=0;b&&c<a.length;c++)0<a[c].length&&(b=b.findBlock(a[c]));return b}addDomElementsUsingSelector(a,b){let c=void 0;try{if("string"===typeof b)(c=r(b))?this.m_children.push(new m(c,
this)):this.addDomElements(a.querySelectorAll(b));else for(let d=0;d<b.length;d++)(c=r(b[d]))?this.m_children.push(new m(c,this)):this.addDomElements(a.querySelectorAll(b[d]))}catch(d){throw dji.logger.error(d),d;}}addDomElements(a){for(let b=0;b<a.length;b++)this.m_children.push(new w(a[b]))}setup(){if(this.m_setup.blocks)for(let b=0;b<this.m_setup.blocks.length;b++){var a=this.m_setup.blocks[b];a=new m(a.name,this,a);this.m_children.push(a)}this.m_setup.dom&&this.addDomElementsUsingSelector(this.m_setup.dom.element,
this.m_setup.dom.selectors);this.m_children=C(this.m_children)}reload(a){let b=a?this.findFocusedElement():void 0;this.clear();this.setup();a&&b&&(a=this.elements,0<=b.index&&b.index<a.length&&a[b.index].focus())}sync(){let a=this.elements,b=void 0;for(let c=0;c<a.length;c++){let d=a[c];v(d.domElement)&&(b=d)}this.blur(void 0,b);return b?(b.focus(),!0):!1}clear(){this.blur();this.m_children.splice(0,this.m_children.length);this.m_current=-1}reset(){0>=this.m_children.length||(0<=this.m_current&&this.m_children[this.m_current].reset(),
this.m_current=-1)}findNextElement(a){let b=this.elements,c=-1,d=void 0,g=-1,f=void 0,l=0>a?b.length:0;a=0>a?-1:1;for(var n=0;n<b.length;n++){let x=b[n];if(x.isFocused){c=n;d=x;break}}for(n=0;n<b.length;n++){g=(l+Math.max(c,0)+a*n)%b.length;f=b[g];if(f!==d&&f.isUsable)break;f=void 0}f||(g=-1);return{oldIndex:c,oldElement:d,newIndex:g,newElement:f}}findFocusedElement(a){a||(a=this.elements);for(let b=0;b<a.length;b++){let c=a[b];if(c.isFocused)return{index:b,element:c}}return null}go(a){a=this.findNextElement(a);
if(a.newElement&&a.newElement!==a.oldElement){var b=!a.newElement.requiresNoFocus;a.oldElement&&a.oldElement.blur(b);a.newElement.focus(b)}}goPrevious(){return this.go(-1)}goNext(){return this.go(1)}enter(){let a=this.findFocusedElement();a&&a.element&&a.element.enter()}select(){let a=this.findFocusedElement();a&&a.element&&a.element.select()}contextMenu(){let a=this.findFocusedElement();a&&a.element&&a.element.contextMenu()}dismiss(){let a=this.findFocusedElement();a&&a.element&&a.element.dismiss()}}
class E{constructor(){this.m_enabled=!1;this.m_blocks=[new m("@default")]}get isEnabled(){return this.m_enabled}get topBlock(){return 0>=this.m_blocks.length?null:this.m_blocks[0]}findBlockIndex(a){let b=[];for(let c=0;c<this.m_blocks.length;c++)this.m_blocks[c].name===a&&b.push(c);return b}findBlockInPath(a){var b=!1;a instanceof Array||(a=(a||"").trim().replace(/[ ]+/g,"/"),b=0===a.indexOf("/"),a=a.split("/"));for(var c=0;c<a.length;c++)if(a[c]&&0<a[c].length){0<c&&a.splice(0,c);break}if(0>=a.length)return null;
0===a[0].indexOf("#")&&(b=!0,a[0]=a[0].substr(1));c=void 0;b?(b=this.findBlockIndex(a[0]),0<b.length&&(c=this.m_blocks[b[0]]),a.splice(0,1)):c=this.topBlock;return c?c.findBlockInPath(a):null}addBlockAndSetup(a,b,c){c||(c=this.topBlock)&&c.blur(!1);a=new m(a,void 0,b);this.m_blocks.splice(0,0,a);return a}popBlock(a){if(a&&0<this.m_blocks.length&&this.m_blocks[0].name!==a)return null;a=this.m_blocks.splice(0,1);0<a.length&&a[0].blur();return a&&0<a.length?a[0]:null}removeBlock(a){a=this.findBlockIndex(a);
for(let b=a.length-1;0<=b;b--){let c=this.m_blocks.splice(a[b],1);0<c.length&&c[0].blur()}}clearBlock(a){(a=this.findBlockInPath(a))&&a.clear()}reloadBlock(a,b){(a=a?this.findBlockInPath(a):this.topBlock)&&a.reload(b)}reset(){for(let a=this.m_blocks.length-1;0<=a;a--)this.m_blocks[a].blur();this.m_blocks=[new m("@default")]}sync(){if(!this.m_enabled)return!1;let a=this.topBlock;return a?a.sync():!1}enable(a,b){void 0===a&&(a=!this.m_enabled);a=!!a;a!==this.m_enabled&&(this.m_enabled=a,b||!this.topBlock||
this.m_enabled||this.topBlock.blur(!1))}goPrevious(){if(this.m_enabled){var a=this.topBlock;a&&a.goPrevious()}}goNext(){if(this.m_enabled){var a=this.topBlock;a&&a.goNext()}}enter(){if(this.m_enabled){var a=this.topBlock;a&&a.enter()}}select(){if(this.m_enabled){var a=this.topBlock;a&&a.select()}}contextMenu(){if(this.m_enabled){var a=this.topBlock;a&&a.contextMenu()}}dismiss(){if(this.m_enabled){var a=this.topBlock;a&&a.dismiss()}}dump(a){a={};for(let b=0;b<this.m_blocks.length;b++)a[b]=this.m_blocks[b].name;
return JSON.stringify(a,null,4)}}k=new E;p=!1;document.documentElement.addEventListener("com.donjohnston.query.vpat",function(a){p&&"cwu"!==a.detail.app&&(a=new CustomEvent(a.detail.answer.event,{detail:{app:"cwu",session:a.detail.answer.session,priority:1E6,active:!0}}),document.documentElement.dispatchEvent(a))},!0);u(window);CWEChromeUtilities.isIframeFree()||((new MutationObserver(t)).observe(document.documentElement,{childList:!0}),t());return{enable:function(a){a=!!a;p!==a&&(p=a,k.enable(a))},
manager:k}}();
