function CWEChromeIME(a,b,c){this.m_isOffice365=!1;this.m_settings={};this.m_hookOffice365=this.m_hookGoogleSlides=this.m_hookGoogleDocs=this.m_hookGeneric=null;this.m_hooks=[];this.m_currentEditor=this.m_currentHook=null;this.m_currentContext={};this.m_currentBkgndRequest={id:0,responseCount:0};this.m_lastActiveElement=null;this.m_shortcut={Shortcuts:{None:0,TrueKeyMode:1,SelectGuess:2},active:0};this.m_digitKeyRegExp=/^(Digit|Numpad)([\d]{1})$/;this.m_arrowKeyRegExp=/^Arrow.*$/;this.m_trueKeyMode=
!1;this.setPort(b);this.m_pause=this.m_on=!1;this.m_caretPosition=void 0;this.m_doSpeakHandler=d=>{this.__onDoSpeak(d)};this.m_asNeededController=this.m_speechRecognitionController=null;this.m_isHighlighting=!1;this.m_lastHighlightedRect=void 0;this.m_TWPModeIsActive=!1;this.m_lastIMELocationWhileReading=void 0;this.m_readTextTask=new window.cwe.ime.tasks.ReadTextIMETask(this,new window.cwe.ime.tasks.IMETaskEventGuard(document,window.dji.twp.TaskScheduler));this.m_highlighterCallbacks={onHighlighted:(d,
e,f)=>{d.highlightWhileTypingIsEnabled?this.m_lastHighlightedRect=null:(this.m_lastHighlightedRect=f&&0<f.width&&0<f.height?f:this.getCaretPosition(!0),this.__moveWindow())}};this.m_forwardTTSTextHighlighter=new window.dji.highlighting.TTSTextHighlighterProxy(this.m_highlighterCallbacks);this.m_forwardTTSTextHighlighter.addEventListener("highlighting-status-changed",d=>{this.__onTextHighlightStatusChanged(d.detail.source,d.detail.status)});this.m_forwardTTSTextHighlighter.addEventListener("proxy-initialized",
()=>{this.setTTSHighlighterSettings()});this.__initAsNeededController(a);this.__initSpeechRecognitionController(a);this.m_contextTimer=this.m_mutationObserver=null;this.m_mutationMonitor={timer:null,editorPoolChanged:!1};this.m_windowPositionCache={scrollX:window.pageXOffset,scrollY:window.pageYOffset};this.m_domContainer=a.domContainer;this.m_developerMode=!1;this.m_guessesQueue=[];this.m_contextForMomentaryTopicRequested=this.m_waitingForGuessResult=!1;this.__initialize(c);window.dji.cwe.i18n.translateHtmlDocument(window.cweMainView.view);
return this}CWEChromeIME.prototype.__initAsNeededController=function(a){this.m_asNeededController=new window.cwe.CWEAsNeededController({getLastWrittenWord:()=>this.getLastWrittenWord()},a.domContainer);this.m_asNeededController.addEventListener("prediction-changed",b=>{this.onPredictionStateChanged(b.detail.data)});this.m_asNeededController.addEventListener("dictation-changed",b=>{this.onDictationStateChanged(b.detail.data)})};CWEChromeIME.prototype.setPort=function(a){this.m_port=a;window.dji.cwe.i18n.initialize(a)};
const selectionType={CLICK:1,NUMBER:2};
class SpeechRecognitionControllerDelegateIME extends window.dji.speechrecognition.SpeechRecognitionControllerDelegate{constructor(a){super();this.m_ime=a}getCurrentContext(){return this.m_ime.m_currentContext}handleInput(a,b){return this.m_ime.__handleInput(a,b)}async replaceTextAsync(a,b){await this.m_ime.__replaceText({selection:a,text:b},!0)}postPortMessage(a){this.m_ime.__postPortMessage(a)}readText(a){a={type:window.dji.highlighting.Origin.BACK_TO_CARET,skip:window.dji.mapping.Skip.WORD,skipCount:window.dji.utils.countWords(a)};
this.m_ime.__onReadText(a,window.dji.highlighting.Granularity.WORD,!0)}}
CWEChromeIME.prototype.__initSpeechRecognitionController=function(a){this.m_speechRecognitionTTSTextHighlighter=new window.dji.highlighting.TTSTextHighlighterProxy;this.m_speechRecognitionTTSTextHighlighter.setWordGranularity();this.m_speechRecognitionTTSTextHighlighter.addEventListener("highlighting-status-changed",b=>{this.__onTextHighlightStatusChanged(b.detail.source,b.detail.status)});this.m_speechRecognitionTTSTextHighlighter.addEventListener("proxy-initialized",()=>{this.setTTSHighlighterSettings()});
this.m_speechRecognitionController=new window.dji.speechrecognition.SpeechRecognitionController(this.m_speechRecognitionTTSTextHighlighter,new SpeechRecognitionControllerDelegateIME(this),a.domContainer,"cwu");this.m_speechRecognitionController.addEventListener("speech-started",()=>{this.__onSpeechStartedHandler()});this.m_speechRecognitionController.addEventListener("speech-ended",b=>{this.__onSpeechEndedHandler(b.detail)});this.m_speechRecognitionController.addEventListener("speech-error",b=>{this.m_asNeededController.onSpeechRecognitionError(b.detail)});
this.m_speechRecognitionController.addEventListener("speech-error-dismissed",()=>{this.m_asNeededController.onSpeechRecognitionErrorDismissed()})};
CWEChromeIME.prototype.__initialize=function(a){const b=this;CWEChromeUtilities.isGoogleDocs()?(this.m_hookGoogleDocs=new CWEChromeHookGoogleDocs(this,this.m_domContainer),this.m_hooks.push(this.m_hookGoogleDocs)):CWEChromeUtilities.isGooglePresentation()&&(this.m_hookGoogleSlides=new window.GoogleDocsApiDjiWrapper.DJIHookGoogleSlides(this,this.m_domContainer,document.querySelector("dji-cowriter")),this.m_hooks.push(this.m_hookGoogleSlides));this.m_hookGeneric=new CWEChromeHookGeneric(this,this.m_domContainer);
this.m_hooks.push(this.m_hookGeneric);DexController.instance.setLocationInfoDelegate(this.getImeLocation.bind(this));DexController.instance.setFixPositionDelegate(this.setFixPosition.bind(this));DexController.instance.addExtensionControls(window.cweMainView.view);this.m_port.onDisconnect.addListener(function(c){b.__onPortDisconnect(c)});this.m_port.onMessage.addListener(function(c){b.__onPortMessage(c)});this.m_mutationObserver=new MutationObserver(function(c){b.onDOMMutations(c)});window.cweMainView.viewDidChangeDelegate=
this.__onViewDidChange.bind(this);window.cweMainView.viewSizeChangedDelegate=this.__onViewSizeChanged.bind(this);window.cweMainView.trueKeyModeDidChangeDelegate=this.__onTrueKeyModeDidChangeDelegate.bind(this);window.cweMainView.speakClickDelegate=this.__onSpeakText.bind(this);window.cweMainView.suggestionClickDelegate=c=>{this.__onSuggestionSelected(c,selectionType.CLICK)};window.cweMainView.keyboardClickDelegate=this.__onVirtualKeyboardInput.bind(this);window.cweMainView.searchTopicsOnWebDelegate=
this.__onSearchTopicsOnWeb.bind(this);window.cweMainView.readClickDelegate=this.__onReadText.bind(this);window.cweMainView.postGA4Event=this.__postGA4Event.bind(this);dji.topicHelper.setActivateTopicDelegate(this.__onActivateTopic.bind(this));dji.topicHelper.setUpdateTopicDelegate(this.__onUpdateTopic.bind(this));window.dji.logger.log("[Co:Writer IME] Document state is: "+document.readyState);"complete"===document.readyState?(window.dji.logger.log("[Co:Writer IME] Document is already loaded: "+window.location),
this.__postNeedSetup(),this.__postDocumentReady()):(window.dji.logger.log("[Co:Writer IME] Waiting for document to finish loading: "+window.location),document.onreadystatechange=function(){window.dji.logger.log("[Co:Writer IME] document state: "+document.readyState);"complete"===document.readyState&&(window.dji.logger.log("[Co:Writer IME] Document fully loaded: "+window.location),b.__postNeedSetup(),b.__postDocumentReady())});window.addEventListener("scroll",()=>{this.m_windowPositionCache.scrollX=
window.pageXOffset;this.m_windowPositionCache.scrollY=window.pageYOffset});a&&a()};CWEChromeIME.prototype.serviceIsSupported=function(a){return"ms-office-word-editor"===a||"canvas-lms"===a};
CWEChromeIME.prototype.serviceAvailable=function(a,b,c){if("ms-office-word-editor"===a){if("cwe-frame-manager"===b){this.m_speechRecognitionTTSTextHighlighter.setMessageProxy(c);this.m_forwardTTSTextHighlighter.setMessageProxy(c);return}if("cwe-word-proxy"===b){this.__setupMSOfficeHook(c);return}}if("canvas-lms"!==a)return c.disconnect()};
CWEChromeIME.prototype.serviceUnavailable=function(a,b){if("ms-office-word-editor"===a&&b&&(a=this.m_hooks.indexOf(b),0<=a&&this.m_hooks.splice(a,1),this.m_isOffice365=!1,this.m_currentHook===b))this.onEditorChanged(null,null)};CWEChromeIME.prototype.__setupMSOfficeHook=function(a){this.m_isOffice365=!0;this.m_hookOffice365=new window.CWEChromeHookOffice365(this,a,!(!this.m_on||this.m_pause));this.m_hooks.push(this.m_hookOffice365);this.m_on&&!this.m_pause&&(this.m_hookOffice365.install(),this.setOfficeHookOptions())};
CWEChromeIME.prototype.__onTextHighlightStatusChanged=function(a,b){if(this.m_isHighlighting!==b){if(b){const c=this.getImeLocation();this.m_lastIMELocationWhileReading=c?{left:c.left,top:c.top,right:c.left+window.cweMainView.size.width,bottom:c.top+window.cweMainView.size.height}:{left:0,top:0,right:window.cweMainView.size.width,bottom:window.cweMainView.size.height}}else this.m_lastIMELocationWhileReading=null;this.m_isHighlighting=b;this.m_isOffice365&&this.m_hookOffice365&&this.m_hookOffice365.setHighlightMode(a.remoteHighlighterId,
b);if(b)this.m_asNeededController.onTextHighlightStarted(a===this.m_forwardTTSTextHighlighter);else this.m_asNeededController.onTextHighlightEnded(),this.m_asNeededController.onCaretChanged(this.getCaretPosition(!0))}};
CWEChromeIME.prototype.setTTSHighlighterSettings=function(){if(this.m_settings&&this.m_settings.speech){var a={highlightTextColor:this.m_settings.speech.highlightTextColor,highlightBackgroundColor:this.m_settings.speech.highlightBackgroundColor,id:"cwu"};this.m_forwardTTSTextHighlighter.setOptions(a);this.m_speechRecognitionTTSTextHighlighter.setOptions(a)}};CWEChromeIME.prototype.setup=function(a){};CWEChromeIME.prototype.getTrueKeyMode=function(){return this.m_trueKeyMode};
CWEChromeIME.prototype.restart=function(a){window.dji.logger.log("------------- CWEChromeIME.restart begin");let b=this;this.setPort(a);this.m_port.onMessage.addListener(function(c){b.__onPortMessage(c)});this.__postNeedSetup();this.__cancelContextTimer();this.stopObservingDOMMutations();this.__showWindow(!1);for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall();this.__accumulateData(null);if(this.m_on&&!this.m_pause){for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.observeDOMMutations();
this.__accumulateData(null)}window.dji.logger.log("------------- CWEChromeIME.restart finished")};
CWEChromeIME.prototype.activate=function(a){window.dji.logger.log("------------- CWEChromeIME.activate begin");if(!this.m_on&&!this.m_pause)if(a&&"create_topic"===a.action)this.m_pause=!0;else{for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.setOfficeHookOptions();this.observeDOMMutations()}this.m_on=!0;this.m_asNeededController.onActivateChanged(this.m_on);window.dji.logger.log("------------- CWEChromeIME.activate finished");return this.m_on};
CWEChromeIME.prototype.deactivate=function(){window.dji.logger.log("------------- CWEChromeIME.deactivate");if(this.m_on){this.m_on=!1;if(this.m_pause)this.m_pause=!1,this.__showWindow(!1,!0,!0);else{this.__cancelContextTimer();this.stopObservingDOMMutations();this.__showWindow(!1,!0,!0);for(let a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall()}this.m_speechRecognitionController.stop()}window.dji.logger.log("------------- CWEChromeIME.deactivate finished");this.m_asNeededController.onActivateChanged(this.m_on);
return this.m_on};CWEChromeIME.prototype.resume=function(){window.dji.logger.log("------------- CWEChromeIME.resume begin");if(this.m_on&&this.m_pause){for(let a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.observeDOMMutations()}this.m_pause=!1;window.dji.logger.log("------------- CWEChromeIME.resume finished")};
CWEChromeIME.prototype.pause=function(a=!1){window.dji.logger.log("------------- CWEChromeIME.suspend");if(!this.m_pause){this.m_pause=!0;if(this.m_on){this.__cancelContextTimer();this.stopObservingDOMMutations();a||this.__showWindow(!1);for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall();this.__accumulateData(null)}this.m_forwardTTSTextHighlighter.isHighlighting()&&this.__postStopSpeak()}window.dji.logger.log("------------- CWEChromeIME.suspend finished")};
CWEChromeIME.prototype.findSruInfo=function(){let a={div:document.getElementById("__dji_sru_main_container"),iframe:document.getElementById("__dji_sru_main_container_iframe"),contentDocument:null};a.div&&!a.iframe&&a.div.shadowRoot&&(a.iframe=a.div.shadowRoot.getElementById("__dji_sru_main_container_iframe"));try{a.iframe&&(a.contentDocument=a.iframe.contentDocument)}catch(b){window.dji.logger.error(b)}return a};CWEChromeIME.prototype.onCapabilitiesUpdate=function(a,b){this.__postDocumentCapabilitiesUpdate({service:b})};
CWEChromeIME.prototype.observeDOMMutations=function(a){var b=this.findSruInfo();if(!a||b.contentDocument&&!b.contentDocument.watchedByCoWriter){var c={subtree:!0,childList:!0},d={subtree:!0,childList:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["contenteditable"]};if(!a){a=[document];CWEChromeUtilities.findValidDocumentElements(document,a);for(let e of a)e.body&&e!==b.contentDocument&&!this.m_mutationObserver.hasTarget(e.body)&&(this.m_mutationObserver.observe(e.body,c),this.m_mutationObserver.observe(e.body,
d))}b.contentDocument&&!b.contentDocument.watchedByCoWriter&&(b.contentDocument.watchedByCoWriter=!0,this.m_mutationObserver.hasTarget(b.contentDocument.body)||(this.m_mutationObserver.observe(b.contentDocument.body,c),this.m_mutationObserver.observe(b.contentDocument.body,d)))}};
CWEChromeIME.prototype.stopObservingDOMMutations=function(){this.__cancelDOMMutationTimer();this.m_mutationObserver.disconnect();var a=this.findSruInfo();a.contentDocument&&a.contentDocument.watchedByCoWriter&&(a.contentDocument.watchedByCoWriter=!1)};
CWEChromeIME.prototype.onDOMMutations=function(a){this.observeDOMMutations();if(!this.m_mutationMonitor.timer||!this.m_mutationMonitor.editorPoolChanged)if(!this.m_currentHook||!this.m_currentHook.shouldIgnoreMutations(a)){var b=!1;for(let c=0;!b&&c<a.length;c++){let d=a[c];"attributes"===d.type?d.target.getAttribute("contenteditable")!==d.oldValue&&(b=!0):"childList"===d.type&&(this.nodesMightHaveEditors(d.addedNodes)||this.nodesMightHaveEditors(d.removedNodes))&&(b=!0)}this.__cancelDOMMutationTimer();
b&&(this.m_mutationMonitor.editorPoolChanged=b,this.m_mutationMonitor.timer=setTimeout(()=>{this.__cancelDOMMutationTimer();for(let c=0;c<this.m_hooks.length;c++)this.m_hooks[c].reload(!0)},b?200:800))}};CWEChromeIME.prototype.nodesMightHaveEditors=function(a){if(a)for(let b of a)if(b.nodeType===Node.ELEMENT_NODE&&(b.matches("iframe,input,textarea,body,[contenteditable]")||b.querySelector("iframe,input,textarea,body,[contenteditable]")))return!0;return!1};CWEChromeIME.prototype.toggleOnOff=function(){this.m_port.postMessage({message:window.dji.messages.cwe.chrome.TOGGLE})};
CWEChromeIME.prototype.onEditorEvent=function(a,b,c){if(c.isTrusted&&"select"!==c.type&&"input"!==c.type){if(this.m_isOffice365&&a===this.m_hookOffice365&&this.m_readTextTask&&this.m_readTextTask.isRunning()&&"keyup"!==c.type)this.m_readTextTask.onGuardedEvent(c);this.m_speechRecognitionController.isActive()&&("blur"!==c.type&&"focus"!==c.type||!this.m_asNeededController.isSpeechStopping())&&this.m_speechRecognitionController.stopAsync()}};
CWEChromeIME.prototype.onEditorChanged=function(a,b){this.__postStopSpeak();this.__accumulateData(null);this.m_shortcut.active=this.m_shortcut.Shortcuts.None;var c=this.m_hookGoogleDocs||this.m_hookGoogleSlides||null;c&&a!==c&&null===b&&this.m_on&&!this.m_pause&&(c=c.getState(),c.active&&(a=c.hook,b=c.editor,window.dji.logger.log("-------------------------------- editor fallback to Google Docs/Slides:",a,b),window.dji.logger.log(a),window.dji.logger.log(b)));c=this.m_currentHook!==a;this.m_currentHook=
a;this.m_currentEditor=b;this.__postIMEActivationChanged(!(null===b||void 0===b));this.__getContext(!0,!0);c&&this.m_contextForMomentaryTopicRequested&&this.postContextForMomentaryTopic()};CWEChromeIME.prototype.onContextChanged=function(a){this.m_isHighlighting||this.__getContext(!1,!0)};CWEChromeIME.prototype.onMouseDown=function(a,b){this.__accumulateData(null)};CWEChromeIME.prototype.onMouseUp=function(a,b){this.__getContext(!1,!0)};
CWEChromeIME.prototype.onKeyDown=function(a,b){if("Alt"===b.key||"Control"===b.key||"Shift"===b.key||"CapsLock"===b.key||"Meta"===b.key)return!1;this.__cancelContextTimer();if("Backspace"===b.code)this.__accumulateData("\b");else if(this.m_arrowKeyRegExp.test(b.code))this.__accumulateData(null);else if("Enter"===b.code&&this.m_hookGoogleDocs===this.m_currentHook&&this.m_hookGoogleDocs===a)this.__onTryToSpeak("\n");else if("KeyN"===b.code){if(b.altKey&&!(b.ctrlKey||b.shiftKey||b.metaKey))return this.m_shortcut.active===
this.m_shortcut.Shortcuts.None&&(this.m_shortcut.active=this.m_shortcut.Shortcuts.TrueKeyMode,this.__toggleTruKeyMode(),this.__getContext(!1,!1)),!0}else if((a=this.suggestionFromEvent(b))&&a.item)return this.__onSuggestionSelected(a,selectionType.NUMBER),!0;this.m_shortcut.active=this.m_shortcut.Shortcuts.None;this.__getContext(!1,!0);return!1};
CWEChromeIME.prototype.suggestionFromEvent=function(a){return!this.m_settings.features.allowTogglePrediction||this.m_trueKeyMode||a.altKey||a.ctrlKey||a.shiftKey||a.metaKey||!(a=a.code?a.code.match(this.m_digitKeyRegExp):null)||3!==a.length?null:(a=parseInt(a[2]),window.cweMainView.suggestionFromNumber(a))};
CWEChromeIME.prototype.onKeyPress=function(a,b){a=String.fromCharCode(b.charCode);this.__cancelContextTimer();if(b.skipHandleInput)this.__accumulateData(a),this.__postRestartGuesses();else if(this.__handleInput(a))return!0;this.__onTryToSpeak(a);b.skipHandleInput||this.__getContext(!1,!1);return!1};CWEChromeIME.prototype.onInput=function(a,b){this.__onTryToSpeak(b.key);this.__getContext(!1,!1)};CWEChromeIME.prototype.onKeyUp=function(a,b){this.m_shortcut.active=this.m_shortcut.Shortcuts.None;return!1};
CWEChromeIME.prototype.onToggleTrueKeyMode=function(){this.__toggleTruKeyMode()};CWEChromeIME.prototype.onDigitKey=function(a,b){return(a=window.cweMainView.suggestionFromNumber(b))&&a.item?(this.__onSuggestionSelected(a,selectionType.NUMBER),!0):!1};
CWEChromeIME.prototype.__onTryToSpeak=function(a){this.__onTryToSpeak.timer&&(clearTimeout(this.__onTryToSpeak.timer),this.__onTryToSpeak.timer=void 0);this.m_settings.features.allowSpeech&&!this.m_speechRecognitionController.isActive()&&(this.__onTryToSpeak.timer=setTimeout(this.m_doSpeakHandler,0,a))};
CWEChromeIME.prototype.__onDoSpeak=async function(a){const b=0<a.length?a.charAt(0):void 0;if(b){var c={type:window.dji.highlighting.Origin.BACK_TO_CARET,skip:-1,skipCount:1,skipConsecutiveSeparatorsAsOne:!1,activate:!0},d=window.dji.highlighting.Granularity.WORD;this.m_settings.speech.sentences&&window.dji.charSet.sentenceSeparator.characterIsMember(b)?c.skip="\r"===a||"\n"===a?-1:window.dji.mapping.Skip.SENTENCE:this.m_settings.speech.words&&window.dji.charSet.wordSeparator.characterIsMember(b)?
(c.skip=window.dji.mapping.Skip.WORD,c.skipConsecutiveSeparatorsAsOne=!!(1<a.length&&a.endsWith(" "))):this.m_settings.speech.letters&&!window.dji.charSet.wordSeparator.characterIsMember(b)&&(c.skip=window.dji.mapping.Skip.CHARACTER,d=window.dji.highlighting.Granularity.CHARACTER);0>c.skip||this.__onReadText(c,d)}};CWEChromeIME.prototype.onSpeak=function(a){this.__postSpeak(a,!0)};CWEChromeIME.prototype.onStopSpeak=function(){this.__postStopSpeak()};CWEChromeIME.prototype.onAddPersonalWords=function(a){this.__postAddPersonalWords(a)};
CWEChromeIME.prototype.onRemovePersonalWords=function(a){this.__postRemovePersonalWords(a)};CWEChromeIME.prototype.__cancelDOMMutationTimer=function(){null!=this.m_mutationMonitor.timer&&(clearTimeout(this.m_mutationMonitor.timer),this.m_mutationMonitor.timer=null,this.m_mutationMonitor.editorPoolChanged=!1)};CWEChromeIME.prototype.__cancelContextTimer=function(){null!=this.m_contextTimer&&(clearTimeout(this.m_contextTimer),this.m_contextTimer=null)};
CWEChromeIME.prototype.__getContext=function(a,b){var c=this;this.__cancelContextTimer();a?setTimeout(function(){c.__onEditorChanged()},0):(setTimeout(function(){c.__onCaretChanged()},0),this.m_contextTimer=setTimeout(function(){c.__onContextChanged(b)},100))};CWEChromeIME.prototype.__onCaretChanged=function(){this.m_asNeededController.onCaretChanged(this.getCaretPosition(!0));this.m_isHighlighting||this.__moveWindow()};
CWEChromeIME.prototype.getCaretPosition=function(a=!1){return a||window.dji.utils.isNullOrUndefined(this.m_caretPosition)?this.m_caretPosition=this.m_currentEditor?this.m_currentHook.getCaret(this.m_currentEditor):null:this.m_caretPosition};
CWEChromeIME.prototype.getImeLocation=function(){let a=this.getCaretPosition();if(a){if(this.m_isHighlighting&&!window.dji.utils.isNullOrUndefined(this.m_lastHighlightedRect)){var b=this.m_lastHighlightedRect.top;var c=this.m_lastHighlightedRect.top+this.m_lastHighlightedRect.height}else b=a.top,c=a.bottom;var d=a.left;c+=2;var e=window.cweMainView.size,f=CWEChromeUtilities.getScrollbarSize(),g=e.width;e=e.height;var h=window.innerHeight+this.m_windowPositionCache.scrollY;window.innerWidth+this.m_windowPositionCache.scrollX<
d+g+f.width+2&&(0<=a.left-g&&(d=a.left-g),d<this.m_windowPositionCache.scrollX&&(d=this.m_windowPositionCache.scrollX));h<c+e+f.height+2&&0<=b-e-2&&(c=b-e-2);return{left:d,top:c,caret:a}}};CWEChromeIME.prototype.setFixPosition=function(a,b,c){a={anchor:a,x:b,y:c};this.m_settings.window.position=a;this.__postGuessWindowPositionUpdate(a)};
CWEChromeIME.prototype.__onEditorChanged=function(){this.m_currentContext=this.m_currentEditor?this.m_currentHook.getContext(this.m_currentEditor):null;this.m_currentEditor&&null!==this.m_currentContext&&this.__postContextAvailable(!0);this.__onCaretChanged();this.__showWindow(null!==this.m_currentEditor);this.m_asNeededController.onEditorChanged(null!==this.m_currentEditor)};
CWEChromeIME.prototype.__onContextChanged=function(a){this.__cancelContextTimer();null!==this.m_currentHook&&(this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor),this.__postContextAvailable(a))};CWEChromeIME.prototype.__toggleTruKeyMode=function(){this.m_settings.features.allowTogglePrediction&&window.cweMainView.toggleTrueKeyMode()&&this.__updateTruKeyMode()};
CWEChromeIME.prototype.__updateTruKeyMode=function(){if(this.m_settings.features.allowTogglePrediction){this.m_trueKeyMode=window.cweMainView.trueKeyMode;for(let a=0;a<this.m_hooks.length;a++)this.m_hooks[a].setTrueKeyMode(this.m_trueKeyMode)}};
CWEChromeIME.prototype.__showWindow=function(a,b=!1,c=!1){window.cweMainView.canShow()?a=!!a||!(b||!window.cweMainView.hasFocus()):(a=!1,c=!0);if(a=a&&this.m_asNeededController.isPredictionActive())this.__postContextAvailable(!0),c&&window.cweMainView.reset();window.cweMainView.show(a);a&&this.__fixIMEPosition();c&&!a&&window.cweMainView.reset()};
CWEChromeIME.prototype.__moveWindow=function(){if(this.m_isHighlighting&&!window.dji.utils.isNullOrUndefined(this.m_lastHighlightedRect)){if(this.m_lastIMELocationWhileReading.top<this.m_lastHighlightedRect.top+this.m_lastHighlightedRect.height&&this.m_lastIMELocationWhileReading.bottom>this.m_lastHighlightedRect.top){var a=this.getImeLocation();if(!a)return;this.m_lastIMELocationWhileReading.left=a.left;this.m_lastIMELocationWhileReading.top=a.top;DexController.instance.move(null,a.top)}this.m_lastIMELocationWhileReading.right=
this.m_lastIMELocationWhileReading.left+window.cweMainView.size.width;this.m_lastIMELocationWhileReading.bottom=this.m_lastIMELocationWhileReading.top+window.cweMainView.size.height}else(a=this.getImeLocation())&&DexController.instance.move(a.left,a.top)};CWEChromeIME.prototype.__fixIMEPosition=function(){this.m_asNeededController.hasSpeechError()?(DexController.instance.fixPosition(null),this.__moveWindow()):DexController.instance.fixPosition(this.m_settings.window.position)};
CWEChromeIME.prototype.__postDocumentReady=function(){this.__postPortMessage({message:window.dji.messages.cwe.chrome.DOCUMENT_READY})};CWEChromeIME.prototype.__postGuessWindowPositionUpdate=function(a){this.__postPortMessage({message:window.dji.messages.cwe.ime.GUESS_WINDOW_POS_UPDATE,position:a})};CWEChromeIME.prototype.__postDocumentCapabilitiesUpdate=function(a){this.__postPortMessage({message:window.dji.messages.cwe.chrome.DOCUMENT_CAPABILITIES_UPDATE,details:a})};
CWEChromeIME.prototype.__postNeedSetup=function(){this.__postPortMessage({message:window.dji.messages.cwe.chrome.NEEDS_SETUP})};
CWEChromeIME.prototype.__postContextAvailable=function(a){if(!this.m_speechRecognitionController.isTextHighlightingActive()&&!this.m_forwardTTSTextHighlighter.isHighlighting()&&this.m_asNeededController.isPredictionActive()&&null!=this.m_currentContext&&null!=this.m_currentContext.selection&&null!=this.m_currentContext.text){var b=this.m_currentContext.selection,c=this.m_currentContext.text;this.m_currentBkgndRequest.id=Math.max(1,(this.m_currentBkgndRequest.id+1)%1E6);this.m_currentBkgndRequest.responseCount=
0;this.__postPortMessage({message:window.dji.messages.cwe.ime.CONTEXT_AVAILABLE,context:{selection:b,text:c,changed:a},fullSpelling:this.m_asNeededController.isSpellingAware(),requestId:this.m_currentBkgndRequest.id})}};
CWEChromeIME.prototype.postContextForMomentaryTopic=function(){if(this.m_on&&!this.m_pause&&this.m_settings.features.allowTogglePrediction)if(this.m_currentHook){let a=this;this.m_currentHook.getContextForMomentaryTopic(this.m_currentEditor,function(b){a.m_settings.isEnglish&&(b=CWEChromeUtilities.wikiHtmlToAscii(b));a.__postContextForMomentaryTopicAvailable(b);this.m_contextForMomentaryTopicRequested=!1})}else this.m_contextForMomentaryTopicRequested=!0};
CWEChromeIME.prototype.__postContextForMomentaryTopicAvailable=function(a){this.__postPortMessage({message:window.dji.messages.cwe.topics.CONTEXT_FOR_MOMENTARY_TOPIC_AVAILABLE,context:{text:a}})};CWEChromeIME.prototype.__postGuessSelected=function(a){window.dji.logger.log("CWEChromeIME.__postGuessSelected: #"+a+"#");this.m_guessesQueue.push(a);this.__postNextGuess()};
CWEChromeIME.prototype.__postNextGuess=function(){if(0!==this.m_guessesQueue.length&&!this.m_waitingForGuessResult){var a=this.m_guessesQueue.shift();this.m_waitingForGuessResult=!0;this.m_currentHook&&(this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor),this.__postContextAvailable(!0));this.__postPortMessage({message:window.dji.messages.cwe.ime.GUESS_SELECTED,guess:a})}};
CWEChromeIME.prototype.__postRestartGuesses=function(){this.m_guessesQueue=[];this.m_waitingForGuessResult=!1;this.__postPortMessage({message:window.dji.messages.cwe.ime.RESTART_GUESSES})};CWEChromeIME.prototype.__postAddPersonalWords=function(a){this.__postPortMessage({message:window.dji.messages.cwe.personal_words.ADD,text:a})};CWEChromeIME.prototype.__postRemovePersonalWords=function(a){this.__postPortMessage({message:window.dji.messages.cwe.personal_words.REMOVE,text:a})};
CWEChromeIME.prototype.__execUpdateTopic=async function(a){return this.__executeCommandAsync(window.dji.messages.cwe.topics.UPDATE,a)};CWEChromeIME.prototype.__execActivateTopic=async function(a){return this.__executeCommandAsync(window.dji.messages.cwe.topics.ACTIVATE,a)};
CWEChromeIME.prototype.__postSpeak=function(a,b,c){this.m_speechRecognitionController.isSpeechRecognitionOn()||0<this.m_forwardTTSTextHighlighter.text.trim().length||this.__postPortMessage({message:window.dji.messages.cwe.speak.SPEAK,text:a,force:b,listenForEvents:c})};
CWEChromeIME.prototype.__postScheduleSpeak=function(a,b,c,d){this.m_speechRecognitionController.isSpeechRecognitionOn()||this.__postPortMessage({message:window.dji.messages.cwe.speak.SCHEDULE,text:a,stopCurrentSpeech:!0,listenForEvents:b,sessionID:c,speechOptions:d})};CWEChromeIME.prototype.__postStopSpeak=function(){this.__postPortMessage({message:window.dji.messages.cwe.speak.STOP})};
CWEChromeIME.prototype.__postIMEActivationChanged=function(a){this.__postPortMessage({message:window.dji.messages.cwe.ime.ACTIVATION_CHANGED,active:a,hostname:location.hostname})};CWEChromeIME.prototype.__postAccumulateData=function(a){this.__postPortMessage({message:window.dji.messages.cwe.ime.ACCUMULATE_DATA,text:a})};CWEChromeIME.prototype.__postPortMessage=function(a){if(this.m_port)try{this.m_port.postMessage(a)}catch(b){window.dji.logger.error(b)}};
CWEChromeIME.prototype.__postGA4Event=function(a,b,c){this.m_port.postMessage({message:"googleAnalyticsEvent",data:{eventName:a,customProperties:b,defaultProperties:c}})};CWEChromeIME.prototype.__executeCommandAsync=async function(a,b,c){if(this.m_port){const d=this;return new Promise(function(e,f){d.__executeCommand(a,b,c,e,f)})}};
CWEChromeIME.prototype.__executeCommand=function(a,b,c,d,e){if(d&&!(d instanceof Function))throw Error("Invalid arguments: successCallback is not a function!");const f=this.m_port;c=this.__executeCommand.session=(this.__executeCommand.session||0)+1;const g=d?`com.donjohnston.cwu.cs.session.${c}`:void 0;a={message:a,params:b,options:{callbackMessage:g}};let h=void 0,l=void 0;try{d&&(h=function(k){if(k&&k.message===g){l&&f.onDisconnect.removeListener(l);f.onMessage.removeListener(h);try{d(k.params)}catch(m){window.dji.logger.error(m)}}},
f.onMessage.addListener(h)),e&&(l=function(){f.onDisconnect.removeListener(l);d&&f.onMessage.removeListener(h);try{e()}catch(k){window.dji.logger.error(k)}},f.onDisconnect.addListener(l)),f.postMessage(a)}catch(k){window.dji.logger.error(k),l&&f.onDisconnect.removeListener(l),h&&f.onMessage.removeListener(h),e&&e(k)}};CWEChromeIME.prototype.__onPortDisconnect=function(a){window.dji.logger.log("CWEChromeIME.__onPortDisconnect");window.dji.logger.log(a)};
CWEChromeIME.prototype.__onPortMessage=function(a){a.message===window.dji.messages.cwe.ime.GUESSES_AVAILABLE?a.requestId===this.m_currentBkgndRequest.id&&(this.m_currentBkgndRequest.responseCount++,this.__showGuesses(1===this.m_currentBkgndRequest.responseCount,a.guesses,a.replacements,void 0)):a.message===window.dji.messages.cwe.ime.TRANSLATIONS_AVAILABLE?a.requestId===this.m_currentBkgndRequest.id&&(this.m_currentBkgndRequest.responseCount++,this.__showGuesses(1===this.m_currentBkgndRequest.responseCount,
void 0,void 0,a.translations)):a.message===window.dji.messages.cwe.ime.SPELLCHECK_DONE?a.requestId===this.m_currentBkgndRequest.id&&(this.m_currentBkgndRequest.responseCount++,this.m_asNeededController.onSpellcheckDone(a)):a.message===window.dji.messages.cwe.ime.REPLACE_TEXT?this.__onReplaceTextMessage(a):a.message===window.dji.messages.cwe.chrome.SETTINGS?(this.m_settings=a.settings,this.m_settings.features||(this.m_settings.features={}),window.dji.utils.isNullOrUndefined(this.m_settings.features.allowTogglePrediction)&&
(this.m_settings.features.allowTogglePrediction=!0),CWEChromeUtilities.isMicrosoftEdge()?this.m_settings.features.allowMicrophone=!1:window.dji.utils.isNullOrUndefined(this.m_settings.features.allowMicrophone)&&(this.m_settings.features.allowMicrophone=!0),window.dji.utils.isNullOrUndefined(this.m_settings.features.allowSpeech)&&(this.m_settings.features.allowSpeech=!0),window.dji.utils.isNullOrUndefined(this.m_settings.features.allowAutoCapitalization)&&(this.m_settings.features.allowAutoCapitalization=
!0),window.dji.utils.isNullOrUndefined(this.m_settings.features.allowCreateTopics)&&(this.m_settings.features.allowCreateTopics=!0),this.__fixIMEPosition(),window.cweMainView.setOptions({presentationLang:this.m_settings.presentationLang,locale:this.m_settings.locale,window:{scale:this.m_settings.window.scale,fontFamily:this.m_settings.text.fontFamily,textColor:this.m_settings.text.textColor,backgroundColor:this.m_settings.text.backgroundColor,position:this.m_settings.window.position},suggestions:this.m_settings.window.suggestions,
translation:this.m_settings.translation,features:this.m_settings.features,speech:this.m_settings.speech}),window.cweMainView.canShow()?this.m_on&&!this.m_pause&&this.m_currentEditor&&this.__getContext(!0,!0):this.__showWindow(!1),this.setOfficeHookOptions(),this.setTTSHighlighterSettings(),this.m_speechRecognitionController.setSettings(this.m_settings),this.m_asNeededController.setLevel(this.m_settings.asNeeded),window.dji._goog=this.m_settings.gdocsConfig):a.message===window.dji.messages.cwe.topics.DATA?
this.topicsDataAvailable(a.data):a.message===window.dji.messages.cwe.topics.UPDATE?window.cweMainView.cancelResetToCreateTopic():a.message===window.dji.messages.cwe.topics.GET_CONTEXT_FOR_MOMENTARY_TOPIC&&this.postContextForMomentaryTopic()};
CWEChromeIME.prototype.__onReplaceTextMessage=async function(a){await this.__replaceText(a.info,!0);this.m_settings.features.allowSpeech&&this.m_settings.speech.words&&(a={type:window.dji.highlighting.Origin.BACK_TO_CARET,skip:window.dji.mapping.Skip.WORD,skipCount:window.dji.utils.countWords(a.info.text),activate:!0},this.__onCaretChanged(),this.__onReadText(a,window.dji.highlighting.Granularity.WORD));this.m_waitingForGuessResult=!1;this.__postNextGuess()};
CWEChromeIME.prototype.__showGuesses=function(a,b,c,d){let e=!1;this.m_settings.features.allowTogglePrediction&&(window.dji.utils.isNullOrUndefined(b)||(window.cweMainView.setSuggestions(b,c,a),e=!0),window.dji.utils.isNullOrUndefined(d)||(window.cweMainView.setTranslations(d,null,a),e=!0));e&&!this.m_TWPModeIsActive&&this.__moveWindow()};
CWEChromeIME.prototype.__replaceText=async function(a,b){this.m_currentEditor&&(this.m_forwardTTSTextHighlighter.isHighlighting()&&(await this.m_forwardTTSTextHighlighter.cancel(),await this.m_forwardTTSTextHighlighter.resetAsync()),this.m_currentHook.replaceTextAsync?await this.m_currentHook.replaceTextAsync(this.m_currentEditor,a,this.m_currentContext):this.m_currentHook.replaceText(this.m_currentEditor,a,this.m_currentContext),a.skipGetContext||this.__getContext(!1),b&&(b="",a.selection.start<
a.selection.end&&(b+=Array(a.selection.end-a.selection.start+1).join("\b")),b+=a.text,this.__accumulateData(b)))};
CWEChromeIME.prototype.__handleInput=function(a,b){if(void 0===a||null===a||0>=a.length||null===this.m_currentHook)return!1;if(!b){if(this.m_isHighlighting&&this.m_TWPModeIsActive)return!1;this.m_asNeededController.onTextInput(a.charAt(0))}if(this.m_asNeededController.allowTextProcessing()){this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor);if(!this.m_currentContext||this.m_currentContext.__unstable)return!1;let d=this.m_currentContext.selection.start,e=this.m_currentContext.selection.length,
f=d+e;var c=this.m_currentContext.text;let g,h=null,l,k;g=a.charAt(0);for(k=d-1;0<=k;k--)if(l=c.charAt(k)," "!=l){h=l;break}if(this.m_settings.features.allowAutoCapitalization&&"\n"!=g&&"\r"!=g&&(null===h||"."==h||"?"==h||"!"==h||";"==h||"\n"==h||"\r"==h))return c=g.toUpperCase(),b?(b.selection={start:d,end:d+e},b.text=c+a.substring(1)):(this.__replaceText({selection:{start:d,end:d+e},text:c}),this.__accumulateData(c),this.__onTryToSpeak(c)),!0;if("."==g||"?"==g||"!"==g||";"==h||","==g)return c=g+
" ",d=k+1,e=f-d,b?(b.selection={start:d,end:d+e},b.text=c):(this.__replaceText({selection:{start:d,end:d+e},text:c,removeLeadingSpaces:!0}),this.__accumulateData(c),this.__onTryToSpeak(c)),!0}b||(this.__accumulateData(a),this.__postRestartGuesses());return!1};CWEChromeIME.prototype.__accumulateData=function(a){a&&13==a.charCodeAt(0)&&(a=null);this.__postAccumulateData(a)};
CWEChromeIME.prototype.__onViewDidChange=function(a,b){this.m_readTextTask.stop();this.m_TWPModeIsActive="talking-word-processor"===a;"topics"===a?(this.saveActiveElement(),this.pause(!0)):"topics"===b&&(this.restoreActiveElement(),this.resume());this.m_speechRecognitionController.stop();"talking-word-processor"===b&&this.__onCaretChanged()};CWEChromeIME.prototype.__onViewSizeChanged=function(a,b){this.__moveWindow()};
CWEChromeIME.prototype.saveActiveElement=function(){this.m_lastActiveElement=this.m_currentHook?"function"===typeof this.m_currentHook.getActiveElement?this.m_currentHook.getActiveElement():document.activeElement:null};CWEChromeIME.prototype.restoreActiveElement=function(){this.m_lastActiveElement&&this.m_lastActiveElement.focus();this.m_lastActiveElement=null};CWEChromeIME.prototype.__onTrueKeyModeDidChangeDelegate=function(a,b){this.__updateTruKeyMode()};
CWEChromeIME.prototype.__onSpeechStartedHandler=function(){this.__postGA4Event("SpeechToTextStarted",null,{website:location.hostname});this.m_asNeededController.onSpeechRecognitionStarted()};CWEChromeIME.prototype.__onSpeechEndedHandler=function(a){this.__postGA4Event("SpeechToTextEnded",{number_of_words_spoken:a&&a.numberOfWordsSpoken},{website:location.hostname});this.m_asNeededController.onSpeechRecognitionEnded()};
CWEChromeIME.prototype.__onSpeakText=function(a){this.m_settings.features.allowSpeech&&this.__postSpeak(a,!0)};
CWEChromeIME.prototype.__onReadText=function(a,b=window.dji.highlighting.Granularity.WORD,c=!1){this.m_settings.features.allowSpeech&&(window.dji.utils.isNullOrUndefined(a.activate)||!1!==a.activate?window.dji.twp.TaskScheduler.schedule(this.m_readTextTask,{mappingOptions:a,fromSpeechRecognition:c,granularity:b,highlighter:c?this.m_speechRecognitionTTSTextHighlighter:this.m_forwardTTSTextHighlighter,isOffice365:!(!this.m_isOffice365||!this.m_hookOffice365),startCallback:()=>{window.cweMainView.onTextHighlightStatusChanged(!0)},
doneCallback:()=>{window.cweMainView.onTextHighlightStatusChanged(!1)}}):this.m_readTextTask.stop())};
CWEChromeIME.prototype.__onSuggestionSelected=async function(a,b){b===selectionType.CLICK?this.__postGA4Event("WordSuggestionSelected",{number_value:a.index},{website:location.hostname}):b===selectionType.NUMBER&&this.__postGA4Event("WordSuggestionByNumberSelected",{number_value:a.index},{website:location.hostname});a.isTranslation&&this.__postGA4Event("WordTranslationSelected",null,{website:location.hostname});this.m_asNeededController.isSpellingActive()?(b=this.getSelectionForLastWrittenWord(),
a=a.item+" ",await this.__replaceText({selection:b,text:a}),await this.replaceLastWordAsync(a),this.m_asNeededController.onSuggestionSelected()):this.__postGuessSelected(a.item)};CWEChromeIME.prototype.replaceLastWordAsync=async function(a){return new Promise(b=>{this.m_speechRecognitionTTSTextHighlighter.replaceLastWord(a,b)})};
CWEChromeIME.prototype.__onVirtualKeyboardInput=function(a){!this.m_currentContext||!a.key||1>a.key.length||this.__replaceText({selection:this.m_currentContext.selection,text:a.key},!0)};CWEChromeIME.prototype.__onSearchTopicsOnWeb=async function(a,b){return this.__executeCommandAsync(window.dji.messages.cwe.topics.SEARCH_WEB,{pattern:a,locale:b})};CWEChromeIME.prototype.__onUpdateTopic=async function(a){return this.__execUpdateTopic(a)};CWEChromeIME.prototype.__onActivateTopic=function(a){return this.__execActivateTopic(a)};
CWEChromeIME.prototype.topicsDataAvailable=async function(a){dji.topicHelper.setTopics(a.topics,a.activeTopics,a.displayTopics);window.cweMainView.topics=a.topics;window.cweMainView.displayTopics=a.displayTopics};
CWEChromeIME.prototype.createTopic=async function(a){let b=await this.acquireTextForTopicAsync(a.from);b&&(b=b.trim());if(b&&!(0>=b.length)){b=a.isEnglish?CWEChromeUtilities.wikiHtmlToAscii(b):window.dji.utils.htmlToUnicode(b);var c=CWEChromeUtilities.titleForTopic({text:b,maxLength:34,useAscii:!0,usePageTitle:"selection"!==a.from,combine:!1});a.topics&&this.topicsDataAvailable(a);var d=this,e=!1;this.pause();try{let f=await dji.topicHelper.updateTopicAsync({name:c,data:b,local:!1,extras:{source:a.from}},
function(g){e="update"===g.userData.action;d.showToastForUpdateTopic(e,a.from)});f&&f.success?(this.showToastForUpdateTopicDidFinish(e,f.active),d.__postGA4Event("page"===a.from?"TopicFromPageCreated":"TopicFromTextCreated",{topic_name:c},{website:location.hostname})):this.showToastForUpdateTopicDidFail(e)}catch(f){window.dji.logger.error(f),this.showToastForUpdateTopicDidFail(e)}this.resume()}};
CWEChromeIME.prototype.acquireTextForTopicAsync=async function(a){let b=void 0;try{null!==b&&void 0!==b||!this.m_hookOffice365||(b=await this.m_hookOffice365.acquireTextForTopicAsync(a)),null!==b&&void 0!==b||!this.m_hookGoogleDocs||(b=(new window.dji.DocumentTextMapperAdapter).getContextWithParams({entireDocument:"page"===a,fromCaretToEnd:!1})?.text),null!==b&&void 0!==b||!this.m_hookGoogleSlides||(b=await this.m_hookGoogleSlides.acquireTextForTopicAsync(a)),null!==b&&void 0!==b||!this.m_hookGeneric||
(b=await this.m_hookGeneric.acquireTextForTopicAsync(a))}catch(c){window.dji.logger.error(c)}return b};CWEChromeIME.prototype.showToastForUpdateTopic=async function(a,b){b=b||"web";a=a?(await window.dji.cwe.i18n.instance.getMessage("cwu_update_topic_from")).replace("<_SOURCE_>",b):(await window.dji.cwe.i18n.instance.getMessage("cwu_create_topic_from")).replace("<_SOURCE_>",b);DjiCwuToast.show(a,{domContainer:this.m_domContainer})};
CWEChromeIME.prototype.showToastForUpdateTopicDidFail=async function(a){a=a?await window.dji.cwe.i18n.instance.getMessage("cwu_error_update_topic"):await window.dji.cwe.i18n.instance.getMessage("cwu_error_create_topic");DjiCwuToast.show(a,{closeOnClick:!0,domContainer:this.m_domContainer},1E4)};
CWEChromeIME.prototype.showToastForUpdateTopicDidFinish=async function(a,b=!1){b=b?await window.dji.cwe.i18n.instance.getMessage("cwu_active_topic"):"";a=a?(await window.dji.cwe.i18n.instance.getMessage("cwu_update_active_topic")).replace("<_ACTIVE_TOPIC_>",b):(await window.dji.cwe.i18n.instance.getMessage("cwu_create_active_topic")).replace("<_ACTIVE_TOPIC_>",b);b={action:{name:"TOPICS",message:window.dji.messages.cwe.chrome.OPTIONS,close:!0},closeOnClick:!0,domContainer:this.m_domContainer};CWEChromeUtilities.isChromeOS()&&
CWEChromeUtilities.isGoogleForms()&&delete b.action;DjiCwuToast.show(a,b,1E4)};
CWEChromeIME.prototype.notificationAvailable=function(a,b){"update_topic_started"===a?b&&b.userData&&this.showToastForUpdateTopic("update"===b.userData.action,b.userData.extras?b.userData.extras.source:void 0):"update_topic_failed"===a?(b&&b.userData&&this.showToastForUpdateTopicDidFail("update"===b.userData.action),this.resume()):"update_topic_finished"===a?(b&&b.userData&&this.showToastForUpdateTopicDidFinish("update"===b.userData.action),this.resume()):"deactivate"===a&&DjiCwuToast.hide()};
CWEChromeIME.prototype.onPredictionStateChanged=function(a){this.setOfficeHookOptions();a?this.__showWindow(!0,!0,!1):this.__showWindow(!1,!0,!1)};CWEChromeIME.prototype.onDictationStateChanged=function(a){a?this.m_speechRecognitionController.startDictation():this.m_speechRecognitionController.stopDictation()};
CWEChromeIME.prototype.getSelectionForLastWrittenWord=function(){const a=this.m_currentContext.selection.start,b=this.m_currentContext.selection.length,c=this.m_currentContext.text;let d=a+b-1;for(;0<=d&&window.dji.charSet.wordSeparator.characterIsMemberNoHypen(c[d]);--d);for(;0<=d&&!window.dji.charSet.wordSeparator.characterIsMemberNoHypen(c[d]);--d);return{start:d+1,end:a+b}};
CWEChromeIME.prototype.getLastWrittenWord=function(){const a=this.getSelectionForLastWrittenWord(),b=this.m_currentContext.text;return a.start>=b.length||a.end>b.length?"":b.substring(a.start,a.end).trim()};CWEChromeIME.prototype.setOfficeHookOptions=function(){if(this.m_hookOffice365){var a=this.m_settings?this.m_settings.features:{};a.allowTextProcessing=this.m_asNeededController.allowTextProcessing();this.m_hookOffice365.setOptions({features:a})}};
