window.dji=window.dji||{};window.dji.speechrecognition=window.dji.speechrecognition||{};window.dji.speechrecognition.SpeechRecognitionControllerDelegate=function(){class e{constructor(){}getCurrentContext(){return null}handleInput(a){}async replaceTextAsync(){}postPortMessage(a){}readText(a){}}return e}();
window.dji.speechrecognition.SpeechRecognitionController=function(){class e{constructor(a,b,c,d){this.m_TTSTextHighlighter=a;this.m_TTSPendingOperations=[];this.m_STTPendingOps=0;this.m_extensionId=d;this.m_domContainer=c;this.m_stopMessage={message:window.dji.messages.cwe.speech_recognition.TOGGLE,on:!1};this.m_stopSpeakMessage={message:window.dji.messages.cwe.speak.STOP};this.m_speechRecognition={session:null,on:!1,scope:null,allText:""};this.m_delegate=b;this.m_eventTarget=new EventTarget;this.m_settings=
{};window.cweMainView.canToggleSpeechRecognitionDelegate=this.canToggle.bind(this);window.cweMainView.speechRecognitionDelegate=this.__onSpeechRecognition.bind(this);window.cweMainView.errorDismissedDelegate=this.__onSpeechRecognitionErrorDismissed.bind(this);chrome.runtime.onMessage.addListener((f,g,h)=>this.__onRuntimeMessage(f,g,h));this.m_TTSTextHighlighter.addEventListener("highlighting-status-changed",f=>{this.__handleNextTTSHighlightingOperation()})}addEventListener(a,b){this.m_eventTarget.addEventListener(a,
b)}resetTextHighlighting(){this.m_TTSTextHighlighter.reset();this.m_TTSPendingOperations=[]}setSettings(a){this.m_settings=a}isActive(){return this.isSpeechRecognitionOn()||0<this.m_STTPendingOps||this.isTextHighlightingActive()}isSpeechRecognitionOn(){return this.m_speechRecognition.on}isTextHighlightingActive(){return this.m_TTSTextHighlighter.isHighlighting()}canToggle(a){return a?0===this.m_TTSTextHighlighter.text.length&&0===this.m_TTSPendingOperations.length&&null===this.m_speechRecognition.session:
!this.isTextHighlightingActive()}startDictation(){this.isActive()||this.__onSpeechRecognition({activate:!0,scope:"dictation"})}stopDictation(){this.stopSpeechRecognition()}stop(){const a=this.isTextHighlightingActive();this.resetTextHighlighting();this.m_STTPendingOps=0;a&&this.m_delegate.postPortMessage(this.m_stopSpeakMessage);this.stopSpeechRecognition()}stopAsync(){return new Promise(a=>{setTimeout(()=>{this.stop();a()},0)})}stopSpeechRecognition(){this.isSpeechRecognitionOn()&&this.m_delegate.postPortMessage(this.m_stopMessage)}__onRuntimeMessage(a,
b,c){a.message===window.dji.messages.cwe.speech_recognition.NOTIFICATION?this.__onSpeechRecognitionNotification(a.session,a.details):a.message===window.dji.messages.cwe.speech_recognition.PROGRESS?this.__onSpeechRecognitionProgress(a.session,a.error,a.text):a.message===window.dji.messages.cwe.speech_recognition.END&&this.__onSpeechRecognitionEnd(a.session,a.error);return!1}__onSpeechRecognition(a){let b={message:window.dji.messages.cwe.speech_recognition.TOGGLE,on:a.activate,langCode:a.langCode,scope:a.scope,
session:this.m_speechRecognition.session};a.activate?(this.m_speechRecognition.session=`${Date.now()}-${parseInt(1E3*Math.random())}`,this.m_speechRecognition.scope=a.scope,this.m_speechRecognition.on=!0,b.session=this.m_speechRecognition.session,this.resetTextHighlighting(),this.m_delegate.postPortMessage(b),this.m_eventTarget.dispatchEvent(new CustomEvent("speech-started"))):(this.m_delegate.postPortMessage(b),window.cweMainView.stopSpeechRecognition(this.m_speechRecognition.scope),this.__postSpeakAfterSpeechRecognition())}__onSpeechRecognitionErrorDismissed(){this.m_eventTarget.dispatchEvent(new CustomEvent("speech-error-dismissed"))}__onSpeechRecognitionNotification(a,
b){a===this.m_speechRecognition.session&&("soundstart"===b.type?window.cweMainView.pulseSpeechRecognition(!0,this.m_speechRecognition.scope):"soundend"===b.type&&window.cweMainView.pulseSpeechRecognition(!1,this.m_speechRecognition.scope))}__handleError(a,b){if(!window.dji.utils.isNullOrUndefined(a)){var c={title:"",message:"",action:"dismiss"};switch(a){case 401:this.__requestPermissions();c.title="Microphone permission is blocked";c.message="Co:Writer does not have permission to use the microphone. Please allow access to use this feature.";
c.action="open-settings";break;case 404:c.title="Cannot find microphone";c.message="Co:Writer could not find a microphone. Please make sure a microphone is connected or microphone input is on.";break;case 408:c.title="No Internet connection found";c.message="Co:Writer requires an internet connection for Speech-to-text. Please make sure you have a connection and try again.";break;default:return}window.cweMainView.showSpeechRecognitionError(!0,b,c);this.m_eventTarget.dispatchEvent(new CustomEvent("speech-error",
{detail:{isPermissionError:401===a}}))}}async __requestPermissions(){let a=this.m_domContainer.getElementById("__DJI_CWE_SPEECHRECOGNITION_PERMISSION");a?a.src=a.src:(a=document.createElement("iframe"),a.id="__DJI_CWE_SPEECHRECOGNITION_PERMISSION",a.src=chrome.extension.getURL("Background/helpers/speechRecognitionPermission.html"),a.allow="microphone",this.m_domContainer.appendChild(a))}async __onSpeechRecognitionProgress(a,b,c){if(a!==this.m_speechRecognition.session)dji.logger.warn("onSpeechRecognitionProgress: invalid speech recognition session, skipping text: ",
c);else if("search_topics"===this.m_speechRecognition.scope)window.cweMainView.searchTopicsPattern=c;else{var d=this.m_delegate.getCurrentContext();"dictation"!==this.m_speechRecognition.scope||!d||!c||1>c.length||(this.__isBusy()?this.m_TTSPendingOperations.push({type:"text",params:{session:a,error:b,text:c}}):(this.m_STTPendingOps++,a=d.selection,b={},this.m_delegate.handleInput(c,b)&&b.selection&&(a=b.selection,c=b.text),c.endsWith(" ")||c.endsWith("\n")||(c+=" "),this.m_speechRecognition.allText+=
c,await this.m_delegate.replaceTextAsync(a,c),this.m_STTPendingOps--,0>this.m_STTPendingOps&&(this.m_STTPendingOps=0),this.__handleNextTTSHighlightingOperation()))}}__onSpeechRecognitionEnd(a,b){if(a!==this.m_speechRecognition.session)dji.logger.warn("Ignoring end speech recognition session:",a,b,this.m_speechRecognition.session,this.m_speechRecognition.on,this.m_speechRecognition.scope,this.m_speechRecognition.allText);else{a=this.m_speechRecognition.allText;var c=this.__resetSpeechRecognitionInfo();
this.__handleError(b,c);window.cweMainView.stopSpeechRecognition(c);401!==b&&404!==b&&408!==b&&this.__postSpeakAfterSpeechRecognition(a);b=window.dji.utils.getNumberOfWordsFromString(a);this.m_eventTarget.dispatchEvent(new CustomEvent("speech-ended",{detail:{numberOfWordsSpoken:b}}))}}__isBusy(){return 0<this.m_STTPendingOps||this.m_TTSTextHighlighter.isHighlighting()}__handleNextTTSHighlightingOperation(){if(0!==this.m_TTSPendingOperations.length&&!this.__isBusy()){var a=this.m_TTSPendingOperations.shift();
"text"===a.type?this.__onSpeechRecognitionProgress(this.m_speechRecognition.session,a.params.error,a.params.text):"start"===a.type&&this.__startTTSHighlighting(this.m_speechRecognition.allText)}}__postSpeakAfterSpeechRecognition(a){this.m_settings&&!this.m_settings.speech.afterSTT?this.resetTextHighlighting():a&&0!==a.length&&(this.m_TTSTextHighlighter.isHighlighting()||this.__startTTSHighlighting(a))}__startTTSHighlighting(a){0<this.m_STTPendingOps?this.m_TTSPendingOperations.unshift({type:"start"}):
this.m_delegate.readText(a)}__resetSpeechRecognitionInfo(){const a=this.m_speechRecognition.scope;this.m_speechRecognition.on=!1;this.m_speechRecognition.scope=null;this.m_speechRecognition.session=null;this.m_speechRecognition.allText="";return a}}return e}();
