function DjiStorageFile(g,k,l){this.id=g;this.title=k;this.type=l;this.description=null;this.isFolder=!1;this.revision=this.checksum=this.downloadUrl=this.thumbnailUrl=this.iconUrl=this.lastModifiedDate=this.creationDate=this.parent=null;this.trashed=!1;this.__custom=null}(function(g){})(window.jsdapi=window.jsdapi||{});
(function(g){function k(a){var b=window.jsdapi.url();b+="/cow";a&&(b+="/"+a);return b}function l(a){var b=k("files");a&&(b+="/"+a);return b}function u(a){var b=k("data");a&&(b+="/"+a);return b}function v(a){var b=k("measurements");a&&(b+="/"+a);return b}g.setUrls=function(a){};g.checkSyncOptionsAsync=async function(){return new Promise(a=>{window.jsdapi.authorize(function(b){if(!b)return a({error:401,message:"Authorization failed!"});b={ignoreStatusCode:!0,responseType:"json",method:"GET",url:k("sync/options"),
query:{access_token:b}};window.jsdapi.http.sendRequest(b,a)})})};g.getLanguage=async function(a,b){window.jsdapi.authorize(function(d){if(!d)return f(b,null);d={responseType:"json",method:"GET",url:k("language"),query:{access_token:d}};window.jsdapi.http.sendRequest(d,function(e){f(b,e&&e.language?e.language:null)})})};g.updateLanguageAsync=function(a){return new Promise(function(b,d){g.updateLanguage(a,function(e){e?b(e):d()})})};g.updateLanguage=function(a,b){if(!a)return f(b,null);window.jsdapi.authorize(function(d){if(!d)return f(b,
null);d={responseType:"json",method:"GET",url:k("language/update"),query:{access_token:d,language:a}};window.jsdapi.http.sendRequest(d,function(e){f(b,e&&e.language?e.language:null)})})};g.getPresentationLanguageAsync=function(){return new Promise(function(a,b){g.getPresentationLanguage(function(d){d?a(d):b()})})};g.getPresentationLanguage=async function(a){window.jsdapi.authorize(function(b){if(!b)return f(a,null);b={responseType:"json",method:"GET",url:k("presentation/language"),query:{access_token:b}};
window.jsdapi.http.sendRequest(b,function(d){f(a,d)})})};g.updatePresentationLanguageAsync=function(a){return new Promise(function(b,d){g.updatePresentationLanguage(a,function(e){e?b(e):d()})})};g.updatePresentationLanguage=function(a,b){if(!a)return f(b,null);window.jsdapi.authorize(function(d){if(!d)return f(b,null);d={responseType:"json",method:"GET",url:k("presentation/language/update"),query:{access_token:d,language:a}};window.jsdapi.http.sendRequest(d,function(e){f(b,e&&e.language?e.language:
null)})})};g.getPrivacyModeAsync=function(){return new Promise(function(a,b){g.getPrivacyMode(function(d){d?a(d):b()})})};g.getPrivacyMode=async function(a){window.jsdapi.authorize(function(b){if(!b)return f(a,null);b={responseType:"json",method:"GET",url:k("privacyMode"),query:{access_token:b}};window.jsdapi.http.sendRequest(b,function(d){f(a,d)})})};g.getFiles=function(a,b,d){window.jsdapi.authorize(function(e){e?(a&&(a instanceof Array&&0<a.length&&(a=a[0]),"string"!==typeof a&&(a="")),e={responseType:"json",
method:"GET",url:l("list"),query:{access_token:e,filters:JSON.stringify({type:a,language:b})}},window.jsdapi.http.sendRequest(e,function(h){q(h,a,!1,d)})):f(d,{errorCode:1})})};g.checkForUpdates=function(a,b){!a||0>=a.length?f(b,{errorCode:400}):window.jsdapi.authorize(function(d){d?(d={responseType:"json",method:"GET",url:l("checkUpdates"),query:{access_token:d,filters:JSON.stringify({basic:!0,types:a})}},window.jsdapi.http.sendRequest(d,function(e){var h={errorCode:e&&0==e.error?0:2};if(0==h.errorCode&&
(h.files={},e.files))for(var c=0;c<a.length;c++){var m=e.files[a[c].type],r=[];if(m)for(var p=0;p<m.length;p++)r.push(n(m[p]));h.files[a[c].type]=r}f(b,h)})):f(b,{errorCode:401})})};g.getFile=function(a,b){window.jsdapi.authorize(function(d){null===d?f(b,{errorCode:401}):(d={responseType:"json",method:"GET",url:l("list"),query:{access_token:d,filters:JSON.stringify({type:a.type,uuid:a.id})}},window.jsdapi.http.sendRequest(d,function(e){q(e,a.type,!0,b)}))})};g.insertFile=function(a,b,d){window.jsdapi.authorize(function(e){if(null===
e)f(d,{errorCode:401});else{var h={uuid:a.id,title:a.title,type:a.type,language:a.__custom&&a.__custom.language?a.__custom.language:null,creationDate:a.creationDate,modifiedDate:a.lastModifiedDate,modifiedUuid:a.lastModifiedUuid,checksum:a.checksum,version:a.revision},c=new JsDapiUtf8Data;c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: info\r\n");c.appendString('Content-Disposition: inline; name="info";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");
c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");c.appendString(JSON.stringify(h));c.appendString("\r\n");a.__custom&&a.__custom.metadata&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: metadata\r\n"),c.appendString('Content-Disposition: inline; name="metadata";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.metadata),c.appendString("\r\n"));
a.__custom&&a.__custom.preview&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: preview\r\n"),c.appendString('Content-Disposition: inline; name="preview";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.preview),c.appendString("\r\n"));c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: body\r\n");c.appendString('Content-Disposition: inline; name="body";\r\n');
c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");b instanceof ArrayBuffer||"[object ArrayBuffer]"==b.toString()?c.appendArrayBuffer(b):b instanceof Array?c.appendArray(b):c.appendString(b);c.appendString("\r\n");c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");e={responseType:"json",method:"POST",url:l("create"),query:{access_token:e},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',
content:c.toUint8Array()};window.jsdapi.http.sendRequest(e,function(m){t(m,d)})}})};g.updateFile=function(a,b,d){window.jsdapi.authorize(function(e){if(null===e)f(d,{errorCode:401});else{var h={uuid:a.id,title:a.title,type:a.type,language:a.__custom&&a.__custom.language?a.__custom.language:null,creationDate:a.creationDate,modifiedDate:a.lastModifiedDate,modifiedUuid:a.lastModifiedUuid,checksum:a.checksum,version:a.revision},c=new JsDapiUtf8Data;c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");
c.appendString("Content-ID: info\r\n");c.appendString('Content-Disposition: inline; name="info";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");c.appendString(JSON.stringify(h));c.appendString("\r\n");a.__custom&&a.__custom.metadata&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: metadata\r\n"),c.appendString('Content-Disposition: inline; name="metadata";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),
c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.metadata),c.appendString("\r\n"));a.__custom&&a.__custom.preview&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: preview\r\n"),c.appendString('Content-Disposition: inline; name="preview";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.preview),c.appendString("\r\n"));
c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: body\r\n");c.appendString('Content-Disposition: inline; name="body";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");b instanceof ArrayBuffer||"[object ArrayBuffer]"==b.toString()?c.appendArrayBuffer(b):b instanceof Array?c.appendArray(b):c.appendString(b);c.appendString("\r\n");c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");
e={responseType:"json",method:"POST",url:l("update"),query:{access_token:e},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',content:c.toUint8Array()};window.jsdapi.http.sendRequest(e,function(m){t(m,d)})}})};g.moveFile=function(a,b,d){f(d,{errorCode:-1})};g.deleteFile=function(a,b,d){window.jsdapi.authorize(function(e,h){null===e||null===h?f(d,{errorCode:1}):(e={responseType:"json",method:"GET",url:l("delete"),query:{access_token:e,dapiApprovalToken:'"'+h+'"',
type:'"'+a.type+'"',uuid:'"'+a.id+'"',version:a.revision,purge:b}},window.jsdapi.http.sendRequest(e,function(c){f(d,c)}))})};g.downloadFile=function(a,b){window.jsdapi.authorize(function(d){null===d?f(b,{errorCode:401}):(d={responseType:a.__responseType||"binary",method:"GET",url:l("content"),query:{access_token:d,type:'"'+a.type+'"',uuid:'"'+a.id+'"'}},window.jsdapi.http.sendRequest(d,function(e,h,c){h=null;if(c&&c.hasOwnProperty("dapi-file-info"))try{h=n(JSON.parse(c["dapi-file-info"]))}catch(m){Logger.instance.error(m)}f(b,
e,h)}))})};g.resetFile=function(a,b){window.jsdapi.authorize(function(d){d?(d={responseType:"json",method:"GET",url:l("reset"),query:{access_token:d,type:a.type,language:a.language}},dji.http.sendRequest(d,function(e){})):f(b,{errorCode:1})})};g.downloadImage=function(a,b){f(b,null)};g.downloadThumbnail=function(a,b){f(b,null)};g.downloadIcon=function(a,b){f(b,null)};g.getDataWordList=function(a,b){window.jsdapi.authorize(function(d){d?(d={responseType:"json",method:"GET",url:u("words/list"),query:{access_token:d,
filters:JSON.stringify({language:a})}},window.jsdapi.http.sendRequest(d,function(e){f(b,e)})):f(b,{errorCode:401})})};g.updateMeasurements=function(a,b){window.jsdapi.authorize(function(d){d?(d={responseType:"json",method:"POST",url:v("update"),query:{access_token:d},contentType:"application/json",content:JSON.stringify(a)},window.jsdapi.http.sendRequest(d,function(e){f(b,e)})):f(b,{errorCode:401})})};var q=function(a,b,d,e){b={errorCode:a&&0==a.error?0:2};if(0==b.errorCode){var h=[];if(a.files)for(var c=
0;c<a.files.length;c++)h.push(n(a.files[c]));d&&1===h.length?b.file=h[0]:b.files=h}f(e,b)},t=function(a,b){var d={errorCode:a&&0==a.error?0:2};0==d.errorCode&&a.file&&(d.file=n(a.file));f(b,d)},n=function(a){if(!a)return null;var b=new DjiStorageFile(a.uuid,a.title,a.type);b.creationDate=a.creationDate;b.lastModifiedDate=a.modifiedDate;b.checksum=a.checksum;b.revision=a.version;b.trashed=a.deleted;b.__custom=a;return b},f=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}}})(window.jsdapi.cow=
window.jsdapi.cow||{});
